### ISSUE TITLE
Quarto ask for GitHub username and password when rendering or preview with command line.

### ISSUE THREAD

**Issue by phongphuhanam** [quarto-dev/quarto-cli#10031]
### Bug description

Hello, thank you for a great work.
Today  I try to render the Quarto document from terminal zsh(without Vscode). Quarto then ask for GitHub login user name and password every time before it render. 
* If I remove the git remote `origin`, or change the `origin` name to something else, or change the remote url of `origin` to public repository, quarto is able to render document without asking the question.
* On the other hand, If I keep the git remote 'origin' and the remote url point to private repository, it will continue asking Github login ID.
* After I press Enter two time, Quarto can render the documents but it will ask the login ID again once the source code is changed.

However, if I render with Vscode quarto plugin, there are no issue.

### Steps to reproduce

Create 'test_project' 
```bash
quarto create test_project
```

The test_project is default from Quarto

Render documents:
```bash
cd test_project
quarto render index.qmd --to html
```

### Expected behavior

Quarto should not ask Github login user id and pw:
```bash
quarto render index.qmd --to html

pandoc
  to: html
  output-file: /media/data/documents/test_projects/test_project/index.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  toc: true

metadata

  document-css: false
  link-citations: true
  date-format: long
  lang: en
  manuscript:
    article: index.qmd
    notebooks: []
    mecaFile: index-meca.zip
  notebook-preview-options:
    back: true
  theme: cosmo
  title-block-style: manuscript
  lightbox: auto
  comments:
    hypothesis: true
  title: ./tesst_project
  authors:
    - name: Norah Jones
      affiliation: The University
      roles: writing
      corresponding: true
  bibliography:
    - references.bib
  google-scholar: true
  toc-location: left
  clear-hidden-classes: none
  remove-hidden: all
  unroll-markdown-cells: true

Output created: _manuscript/index.html
```

### Actual behavior

Add dummy private repository:
```bash
git remote add origin https://github.com/phongphuhanam/my-dummpy-private-repo
```

Render again:
```bash
 git remote -v && quarto render index.qmd --to html

origin  https://github.com/phongphuhanam/my-dummpy-private-repo (fetch)
origin  https://github.com/phongphuhanam/my-dummpy-private-repo (push)
Username for 'https://github.com': abc
Password for 'https://abc@github.com':
```

### Your environment

- Shell : zsh with ohmyzsh plugin
- OS: Debian GNU/Linux trixie/sid

### Quarto check output

```bash
 quarto check                                         1 ↵
Quarto 1.4.555
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.555
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.8
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by danieltomasz** [comment]
@phongphuhanam I am not a dev team, but it seems that is the `git` that ask fro a password, not `quarto` , so maybe you have something misconfigured in your zsh

**Comment by phongphuhanam** [comment]
@danieltomasz, Thank you for the suggestion. I tried the `preview` option but the results are similar:
```bash
 git remote -v && quarto preview index.qmd --to html                        1 ↵

origin  https://github.com/phongphuhanam/my-dummpy-private-repo (fetch)
origin  https://github.com/phongphuhanam/my-dummpy-private-repo (push)
Username for 'https://github.com':
```
So for now, my quick fix is to change the `origin` remote to some other name, and the `render` or `preview` is OK.

**Comment by hanchenduming** [comment]
Maybe need to install again with root user

**Comment by mcanouil** [comment]
You should not need to use root permission.

The one asking the credentials is Git because there is a Git operation (likely a check of some guide) that needs access to the remote which is private.

I am not 100% certain (and cannot check right now) but I don't think `quarto render/preview` uses Git at all.

If it works in VSCode it is because you are logged in using a GitHub account with access to the repository. "Everything" inside VSCode has access to the account credentials so, the request for credentials happens but it is satisfied in this context/environment.

**Comment by cderv** [comment]
@phongphuhanam did you share all the information on your example ? 

My following answers will be wild guesses based the hint you shared. 

> The test_project is default from Quarto

I understand you ran `quarto create project` and selected the default type, is that so ? What is in your `_quarto.yml` as project type ? 

> ```
>  manuscript:
>      article: index.qmd
>      notebooks: []
>      mecaFile: index-meca.zip
> ```

I am seeing this in your log, which is usually used for a [Quarto Manuscript](https://quarto.org/docs/manuscripts/) project 

So it seems the project you are using and produce this problem is a Manuscript project which produce a [Meca Bundle](https://quarto.org/docs/manuscripts/components.html#meca-bundle). 

It happens, Quarto is using `git` when available to list all the files that should be included in the Meca Bundle
https://github.com/quarto-dev/quarto-cli/blob/d5edb79404188308630370617c8d7a3f14d2de33/src/project/types/manuscript/manuscript-meca.ts#L151-L175

The command used is `git ls-files`. You could check in terminal that this commands is asking you for credentials in your specific case (because of how you git repo is configured). 

You can try set `meca-bundle: false` in the `format: manuscript` configuration. This should opt-out the bundle creation, and probably not show the error you see. 

It would be really appreciated if you could provide a github repo that reproduce this problem so that we can confirm this is indeed related to Manuscript, and we could think of ways to nicely fails when `git` is not correctly configured. 

At least, we will document that `git` is used when available to list the file. 

Hope it helps understand

**Comment by phongphuhanam** [comment]
@cderv Here is my source file for the `test_project`
_quarto.yaml
```yaml
project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true
```
index.qmd
```markdown
---
title: ./test_project
authors:
  - name: Norah Jones
    affiliation: The University
    roles: writing
    corresponding: true
bibliography: references.bib
---

## Section
This is a simple placeholder for the manuscript's main document [@knuth84].
```

references.bib
```bibtex
@article{knuth84,
  author = {Knuth, Donald E.},
  title = {Literate Programming},
  year = {1984},
  issue_date = {May 1984},
  publisher = {Oxford University Press, Inc.},
  address = {USA},
  volume = {27},
  number = {2},
  issn = {0010-4620},
  url = {https://doi.org/10.1093/comjnl/27.2.97},
  doi = {10.1093/comjnl/27.2.97},
  journal = {Comput. J.},
  month = may,
  pages = {97–111},
  numpages = {15}
}
```
I believed that is the default file generate by `quarto create` command. 
One more thing is I used Quarto inside Debian docker container, so that's why git credentials are not available.

**Comment by mcanouil** [comment]
@phongphuhanam look at Christophe's comment, in particular the part about "meca".

**Comment by phongphuhanam** [comment]
@cderv  Oh, I forgot to mention the choice after the `quarto create` command.
Until the issue is fixed, here is my quick solution. 

> @danieltomasz, Thank you for the suggestion. I tried the `preview` option but the results are similar:
> 
> ```shell
>  git remote -v && quarto preview index.qmd --to html                        1 ↵
> 
> origin  https://github.com/phongphuhanam/my-dummpy-private-repo (fetch)
> origin  https://github.com/phongphuhanam/my-dummpy-private-repo (push)
> Username for 'https://github.com':
> ```
> 
> So for now, my quick fix is to change the `origin` remote to some other name, and the `render` or `preview` is OK.

**Comment by Fpadt** [comment]
Hi, I run in the same problem

Sounds like a nice feature the manuscript .

1.  Quarto instructions for VS code work and generate the manuscript
     https://quarto.org/docs/manuscripts/authoring/vscode.html
    - a copy of the template in Github and (currently) public
1.   Quarto instructions for RStudio do not work
     https://quarto.org/docs/manuscripts/authoring/rstudio.html
     - a public copy of the template, doesn't generate and indicates the public key is ot correct (SSH)     
    As indicated above after changing the git origin to a dummy public repository on github it does work
    
## Preview Does Work!!

$ git remote -v && quarto preview index.qmd --to html
origin  git@github.com:Fpadt/MANU_R.git (fetch)
origin  git@github.com:Fpadt/MANU_R.git (push)


processing file: index.qmd

output file: index.knit.md

Rendering qmd embeds
[1/1] notebooks/explore-earthquakes.qmd
Rendering qmd embeds [index.qmd]
Rendering output notebook [index.qmd]
Rendering HTML preview [index.qmd]
pandoc
  to: html
  output-file: 'U:\floris\GH\MANU_R\index.html'
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  toc: true
  number-sections: true

metadata

  document-css: false
  link-citations: true
  date-format: long
  lang: en
  manuscript:
    article: index.qmd
    notebooks:
      - notebook: index.qmd
        title: Article Notebook
        order: 9999
      - notebook: notebooks/explore-earthquakes.qmd
    mecaFile: index-meca.zip
  notebook-preview-options:
    back: true
  theme: cosmo
  title-block-style: manuscript
  lightbox: auto
  comments:
    hypothesis: true
  title: La Palma Earthquakes
  author:
    - name: Steve Purves
      orcid: 0000-0002-0760-5497
      corresponding: true
      email: steve@curvenote.com
      roles:
        - Investigation
        - Project administration
        - Software
        - Visualization
      affiliations:
        - Curvenote
    - name: Rowan Cockett
      orcid: 0000-0002-7859-8394
      corresponding: false
      roles: []
      affiliations:
        - Curvenote
  keywords:
    - La Palma
    - Earthquakes
  abstract: |
    In September 2021, a significant jump in seismic activity on the island of La Palma (Canary Islands, Spain) signaled the start of a volcanic crisis that still continues at the time of writing. Earthquake data is continually
collected and published by the Instituto Geográphico Nacional (IGN). ...
  plain-language-summary: |
    Earthquake data for the island of La Palma from the September 2021 eruption is found ...
  key-points:
    - A web scraping script was developed to pull data from the Instituto Geogràphico Nacional into a machine-readable form for analysis
    - Earthquake events on La Palma are consistent with the presence of both mantle and crustal reservoirs.
  date: last-modified
  bibliography:
    - references.bib
  citation:
    container-title: Earth and Space Science
  google-scholar: true
  toc-location: left
  clear-hidden-classes: none
  remove-hidden: all
  unroll-markdown-cells: true

Output created: _manuscript\index.html

Preparing to preview
[1/1] notebooks\explore-earthquakes.qmd

Watching files for changes
Browse at http://localhost:6188/
Rendering HTML preview [index.qmd]
GET: /


## RENDER doesn't

==> quarto preview index.qmd --to html --no-watch-inputs --no-browse



processing file: index.qmd
                                                                                                            
output file: index.knit.md

Rendering HTML preview [index.qmd]
ERROR: There is an error while retrieving information from remote 'origin'.
 Git error: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
. 
 Git status code: 128.

Stack trace:
 Git error: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
. 
 Git status code: 128.
    at gitHubContext (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:73307:31)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Object.filterParams (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:95426:39)
    at async projectFilterParams (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:44243:45)
    at async filterParamsJson (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:44015:12)
    at async runPandoc (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:69675:24)
    at async renderPandoc (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:70717:26)
    at async pandocRenderNb (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:95026:29)
    at async Object.onRender (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:95069:40)
    at async renderFileInternal (file:///C:/Users/floris/AppData/Local/Programs/Quarto/bin/quarto.js:78245:17)

**Comment by mcanouil** [comment]
@Fpadt
Could you properly format your post using code blocks for code and terminal outputs? Thanks.
Your post is almost ineligible.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
Use `/details` for long entry.
See <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>.

**Comment by philippbaessler** [comment]
I ran into the same issue. 

### Repro steps:
1. Create a clean quarto manuscript project:
    ````bash
    quarto create project manuscript . "helloworld"
    ````

2. Initialize git, add private remote origin, commit & push
    ````bash
    git init
    git remote add origin <my_private_origin>
    git branch -M main
    git add --all
    git commit -m "initial commit"
    git push -uf origin main
    ````

3. Revoke access to private remote repository
4. Try to render the quarto project and watch it fail
    ```` bash
    quarto render
    ````

    <details><summary>Error message</summary>
    <p>
    
    ERROR: There is an error while retrieving information from remote 'origin'.
     Git error: git@<my_private_origin>: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    .
     Git status code: 128.
    
    Stack trace:
     Git error: git@<my_private_origin>: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
    </p>
    </details> 

Now, I understand that this error is caused by git and is in fact expected if access to the private repo is revoked. However, I actually do not at all intend to invoke git when doing `quarto render`.  Also, following the [reply](https://github.com/quarto-dev/quarto-cli/issues/10031#issuecomment-2172774572) of @cderv, I tried setting `meca-bundle: false`, like so:
````yaml
manuscript:
  article: index.qmd
  meca-bundle: false
```` 
<details><summary>full _quarto.yml file</summary>
<p>

````yaml
project:
  type: manuscript

manuscript:
  article: index.qmd
  meca-bundle: false

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true
```` 

</p>
</details> 

But the error persists. 

- Did I maybe add the `meca-bundle` option in the wrong place?
- Is there a way to force quarto to render the manuscript project using just the local files in the local project directory, without invoking git?

**Comment by cderv** [comment]
> Did I maybe add the meca-bundle option in the wrong place?

I think this is the right place, but as we document in https://quarto.org/docs/manuscripts/components.html#meca-bundle using `format: jats` opt-in for the bundle anyway. 

> Is there a way to force quarto to render the manuscript project using just the local files in the local project directory, without invoking git?

This is what this issue is about. I need to understand what exactly is happening here related to how git is used. 

To build the bundle, `git ls-files` command is used, and I don't know if it can avoid a remote call. 

The minimul we can do is catched the git error here, and fallback to the non git mode maybe.

**Comment by Fpadt** [comment]
@mcanouil You are right, apologies! 

I was in a hurry for a business trip and wanted to post this hoping for a solution on my return ;)  
In the end, I just replicate the RStudio instructions, didn't change any code and just tried the preview feature and the **RENDER** button

the strange thing is that it does work in VSCode but the same not in RStudio

Tried to make it more readable, added quarto check.
Hope it helps

**Comment by Fpadt** [comment]
## Update

Searching for a workaround to use a private repository on GitHub whilst being able to render my document I ran into the following:  

- the ```Render Project``` button in Rstudio throws an error regarding the Git permission
- the same command entered via he terminal **does** work.

The commnad I used is: ```quarto preview --render all --no-watch-inputs --no-browse``` and it generates the manuscript which can be opened in a browser. It seems the ```Render Project``` button does more behind the scenes, resulting in the error.

### Repository

The repository i am using is **PUBLIC** and still throws an error using the ```Render Project``` button.
It is a clone of the original template from RStudio and can be found here: [manuscript-template-rstudio](https://github.com/Fpadt/MANU_R).

Note that the ```_quarto.yml``` only has two formats and no ```meca-bundle```.

**Comment by cderv** [comment]
> ❌ the Render Project button in Rstudio throws an error regarding the Git permission
> ✔ the same command entered via he terminal does work.

That is interesting information. It would indicate this is RStudio IDE integration issue somehow if both quarto version are identical. 

`Render Project` will do a `quarto preview` so be sure to try preview on the terminal. 

> The repository I am using is PUBLIC and still throws an error using the Render Project button.
It is a clone of the original template from RStudio and can be found here: [manuscript-template-rstudio](https://github.com/Fpadt/MANU_R).
>
> Note that the _quarto.yml only has two formats and no meca-bundle.

we'll look into this.

**Comment by nicolas-roelandt** [comment]
Hi,

I do have this issue too on a project.

I thought it was something I did to the git history but it so I also replicated on another (regular) notebook and the compilation failed too.
I can't use CLI (windows machine)

It was working fine a couple weeks ago then stopped (I might have updated packages, I'm not sure)

A temporary workaround can be to use `website` rather than `manuscript` in `_quarto.yml`

````
project:
  # type: manuscript
  type: website
````

Another workaround is to use HTTPS credentials rather SSH but it is not possible everywhere and it is very cumbersome.

**Comment by nicolas-roelandt** [comment]
@cderv it was not running this morning I swear, probably because CMD called an R version which did'nt have the right packages and I was not able to determine which one.

But I had another issue (completely unrelated - a conflict between xfun::is_false() and base::is_false() ) so I ended updating R to 4.4.2 and reinstalling all the env,
I retried and CLI works just fine now 🥳

**Comment by nicolas-roelandt** [comment]
Did more tests this morning using the [manuscript-tutorial](https://github.com/nicolas-roelandt/manuscript-tutorial) repo,

Did several things
- [Record project state when compilation crashed within Rstudio](https://github.com/nicolas-roelandt/manuscript-tutorial/commit/2fb29db38f706a4194564c0912df2b030cb8a464)
- [Activate renv to record env state](https://github.com/nicolas-roelandt/manuscript-tutorial/commit/84c68a8fc90d2daef56a46245d2ff919e233f0b3)
- [Record state after failed compilation from CLI](https://github.com/nicolas-roelandt/manuscript-tutorial/commit/3b1486b6cfbf42066172441a0e3e88d9fbaaf5e1)

### How to reproduce : 

1. `git clone git@github.com:nicolas-roelandt/manuscript-tutorial.git`
2. `cd manuscript-tutorial`
3. `renv::restore()`
4.  `quarto render`

### Error message
````
> cd manuscript-tutorial

manuscript-tutorial>quarto render
[1/2] notebooks\explore-earthquakes.qmd


processing file: explore-earthquakes.qmd
1/7
2/7 [unnamed-chunk-1]
3/7
4/7 [unnamed-chunk-2]
5/7
6/7 [fig-spatial-plot]
7/7
output file: explore-earthquakes.knit.md

ERROR: There is an error while retrieving information from remote 'origin'.
 Git error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
.
 Git status code: 128.

Stack trace:
 Git error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
.
 Git status code: 128.
    at gitHubContext (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:80515:31)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Object.filterParams (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:102623:39)
    at async projectFilterParams (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:51123:45)
    at async filterParamsJson (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:50886:12)
    at async runPandoc (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:76833:24)
    at async renderPandoc (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:78003:26)
    at async pandocRenderNb (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:102334:33)
    at async Object.onRender (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:102426:36)
    at async renderFileInternal (file:///C:/Users/roelandt/AppData/Local/Programs/Quarto/bin/quarto.js:85523:17)

manuscript-tutorial>quarto --version
1.6.33
````

### Note : Github actions CI/CD worked when I cloned the repo 2 months ago but failed today. Possibly because of renv use, relation to current issue not obvious.

````
Run quarto-dev/quarto-actions/publish@v2
Run git config --global user.email "quarto-github-actions-publish@example.com"
From https://github.com/nicolas-roelandt/manuscript-tutorial
 * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
Rendering for publish:


[1/2] notebooks/explore-earthquakes.qmd
# Bootstrapping renv 1.0.11 --------------------------------------------------
- Downloading renv ... OK
- Installing renv  ... OK

- One or more packages recorded in the lockfile are not installed.
- Use `renv::status()` for more details.
Error in loadNamespace(x) : there is no package called ‘rmarkdown’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
R installation:
  Version: 4.4.2
  Path: /usr/lib/R
  LibPaths:
    - /home/runner/work/manuscript-tutorial/manuscript-tutorial/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu
    - /home/runner/.cache/R/renv/sandbox/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/9a444a72
  knitr: (None)
  rmarkdown: (None)

The knitr package is not available in this R installation.
Install with install.packages("knitr")

The rmarkdown package is not available in this R installation.
Install with install.packages("rmarkdown")
````

**Comment by cderv** [comment]
Thanks a lot. I'll take into account this new information when I'll look into this.

**Comment by gbruer15** [comment]
I have this shell script to reproduce the git access error:

```shell
git init
touch index.qmd
echo "project:
  type: manuscript" > _quarto.yml
git remote add origin asdf
quarto preview .
```

I tried setting `meca-bundle: false`, but quarto still errors trying to access git.

```shell
git init
touch index.qmd
echo "project:
  type: manuscript
manuscript:
  meca-bundle: false" > _quarto.yml
git remote add origin asdf
quarto preview .
```

Also, `git ls-files` does not error, so I'm thinking there must be a different issue.

<details>

<summary>
Here's the output from running this.</summary>



```
gbruer@nathanielU:~/tmp$ mkdir a
gbruer@nathanielU:~/tmp$ cd a
gbruer@nathanielU:~/tmp/a$ git init
Initialized empty Git repository in /home/gbruer/tmp/a/.git/
gbruer@nathanielU:~/tmp/a$ touch index.qmd
gbruer@nathanielU:~/tmp/a$ echo "project:
  type: manuscript
manuscript:
  meca-bundle: false" > _quarto.yml
gbruer@nathanielU:~/tmp/a$ git remote add origin asdf
gbruer@nathanielU:~/tmp/a$ git ls-files
gbruer@nathanielU:~/tmp/a$ quarto preview .
Preparing to preview
[1/1] index.qmd
ERROR: There is an error while retrieving information from remote 'origin'.
 Git error: fatal: 'asdf' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
. 
 Git status code: 128.

Stack trace:
 Git error: fatal: 'asdf' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
. 
 Git status code: 128.
    at gitHubContext (file:///opt/quarto/bin/quarto.js:80767:31)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Object.filterParams (file:///opt/quarto/bin/quarto.js:102679:39)
    at async projectFilterParams (file:///opt/quarto/bin/quarto.js:51137:45)
    at async filterParamsJson (file:///opt/quarto/bin/quarto.js:50900:12)
    at async runPandoc (file:///opt/quarto/bin/quarto.js:77090:24)
    at async renderPandoc (file:///opt/quarto/bin/quarto.js:78261:26)
    at async Object.onRender (file:///opt/quarto/bin/quarto.js:102479:33)
    at async renderFileInternal (file:///opt/quarto/bin/quarto.js:85780:17)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:85604:17)

```

</details>

**Comment by gbruer15** [comment]
The error is caused by the initialization of `gitHubContext` here: https://github.com/quarto-dev/quarto-cli/blob/c1c5a4308f77fa2674082f41be12446cdcf415fd/src/core/github.ts#L46-L73

Specifically, if `gitHubContext` is created and the directory is a git repository with a remote called `origin`, then it will call `git ls-remote` to see if there is a `gh-pages` branch. As far as I can tell, this branch is only used when publishing, so maybe we could defer the check to publishing time.

@cderv If you think there is a straightforward fix, let me know and I'd be willing to contribute a PR.

**Comment by lentinj** [comment]
As hinted at by @gbruer15, you can work around this by your git repository not having a remote called "origin". Rename the remote to something else with:

```shell
git remote rename origin github
```

Rename will go through and rename all references to the remote, so ``git pull`` and ``git push`` still work without having to retrain your fingers. But github.ts doesn't check what the upstream branch is called, so can no longer find it.

**Comment by nicolas-roelandt** [comment]
@lentinj I tested it and it works, thanks ! Very simple workaround even I think it is still an issue for people that are not git veterans (I'm not able to extrapolate what you did from @gbruer15 comments for example)

**Comment by kwojcik** [comment]
Since Github is having an outage right now, it's currently not possible to render without doing the [workaround](https://github.com/quarto-dev/quarto-cli/issues/10031#issuecomment-2987699754). It also means that you cannot render if you are in a git repo with an `origin` but have no internet connectivity. Having a config flag for this would be great.
