### ISSUE TITLE
Build errors with recent Deno version (1.44)

### ISSUE THREAD

**Issue by trap000d** [quarto-dev/quarto-cli#10150]
### Bug description

Both stable and pre-release versions (at the moment 1.4.556 and 1.5.47 correspondingly) won't build against the Deno 1.44 with the following error message about mismatch between number and bigint:

```
Check file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/src/quarto.ts
error: TS2345 [ERROR]: Argument of type '(args_0: BufferSource | null, args_1: bigint, args_2: BufferSource | null) => void' is not assignable to parameter of type '(srcBuf: Uint8Array, srcLength: number, returnBuf: Uint8Array) => void'.
  Types of parameters 'args_1' and 'srcLength' are incompatible.
    Type 'number' is not assignable to type 'bigint'.
          return genericParse(dylibParseSync, html);
                              ~~~~~~~~~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/src/core/deno-dom.ts:122:31

TS2345 [ERROR]: Argument of type '(args_0: BufferSource | null, args_1: bigint, args_2: BufferSource | null) => void' is not assignable to parameter of type '(srcBuf: Uint8Array, srcLength: number, returnBuf: Uint8Array) => void'.
  Types of parameters 'args_1' and 'srcLength' are incompatible.
    Type 'number' is not assignable to type 'bigint'.
          return genericParse(dylibParseFragSync, html);
                              ~~~~~~~~~~~~~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/src/core/deno-dom.ts:126:31

Found 2 errors.
ERROR: Failure to bundle /var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/src/quarto.ts

Stack trace:
    at bundle (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/package/src/util/deno.ts:40:11)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async prepareDist (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/package/src/common/prepare-dist.ts:129:3)
    at async Command.actionHandler (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/package/src/cmd/pkg-cmd.ts:55:7)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quartoBld (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/package/src/bld.ts:52:3)
    at async mainRunner (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/src/core/main.ts:35:5)
    at async file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.5.47/package/src/bld.ts:56:3
```

The following patch seems "fixes" the issue:

```diff
--- quarto-cli-1.4.556.original/src/core/deno-dom.ts	2024-06-27 08:15:10.000000000 +1200
+++ quarto-cli-1.4.556/src/core/deno-dom.ts	2024-06-27 10:02:37.434536479 +1200
@@ -98,13 +98,13 @@
         const genericParse = (
           parser: (
             srcBuf: Uint8Array,
-            srcLength: number,
+            srcLength: bigint,
             returnBuf: Uint8Array,
           ) => void,
           srcHtml: string,
         ): string => {
           const encodedHtml = utf8Encoder.encode(srcHtml);
-          parser(encodedHtml, encodedHtml.length, returnBufSizeLen);
+          parser(encodedHtml, BigInt(encodedHtml.length), returnBufSizeLen);
 
           const outBufSize = Number(
             new DataView(returnBufSizeLenRaw).getBigUint64(0, !isBigEndian),
```

### Steps to reproduce

N/A

### Expected behavior

Successful package build

### Actual behavior

Errors above

### Your environment

Arch Linux with the most recent updates and clean clean chroot environment (I'm quarto-cli maintainer)

### Quarto check output

N/A

**Comment by cscheid** [comment]
You can't change the version of Deno in Quarto.

**Comment by cscheid** [comment]
I assume Arch can work with a pinned version of Deno, and the quarto-cli package should always explicitly request the version on https://github.com/quarto-dev/quarto-cli/blob/main/configuration.

**Comment by trap000d** [comment]
No problem, this is only to note issues if/when you decide to synchronize Deno version with upstream.

P.S. Unfortunately, there is no easy way to keep a certain package version pinned in Arch. For Quarto, it's currently maintained in AUR ("unofficial"), whereas Deno - in extra ("official"). Effectively, you might assume there are no dependency checks between these repositories.

**Comment by cscheid** [comment]
Thanks. We really want to be running the latest Deno, but we need to wait for this stream redirection issue to be fixed.
