### ISSUE TITLE
Rendering with Typst fails in Quarto 1.5.49 and 1.5.48 (`Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib`)

### ISSUE THREAD

**Issue by mvuorre** [quarto-dev/quarto-cli#10157]
### Bug description

I am rendering this document:

```md
---
title: "Untitled"
format: typst
---

Hello world!
```

It works well with Quarto 1.5.47:

```bash
quarto -v # 1.5.47
quarto render hello-world.qmd
```

```bash
pandoc 
  to: typst
  output-file: hello-world.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Untitled
  
[typst]: Compiling hello-world.typ to hello-world.pdf...DONE

Output created: hello-world.pdf
```

It does not work with Quarto 1.5.48 or 1.5.49:

```bash
quarto -v # 1.5.49
quarto render hello-world.qmd
```

```bash
pandoc 
  to: typst
  output-file: hello-world.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Untitled
  
[typst]: Compiling hello-world.typ to hello-world.pdf...dyld[53008]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <12665645-652B-3D2C-98F8-5A66D2DABB2D> /Applications/quarto/bin/tools/aarch64/typst
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
```

This seems to have something to do with `xz`'s security issues (<https://github.com/orgs/Homebrew/discussions/5243>) and my homebrew install of it.

I can also verify that my system Typst works, but no the one packaged with Quarto:

```bash
typst --version
```

```bash
typst 0.11.1
```

```bash
/Applications/quarto/bin/tools/aarch64/typst --version
```

```bash
dyld[79269]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <12665645-652B-3D2C-98F8-5A66D2DABB2D> /Applications/quarto/bin/tools/aarch64/typst
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
[1]    79269 abort      /Applications/quarto/bin/tools/aarch64/typst --version
```

In case it is informative, here are also the relevant outputs from brew:

```bash
brew list xz
```

```bash
/opt/homebrew/Cellar/xz/5.4.6/bin/lzcat
/opt/homebrew/Cellar/xz/5.4.6/bin/lzcmp
/opt/homebrew/Cellar/xz/5.4.6/bin/lzdiff
/opt/homebrew/Cellar/xz/5.4.6/bin/lzegrep
/opt/homebrew/Cellar/xz/5.4.6/bin/lzfgrep
/opt/homebrew/Cellar/xz/5.4.6/bin/lzgrep
/opt/homebrew/Cellar/xz/5.4.6/bin/lzless
/opt/homebrew/Cellar/xz/5.4.6/bin/lzma
/opt/homebrew/Cellar/xz/5.4.6/bin/lzmadec
/opt/homebrew/Cellar/xz/5.4.6/bin/lzmainfo
/opt/homebrew/Cellar/xz/5.4.6/bin/lzmore
/opt/homebrew/Cellar/xz/5.4.6/bin/unlzma
/opt/homebrew/Cellar/xz/5.4.6/bin/unxz
/opt/homebrew/Cellar/xz/5.4.6/bin/xz
/opt/homebrew/Cellar/xz/5.4.6/bin/xzcat
/opt/homebrew/Cellar/xz/5.4.6/bin/xzcmp
/opt/homebrew/Cellar/xz/5.4.6/bin/xzdec
/opt/homebrew/Cellar/xz/5.4.6/bin/xzdiff
/opt/homebrew/Cellar/xz/5.4.6/bin/xzegrep
/opt/homebrew/Cellar/xz/5.4.6/bin/xzfgrep
/opt/homebrew/Cellar/xz/5.4.6/bin/xzgrep
/opt/homebrew/Cellar/xz/5.4.6/bin/xzless
/opt/homebrew/Cellar/xz/5.4.6/bin/xzmore
/opt/homebrew/Cellar/xz/5.4.6/include/lzma/ (14 files)
/opt/homebrew/Cellar/xz/5.4.6/include/lzma.h
/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib
/opt/homebrew/Cellar/xz/5.4.6/lib/pkgconfig/liblzma.pc
/opt/homebrew/Cellar/xz/5.4.6/lib/ (2 other files)
/opt/homebrew/Cellar/xz/5.4.6/sbom.spdx.json
/opt/homebrew/Cellar/xz/5.4.6/share/doc/ (87 files)
/opt/homebrew/Cellar/xz/5.4.6/share/man/ (23 files)
```

```bash
brew info xz
```

```bash
==> xz: stable 5.4.6 (bottled)
General-purpose data compression with high compression ratio
https://tukaani.org/xz/
Installed
/opt/homebrew/Cellar/xz/5.4.6 (164 files, 2.6MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-06-27 at 10:57:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/x/xz.rb
License: Public Domain and GPL-2.0-or-later
==> Analytics
install: 279,922 (30 days), 875,965 (90 days), 2,978,515 (365 days)
install-on-request: 99,795 (30 days), 269,438 (90 days), 687,518 (365 days)
build-error: 9 (30 days)
```

### Steps to reproduce

Render this document with Quarto 1.5.49

```md
---
title: "Untitled"
format: typst
---

Hello world!
```

```bash
quarto render hello-world.qmd
```

### Expected behavior

A .pdf should be compiled.

### Actual behavior

Command returns

```bash
pandoc 
  to: typst
  output-file: hello-world.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Untitled
  
[typst]: Compiling hello-world.typ to hello-world.pdf...dyld[53008]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <12665645-652B-3D2C-98F8-5A66D2DABB2D> /Applications/quarto/bin/tools/aarch64/typst
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
```

### Your environment

- Using via terminal
- MacOS 14.5
- Homebrew 4.3.7

### Quarto check output

Quarto 1.5.49
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
dyld[81858]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <12665645-652B-3D2C-98F8-5A66D2DABB2D> /Applications/quarto/bin/tools/aarch64/typst
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' (code signature in <1E29DFAD-90C2-3D94-889D-7A212125B52B> '/opt/homebrew/Cellar/xz/5.4.6/lib/liblzma.5.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.49
      Path: /Applications/quarto/bin

error: Uncaught (in promise) Error: Unable to determine Typst version
            throw new Error(`Unable to determine ${name} version`);
                  ^
    at checkVersion (file:///Applications/quarto/bin/quarto.js:101073:19)
    at checkVersions (file:///Applications/quarto/bin/quarto.js:101114:5)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async check (file:///Applications/quarto/bin/quarto.js:101055:13)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:101378:5)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8017:13)
    at async Command.parseCommand (file:///Applications/quarto/bin/quarto.js:7907:20)
    at async quarto (file:///Applications/quarto/bin/quarto.js:118208:9)
    at async file:///Applications/quarto/bin/quarto.js:118227:9
    at async mainRunner (file:///Applications/quarto/bin/quarto.js:118112:9)

**Comment by mcanouil** [comment]
I believe this to exactly the issue discussed in:

- https://github.com/quarto-dev/quarto-cli/discussions/9272#discussioncomment-9010748

**Comment by cscheid** [comment]
@mcanouil This is not the same. If you follow the diagnostic for the version of `typst` we ship with 1.4, we have:

```
$ ./typst --version
typst 0.10.0 (70ca0d25)
$ otool -L typst
typst:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1953.255.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1228.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

The same happens with `typst` 0.11.0. But, with `typst` 0.11.1, this happens:

```
$ otool -L typst
typst:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2420.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1226.0.0)
	/opt/homebrew/opt/xz/lib/liblzma.5.dylib (compatibility version 10.0.0, current version 10.6.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 61123.100.169)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
```

So it seems that typst 0.11.1 is not fully statically linked (!).

**Comment by cscheid** [comment]
@gordonwoodhull I think we need to revert the 0.11.1 change we made.

**Comment by mcanouil** [comment]
> So it seems that typst 0.11.1 is not fully statically linked (!).

On Typst side?

Thanks for the explanation and the otools command!

**Comment by gordonwoodhull** [comment]
Wow, outrageous to ship as an executable in a tarball, and then use dynamic linking! 

It should not cause any trouble to downgrade.

**Comment by cscheid** [comment]
I'm sure it's just an oversight on their part, since 0.11.0 isn't affected either. I'm on their discord and will report back when I know more.

**Comment by mcanouil** [comment]
> It should not cause any trouble to downgrade.

We'll need to reopen the bibliography issue.

- https://github.com/quarto-dev/quarto-cli/issues/10105
