### ISSUE TITLE
YAMLException: expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by llrs** [quarto-dev/quarto-cli#10296]
### Bug description

I am trying to render a basic file that worked a month ago. 
I only updated rstudio and quarto but now I get error messages. 
I have tried the Rstudio qmd file and it still have the same error

### Steps to reproduce

A file like this in project/quarto:

````qmd
---
title: "Untitled"
format: html
---

## Quarto

hi
````

And I have a _quarto.yml with:

```yaml
---
project:
  type: default
  output-dir: quarto
  execute-dir: project
  preview:
    port: 4200
    browser: true
  render:
    - "quarto"
---
```
But I keep getting an error after pressing Render in Rstudio.

### Expected behavior

I would expect that the default example file from Rstudio would render or that the error message were informative

### Actual behavior

I get an error from Rstudio:

```
==> quarto preview untitled1.qmd --to html --no-watch-inputs --no-browse

ERROR: YAMLException: expected a single document in the stream, but found more

Stack trace:
    at load$1 (file:///opt/quarto/bin/quarto.js:17424:11)
    at buildJsYamlAnnotation (file:///opt/quarto/bin/quarto.js:18196:5)
    at readAnnotatedYamlFromMappedString (file:///opt/quarto/bin/quarto.js:18096:16)
    at readAndValidateYamlFromMappedString (file:///opt/quarto/bin/quarto.js:18454:30)
    at readAndValidateYamlFromFile (file:///opt/quarto/bin/quarto.js:20495:50)
    at file:///opt/quarto/bin/quarto.js:73752:32
    at projectContext (file:///opt/quarto/bin/quarto.js:73546:32)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:100720:25)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8017:13)
    at async Command.parseCommand (file:///opt/quarto/bin/quarto.js:7907:20)
```

From the terminal:

```
export QUARTO_PRINT_STACK=true
quarto render untitled1.qmd 
ERROR: YAMLException: expected a single document in the stream, but found more

Stack trace:
    at load$1 (file:///opt/quarto/bin/quarto.js:17424:11)
    at buildJsYamlAnnotation (file:///opt/quarto/bin/quarto.js:18196:5)
    at readAnnotatedYamlFromMappedString (file:///opt/quarto/bin/quarto.js:18096:16)
    at readAndValidateYamlFromMappedString (file:///opt/quarto/bin/quarto.js:18454:30)
    at readAndValidateYamlFromFile (file:///opt/quarto/bin/quarto.js:20495:50)
    at file:///opt/quarto/bin/quarto.js:73752:32
    at projectContext (file:///opt/quarto/bin/quarto.js:73546:32)
    at async render (file:///opt/quarto/bin/quarto.js:82900:19)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:83077:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8017:13)

```

### Your environment

RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.5.54 (/opt/quarto/bin/quarto)

### Quarto check output

I tried

```
quarto check
Quarto 1.5.54
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.54
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 19, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

After `python -m pip install nbclient` when I run again the `quarto check` I get now:

```
quarto check
Quarto 1.5.54
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.54
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

(|) Checking Jupyter engine render....2024-07-15 13:02:58,278 - traitlets - WARNING - Kernelspec name python3 cannot be found!
2024-07-15 13:02:58,278 - traitlets - ERROR - No such kernel named python3
Traceback (most recent call last):
  File "/home/lrevilla@irsicaixa.es/.local/lib/python3.10/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
  File "/home/lrevilla@irsicaixa.es/.local/lib/python3.10/site-packages/jupyter_client/manager.py", line 435, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
  File "/home/lrevilla@irsicaixa.es/.local/lib/python3.10/site-packages/jupyter_client/manager.py", line 397, in _async_pre_start_kernel
    self.kernel_spec,
  File "/home/lrevilla@irsicaixa.es/.local/lib/python3.10/site-packages/jupyter_client/manager.py", line 195, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/lrevilla@irsicaixa.es/.local/lib/python3.10/site-packages/jupyter_client/kernelspec.py", line 285, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3


No such kernel named python3
[✓] Checking Jupyter engine render....OK

ERROR: Error
    at renderFiles (file:///opt/quarto/bin/quarto.js:78081:29)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async render (file:///opt/quarto/bin/quarto.js:82929:21)
    at async checkJupyterRender (file:///opt/quarto/bin/quarto.js:101297:21)
    at async file:///opt/quarto/bin/quarto.js:101261:21
    at async withSpinner (file:///opt/quarto/bin/quarto.js:76250:16)
    at async checkJupyterInstallation (file:///opt/quarto/bin/quarto.js:101257:17)
    at async check (file:///opt/quarto/bin/quarto.js:101072:13)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:101389:5)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8017:13)

```

**Comment by cderv** [comment]
> And I have a _quarto.yml with:
> ```
> ---
> project:
>  type: default
>  output-dir: quarto
>  execute-dir: project
>  preview:
>    port: 4200
>    browser: true
>  render:
>    - "quarto"
> ---
> ```

Could you remove the `---` ? This file is supposed to be YAML file directly, following YAML syntax specification. And `---` means something in YAML - See https://yaml.org/spec/1.2.2/#22-structures

It allows to separate YAML doc in stream, and I believe the parser is really happy with this in the `_quarto.yml`

There should not be any `---` in `_quarto.yml`. If you have seen that somewhere out there, please share with us so we can fix. 

I don't know if we can error better on this so I'll leave this open to have other thoughts (cc @cscheid )

**Comment by llrs** [comment]
Is this! I removed and the sample file rendered without problems. Now it is so obvious. Thank you! 
I am not sure if it came from moving some code from a *.qmd to the _quarto.yaml or some other source. But I don't think it is in the official documentation now that I think of it.
