### ISSUE TITLE
Using lightbox with svg figures

### ISSUE THREAD

**Issue by meierluk** [quarto-dev/quarto-cli#10315]
### Bug description

When using `lightbox: true` and `fig-format: svg`, the lightbox image will have the same size as the original one (i.e., there is no zoom-in). When removing `fig-format: svg` in the code below, everyting works as intended.

### Steps to reproduce

````
---
title: "Untitled"
editor: visual
format: 
  html:
    lightbox: true
    fig-format: svg
---

```{r}
plot(1:10)
```
````

### Expected behavior

There should be a zoom-in effect.

### Actual behavior

No zoom-in effect.

### Your environment

- RStudio 2024.04.2+764 
- Quarto 1.5.54 (C:/Users/meierluk/AppData/Local/Programs/Quarto/bin/quarto.exe)

### Quarto check output

```
Quarto 1.5.54
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.54
      Path: C:\Users\meierluk\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\meierluk\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.0
      Path: C:/Users/meierluk/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 5.7.2
      Kernels: julia-1.9, python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\meierluk\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\meierluk\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
I can't reproduce on `main`:

https://github.com/user-attachments/assets/96ebeb90-bf53-4cb6-9a1c-84f87ab77ba8

**Comment by cderv** [comment]
The difference you see is about default size for the image. The png image as an intrisic size way bigger than the svg, so it shows bigger when "zoomed" because it is using its full size (while in body it was a reduced display sized). 

Probably creating svg with different size, bigger like the png would work. 

Though I am seing that GLightbox offers some size option https://github.com/biati-digital/glightbox/blob/master/README.md#examples but we don't allow those configuration to be passed currently. Only a subset are supported and we need to update our doc about it. Currently what is supported is shown in https://github.com/quarto-dev/quarto-cli/blob/8e357529a50424c6ca876ce92e7457e22b5eb3ed/src/resources/filters/layout/lightbox.lua

So until we support setting size specific to lightbox image, creating bigger images seems to be the way to go. 

Try for example 
- Setting `fig-width` and `fig-height` to create bigger image file
- Set `out-width` to control the display size

````markdown
---
title: "Untitled"
editor: visual
format: 
  html:
    lightbox: true
    fig-format: svg
---

```{r}
#| fig-width: 12
#| fig-height: 7
#| out-width: 80%
plot(1:10)
```

````

![Arc_7a2Las4h9m](https://github.com/user-attachments/assets/d7e8f8a7-d9d6-4c87-bf8c-e8c56011cd6d)

**Comment by meierluk** [comment]
Ok, thanks for the clarification. Such an option would be great (my use case is an existing quarto book with lot's of images, sometimes with custom size).

**Comment by cswingle** [comment]
FWIW, @cderv is correct that you can use fig-width/-height to make the SVG image larger, and thus more effectively display in a lightbox zoom, but that will also result in reducing the size of labels and other graphics objects in the normally displayed figure.

**Comment by cderv** [comment]
yes possibly. Did you try it and notice this ?

**Comment by mcanouil** [comment]
> FWIW, [@cderv](https://github.com/cderv) is correct that you can use fig-width/-height to make the SVG image larger, and thus more effectively display in a lightbox zoom, but that will also result in reducing the size of labels and other graphics objects in the normally displayed figure.

When using SVG and changing the dimensions for generated images using `knitr` as the engine, you can leverage `scaling` from `svglite` and `ragg` packages' graphics devices to avoid this issue.

- In code cells

```
#| dev-args: { scaling: 2 }
```

- In YAML header:

```yaml
knitr:
  opts_chunk:
    dev: "svglite"
    dev-args: { scaling: 2 }
```

---

Full example:

````qmd
---
title: "Quarto Playground"
format: html
engine: knitr
knitr:
  opts_chunk:
    # dev: "ragg_png"
    dev: "svglite"
    dev-args: { scaling: 1 }
lightbox: true
---

```{r}
library(ggplot2)

p <- ggplot(mtcars) +
  aes(mpg, wt) +
  geom_point() +
  labs(
    title = "A scatterplot of mtcars",
    subtitle = "Weight vs. MPG",
    x = "Miles per Gallon",
    y = "Weight (1000 lbs)"
  )
p
```

```{r}
#| dev-args: { scaling: 5 }
#| fig-width: 16
#| fig-height: 10
p
```
````

**Comment by cswingle** [comment]
@mcanouil Brilliant, thanks!

**Comment by AlbertoFabbri93** [comment]
When modifying the default scaling applied to SVG images produced by _svglite_, the default figure dimensions should be adjusted accordingly. What are the default width and height of SVG images generated by _svglite_? Additionally, is it possible to change `fig-width` and `fig-height` only for the svglite-generated images?
