### ISSUE TITLE
`quarto publish accounts` fails when trying to remove an account

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#10395]
### Bug description

I can't remove publishing accounts with `quarto publish accounts`

### Steps to reproduce

```bash
quarto publish accounts
```
Then select one for removal:

https://github.com/user-attachments/assets/bed7e8c8-8db2-4da7-9796-a3673d933038

### Expected behavior

Account should be removed.

### Actual behavior

An error:
```bash
ERROR: SyntaxError: "undefined" is not valid JSON

Stack trace:
    at JSON.parse (<anonymous>)
    at file:///Users/charlottewickham/Documents/posit/quarto-cli/src/command/publish/account.ts:173:34
    at Array.find (<anonymous>)
    at manageAccounts (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/command/publish/account.ts:172:21)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Command.actionHandler (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/command/publish/cmd.ts:154:11)
    at async Command.execute (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/quarto.ts:163:5)
    at async file:///Users/charlottewickham/Documents/posit/quarto-cli/src/quarto.ts:185:5
```

### Your environment

Mac OS Sonoma 14.4

### Quarto check output

```bash
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: ff56839c621fc1fbac2997a38550d4d4f5a939d6
      Path: /Users/charlottewickham/Documents/posit/quarto-cli/package/dist/bin

Check file:///Users/charlottewickham/Documents/posit/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/charlottewickham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /Users/charlottewickham/.pyenv/versions/3.12.2/bin/python3
      Jupyter: 5.7.2
      Kernels: julia-1.10, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources
      LibPaths:
        - /Users/charlottewickham/Library/R/arm64/4.4/library
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Not sure why but I can't see the video, but I can reproduce. Same issue we had in the past with `prompt` and detailed in this discussion 
- https://github.com/quarto-dev/quarto-cli/pull/9765

I know how to fix.
