### ISSUE TITLE
Unable to render Quarto Book to DOCX

### ISSUE THREAD

**Issue by CommunyAS** [quarto-dev/quarto-cli#10427]
### Bug description

I want to render a **Quarto Book** to **DOCX** - but unfortunately it doesn't  work (with RStudio 2024.04.2+764).
I constantly get an error message: `Unable to determine proper path to use when computing bibliography path for index.html.`

This also happens when creating a new Project with Project Type **Quarto Book** with RStudio and only change the default _html_-setting in the `_quarto.yml`to _docx_-setting using  the "standard" settings taken from the [Quarto documentation](https://quarto.org/docs/output-formats/ms-word.html).

This is the code of the  `_quarto.yml`:

```
project:
  type: book

book:
  title: "TEST"
  author: "Norah Jones"
  date: "7/31/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  docx:
    toc: true
    number-sections: true
```
 
This is the error message I get;

```
ERROR: Unable to determine proper path to use when computing bibliography path for index.html.

Stack trace:
    at bookBibliography (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:91299:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async bookBibliographyPostRender (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:91317:52)
    at async Object.bookPostRender [as postRender] (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:91696:9)
    at async renderProject (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:77615:13)
    at async Command.fn (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:98150:46)
    at async Command.execute (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:115004:5)
    at async file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:115022:9
```

If change to HTML-output
```
format:
  html:
    toc: true
    number-sections: true
```
there is no problem, the book is rendered as it should.

Could anyone tell me, how I can render my **Quarto Book** to **DOCX**?
Any help would be much appreciated :-)

### Your environment

- IDE: RStudio  2024.04.2+764
- OS: macOS Sonoma 14.5

### Quarto check output

```
Quarto 1.4.555
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.555
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /opt/homebrew/Cellar/r/4.4.1/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.4/site-library
        - /opt/homebrew/Cellar/r/4.4.1/lib/R/library
      knitr: 1.47
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
FWIW I can't reproduce on windows, starting from `quarto create project book test-book`

So I looked closer to the RStudio IDE scenario.

How are you rendering your book in RStudio IDE ? 

What I found is that, if I open the `index.qmd`, and click render it will call `quarto preview --to html`. 
It does not take into account the only format being specificied which is `docx` in this case. 

**This is only happening before I restart the RStudio IDE after modifying `_quarto.yml` format key**

Can you try updating your `_quarto.yml` with docx format you need, and then Restart IDE and try again ? 

Thank you !

**Comment by cderv** [comment]
So we do have an issue to fix as you get an error when 
````
❯ quarto render --to html
[1/4] index.qmd
[2/4] intro.qmd
[3/4] summary.qmd
[4/4] references.qmd

ERROR: Unable to determine proper path to use when computing bibliography path for index.html.

Stack trace:
    at bookBibliography (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/book/book-bibliography.ts:105:11)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async bookBibliographyPostRender (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/book/book-bibliography.ts:135:48)
    at async Object.bookPostRender [as postRender] (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/book/book-render.ts:614:5)
    at async renderProject (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/project.ts:808:7)
    at async Command.actionHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:163:5)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:185:5
````

and `_quarto.yml` does not have `html` specified in one of the format.

**Comment by CommunyAS** [comment]
> Can you try updating your _quarto.yml with docx format you need, and then Restart IDE and try again ?

I did and you are right. When _quarto.yml is set to docx format and RStudio restarted, the DOCX is rendered as it should.
