### ISSUE TITLE
`quarto publish connect` should surface deployment errors in the log messge

### ISSUE THREAD

**Issue by gadenbuie** [quarto-dev/quarto-cli#10452]
### Bug description

I used `quarto publish connect dashboard.qmd` to deploy a static document to Connect. The document's `title` contained characters that are not allowed as the name of a piece of content on Connect -- `title: "posit::conf()"`.

The output of `quarto publish connect` only said 400 Bad Request, but I believe the actual error is part of the response.

### Steps to reproduce

Attempt to deploy a static document to Connect with an invalid character in the document title name.

### Expected behavior

I don't remember the actual error message, but it was something like this...

```
❯ quarto publish connect dashboard.qmd --log-level debug
? Publish with account: › gadenbuie (https://connect.example.com/)
[✓] Preparing to publish document
ERROR: API Error: 400 - Bad Request: Content title cannot contain invalid characters.

Stack trace:
    at RSConnectClient.handleResponse (file:///Applications/quarto/bin/quarto.js:106512:19)
    at RSConnectClient.fetch (file:///Applications/quarto/bin/quarto.js:106466:25)
```

### Actual behavior

```
❯ quarto publish connect dashboard.qmd --log-level debug
? Publish with account: › gadenbuie (https://connect.example.com/)
[✓] Preparing to publish document
ERROR: API Error: 400 - Bad Request

Stack trace:
    at RSConnectClient.handleResponse (file:///Applications/quarto/bin/quarto.js:106512:19)
    at RSConnectClient.fetch (file:///Applications/quarto/bin/quarto.js:106466:25)
```

### Quarto check output

```
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/garrick/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /Users/garrick/.rye/py/cpython@3.12.2/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources
      LibPaths:
        - /Users/garrick/Library/R/arm64/4.4/library
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by gadenbuie** [comment]
As a feature request, it'd be helpful if `quarto publish connect` could take a `--name` argument; I had to change the title, deploy and then change the title of the published content to get around this limitation.

**Comment by odepjf** [comment]
I am experiencing the same problem publishing a quarto html document
