### ISSUE TITLE
error 500 is appearing again on Quarto Pub

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10461]
Hi, is it possible that this error 500 is appearing again? In my case, I cannot republish a website on quarto-pub, unfortunately. Would appreciate if you have a look into this. Thank you!

_Originally posted by @dani-f in https://github.com/quarto-dev/quarto-cli/issues/7639#issuecomment-2267526375_

**Comment by dsatyavolu** [comment]
I am receiving the same error as well. Message looks something like this:

ERROR: API Error: 500 - Internal Server Error

Stack trace:
    at QuartoPubClient.uploadDeployFile (file:///Applications/quarto/bin/quarto.js:105732:23)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async file:///Applications/quarto/bin/quarto.js:104821:13
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:76250:16)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:104814:5)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:109376:38)
    at async publish7 (file:///Applications/quarto/bin/quarto.js:109595:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:109555:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:109587:13)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:109543:9)

**Comment by mcanouil** [comment]
We are aware of the issue.
There is not need to comment with the error.
A simple reaction (with the reaction button) is enough.

We'll update here as soon as we have something to share thus if we share nothing it means we have no updates to provide.

Sorry for the inconvenience and thank you for your cooperation and patience.

**Comment by davidkane9** [comment]
Apologies to be a bother, but any updates? My 40 students are presenting their final projects on Thursday: https://bootcamp.davidkane.info/

I teach them to use Quarto Pubs, which is wonderful! But if this issue might persist, we need to pivot to Github Pages.

**Comment by dani-f** [comment]
Good news, it seems to work again. Thanks for working on this!

**Comment by mcanouil** [comment]
The incident with Quarto Pub service is now resolved!
Thanks for your patience!

**Comment by senthilkumarm1901** [comment]
Is the 500 error occurring again? 

```
[✓] Preparing to publish site
ERROR: API Error: 500 - Internal Server Error

Error: API Error: 500 - Internal Server Error
    at QuartoPubClient.uploadDeployFile (file:///Applications/quarto/bin/quarto.js:111404:23)
    at async file:///Applications/quarto/bin/quarto.js:109037:13
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:56612:9)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:109030:5)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:121220:38)
    at async publish5 (file:///Applications/quarto/bin/quarto.js:121438:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:121394:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:121405:9)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:121382:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
```

**Comment by mcanouil** [comment]
Thanks for the report. The team is looking into it. Reopening.

**Comment by mcanouil** [comment]
@senthilkumarm1901 Could you try again now?

**Comment by senthilkumarm1901** [comment]
Sorry, my bad. Once I got out of VPN, it worked I suppose. Thanks for your reply @mcanouil !

**Comment by mcanouil** [comment]
Not you, some services were actually down.
