### ISSUE TITLE
Error when using `quarto-live` format with `_metadata.yml` in blog

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#10544]
### Bug description

Using a `posts/_metadata.yml` file with options for `html` format in a Quarto blog causes an error with the `live-html` format from the `quarto-live` extension.

### Steps to reproduce

I created a reproducible example here: <https://github.com/maxdrohde/quarto_bug_test>

using the following steps.

1. Create the default blog with `quarto create project blog myblog`
2. Install `quarto-live` with `quarto add r-wasm/quarto-live`
3. Modify the `posts/_metadata.yml` and `posts/post-with-code/index.qmd` file
4. Run `quarto render`

###  `posts/_metadata.yml`

````
format: 
  html:
    toc: true
````

### `posts/post-with-code/index.qmd`

````
---
title: "Post With Code"
author: "Harlow Malloc"
date: "2024-08-17"
categories: [news, code, analysis]
image: "image.jpg"
engine: jupyter
format: live-html
---

```{webr}
for (x in 1:5) {
  print(x ** 2)
}
```
````

### Actual behavior

When I remove the `_metadata.yml` file, `quarto render` works.

When I have the `_metadata.yml` file and I run `quarto render`, I receive the following error.

```
❯ quarto render
[1/4] posts/post-with-code/index.qmd

Starting python3 kernel...Done

Executing 'index.quarto_ipynb'


Starting python3 kernel...Done

Executing 'index.quarto_ipynb'

[2/4] posts/welcome/index.qmd
[3/4] index.qmd
[4/4] about.qmd

ERROR: NotFound: No such file or directory (os error 2): rename '/Users/max/Desktop/myblog/posts/post-with-code/index.html' -> '/Users/max/Desktop/myblog/_site/posts/post-with-code/index.html'

Stack trace:
    at Object.renameSync (ext:deno_fs/30_fs.js:267:3)
    at renderProject (file:///Applications/quarto/bin/quarto.js:78512:22)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:83077:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8017:13)
    at async Command.parseCommand (file:///Applications/quarto/bin/quarto.js:7907:20)
    at async quarto (file:///Applications/quarto/bin/quarto.js:118224:9)
    at async file:///Applications/quarto/bin/quarto.js:118244:9
    at async mainRunner (file:///Applications/quarto/bin/quarto.js:118128:9)
    at async file:///Applications/quarto/bin/quarto.js:118235:5
```

Also, I notice that Quarto tries to render the file twice? Maybe this is part of the issue that `html` and `live-html` are somehow being misinterpreted by Quarto?

### Your environment

- MacOS: Version 14.5 (23F79)

### Quarto check output

```bash
❯ quarto check
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: 5.3.0
      Kernels: ir, julia-1.6, julia-1.8, julia-1.9, juliapro_v1.5.0-1-1.5, julia-1.5, julia-12-threads-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
That's not a bug.
That's because of metadata merging described in <https://quarto.org/docs/projects/quarto-projects.html>.

**Comment by cderv** [comment]
For reference, this is about this issue
- https://github.com/quarto-dev/quarto-cli/issues/4583
