### ISSUE TITLE
Unable to render: "quarto render temp.py" 

### ISSUE THREAD

**Issue by MarkEdmondson1234** [quarto-dev/quarto-cli#10570]
### Bug description

I have this temp.py:

```python
# %% [markdown]
# ---
# title: Palmer Penguins
# author: Norah Jones
# date: 3/12/23
# ---

# %%
#| echo: false
print("hello")

# %% [markdown]
"""
## Exploring the data

See @fig-bill-sizes for an exploration of bill sizes by species.
"""
```

When I try to render it I get an error:

```bash
quarto render temp.py
ERROR: Unable to render temp.py

Error: Unable to render temp.py
    at fileExecutionEngineAndTarget (file:///Applications/quarto/bin/quarto.js:58031:15)
    at renderFiles (file:///Applications/quarto/bin/quarto.js:86522:52)
    at async render (file:///Applications/quarto/bin/quarto.js:90681:21)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:90856:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:127545:5)
    at async file:///Applications/quarto/bin/quarto.js:127563:9
```

I am in the right folder:

```bash
cat temp.py
# %% [markdown]
# ---
# title: Palmer Penguins
# author: Norah Jones
# date: 3/12/23
# ---

# %%
#| echo: false
print("hello")

# %% [markdown]
"""
## Exploring the data

See @fig-bill-sizes for an exploration of bill sizes by species.
"""%                              
```

.qmd files in same folder render ok:

```bash
quarto render tmp1ghwwbkt.qmd 

Starting python3 kernel...Done

Executing 'tmp1ghwwbkt.ipynb'
  Cell 1/1...Done

pandoc 
  to: html
  output-file: tmp1ghwwbkt.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Agent Basics
  
Output created: tmp1ghwwbkt.html
```

I tried the example at https://quarto.org/docs/computations/render-scripts.html and that also does not render with same error.

### Steps to reproduce

See above

### Expected behavior

Rendered .py script

### Actual behavior

Error.

### Your environment

- Mac OS 14.2.1 (23C71)

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /Users/mark/dev/sunholo/quarto-agent/.venv/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mark/Library/R/x86_64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.40
      rmarkdown: 2.17

[✓] Checking Knitr engine render......OK
```

**Comment by MarkEdmondson1234** [comment]
I thought I had latest version, but I did not - upgrading to 1.5.56 solved the issue. Party.
