### ISSUE TITLE
Broken build to PDF with kableExtra:

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#10584]
### Bug description

I have the following document:

~~~markdown
# A book

```{r, tbl-my-table}
df <- as.data.frame(matrix(runif(n=10, min=1, max=20), nrow=5))
kableExtra::kable_styling(kableExtra::kable(df, caption = 'Text {text}'))
```
~~~

with `_quarto.yml`:

```yaml
project:
  type: book

book:
  chapters:
    - index.Rmd
```

When I build with:

```bash
quarto render --no-cache --to pdf
```

I get the following error:

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Misplaced \cr.
\reserved@c ->\ifnum 0=`{}\fi \cr 
                                  
l.241 \toprule
               

see /Users/mb312/dev_trees/min-quarto-pdf/index.log for more information.
ERROR: Error
    at Object.onComplete (file:///Users/mb312/dev_trees/quarto-cli/src/project/types/book/book-render.ts:317:15)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async renderFiles (file:///Users/mb312/dev_trees/quarto-cli/src/command/render/render-files.ts:346:12)
    at async renderProject (file:///Users/mb312/dev_trees/quarto-cli/src/command/render/project.ts:441:23)
    at async Command.actionHandler (file:///Users/mb312/dev_trees/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///Users/mb312/dev_trees/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///Users/mb312/dev_trees/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async quarto (file:///Users/mb312/dev_trees/quarto-cli/src/quarto.ts:163:5)
    at async file:///Users/mb312/dev_trees/quarto-cli/src/quarto.ts:185:5
    at async mainRunner (file:///Users/mb312/dev_trees/quarto-cli/src/core/main.ts:35:5)
make: *** [book] Error 1
```

I do not get the error:

* Building with `rmarkdown::render('index.Rmd', 'pdf_document')`
* Without the `kableExtra::kable_styling()` wrapper
* Without text in curly braces in the caption.

### Steps to reproduce

```
git clone https://github.com/matthew-brett/min-quarto-pdf
cd min-quarto-pdf
make
```

### Expected behavior

The PDF should build without error.

### Actual behavior

See error message above.

### Your environment

- Macos Sonoma 14.6.1, running on command line.

### Quarto check output

```bash
﻿﻿Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: 39dc173c4869ebaf4d6bb087a972acb87533b64e
      Path: /Users/mb312/dev_trees/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.14
      Path: /Users/mb312/.virtualenvs/resampling-with/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, ir, xibabel

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /opt/homebrew/Cellar/r/4.4.1/lib/R
      LibPaths:
        - /Users/mb312/Library/R/arm64/4.4/library
        - /opt/homebrew/lib/R/4.4/site-library
        - /opt/homebrew/Cellar/r/4.4.1/lib/R/library
      knitr: 1.47
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

Running on latest `quarto-cli/quarto`, commit 39dc173c4.

**Comment by mcanouil** [comment]
Use `keep-md: true` and `keep-te: true` to investigate what is produced and where the issue is.

**Comment by matthew-brett** [comment]
Aha - I assume you were not able to reproduce from my minimal example?

**Comment by mcanouil** [comment]
I did not try.

The issue is that kableExtra changes the output of kable which can block Quarto from doing its thing.
You can see that using the options I mentioned. Note that those options are the best way to debug your code.

The issue in your code is the use of caption arg.
In Quarto, you should use `tbl-cap:` code cell option.


I am pretty sure your issue is a duplicate of another issue or discussion.

**Comment by matthew-brett** [comment]
I think you will find, if you do try to reproduce, that any text inside
curly brackets, including the correct table label, leads to the same error.
  I conclude this is not a bug in my code, but a bug in Quartos handling of
kableExtra.  Maybe you can persuade me otherwise?

**Comment by mcanouil** [comment]
>   I conclude this is not a bug in my code,

Did you look at the markdown/latex code "you" are producing before concluding (i.e., using the `keep-*` option)?

**Comment by mcanouil** [comment]
For instance, look at the markdown intermediate file produced. I added the format argument because `kableExtra` is limited to HTML/LaTeX which is not the case of `knitr::kable()`.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
title: "Diagram"
format: pdf
keep-md: true
keep-tex: true
---

# A book

```{r}
#| label: tbl-my-table
df <- as.data.frame(matrix(runif(n=10, min=1, max=20), nrow=5))
knitr::kable(df, caption = 'Text {text}', format="latex")
```
````

</td><td>

````qmd
\begin{table}

\caption{\label{tab:tbl-my-table}Text {text}}
\centering
\begin{tabular}[t]{r|r}
\hline
V1 & V2\\
\hline
14.315128 & 2.367047\\
\hline
16.087185 & 16.611381\\
\hline
5.635114 & 10.688894\\
\hline
8.373245 & 7.887350\\
\hline
1.900025 & 15.203564\\
\hline
\end{tabular}
\end{table}
````

</td></tr>
</table>

You are taking over the cross-reference system blocking Quarto to do its job here.
Also, look at what is happening to your brackets. That's not Quarto.

Now `kableExtra` does not produce the exact same thing and produce one of the worst float environment in LaTeX, namely `longtable`.

<table>
<tr><th>Input</th><th>Markdown Output</th><th>LaTeX Output</th></tr>
<tr><td>

````qmd
---
title: "Diagram"
format: pdf
keep-md: true
keep-tex: true
---

# A book

```{r}
#| label: tbl-my-table
df <- as.data.frame(matrix(runif(n=10, min=1, max=20), nrow=5))
kableExtra::kable_styling(knitr::kable(df, caption = 'Text {text}'))
```

````

</td><td>

````md
\begin{longtable}[t]{rr}
\caption{\label{tab:tbl-my-table}Text {text}}\\
\toprule
V1 & V2\\
\midrule
17.696599 & 16.883892\\
1.352881 & 6.215979\\
3.500358 & 1.579606\\
6.053643 & 11.094220\\
17.200911 & 4.474271\\
\bottomrule
\end{longtable}
````

</td><td>

```latex
\begin{longtable}[t]{rr}

\caption{\label{tbl-my-table}Text \{text}

\tabularnewline

}\\
\toprule
V1 & V2\\
\midrule
17.696599 & 16.883892\\
1.352881 & 6.215979\\
3.500358 & 1.579606\\
6.053643 & 11.094220\\
17.200911 & 4.474271\\
\bottomrule

\end{longtable}
````

</td></tr>
</table>

As you can see, Quarto is trying to make the cross-reference while you also ask to do it yourself. In the process, Quarto fails to parse the table and remove a piece of it leading to the error message because of the extra bracket which as is cannot be displayed in LateX anyway.

So, yes there is a table parsing bug, but no, you won't get the desired behaviour anyway.
What you'll get is:

> Raw LaTeX table found with non-tbl label: tab:tbl-my-table
> Won't be able to cross-reference this table using Quarto's native crossref system.

and this:

<img width="225" alt="image" src="https://github.com/user-attachments/assets/c51e899d-cc36-41db-8c31-14b9b7817c17">


Note that `knitr::kable` and `kableExtra` have options to control what is emitted.
For instance, setting the format in `knitr::kable` avoid `kableExtra` to use `longtable`, thus avoid Quarto failing to parse the table.

<table>
<tr><th>Input</th><th>"Expected" Output</th></tr>
<tr><td>

````qmd
---
format: pdf
keep-md: true
keep-tex: true
---

```{r}
#| label: tbl-my-table
df <- as.data.frame(
  matrix(
    runif(n = 10, min = 1, max = 20),
    nrow = 5
  )
)
kableExtra::kable_styling(knitr::kable(
  x = df,
  caption = "Text {text}",
  format = "latex"
))
```
````

</td><td>

<img width="719" alt="image" src="https://github.com/user-attachments/assets/1234f97a-0a95-4519-a7b7-8c37a38e8e24">

</td></tr>
</table>

**Comment by cscheid** [comment]
To rephrase what @mcanouil is saying.

`kableExtra` does something that's fundamentally incompatible with Quarto's handling of crossreferences: it emits a crossreferencing environment of its own (`longtable`, a LaTeX environment that increments its own counters). That makes it impossible for Quarto to use its own crossreferencing environments. Quarto needs to do so because Quarto supports a more general class of crossreferencing situations: you can put a table inside a Figure, you can create custom crossref environments, etc.

Moreover, `longtable` is a fundamentally broken LaTeX package. It always increments the `table` counter specifically, and there's no way to disable it. So, every time some library emits `longtable` code, Quarto needs to go into "workaround mode"

When Quarto detects that a library emitted its own crossreferencing environment, what Quarto does is attempt to detect different parts of the LaTeX code: where the caption could be, where the label could be, where the beginning and end of environment could be, etc.

As you well know, this is fundamentally impossible, because TeX is not a programming language with an AST that can be traversed meaningfully.

So our technique is necessarily heuristic, and breaks. That's what you're seeing.

Possible solutions:

- do not use `kableExtra` in Quarto crossreferencing code cells (that is, move the label assignment to the code, and then use raw LaTeX crossreferences instead of Quarto)
- convince `kableExtra` to not use `longtable`
- convince `longtable` to fix their hardcoded `table` counter

**Comment by mcanouil** [comment]
> convince kableExtra to not use longtable

Setting the format in `kable()` will emit `table`.
Additionally, there are options in `kableExtra` to control the output including the environment.

**Comment by matthew-brett** [comment]
Thanks for the explanation - but - just to clarify - you seem to be saying this is a fault in the heuristic to find the caption in the longtable output, but you've put "wontfix" on it.  Is that because you do not intend to improve the heuristic?

**Comment by mcanouil** [comment]
Labels are for us.

What you should consider is the "expected output" you are looking for with the code you shared.
See my example.

The highly recommended way to get crossreference and caption is to use Quarto feature and syntax, namely using the code cell options: `label: tbl-XXXX` and `fig-cap: Your caption`.
What Carlos is saying is that there is a working and a guarantee that the syntax I mentioned should work but that's not really doable to try to define an heuristic for every possible very weird syntax that is possible in LaTeX and longtable.

**Comment by cscheid** [comment]
> Is that because you do not intend to improve the heuristic?

Yes, currently I'm not confident that I will be able to fundamentally improve it (the regression suite is full of testimonies of my previous hubris in this particular area...)

**Comment by matthew-brett** [comment]
Summarizing for my own understanding:

* Curly-braces in captions will break `kableExtra` styling, because this styling (by default) generates a longtable LaTeX environment, and Quarto's heuristics to adjust the generated LaTeX code generate broken LaTeX, when the caption has curly braces.
* The general solution is not to put curly braces in the caption with `kableExtra`.  This is no great burden as the label for cross-referencing should in any case be in the code-cell options, not the caption.
* If, for some reason, I do want curly braces in the caption, I can put the caption in the code cell options with `fig.cap=` (although I see this generates captions below the figure, not with the figure name).

For example, this works (with the priviso the caption will look different from other tables):

~~~
# A book

```{r tbl-my-table, fig.cap="Text {text}"}
df <- as.data.frame(matrix(runif(n=10, min=1, max=20), nrow=5))
kableExtra::kable_styling(kableExtra::kable(df)
)
```

See @tbl-my-table.
~~~

**Comment by mcanouil** [comment]
> If, for some reason, I do want curly braces in the caption

Did you look at the final example of <https://github.com/quarto-dev/quarto-cli/issues/10584#issuecomment-2304662133>?
Your code won't let you have brackets anyway. That's not Quarto, that's LaTeX.

> I can put the caption in the code cell options with fig.cap= (although I see this generates captions below the figure, not with the figure name).

Quarto uses and recommends the YAML syntax for code cells:

````qmd
```{r tbl-my-table, fig.cap="Text {text}"}
````

Becomes

````qmd
```{r}
#| label: tbl-my-table
#| fig-cap: "Text {text}"
````

Note that you should use `tbl-cap` for tables.
See code-cells options for `knitr`: https://quarto.org/docs/reference/cells/cells-knitr.html

Quarto offers ways to control position of caption such as `tbl-cap-location`, see <https://quarto.org/docs/reference/formats/pdf.html#layout>.
