### ISSUE TITLE
quarto attempts to write into a read-only loction under /usr/local

### ISSUE THREAD

**Issue by yurivict** [quarto-dev/quarto-cli#10680]
### Bug description

I am attempting to port Quarto to FreeBSD.

Quarto is installed in /usr/local/share/quarto which is a read-only location.

For some reason Quarto attempts to write under /usr/local/share:
```
$ quarto render hello.qmd --to pdf

Executing 'hello.quarto_ipynb'
  Cell 1/1: 'fig-polar'...Done

pandoc 
  to: latex
  output-file: hello.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Quarto Basics
  jupyter: python3
  

Rendering PDF
running xelatex - 1
command xelatex not found, attempting install
finding package for xelatex
> 1 package to install
> installing xelatex (1 of 1)
ERROR: [non-error-thrown] tlmgr returned a non zero status code
You don't have permission to change the installation in any way,
specifically, the directory /usr/local/share/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.


Stack trace:
You don't have permission to change the installation in any way,
specifically, the directory /disks/disk1/local/share/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.

    at Command.handleError (file:///usr/local/share/quarto/bin/quarto.js:8185:126)
    at Command.parseCommand (file:///usr/local/share/quarto/bin/quarto.js:7910:18)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async quarto (file:///usr/local/share/quarto/bin/quarto.js:118803:9)
    at async file:///usr/local/share/quarto/bin/quarto.js:118823:9
    at async mainRunner (file:///usr/local/share/quarto/bin/quarto.js:118707:9)
    at async file:///usr/local/share/quarto/bin/quarto.js:118814:5
```

Do you know how to prevent this?
Is it possible to change this location to under the current user's home directory?

Thank you,
Yuri

### Your environment

FreeBSD 14.1

### Quarto check output

n/a

**Comment by yurivict** [comment]
The problem was that tex-xetex wasn't installed.

**Comment by mcanouil** [comment]
@yurivict Could you open a GitHub Discussion rather than issues next time? Thank you.

**Comment by cscheid** [comment]
The good behavior would be for Quarto to check for the existence of the path/etc.

**Comment by yurivict** [comment]
The problem was that some TeX/LaTeX package wasn't installed, and LaTeX was attempting to download and install ut under local/share/tlpkg.

IMO, the core problem is that Quarto doesn't have the installation procedure that would be useful for packagers, among others.

Dependency checks should be performed during the installation procedure.

For example, in the FreeBSD port we take the binary distribution of Quarto and copy it into proper location under $PREFIX while replacing binary dependencies with FreeBSD binary dependencies.

IMO, Quarto should be able to perform such installation by itself using its source tree, and locating proper dependencies.
Dependency checking should be performed in this installation procedure.

**Comment by cscheid** [comment]
> Dependency checks should be performed during the installation procedure.

That's not how Quarto is intended to work. We don't want these packages to be installed until they're necessary (and they'll become necessary by virtue of being used in a document that needs rendering)

We don't package Quarto in FreeBSD ourselves, and so you're entitled to change the behavior, but I would very strongly prefer you didn't, because that will by itself cause a lot of confusion and bug reports for us.

**Comment by yurivict** [comment]
> We don't package Quarto in FreeBSD ourselves, and so you're entitled to change the behavior, but I would very strongly prefer you didn't, because that will by itself cause a lot of confusion and bug reports for us.

Users who need to install Quarto have no other choice but install from the package that we will provide.
Otherwise, like you said, you don't package Quarto so that users don't have a choice to download it themselves.
And even if you would provide the Quarto as a binary package this wouldn't work in the context of system using packages.
RStudio now uses Quarto to format documents, and Quarto needs to be packaged (not just downloaded) as a dependency of the RStudio package.

**Comment by cscheid** [comment]
Quarto itself shouldn't require a TeX installation, in the same way that Quarto doesn't require R or Python or Julia. (We _do_ package `typst` because it's a single statically-linked binary. TeX, in contrast, is a monstrosity of a system)

We can consider providing a mechanism for the dependency installation code to be OS-specific. All that code is currently in https://github.com/quarto-dev/quarto-cli/blob/950768f104f130ae4fc6b60e78efc1c6f5dff285/src/command/render/latexmk/pkgmgr.ts; it should be possible for us to be cleverer, and I'm willing to help with a design around it.

**Comment by yurivict** [comment]
Thank you, @cscheid .

There should be a script that would accept true/false choices for all optional dependencies that Quarto has.
The caller of this script would decide which dependencies he wants, and this script should check that these dependencies are present, and it should re-create a correct directory structure for Quarto under a given $PREFIX and $DESTDIR.

In the context of a FreeBSD package we allow the user to select what port options he wants, and these options would be passed to this script as arguments.

Having such script would greatly facilitate adoption of Quarto by packaging systems, because this is how most users install software nowadays.

**Comment by yurivict** [comment]
TeX and LaTeX packages can't be installed at run-time because they are installed into the red-only location under /usr/local.

**Comment by cscheid** [comment]
We can still have a os-specific path that communicates what the user needs to call so that those are installed, and then fails with a more understandable error message.
