### ISSUE TITLE
Custom cross reference code chunk does not reference correctly

### ISSUE THREAD

**Issue by ddlawton** [quarto-dev/quarto-cli#10831]
### Bug description

I am trying to have four cross references for a scientific publication: tabel, figure, supplementary table, and supplementary figure. Table and Figure references works as expected, however when I try to cross reference supplementary type references, I receive these errors:

````
WARNING (/Applications/quarto/share/filters/main.lua:13900) Unable to resolve crossref @supptbl-sample-data
WARNING (/Applications/quarto/share/filters/main.lua:13900) Unable to resolve crossref @suppfig-sample-data
WARNING (/Applications/quarto/share/filters/main.lua:13900) Unable to resolve crossref @supptbl-sample-data
WARNING (/Applications/quarto/share/filters/main.lua:13900) Unable to resolve crossref @suppfig-sample-data
````

I am not sure what is happening here. Thanks!

### Steps to reproduce

````
---
title: Minimal Example
number-sections: true
crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Supplementary Figure
      space-before-numbering: true
      latex-list-of-description: Supplementary Figure
    - kind: float
      key: supptbl
      latex-env: supptbl
      reference-prefix: Supplementary Table
      space-before-numbering: true
      latex-list-of-description: Supplementary Table
bibliography: references.bib
csl: citation_style.csl
---

## Introduction

Let's reference @tbl-sample-data.

Let's reference @supptbl-sample-data.

Let's reference @fig-sample-data

Let's reference @suppfig-sample-data

## Referencing tables

### tbl reference

```{r}
#| label: tbl-sample-data
#| tbl-cap: "Sample table caption."
#| layout-nrow: 1

library(gt)

data <- data.frame(
  Column1 = c("A", "B", "C"),
  Column2 = c(1, 2, 3)
)

data |> 
  gt() |> 
  fmt_number(columns = vars(Column2), decimals = 2)
```




```{r}
#| label: supptbl-sample-data
#| tbl-cap: "Sample table caption."
#| layout-nrow: 1

library(gt)

data <- data.frame(
  Column1 = c("A", "B", "C"),
  Column2 = c(1, 2, 3)
)

data |> 
  gt() |> 
  fmt_number(columns = vars(Column2), decimals = 2)
```

## Referencing Figures

### fig reference


```{r}
#| label: fig-sample-data
#| layout-nrow: 1

library(gt)
library(ggplot2)

data <- data.frame(
  Column1 = c("A", "B", "C"),
  Column2 = c(1, 2, 3)
)

ggplot(data,aes(x=Column1,y=Column2)) + geom_point()

```


### suppfig reference

```{r}
#| label: suppfig-sample-data
#| fig-cap: "Sample table caption."
#| layout-nrow: 1

library(gt)
library(ggplot2)

data <- data.frame(
  Column1 = c("A", "B", "C"),
  Column2 = c(1, 2, 3)
)

ggplot(data,aes(x=Column1,y=Column2)) + geom_point()

```

````

### Expected behavior

Four cross reference types

### Actual behavior

Two cross reference types (table and figures, which are the default references) work but the two custom cross references do not work.

### Your environment

- IDE VScode: 1.76.2 
- MacOS Sonoma 14.6.1

### Quarto check output

````
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ddlawton/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.3 (Conda)
      Path: /Users/ddlawton/opt/anaconda3/bin/python
      Jupyter: 4.6.3
      Kernels: python3

(\) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 19, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
Yes - in these cases you have to use the div syntax, as we describe in the docs.

**Comment by cscheid** [comment]
https://quarto.org/docs/authoring/cross-references-divs.html

(in the future, please consider starting a discussion first to make sure you understand the parts involved. Thanks!)
