### ISSUE TITLE
Including a landscape document makes all pages landscape

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#10843]
### Bug description

Including a landscape document makes all pages rendered as landscape

### Steps to reproduce

1. Create file "paper.qmd" with this content

```
---
title: "My document"
---

# Introduction

This page is rendered in landscape mode, but should be rendered in portrait mode.

# Tables

\newpage

{{< include Table1.qmd >}}
```

2. Create file  "Table1.qmd"  with this content:
```
---
format:
  pdf:
    papersize: A4
    classoption: [landscape]
---

\addtocounter{table}{1}

|country                | 2013| 2014| 2015| 2016| 2017| 2018| 2019| 2020| 2021| 2022| 2023|
|:----------------------|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|
|Albania                |   12|   10|   18|   13|   21|   31|   22|   14|    6|    6|    1|

: Startups per country per year
```

3. Compile file "paper.qmd"
```
quarto render paper.qmd
```

### Expected behavior

The first page should  be in portrait

### Actual behavior

All pages are in landscape

### Your environment

- CLI
- Arch Linux
```
➜  quarto --version
1.5.57
```

```
➜  pandoc  --version
pandoc 3.1.9
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/raffaele/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

### Quarto check output

```bash
➜  quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.6
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: ir, python3

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 19, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

**Comment by raffaem** [comment]
Related #8512

**Comment by raffaem** [comment]
> Related #8512

The solution provided there does not work, moreover `kee-tex: true` seems to remove the tex file regardless if there is an `include` in the document

**Comment by cscheid** [comment]
Metadata is not scoped - it applies to the entire document. When you include a document that has metadata, the "includer" ends up getting the metadata for the entirety of the document.

Consider using the feature described here: https://github.com/quarto-dev/quarto-cli/pull/10581

**Comment by cscheid** [comment]
In the future, please use the discussion forum to ask questions before filing a bug report.
