### ISSUE TITLE
Typst rule does not work on markdown table

### ISSUE THREAD

**Issue by oliviermeslin** [quarto-dev/quarto-cli#10872]
### Bug description

I want to define a show rule to center the first row of the table. The rule works on a Typst table (embedded in a Typst chunk), but does not work on a Markdown table. I'm not sure I'm using Typst properly though.

### Steps to reproduce

````
---
format:
  typst:
    keep-typ: true
---

```{=typst}
// This rule does work on both tables
#show table.cell.where(y: 0): set text(weight: "bold")

// This rule does not work on the Markdown table
#show table.cell.where(y: 0): set align(center)
```

```{=typst}
#table(
  columns: (0.4fr, 1fr, 1fr, 1fr),

  table.header[Month][Title][Author][Genre],
  [January], [The Great Gatsby], [F. Scott Fitzgerald], [Classic],
  [February], [To Kill a Mockingbird], [Harper Lee], [Drama],
  [March], [1984], [George Orwell], [Dystopian],
  [April], [The Catcher in the Rye], [J.D. Salinger], [Coming-of-Age],
)
```

| Month    | Title                  | Author              | Genre         |
|:---------|:-----------------------|:--------------------|:--------------|
| January  | The Great Gatsby       | F. Scott Fitzgerald | Classic       |
| February | To Kill a Mockingbird  | Harper Lee          | Drama         |
| March    | 1984                   | George Orwell       | Dystopian     |
| April    | The Catcher in the Rye | J.D. Salinger       | Coming-of-Age |

````

### Expected behavior

The first row of the markdown table is centered.

### Actual behavior

The first row of the markdown table is not centered.

### Your environment

- OS: Linux
- VS Code, code-server: v4.92.2 Code: 1.92.2

### Quarto check output

````
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/onyxia/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5 (Conda)
      Path: /opt/conda/bin/python
      Jupyter: 5.7.2
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK

````

**Comment by cscheid** [comment]
Please consider a Q&A post before filing a bug report. I'm going to convert this to discussions.
