### ISSUE TITLE
altair plots not showing in revealjs render?

### ISSUE THREAD

**Issue by Bonnevie** [quarto-dev/quarto-cli#10903]
I'm trying to write some plot-heavy slides with Quarto rendering to RevealJS, and I am using python and `altair` for plotting. I'm coding in VSCode. 
I get the impression from the documentation that altair should work, and I believe I've also been able to do it before rendering to html.
But now, the plots are not showing on render. I found an error in the console log that is most likely related
```
Uncaught TypeError: vegaEmbed is not a function
    at displayChart (this_is_your_db.html:420:7)
    at Object.execCb (require.min.js:1:16727)
    at e.check (require.min.js:1:10499)
    at e.<anonymous> (require.min.js:1:12915)
    at require.min.js:1:1542
    at require.min.js:1:13376
    at each (require.min.js:1:1020)
    at e.emit (require.min.js:1:13344)
    at e.check (require.min.js:1:11058)
    at e.enable (require.min.js:1:13242)
```

This is the code in the html, within a script tag (truncated)

```html
  <script type="text/javascript">
      var VEGA_DEBUG = (typeof VEGA_DEBUG == "undefined") ? {} : VEGA_DEBUG;
      (function(spec, embedOpt) {
          let outputDiv = document.currentScript.previousElementSibling;
          if (outputDiv.id !== "altair-viz-f5a273b5c427426c987b81d42dfa2ddc") {
              outputDiv = document.getElementById("altair-viz-f5a273b5c427426c987b81d42dfa2ddc");
          }
          const paths = {
              "vega": "https://cdn.jsdelivr.net/npm/vega@5?noext",
              "vega-lib": "https://cdn.jsdelivr.net/npm/vega-lib?noext",
              "vega-lite": "https://cdn.jsdelivr.net/npm/vega-lite@5.20.1?noext",
              "vega-embed": "https://cdn.jsdelivr.net/npm/vega-embed@6?noext",
          };

          function maybeLoadScript(lib, version) {
              var key = `${lib.replace("-", "")}_version`;
              return (VEGA_DEBUG[key] == version) ? Promise.resolve(paths[lib]) : new Promise(function(resolve, reject) {
                  var s = document.createElement('script');
                  document.getElementsByTagName("head")[0].appendChild(s);
                  s.async = true;
                  s.onload = () => {
                      VEGA_DEBUG[key] = version;
                      return resolve(paths[lib]);
                  }
                  ;
                  s.onerror = () => reject(`Error loading script: ${paths[lib]}`);
                  s.src = paths[lib];
              }
              );
          }

          function showError(err) {
              outputDiv.innerHTML = `<div class="error" style="color:red;">${err}</div>`;
              throw err;
          }

          function displayChart(vegaEmbed) {
              vegaEmbed(outputDiv, spec, embedOpt).catch(err => showError(`Javascript Error: ${err.message}<br>This usually means there's a typo in your chart specification. See the javascript console for the full traceback.`));
          }

          if (typeof define === "function" && define.amd) {
              requirejs.config({
                  paths
              });
              require(["vega-embed"], displayChart, err => showError(`Error loading script: ${err.message}`));
          } else {
              maybeLoadScript("vega", "5").then( () => maybeLoadScript("vega-lite", "5.20.1")).then( () => maybeLoadScript("vega-embed", "6")).catch(showError).then( () => displayChart(vegaEmbed));
          }
      }
<!-- TRUNCATED --!>
</script>
```

Is this a RevealJS limitation?

My python versions are 
- Altair at 5.4.1

Quarto version is 1.5.57

I did find a non-ideal workaround, namely to render to `png` by calling `altair.renderers.enable("png")`

**Comment by cderv** [comment]
@Bonnevie any more information to share on this one ? Thank you

**Comment by Bonnevie** [comment]
@cderv sorry, I had some other things I needed to attend to, but went back and tried to do an MWE. I use `.qmd` format, not using a project I think.
In short, this code below replicates the issue.

````markdown
---
title: "Testing Altair in RevealJS"
format:
  # html: {} # this works when viewed in external browser, but not always in VSCode preview
  revealjs: 
    theme: default
    slide-number: true
    preview-links: auto
  
---

## Test Altair
```{python}
import pandas as pd
import altair as alt


df = pd.DataFrame({"x": ["a", "b", "c"], "y": [1,2, 3], "c": [-1, 0, 1]})
alt.Chart(df).mark_bar().encode(x="x", y="y", color="c", tooltip=["c"]).properties(width=500)
```

altair version: `{python} alt.__version__`
````

BUT I am now observing that it renders correctly every second time I hit render? So half the time I get this:
![image](https://github.com/user-attachments/assets/3b1e048f-3960-470b-aae1-c302f01c666e)
and half the time I get this:
![image](https://github.com/user-attachments/assets/d6eb607d-1d11-4229-b69e-132314f254b6)
(literally two renders in quick succession)

**Comment by mcanouil** [comment]
Seems related if not a duplicate of https://github.com/quarto-dev/quarto-cli/issues/2891

**Comment by cderv** [comment]
Thanks a lot for the example. I don't know if this is rendering twice, or just related somehow to browser loading and caching. 

In my case, first render is getting me the plot but then if I click reload in the opened browser (CTRL + R) then it does not show, with this error in the console 
````
index.html:390 Uncaught TypeError: vegaEmbed is not a function
    at displayChart (index.html:390:7)
    at Object.execCb (require.min.js:1:16727)
    at e.check (require.min.js:1:10499)
    at e.<anonymous> (require.min.js:1:12915)
    at require.min.js:1:1542
    at require.min.js:1:13376
    at each (require.min.js:1:1020)
    at e.emit (require.min.js:1:13344)
    at e.check (require.min.js:1:11058)
    at e.enable (require.min.js:1:13242)
````

So somehow something is not right when loading dependency after the first revealjs loading. 

Possibly related to other JS conflict we have with require.min.js too... 🤔 

Won't be easy to debug... 😞

**Comment by Bonnevie** [comment]
@cderv "happy" to hear that the example was reproducible on your machine. Dependency load order sounds plausible, but a bit too deep in the weeds for me to have anything intelligent to say about the matter unfortunately...  Hope a fix can be found, was otherwise a pretty enjoyable way to author slides with plots 😃

**Comment by Bonnevie** [comment]
@cderv can you tell the bot that an example was added previously? 😄

**Comment by thielem** [comment]
Hi! I do get the same error with all render types.
This is the output in the console for HTML and revealjs.

```js
(Index):129 Uncaught TypeError: vegaEmbed is not a function
    at displayChart ((Index):129:7)
    at Object.execCb (require.min.js:1:16727)
    at e.check (require.min.js:1:10499)
    at e.<anonymous> (require.min.js:1:12915)
    at require.min.js:1:1542
    at require.min.js:1:13376
    at each (require.min.js:1:1020)
    at e.emit (require.min.js:1:13344)
    at e.check (require.min.js:1:11058)
    at e.enable (require.min.js:1:13242)
```

The error does not occur all the time, and it is mostly stable on my local machine (1/10 error rate), but it happens almost all the time (99/100) on my work server, which runs Ubuntu.

I am testing this with this example plot:
```python
---
title: "Test Altair"
echo: false
format: revealjs
jupyter: python3

---

## Test Altair
```{python}

#| title: Iowa Electricity
import altair as alt
from vega_datasets import data
source = data.iowa_electricity()
alt.Chart(source).mark_area(opacity=0.3).encode(
  x="year:T",
  y=alt.Y("net_generation:Q").stack(None),
  color="source:N"
)
\```
```

**Comment by thielem** [comment]
Thanks for the tip! I can confirm that it is quite stable in Firefox.
However, as long as #2891 is open, the SVG render is the nicer option anyway, so I will stick to it for now.
Looking forward to interactive plots working with revealjs at some point, this would be great!

**Comment by cderv** [comment]
@rpruim shared some interesting Revealjs plugin in https://github.com/quarto-dev/quarto-cli/issues/2891#issuecomment-2675390289: 

Someone did a specific handling in Revealjs plugin to make vegaEmbed works. 
https://github.com/dainiak/revealjs-plugins/blob/main/reveal-custom/plugins/vega-embed.js?rgh-link-date=2025-02-21T19%3A37%3A30.000Z

I don't know if this would work with quarto, but it gives some hint.
