### ISSUE TITLE
Deno sometimes SEGVs when the command 'quarto render tufte.qmd --to html' is executed, and sometimes there is a JSON parsing error

### ISSUE THREAD

**Issue by yurivict** [quarto-dev/quarto-cli#10920]
### Bug description

The problem occurs on the [tufte.qmd](https://github.com/quarto-dev/quarto-gallery/blob/main/page-layout/tufte.qmd) example.

Example of SEGV:

```
$ quarto render tufte.qmd --to html

processing file: tufte.qmd
1/29                        
2/29 [fig-margin]           
3/29                        
4/29 [fig-fullwidth]        
5/29                        
6/29 [fig-main]             
7/29                        
8/29 [fig-main-margin-cap]  
9/29                        
10/29 [unnamed-chunk-5]      
11/29                        
12/29 [fig-two-together]     
13/29                        
14/29 [fig-two-separate]     
15/29                        
16/29 [fig-margin-together]  
17/29                        
18/29 [unnamed-chunk-8]      
19/29                        
20/29 [fig-margin-separate-a]
21/29                        
22/29 [unnamed-chunk-10]     
23/29                        
24/29 [unnamed-chunk-11]     
25/29                        
26/29 [unnamed-chunk-12]     
27/29                        
28/29 [unnamed-chunk-13]     
29/29                        
output file: tufte.knit.md

pandoc 
  to: html
  output-file: tufte.html
  standalone: true
  self-contained: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  reference-location: margin
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: A Quarto Page Layout Example
  subtitle: 'Inspired by Tufte Handout, Using Quarto'
  date: '`r Sys.Date()`'
  citation-location: margin
  bibliography:
    - skeleton.bib
  grid:
    margin-width: 350px
  
/usr/local/bin/quarto: line 170: 42675 Segmentation fault      "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_MAP_ARG}" "${QUARTO_TARGET}" "$@"
```

Example of JSON parsing error:
```
$ quarto render tufte.qmd --to html

processing file: tufte.qmd
1/29                        
2/29 [fig-margin]           
3/29                        
4/29 [fig-fullwidth]        
5/29                        
6/29 [fig-main]             
7/29                        
8/29 [fig-main-margin-cap]  
9/29                        
10/29 [unnamed-chunk-5]      
11/29                        
12/29 [fig-two-together]     
13/29                        
14/29 [fig-two-separate]     
15/29                        
16/29 [fig-margin-together]  
17/29                        
18/29 [unnamed-chunk-8]      
19/29                        
20/29 [fig-margin-separate-a]
21/29                        
22/29 [unnamed-chunk-10]     
23/29                        
24/29 [unnamed-chunk-11]     
25/29                        
26/29 [unnamed-chunk-12]     
27/29                        
28/29 [unnamed-chunk-13]     
29/29                        
output file: tufte.knit.md

pandoc 
  to: html
  output-file: tufte.html
  standalone: true
  self-contained: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  reference-location: margin
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: A Quarto Page Layout Example
  subtitle: 'Inspired by Tufte Handout, Using Quarto'
  date: '`r Sys.Date()`'
  citation-location: margin
  bibliography:
    - skeleton.bib
  grid:
    margin-width: 350px
  
ERROR: SyntaxError: Unexpected token '', ""... is not valid JSON

Stack trace:
    at JSON.parse (<anonymous>)
    at fragmentNodesFromString (file:///usr/local/share/quarto/bin/quarto.js:25613:25)
    at Element1.set innerHTML (file:///usr/local/share/quarto/bin/quarto.js:25136:28)
    at processTableMarginCaption (file:///usr/local/share/quarto/bin/quarto.js:121551:31)
    at file:///usr/local/share/quarto/bin/quarto.js:121588:21
    at NodeList.forEach (<anonymous>)
    at NodeList.forEach (file:///usr/local/share/quarto/bin/quarto.js:21992:19)
    at processMarginCaptions (file:///usr/local/share/quarto/bin/quarto.js:121564:20)
    at processColumnElements (file:///usr/local/share/quarto/bin/quarto.js:121410:5)
    at file:///usr/local/share/quarto/bin/quarto.js:121318:49
```

### Your environment

FreeBSD 14.1

### Quarto check output

```
$ quarto check
Quarto 1.6.15
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.49.8: OK
      Deno version 1.46.2: OK
      Typst version 0.11.1: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.15
      Path: /usr/local/share/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.10
      Path: /usr/local/bin/python3.11
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK

```

**Comment by mcanouil** [comment]
Working fine (20 times) using proper Quarto installation on macOS , see <https://github.com/quarto-dev/quarto-cli/blob/main/configuration>.

**Comment by cscheid** [comment]
Which distribution of Quarto is this? Unfortunately, if this is using a bundled version that's not ours, we cannot promise any support.

**Comment by mcanouil** [comment]
It's FreeBSD and again a build using not validated Deno version `Deno version 1.46.2`.
