### ISSUE TITLE
Confluence exports fails updating document with diagram after the first upload

### ISSUE THREAD

**Issue by fkgruber** [quarto-dev/quarto-cli#10947]
### Bug description

I have a document with text and graphviz diagrams. The first time I upload the confluence it works fine. However, if I try to upload again (say I make a change in the text) then it crashes with the error below. This does not happen if I remove the diagrams. Can anyone replicate this behavior?
The only way to fix this problem is to open the _publish.yml file and remove the lines corresponding to this submission.

### Steps to reproduce

---
format: confluence-html
title: Test diagram new title
author: Me
---

This is a diagram

another change
asdf

```{dot}
  graph G {
  layout=neato
  run -- intr;
  intr -- runbl;
  runbl -- run;
  run -- kernel;
  kernel -- zombie;
  kernel -- sleep;
  kernel -- runmem;
  sleep -- swap;
  swap -- runswap;
  runswap -- new;
  runswap -- runmem;
  new -- runmem;
  sleep -- runmem;
}
```
```{dot}
digraph D {

  A -> {B, C, D} -> {F}

}
```

### Expected behavior

it should update the confluence document

### Actual behavior

get error

> ERROR: API Error: 404 - Not Found
> 
> Stack trace:
>     at ConfluenceClient.handleResponse (file:///Applications/quarto/bin/quarto.js:108210:19)
>     at ConfluenceClient.fetch (file:///Applications/quarto/bin/quarto.js:108015:25)
>     at eventLoopTick (ext:core/01_core.js:153:7)
>     at async updateContent (file:///Applications/quarto/bin/quarto.js:108454:30)
>     at async doOperation (file:///Applications/quarto/bin/quarto.js:108589:33)
>     at async withSpinner (file:///Applications/quarto/bin/quarto.js:76250:16)
>     at async doWithSpinner (file:///Applications/quarto/bin/quarto.js:107563:12)
>     at async publishDocument (file:///Applications/quarto/bin/quarto.js:108600:13)
>     at async Object.publish5 [as publish] (file:///Applications/quarto/bin/quarto.js:108741:49)
>     at async publishDocument (file:///Applications/quarto/bin/quarto.js:109503:38)

### Quarto check output

quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.8 (Conda)
      Path: /Users/fgruber/miniconda3/bin/python
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26.1

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
A search of our issues for "confluence update" shows this as a top-level hit: https://github.com/quarto-dev/quarto-cli/issues/9407

In the future, please try to search for existing issues before filing a new one.
