### ISSUE TITLE
ERROR: TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by cfreder2** [quarto-dev/quarto-cli#11019]
### Bug description

I have the Quarto Extension Enabled. 

I made a very simple test.qmd file in that produces the ERROR: TypeError: Cannot read properties of undefined (reading 'toLowerCase') when previewing the notebook in Positron.  

**Working Quarto Example (No python code block):**

---
title: "Untitled"
format: html
---

Test

**Failing Quarto Example (HAS a python code block):**
---
title: "Untitled"
format: html
---

Test

```{python}
i=10
```

### Steps to reproduce

---
title: "Untitled"
format: html
---

Test

```{python}
i=10
```

### Expected behavior

Quarto Renders HTML page served locally

### Actual behavior

quarto preview test.qmd --no-browser --no-watch-inputs
ERROR: TypeError: Cannot read properties of undefined (reading 'toLowerCase')

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at jupyterKernelspecFromMarkdown (file:///Applications/quarto/bin/quarto.js:53170:41)
    at async quartoMdToJupyter (file:///Applications/quarto/bin/quarto.js:53021:36)
    at async createNotebookforTarget (file:///Applications/quarto/bin/quarto.js:55428:16)
    at async Object.target (file:///Applications/quarto/bin/quarto.js:55221:18)
    at async fileExecutionEngineAndTarget (file:///Applications/quarto/bin/quarto.js:58033:20)
    at async renderContexts (file:///Applications/quarto/bin/quarto.js:82635:34)
    at async renderFormats (file:///Applications/quarto/bin/quarto.js:82688:26)
    at async previewFormat (file:///Applications/quarto/bin/quarto.js:102399:36)
    at async preview (file:///Applications/quarto/bin/quarto.js:102303:20)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:103770:9)

### Your environment

Positron (2024.08.0 (Universal) build 83).
Python 3.12.0
IPython 8.17.2

### Quarto check output

quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: /usr/local/bin/python3.12
      Jupyter: 5.5.0
      Kernels: ir, sparkrkernel, powershell, pysparkkernel, sparkkernel, python3

[✓] Checking Jupyter engine render....OK

**Comment by cscheid** [comment]
```
Version: 1.3.450
```

Can you please upgrade to 1.5.57 or later? That's two stable versions behind.

**Comment by mcanouil** [comment]
@cfreder2 for future bug reports, please do read the guidelines (provided at the top when filling an issue), especially about formatting code. Your report is almost ineligible as is and not useful as we can't see/use it.
