### ISSUE TITLE
Inline reference with custom prefix expanded differently in LaTeX and  HTML output

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#11092]
### Bug description

Consider the following MWE:

```
---
title: "My title"
format:
  pdf: default
  html: default
---

# Section 1

See [TABLE @tbl-letters]:

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: My Caption {#tbl-letters}
```

If you render it to PDF, the `TABLE` in the inline reference does not contain a hyperlink:
![Image](https://github.com/user-attachments/assets/07eb9cc3-55df-44e7-8791-3232a4cc2384)

But if you render it to HTML, it does:
![Image](https://github.com/user-attachments/assets/f7e3318c-e2f3-4646-947d-648e7bba8865)

### Steps to reproduce

See above

### Expected behavior

Both versions should contain a hyperlink

### Actual behavior

HTML output contains a hyperlink, but PDF output does not

### Your environment

- IDE: RStudio: 2024.09
- OS: Arch Linux

### Quarto check output

```bash
Quarto 1.5.57

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK

[✓] Checking versions of quarto dependencies......OK

[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin


(|) Checking tools....................
(/) Checking tools....................[2K[G
[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)


(|) Checking LaTeX....................
(/) Checking LaTeX....................
(-) Checking LaTeX....................
(\) Checking LaTeX....................
(|) Checking LaTeX....................[2K[G
[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined


(|) Checking basic markdown render....
(/) Checking basic markdown render....
(-) Checking basic markdown render....
(\) Checking basic markdown render....[2K[G
[✓] Checking basic markdown render....OK


(|) Checking Python 3 installation....[2K[G
[✓] Checking Python 3 installation....OK
      Version: 3.12.7
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: ir, python3


(|) Checking Jupyter engine render....
(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[2K[G
[✓] Checking Jupyter engine render....OK

```

**Comment by mcanouil** [comment]
That's not a bug, that's LaTeX behaviour.

**Comment by raffaem** [comment]
I think we have to replace
```
See Table~\ref{tbl-letters}:
```

with
```
See \hyperref[tbl-letters]{Table 1}.
```
in the resulting LaTeX file.

See [here](https://tex.stackexchange.com/questions/70143/cross-reference-with-custom-text)

**Comment by cscheid** [comment]
Our formats are not intended to be exactly identical to each other. In PDF specifically, we choose the rendering that is most common for pdflatex documents. We'd like to support the ability to customize the behavior, but we don't consider it a bug.
