### ISSUE TITLE
filename argument not working for ojs code blocks

### ISSUE THREAD

**Issue by ryanzomorrodi** [quarto-dev/quarto-cli#11203]
### Bug description

When using the `filename` argument within an ojs code block, the ojs filename is not added.

![Image](https://github.com/user-attachments/assets/b9636901-2869-4d84-80b7-45d951824241)

### Steps to reproduce

````qmd
---
title: "No ojs file name :("
format: html
---

```{r filename = "R"}
ojs_define(iris = iris)
```

```{ojs filename = "ojs"}
iris
```
````

### Quarto check output

Quarto 1.6.30
[✓] Checking environment information...
      Quarto cache location: /home/user/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.30
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/user/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2 (Conda)
      Path: /home/user/miniconda3/bin/python
      Jupyter: 5.7.2
      Kernels: python3

Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK

**Comment by mcanouil** [comment]
It works for R code cell by "accident" I believe.

From the documentation, it is said "code blocks" so not code cells (i.e., computational code blocks).

The code below won't have any filename.

````qmd
---
title: "No ojs file name :("
format: html
---

```{python filename="Python"}
print("Hello World")
```

```{ojs filename="ojs"}
print("Hello World")
```
````

**Comment by mcanouil** [comment]
This being said, code cells should not have attributes set in the brackets, only the language should be there.
Use YAML instead.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
title: "No ojs file name :("
format: html
---

```{r}
#| filename: R
ojs_define(iris = iris)
```

```{ojs}
//| filename: ojs
iris
```

````

</td><td>

![Image](https://github.com/user-attachments/assets/757b10b2-e035-4bcd-8b60-003fc2caa4af)


</td></tr>
</table>

**Comment by ryanzomorrodi** [comment]
Ahh, that makes sense! I assumed that putting the attributes within the brackets was interchangeable, but guess not. Thank you

**Comment by mcanouil** [comment]
Let's reopen because:
- it might still be a bug
- if it's not then we could improve the documentation about filename to include an example

**Comment by cderv** [comment]
> It works for R code cell by "accident" I believe.

It works for R because of **knitr** historic syntax. Doing 
````markdown
```{r filename = "R"}
ojs_define(iris = iris)
```
````
is equivalent to 
````markdown
```{r}
#| filename: R
ojs_define(iris = iris)
```
````

But this is true only for **knitr** and why this syntax is not recommended to use. 

> if it's not then we could improve the documentation about filename to include an example

We should definitely add an example in the doc about `filename` for computational code cell: https://quarto.org/docs/output-formats/html-code.html#code-filename. I think this is supported as a feature.

> it might still be a bug

I don't thing though. Using `attributes` on computational code cell is not a supported syntax. It should be in cell option. 

@cscheid you labelled as ojs-engine problem, but I think this is working properly as when using in-cell YAML syntax it works ok as shown in @mcanouil example: https://github.com/quarto-dev/quarto-cli/issues/11203#issuecomment-2439636675

**Comment by ryanzomorrodi** [comment]
Totally makes sense that the historical syntax works because of knitr.

If you are not thinking of how the quarto document is being rendering, it is a little confusing that the knitr historical syntax works for R code cells AND python cells IF there is an R cell also within the notebook, but not python cells alone or ojs cells ever.

**Comment by mcanouil** [comment]
> If you are not thinking of how the quarto document is being rendered, it is a little confusing that the knitr historical syntax works for R code cells AND python cells IF there is an R cell also within the notebook, but not python cells alone or ojs cells ever.


That's the engine detection. If there is an R code cell, knitr is used for all code cells (you cannot mix engines as documented).
For all other cases, Quarto uses Jupyter with the default/standard Python kernel.
