### ISSUE TITLE
Cannot render multiple Mermaid diagrams to PDF using Quarto 1.5.57

### ISSUE THREAD

**Issue by dsbitor** [quarto-dev/quarto-cli#11202]
### Quarto will not render two or more Mermaid diagrams to a PDF

Works to HTML

**Using  Quarto 1.5.57 which had a fix for this problem** identified August 2024.

### Steps to reproduce

---
title: "Mermaid Test Diagrams"
date: last-modified

format: 
  pdf:
    documentclass: scrreprt
    papersize: letter
    monofontoptions: 
       - Scale=0.75
   
---

------------------------------------------------------------------------

# Mermaid Diagrams - Rendering Multiple Diagrams 

## Simple Flowchart

```{mermaid}
flowchart LR
   A-->B
```

### Notes

Renders correctly if only one diagram

### Second Mermaid Diagram

If a second Mermaid diagram if included Quarto does not render either diagram.

```{mermaid}
flowchart LR
   Y-->Z
```

### Notes 

The above does not render: After a long period times out with message:

```
error: Top-level await promise never resolved
    await mainRunner(async (args)=>{
    ^
    at <anonymous> (file:///Applications/quarto/bin/quarto.js:118235:5)
```

### Expected behavior

Not consciously changed anything

### Actual behavior

In the past this worked after upgrading to Quarto 1.5.57

## Quarto Check Output

```
quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/davidbanham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /Users/davidbanham/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
See <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>.

**Comment by dsbitor** [comment]
Code Bocks for  YAML Header and Markdown with two mermaid diagrams plus text in the test file:

````
title: "Mermaid Test Diagrams"
date: last-modified

format:
pdf:
documentclass: scrreprt
papersize: letter
monofontoptions:
- Scale=0.75
````

````
# Mermaid Diagrams - Rendering Multiple Diagrams 

## Simple Flowchart

```{mermaid}
flowchart LR
   A-->B
```

### Notes

Renders correctly if only one diagram


### Second Mermaid Diagram

If a second Mermaid diagram if included Quarto does not render either diagram.


```{mermaid}
flowchart LR
   Y-->Z
```

### Notes 

The above does not render: After a long period times out with message:

```
error: Top-level await promise never resolved
    await mainRunner(async (args)=>{
    ^
    at <anonymous> (file:///Applications/quarto/bin/quarto.js:118235:5)
```

````

**Comment by mcanouil** [comment]
@dsbitor please make an effort to properly format your code.
I provided an example and a link showing how to do it.

---

If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
See <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>.

**Comment by dsbitor** [comment]
Updated original report with back ticks as requested and added computer environment

**Comment by mcanouil** [comment]
I cannot reproduce with the development version using:

````qmd
---
title: "Quarto Playground"
format: pdf
---

```{mermaid}
flowchart LR
   A-->B
```

```{mermaid}
flowchart LR
   A-->B
```
````

````
❯ quarto preview index.qmd --no-browser --no-watch-inputs
pandoc 
  to: latex
  output-file: index.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - \KOMAoption{captions}{tableheading}
  block-headings: true
  title: Quarto Playground
  

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  

Output created: index.pdf

Watching files for changes
Browse at http://localhost:6180/web/viewer.html
````

**Comment by dsbitor** [comment]
**Downloaded and installed  Quarto 1.6.30 ran `quarto check' Output Below**

 **Did not make any difference**

````
quarto check
Quarto 1.6.30
[✓] Checking environment information...
      Quarto cache location: /Users/davidbanham/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.30
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/davidbanham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /Users/davidbanham/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

````

**Comment by mcanouil** [comment]
Could you try reinstalling chromium via Quarto as it seems you are using it?

**Comment by snirye** [comment]
Im facing the same issue with `format: pptx`.
quarto version version 1.6.30

**Comment by dsbitor** [comment]
**Deleted both Google Chrome and Chromium from Apps and Reinstalled  Google Chrome. Deleted and reinstalled Quarto 1.6.30.
I cannot seer that Quarto installed Chromium (and see Chromium in Apps folder) where should it install as part of Quarto folder or  as a separate App?. In addition, based on Activity Monitor monitoring of active apps Quarto Render appears to start Google Chrome, and it never completes. Note I had not activated Google Chrome**

**Comment by dsbitor** [comment]
**Marking  needs-repro** Issues that are blocked until reporter provides an adequate reproduction  [yesterday](https://github.com/quarto-dev/quarto-cli/issues/11202#event-14906566526)

**The example given is a valid syntax minimal quarto document.**

1. It's a well known fact that a developers system may well run a solution while a users will not.
2. The error message is clearly from the Quarto environment. 
3. I am sorry [mcanouil], (https://github.com/mcanouil) butI feel you are 'Cicking the can down the road! '
4. Every request for information and activity has been promptly provided** 
5. You now have two users reporting.

**Comment by dsbitor** [comment]
I am sorry the last post was terse.

I really appreciate the care and attention the Posit puts into the development, update and problem resolution for their software and apps. Please do not take the comments above top be a criticism, rather just analysis of a problem!

I have been a user of RStudio and various other Posit tools since 2011.

David S. Banham,  IT Operational Risk Ltd. Canada

**Comment by mcanouil** [comment]
> **Marking needs-repro** Issues that are blocked until reporter provides an adequate reproduction [yesterday](https://github.com/quarto-dev/quarto-cli/issues/11202#event-14906566526)
> 
> **The example given is a valid syntax minimal quarto document.**
> 
> 1. It's a well known fact that a developers system may well run a solution while a users will not.
> 2. The error message is clearly from the Quarto environment.
> 3. I am sorry [mcanouil], (https://github.com/mcanouil) butI feel you are 'Cicking the can down the road! '
> 4. Every request for information and activity has been promptly provided
> 5. You now have two users reporting.

This feels inappropriate and borderline (see [Code of Conduct](https://github.com/quarto-dev/quarto-cli?tab=coc-ov-file), especially because you assume some meaning for a label that is part of an internal workflow.
I am running nearly the same environment as you beside being on Sequoia and as I said, I cannot reproduce the issue you have (see <https://github.com/quarto-dev/quarto-cli/issues/11202#issuecomment-2439630406>), this means "needs-repro" for the Quarto team.
Not providing a reproducible example could also be a reason for the label, but obviously this was not the reason here.

---

I asked about chromium-based install because that's a possible cause of the issue.
Installing chromium via Quarto means to install a local (to Quarto) Chromium.
Quarto can also use Chrome or Edge (automatically detected).
Since very recently (in the future 1.6.31 Release Candidate I believe), there is `QUARTO_CHROMIUM` environment variable allowing to use any chromium-based browser. For instance, I'm using Brave.

There are two PRs that are not part of 1.6.30:

- #11187
- #11195

The future 1.6.31 Release Candidate might be the fix you need.

**Comment by dsbitor** [comment]
mcanouil, First sorry, i read the pop-up behind the needs-repro and read the comment literally... Did not realize it had POSIT specific internal problem resolution context and  meaning. 

Second i would be happy to try with Brave as the browser / renderer and blow away Google Chrome for the test!  Do I require QUARTO_CHROMIUM environment variable to be set and to what value?

**Comment by mcanouil** [comment]
No need to use Brave.
Unless, you are willing to try the development version, I would suggest to wait a bit for the new pre-release to be built (likely during next week).

**Comment by dsbitor** [comment]
Thanks will wait - while Mermaid diagrams are relatively important they are not essential to my current work.

Thank you also for your prompt attention. Will stay on Quarto 1.6.30  update to future prelease versions as they become available, and get on with try main task.

**Comment by mcanouil** [comment]
Not that 1.6 entered Release Candidate state as we approach a release.

To explain the issue in general terms, Mermaid diagrams are rendered via JavaScript. This works natively for HTML-based documents, but for static formats such as PowerPoint, Word, LaTeX, or Typst, Mermaid cannot be rendered. Instead, Quarto uses chromium-based browsers to open the mermaid diagram and "take a screenshot" which is then used.

As you can see in one of the PR, I linked, it seems the browser is not properly closed. This could be a reason why it cannot be reached a second time in your case.

**Comment by mcanouil** [comment]
@snirye thabks for checking

See the PRs I've linked in https://github.com/quarto-dev/quarto-cli/issues/11202#issuecomment-2440116759

**Comment by cderv** [comment]
This went far in discussion ! 😅 Sorry to be late to the party 😉 

@dsbitor @snirye To sump up the situation: 

* Quarto leverages chromium feature to do some screenshot of mermaid HTML to PNG so that it can be included in non HTML format. 
* This means Quarto highly depends on the version of chromium you used. By default Quarto will use the chrome binary found on your system. **So in case of such problem, you should check your chrome version**. 
* A precision on `quarto install chromium`: it is currently used as last resort when no chrome or edge, is found on the system by Quarto. It is a very old version that we don't update often. 

* What happens is that Chrome v130 seems to have changed some things that make the new Headless mode introduced by default in Chrome v128 usable for now with Quarto. So we did pin to `--headless=old` in Quarto v1.6.30 so that old  mode is used, which is known to be working. So yes @snirye you found the story. 

* For helping getting users unstuck in case of new situation like that (and to help user on OS we don't detect chrome one), we've added a `QUARTO_CHROMIUM` variable that could be set by user to use a specific version they have. 

Hope this helps clarify. 

@snirye I can't reproduce your issue using Quarto 1.6.30 and also using latest chrome version 
Here is the document I used
````
---
title: "Mermaid Test Diagrams"
date: last-modified
format: 
  pdf:
    documentclass: scrreprt
    papersize: letter
    monofontoptions:
      - Scale=0.75
---

# Mermaid Diagrams - Rendering Multiple Diagrams 

## Simple Flowchart

```{mermaid}
flowchart LR
   A-->B
```

### Notes

Renders correctly if only one diagram


### Second Mermaid Diagram

If a second Mermaid diagram if included Quarto does not render either diagram.


```{mermaid}
flowchart LR
   Y-->Z
```

### Notes 

The above does not render: After a long period times out with message:

```
error: Top-level await promise never resolved
    await mainRunner(async (args)=>{
    ^
    at <anonymous> (file:///Applications/quarto/bin/quarto.js:118235:5)
```

````

Please do check you chrome version, and be sure to use Quarto 1.6.30 as 1.5.57 won't work for sure with recent chrome.

**Comment by snirye** [comment]
Im using chrome Version 130.0.6723.70 (Official Build) (arm64) on MacOS

**Comment by cderv** [comment]
> i used quarto 1.6.30 and it didnt worked.
it did after i used the development version

Thanks for confirming. It was misleading of me. 1.6.30 does not have the fix, we did not build a new version after   #11187 as I thought. 1.6.31 will have it. 

Glad it is solved !

**Comment by mcanouil** [comment]
> I asked about chromium-based install because that's a possible cause of the issue. Installing chromium via Quarto means to install a local (to Quarto) Chromium. Quarto can also use Chrome or Edge (automatically detected). Since very recently (in the future 1.6.31 Release Candidate I believe), there is `QUARTO_CHROMIUM` environment variable allowing to use any chromium-based browser. For instance, I'm using Brave.
> 
> There are two PRs that are not part of 1.6.30:
> 
> * [Better Handle new chrome #11187](https://github.com/quarto-dev/quarto-cli/pull/11187)
> * [ensure that a chromium process started by Quarto is always closed #11195](https://github.com/quarto-dev/quarto-cli/pull/11195)
> 
> The future 1.6.31 Release Candidate might be the fix you need.

FYI

**Comment by dsbitor** [comment]
Upgraded to Quarto Quarto 1.6.32 today 2024-11-01 - Problem resolved - believe based on observation if Chrome was called multiple times in same document to render diagrams the first call to Chrome did not close / return. Chrome timed out on my Mac after about 10 to fifteen minutes.
