### ISSUE TITLE
quarto render fails when enabling self-contained or embed-resources in yaml

### ISSUE THREAD

**Issue by eeenilsson** [quarto-dev/quarto-cli#11206]
### Bug description

Problem: quarto render fails when enabling self-contained or embed-resources in yaml.

Steps to reproduce:

1. In terminal: 
`> quarto create project book testbook`
2. Add the following to _quarto.yml (any of these options produce same error):
```
format:
  html:
    self-contained: true
    embed-resources: true
```

3. Add to any qmd file:

```
```{r } 
#| label: test-plot

plot(1:10, 1:10)

```

4. `> quarto render`

Result in error:
    
```
ERROR: 
compilation failed- error
Unable to load picture or PDF file 'intro_files/figure-pdf/test-plot-1.pdf'.
```

...and warning:

`[WARNING] Could not fetch resource ./summary.html`

Works when option `quarto render --to html` is used. Curiously, `quarto render --to pdf `also works if run separately.

System info:

quarto --version: 1.5.57 on Arch linux
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)

### Expected behavior

`quarto render` should produce html and pdf book

### Actual behavior

`quarto render` fails
`quarto render --to html` and `quarto render --to pdf` works

### Your environment

Linux Version: 6.9.2.arch1-1
quarto --version: 1.5.57 on Arch linux
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
R version 4.4.0 

### Quarto check output

` > quarto check`

Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/e/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK

**Comment by mcanouil** [comment]
`self-contained` is the outdated name.
You should only use `embed-resources` as documented.

Book project using HTML are multi-page site.
As with Website project, `embed-resources` cannot really work.

**Comment by eeenilsson** [comment]
Thanks for the input! However, embed resources gives the same error.

Den lör 26 okt. 2024 20:08Mickaël Canouil ***@***.***> skrev:

**Comment by mcanouil** [comment]
Yes, as I explained, it's not supposed to be used for multi-pages project such as book/website.

**Comment by eeenilsson** [comment]
Ok, that explains it then! Thanks for the clarification.

Den lör 26 okt. 2024 21:36Mickaël Canouil ***@***.***> skrev:

**Comment by mcanouil** [comment]
I'm reopening because there's might be something to be done here to improve things.

**Comment by eeenilsson** [comment]
Ok, gret. It is a bit curious that using the --to options work. It's also seems to work with multi page webpages.

**Comment by bastienchassagnol** [comment]
Similar issue here: single `qmd` file, with option `embed-resources: true` is rendered as a standalone HTML file. Yet, as soon as I had   other `qmd` files, with command `{{< include extra_file.qmd >}}`, the `embed-resources: true` seems to no longer be functional.

Is this the expected behaviour? I thought that `{{< include extra_file.qmd >}}` just copy-pasted the qmd content, without side effects. 

- Quarto version: `1.6.42`
- Preamble of `extra_file.qmd`:

```yaml
---
title: "Tools installation"
format: html
editor: source
engine: knitr
---
```

**Comment by cderv** [comment]
@bastienchassagnol please open a new issue following the reply above ☝ 

This one is about better error / warning / support for `embed-ressources` when used in Quarto Project - which is not compatible. (`embed-ressources` is for single document)

Thank you !

**Comment by AlbertoFabbri93** [comment]
So if I understand correctly, it's currently not possible to generate a single HTML file as the output when rendering a Quarto notebook?

My use case involves sharing a fairly long analysis notebook. To make it more manageable, I’d like to split it into several .qmd files. This would make it easier to work with during development and also give me the flexibility to share individual sections when needed. Ideally, though, I would still like to be able to render the entire analysis as a single, standalone HTML file for sharing or publishing.

**Comment by mcanouil** [comment]
> So if I understand correctly, it's currently not possible to generate a single HTML file as the output when rendering a Quarto notebook?
> 
> My use case involves sharing a fairly long analysis notebook. To make it more manageable, I’d like to split it into several .qmd files. This would make it easier to work with during development and also give me the flexibility to share individual sections when needed. Ideally, though, I would still like to be able to render the entire analysis as a single, standalone HTML file for sharing or publishing.

Use the include shortcode as demonstrated in the thread: https://github.com/quarto-dev/quarto-cli/issues/11206#issuecomment-2791013893

**Comment by AlbertoFabbri93** [comment]
Thank you! I looked into include, and while it’s definitely an improvement over working with a single, massive file, it still feels a bit limited in terms of structure. I find the book format a bit more elegant and organized.

That said, is there any way to structure a project into chapters without using the book format?

Also, is it possible to tell Quarto to respect the YAML options when rendering a single document—for example, when running `quarto render _filtering.qmd`?

**Comment by cderv** [comment]
> That said, is there any way to structure a project into chapters without using the book format?

Yes, using a chapter structure does require a book format. This is because all the outputs are 'assembled' together as a website with specific navigation and other feature. 

A single HTML document as output needs to be a single source document as input for rendering. `{{< include >}}` allows splitting a single .qmd in several, and still get a single source document for renderings. 

Maybe the specific project type Manuscript could be a more useful framework to you: https://quarto.org/docs/manuscripts/

It is a project that allows splitting a main analysis into different notebooks. Not directly related, but less book format and still a project. 

> Also, is it possible to tell Quarto to respect the YAML options when rendering a single document—for example, when running quarto render _filtering.qmd?

I guess `_filtering.qmd` is an include file, right? If you add a YAML header in there, it will also be used in the main document when included. As include is like a copy-paste from included file to main file.

So yes you could render a single document, but you need to cleverly leverage shared metadata to render the file, or even use external one passed through command line flag or project profile. 
Ressources:
- https://quarto.org/docs/projects/quarto-projects.html#shared-metadata
- https://quarto.org/docs/projects/profiles.html

**Comment by mcanouil** [comment]
In addition, the include shortcode as documented is a "copy/paste", thus if it includes metadata they will override the main document metadata using the "last one wins" rule.
You can use Quarto CLI flags to pass metadata as key:value or YAML file for instance.
