### ISSUE TITLE
When setting lang to ja-JP in Beamer, it attempts to install non-existent LaTeX packages, causing rendering to fail.

### ISSUE THREAD

**Issue by ujtwr** [quarto-dev/quarto-cli#11256]
### Bug description

```qmd
---
title: "Untitled"
format:
  beamer:
    pdf-engine: lualatex
    lang: ja-JP
---

## Quarto

あいうえお

```
When rendering this qmd file, an error occurs with the following message. Although it shows a permission issue here, even attempting installation as root fails because the specified LaTeX package does not exist."

> &gt; 1 package to install
> &gt; installing hyphen-japanese (1 of 1)
> ERROR: [non-error-thrown] tlmgr returned a non zero status code
> You don't have permission to change the installation in any way,
> specifically, the directory /usr/local/texlive/2024/tlpkg/ is not writable.
> Please run this program as administrator, or contact your local admin.
> tlmgr: An error has occurred. See above messages. Exiting.

### Steps to reproduce

Render qmd file bellow:
```qmd
---
title: "Untitled"
format:
  beamer:
    pdf-engine: lualatex
    lang: ja-JP
---

## Quarto

あいうえお

```

### Your environment

RStudio Server:  2024.09.0+375 on Ubuntu 24.04.1
Client: Windows11 + chrome
Quarto: 1.5.57 (bundled with RStudio)
Latex: texlive2024 (the latest version today)

### Quarto check output

```bash
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /usr/lib/rstudio-server/bin/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/bin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /tmp/RtmpdepXB2/rstudio/terminal/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/nishide/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by TomBener** [comment]
It seems this bug is similar to the scenario that happened to Chinese https://github.com/quarto-dev/quarto-cli/issues/10291

**Comment by cscheid** [comment]
I believe @TomBener is correct, and we need the analogous fix to https://github.com/quarto-dev/quarto-cli/commit/7b5c2477d12c84a0ddc9ca11e6b492cdac21f616

But, more generally, I subscribe to the "there's only three numbers in software engineering: 0, 1, and infinity" theory. So I don't believe this is only needed for simplified chinese and japanese; other writing systems probably need addressing as well, and we should come up with a more general fix.

**Comment by cderv** [comment]
> So I don't believe this is only needed for simplified chinese and japanese; other writing systems probably need addressing as well, and we should come up with a more general fix.

Totally. We just need a way to know which one needs it or which don't. Or we just need to revert the feature in a way that we don't try to install it automatically and let user do it if there is a real problem. 

I'll compare with **tinytex** R package because we don't have this issue, and probably because we don't try to install automatically a package if we detect this hyphen message in the log file.

**Comment by winniehell** [comment]
there is a list of languages that support hypenation at https://github.com/hyphenation/tex-hyphen/blob/master/data/language-codes/tex-languages.txt

maybe that helps

**Comment by cderv** [comment]
Definitely helpful ! This can be a good base for us, to only try installing for one of those known packages

**Comment by spring-haru** [comment]
I encountered the same issue when trying to preview an `.ipynb` file as `.pdf`.

**Comment by gavinhesketh** [comment]
I have a very similar issue when setting the language to en-GB.

Test file test.qmd:

```
---
title: "A title"
lang: en-GB
format: pdf
---

Will this compile?
```

Output of render:

```
> quarto render test.qmd
pandoc 
  to: latex
  output-file: test.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: A title
  lang: en-GB
  


Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Debian) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
> 1 package to install
> installing hyphen-british (1 of 1)
ERROR: [non-error-thrown] tlmgr returned a non zero status code
TLPDB: not a directory, not loading: /home/hesketh/texmf
tlmgr: user mode not initialized, please read the documentation!


Stack trace:
TLPDB: not a directory, not loading: /home/hesketh/texmf
tlmgr: user mode not initialized, please read the documentation!

    at Command.handleError (file:///opt/quarto/bin/quarto.js:8184:126)
    at Command.parseCommand (file:///opt/quarto/bin/quarto.js:7909:18)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async quarto (file:///opt/quarto/bin/quarto.js:118224:9)
    at async file:///opt/quarto/bin/quarto.js:118244:9
    at async mainRunner (file:///opt/quarto/bin/quarto.js:118128:9)
    at async file:///opt/quarto/bin/quarto.js:118235:5
```

If I run xelatex on the test.tex file which is produced, then it compiles with no problem.

**Comment by mcanouil** [comment]
I cannot reproduce the issue. @gavinhesketh please provide the output of `quarto check` and ensure you are using the latest Quarto CLI version (1.7.31).

**Comment by gavinhesketh** [comment]
Arg, sorry, was using an old version. Indeed fixed in 1.7.3.

**Comment by cderv** [comment]
I think the new pandoc that we bundled in the 1.7 version, with updated Beamer and LaTeX template, changed the way lang is supported. 

It may have fix this problem. 

So I suggest we close this issue, and if this comes up again, I'll have a new look at it.
