### ISSUE TITLE
Improve error message when EJS execution fails

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#11529]
See https://github.com/beyond2060/quarto-bug-reproduction for a minimal example.

**Comment by cderv** [comment]
For more context the error traceback is 
````
❯ quarto render index.qmd
ERROR: TypeError: Cannot read properties of undefined (reading 'split')

Stack trace:
    at eval (eval at <anonymous> (https://cdn.skypack.dev/-/lodash@v4.17.21-K6GEbP02mWFnLA45zAmi/dist=es2019,mode=imports/unoptimized/template.js:58:12), <anonymous>:23:22)
    at renderEjs (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/ejs.ts:39:16)
    at templateMarkdownHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/website/listing/website-listing-template.ts:183:26)
    at markdownHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/website/listing/website-listing.ts:352:14)
    at file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/website/listing/website-listing.ts:179:7
    at Array.forEach (<anonymous>)
    at listingHtmlDependencies (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/website/listing/website-listing.ts:177:22)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Object.formatExtras (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/project/types/website/website.ts:235:39)
    at async runPandoc (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/pandoc.ts:392:10)
````

And it happens because 

- A post does not have a `title`
- The custom EJS is doing 
	````ejs
	<a href="<%- item.path %>" class="title listing-title" data-original-href="<%- item.path %>"><%= item.title.split('*').join('') %></a>
	````

`item.title` being undefined, it throws an error. Though it requires investigation to understand what and where.

**Comment by cscheid** [comment]
We should be catching any exception there, though, and reporting the file where this fails to the user.
