### ISSUE TITLE
I cannot pubish any website anymore - ERROR: API Error: 504 - Gateway Timeout

### ISSUE THREAD

**Issue by Barts78** [quarto-dev/quarto-cli#11535]
### Bug description

Hello,

Since this morning I cannot publish any website from a .qmd file anymore.

I got the following error ERROR: API Error: 504 - Gateway Timeout

I tried to republished some old files or to create new documents  and it doesn't publish either.

The page renders absolutely fine in RStudio but it will not publish it.

I would really appreciate any advice you might, have as I only partly finished a report last night, and wanted to upload the latest version this morning, but it does not work.

### Steps to reproduce

quarto publish command from the terminal window in RStudio

### Expected behavior

it should render and then publish the website

### Actual behavior

it give out the below error and messages:

ERROR: API Error: 504 - Gateway Timeout

Stack trace:
    at QuartoPubClient.slugAvailable (file:///Applications/quarto/bin/quarto.js:102926:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async promptForSlug (file:///Applications/quarto/bin/quarto.js:102204:23)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:102032:20)
    at async publishDocument (file:///Applications/quarto/bin/quarto.js:106620:38)
    at async publish6 (file:///Applications/quarto/bin/quarto.js:106712:132)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:106672:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:106704:13)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:106660:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8104:13)

### Your environment

- IDE: RStudio 2024.09.1+394
- macos: 15.1.1 (24B91)

### Quarto check output

(r-reticulate) (base) XXXXXX$ quarto check
Quarto 1.4.557
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.12: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.557
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /Users/Barts78/.virtualenvs/r-reticulate/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.49
      rmarkdown: 2.29

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Sorry to hear you are having issues.
Unfortunately, you did not provide sufficient information, for instance you don't say to where you are publishing.
You did not provide the exact command either.
Please, update your report with accurate and precise information on your issues.

**Comment by Barts78** [comment]
sorry i thought i had provided the information

the command i have used is from the terminal window in RStudio

_quarto publish_

I am aiming to publish to quarto pub

i have tried to upgrade quarto and it says it can't find the document to publish, it was working find until this morning

**Comment by Barts78** [comment]
just to note it errors on the preparing to publish document stage:

[✓] Preparing to publish document
ERROR: API Error: 504 - Gateway Timeout

Stack trace:
    at QuartoPubClient.createDeploy (file:///Applications/quarto/bin/quarto.js:102963:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///Applications/quarto/bin/quarto.js:102076:22
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:75276:16)
    at async handlePublish (file:///Applications/quarto/bin/quarto.js:102054:5)
    at async publishDocument (file:///Applications/quarto/bin/quarto.js:106620:38)
    at async publish6 (file:///Applications/quarto/bin/quarto.js:106712:132)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:106672:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:106683:9)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:106660:9)

**Comment by mcanouil** [comment]
Could you try to publish another simple document that you place in a different directory elsewhere on your laptop?

Did you check your Quarto Pub account?
Is your profile still online? Any previous work already published?

**Comment by mcanouil** [comment]
Since, I know now you are trying to publish to Quarto Pub, I tried to see if this was some kind of global outage on the service.

```
quarto publish index.qmd
? Provider: › Quarto Pub
? Publish with account: › 
ERROR: API Error: 504 - Gateway Timeout

Stack trace:
    at QuartoPubClient.slugAvailable (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/publish/quarto-pub/api/index.ts:134:11)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async promptForSlug (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/publish/common/publish.ts:342:21)
    at async handlePublish (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/publish/common/publish.ts:94:14)
    at async publishDocument (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/publish/publish.ts:310:36)
    at async publish (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/publish/cmd.ts:282:9)
    at async doPublish (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/publish/cmd.ts:205:7)
    at async publishAction (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/publish/cmd.ts:258:7)
    at async Command.actionHandler (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/publish/cmd.ts:163:11)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
```

It seems so. Investigation is ongoing.
Thanks for the report.
We'll update soon as there is something to update about.

**Comment by mcanouil** [comment]
@Barts78 it should be back online and work as expected again.

**Comment by Barts78** [comment]
Thank you @mcanouil yes i've just checked and managed to publish as usual, still using the old quarto version tho

thanks for your help
