### ISSUE TITLE
Unable to Render Mermaid Diagrams in PDFs

### ISSUE THREAD

**Issue by ForBo7** [quarto-dev/quarto-cli#11581]
### Bug description

I have a Mermaid diagram in a Quarto document. Rendering it with `quarter render summary.qmd --to pdf` results in the following stack trace:
```
ERROR: Internal Error: Couldn't find an svg element in svg string

This is a bug in quarto. We apologize for the inconvenience.
Please consider reporting it at https://github.com/quarto-dev/quarto-cli. Thank you!

Stack trace:
    at resolveSize (file:///Applications/quarto/bin/quarto.js:82166:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async makePng (file:///Applications/quarto/bin/quarto.js:82509:55)
    at async makeDefault (file:///Applications/quarto/bin/quarto.js:82561:24)
    at async Object.cell (file:///Applications/quarto/bin/quarto.js:82584:20)
    at async Promise.all (index 0)
    at async Object.document (file:///Applications/quarto/bin/quarto.js:39242:25)
    at async handleLanguageCells (file:///Applications/quarto/bin/quarto.js:39212:42)
    at async file:///Applications/quarto/bin/quarto.js:85949:51
    at async withTimingAsync (file:///Applications/quarto/bin/quarto.js:16879:25)
```
I can confirm my Mermaid diagram has no issues, since I can view it perfectly fine with the VS Code Quarto Extension, and the mermaid.live editor.

### Steps to reproduce

````qmd
---
title: "Demonstration Learning"
subtitle: "A Summary"
format: pdf
---
```{mermaid}
graph TD
  A[Create Demonstration Data Set]
  B[Learning from Demonstrations]
  C[Refinement/Optimization]
  D[Policy Evaluation/Generalization]

  A --> B
  B --> C
  C --> D

  A1[Select Demonstrator] --> A
  A2[Choose Demonstration Technique] --> A
  A3[Data Representation] --> A

  B1[Policy Learning] --> B
  B2[Model Learning] --> B
  B3[Reward Learning] --> B

  C1[Online Interactions] --> C
  C2[Active Learning] --> C
  C3["Generative Adversarial Imitation Learning (GAIL)"] --> C

  D1[Quantitative Evaluation] --> D
  D2[Qualitative Evaluation] --> D
```
````

### Expected behavior

I should be able to have PDF rendered that includes this diagram.

### Actual behavior

The `quarto-cli` throws the following command, after running `quarto render summary.qmd --to pdf`.

```bash
ERROR: Internal Error: Couldn't find an svg element in svg string

This is a bug in quarto. We apologize for the inconvenience.
Please consider reporting it at https://github.com/quarto-dev/quarto-cli. Thank you!

Stack trace:
    at resolveSize (file:///Applications/quarto/bin/quarto.js:82166:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async makePng (file:///Applications/quarto/bin/quarto.js:82509:55)
    at async makeDefault (file:///Applications/quarto/bin/quarto.js:82561:24)
    at async Object.cell (file:///Applications/quarto/bin/quarto.js:82584:20)
    at async Promise.all (index 0)
    at async Object.document (file:///Applications/quarto/bin/quarto.js:39242:25)
    at async handleLanguageCells (file:///Applications/quarto/bin/quarto.js:39212:42)
    at async file:///Applications/quarto/bin/quarto.js:85949:51
    at async withTimingAsync (file:///Applications/quarto/bin/quarto.js:16879:25)
```

### Your environment

- OS: macOS Sonoma 14.5

### Quarto check output

```bash
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/[REDACTED]/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.11
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/[REDACTED]/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.9
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by cscheid** [comment]
Strange - I can't repro this.

![Image](https://github.com/user-attachments/assets/797f6597-7c01-445b-804b-e3bdefe49136)

**Comment by cderv** [comment]
I believe this is a duplicate of this one 
- https://github.com/quarto-dev/quarto-cli/issues/10961

and it is an issue with the chrome version installed with `quarto install chromium`

````
[✓] Checking tools....................OK
      TinyTeX: v2024.11
      Chromium: 869685
````

@ForBo7 do you have an other chrome version on your environment ? If not could you install a recent one, and check that it works ? 

Version `869685` is broken as discussed in #10961

**Comment by cderv** [comment]
I confirm this is a duplicate of #10961  

I can reproduce on Windows with 
````
$env:QUARTO_CHROMIUM="C:/Users/chris/AppData/Local/quarto/chromium/win64-869685/chrome-win/chrome.exe"
quarto render index.qmd
````

> We could detect this bad version and warn users when this happens.

Yes. This version is also the one Quarto does install. So ultimately we need to install a version that don't have the problem. Currently `quarto install chromium` does not help with Quarto and screenshotting mermaid. 

Closing in favor of #10961
