### ISSUE TITLE
Error adding css vars block Error: Can't handle character: "÷"

### ISSUE THREAD

**Issue by LucyMcGowan** [quarto-dev/quarto-cli#11645]
### Bug description

Similar to #11148, I am seeing the following: 

Error adding css vars block Error: Can't handle character: "÷" (12999:13)
    at InputStream.err (file:///Applications/quarto/bin/quarto.js:48871:15)
    at Object.err (file:///Applications/quarto/bin/quarto.js:48890:23)
    at TokenStream.err (file:///Applications/quarto/bin/quarto.js:48960:27)
    at TokenStream.read_next (file:///Applications/quarto/bin/quarto.js:48996:14)
    at TokenStream.peek (file:///Applications/quarto/bin/quarto.js:48946:32)
    at Object.peek (file:///Applications/quarto/bin/quarto.js:49118:22)
    at file:///Applications/quarto/bin/quarto.js:49153:36
    at Array.reduce (<anonymous>)
    at Parser.is_type (file:///Applications/quarto/bin/quarto.js:49152:23)
    at Parser.is_punctuation (file:///Applications/quarto/bin/quarto.js:49164:21)
The resulting CSS file will not have SCSS color variables exported as CSS.
This is likely a Quarto bug.

```
// quarto-scss-analysis-annotation { "quarto-version": "1.6.39" }

// quarto-scss-analysis-annotation { "origin": "'use' section from format" }
``` 

### Quarto check output

Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/lucymcgowan/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/lucymcgowan/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks for the report! Can we get a reprex (where are you using `÷` specifically?)

**Comment by LucyMcGowan** [comment]
I’m not knowingly using it 🫣

**Comment by LucyMcGowan** [comment]
Oh boy, just found it, it was an accident, sorry!! Thank you for the quick repky

**Comment by cscheid** [comment]
@LucyMcGowan Sorry, I should have clarified! This is clearly a bug in Quarto, but it helps us to fix if we know what causes it. Do you have a link to a GitHub repo, eg?

**Comment by LucyMcGowan** [comment]
My scss file had this: 

#user-info {
  font-size: .8em;
  font-weight: bold;
  color: #343÷;
}

(but it was a typo!)

**Comment by cscheid** [comment]
Thank you. The crash is coming from a third-party library that we know is fairly sketchy (but we don't have the resources to rewrite ourselves just yet), and so we're collecting an increasing number of workarounds. This will fit right in.
