### ISSUE TITLE
Couldn't build against Deno 1.23.0 

### ISSUE THREAD

**Issue by trap000d** [quarto-dev/quarto-cli#1174]
### Bug description

Hi, I'm maintainer of Arch Linux package `quarto-cli` (0.9.594 currenly). Few days ago deno was updated there to 1.23.0 With the new Deno version I'm getting half a dozen of errors during the build:
```
../dist/bin/tools/deno run --unstable --allow-env --allow-read --allow-write --allow-run --allow-net --allow-ffi --importmap=../../src/import_map.json bld.ts prepare-dist --log-level info
Using configuration:
{"productName":"Quarto","version":"0.9","importmap":"/home/trap000d/src/quarto-cli/src/dev_import_map.json","directoryInfo":{"root":"/home/trap000d/src/quarto-cli","pkg":"/home/trap000d/src/quarto-cli/package","dist":"/home/trap000d/src/quarto-cli/package/dist","share":"/home/trap000d/src/quarto-cli/package/dist/share","src":"/home/trap000d/src/quarto-cli/src","out":"/home/trap000d/src/quarto-cli/package/out","bin":"/home/trap000d/src/quarto-cli/package/dist/bin"}}

Moving supporting files
Ensuring dir /home/trap000d/src/quarto-cli/package/dist/share exists
Copying /home/trap000d/src/quarto-cli/COPYING.md to /home/trap000d/src/quarto-cli/package/dist/share/COPYING.md
Ensuring dir /home/trap000d/src/quarto-cli/package/dist/share exists
Copying /home/trap000d/src/quarto-cli/COPYRIGHT to /home/trap000d/src/quarto-cli/package/dist/share/COPYRIGHT
Ensuring dir /home/trap000d/src/quarto-cli/package/dist exists
Copying /home/trap000d/src/quarto-cli/src/resources to /home/trap000d/src/quarto-cli/package/dist/share
Ensuring dir /home/trap000d/src/quarto-cli/package/dist/bin exists
Copying /home/trap000d/src/quarto-cli/src/resources/vendor to /home/trap000d/src/quarto-cli/package/dist/bin/vendor


Creating Deno Bundle
/home/trap000d/src/quarto-cli/package/dist/bin/quarto.js
["/home/trap000d/src/quarto-cli/package/dist/bin/tools/deno","bundle","--unstable","--importmap=/home/trap000d/src/quarto-cli/src/dev_import_map.json","/home/trap000d/src/quarto-cli/src/quarto.ts","/home/trap000d/src/quarto-cli/package/dist/bin/quarto.js"]
Check file:///home/trap000d/src/quarto-cli/src/quarto.ts
error: TS2352 [ERROR]: Conversion of type 'bigint' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
        const usizeBytes = dylib.symbols.deno_dom_usize_len() as number;
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/trap000d/src/quarto-cli/src/core/deno-dom.ts:61:28

TS2783 [ERROR]: 'type' is specified more than once, so this usage will be overwritten.
        type: "full",
        ~~~~~~~~~~~~
    at file:///home/trap000d/src/quarto-cli/src/project/types/website/listing/website-listing.ts:245:9

TS2785 [ERROR]:     This spread always overwrites this property.
            ...options[kFeed],
            ~~~~~~~~~~~~~~~~~
        at file:///home/trap000d/src/quarto-cli/src/project/types/website/listing/website-listing.ts:246:9

TS2352 [ERROR]: Conversion of type 'undefined' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
            giscusOptions[kGiscusCategoryId] as string,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/trap000d/src/quarto-cli/src/project/types/website/website-giscus.ts:77:13

TS2551 [ERROR]: Property 'sleepSync' does not exist on type 'typeof Deno'. Did you mean 'seekSync'?
        Deno.sleepSync(3000);
             ~~~~~~~~~
    at file:///home/trap000d/src/quarto-cli/src/project/serve/serve.ts:571:14

    'seekSync' is declared here.
      export function seekSync(
                      ~~~~~~~~
        at asset:///lib.deno.ns.d.ts:999:19

TS2564 [ERROR]: Property '[Symbol.toStringTag]' has no initializer and is not definitely assigned in the constructor.
  readonly [Symbol.toStringTag]: string;
           ~~~~~~~~~~~~~~~~~~~~
    at file:///home/trap000d/src/quarto-cli/src/publish/netlify/api/core/CancelablePromise.ts:25:12

Found 5 errors.
ERROR: Failure to bundle /home/trap000d/src/quarto-cli/src/quarto.ts

Error: Failure to bundle /home/trap000d/src/quarto-cli/src/quarto.ts
    at bundle (file:///home/trap000d/src/quarto-cli/package/src/util/deno.ts:38:11)
    at async prepareDist (file:///home/trap000d/src/quarto-cli/package/src/common/prepare-dist.ts:39:3)
    at async Command.fn (file:///home/trap000d/src/quarto-cli/package/src/cmd/pkg-cmd.ts:38:5)
    at async Command.execute (https://deno.land/x/cliffy@v0.24.2/command/command.ts:1275:7)
    at async quartoBld (file:///home/trap000d/src/quarto-cli/package/src/bld.ts:48:3)
    at async mainRunner (file:///home/trap000d/src/quarto-cli/src/core/main.ts:39:5)
    at async file:///home/trap000d/src/quarto-cli/package/src/bld.ts:52:3
```
After rolling back to old Deno version (1.22.3) all seems OK. As a temporary override I've added "deno <1.23.0" into PKGBUILD. However it's just a matter of time when other distributions (Manjaro of Fedora) will pick up the new Deno. So please take a look occasionally at these errors.

Regards.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for pointing this out! During development we try to track pretty closely to the Deno tip (although since they release every 5-10 days we do sometimes fall a bit behind). We are currently in the process of stabilizing for a v1.0 release (after which time there will be both "stable" and "development" binaries available). 

Deno is still prone to many breaking changes so we won't just slam the latest Deno into our "stable" binaries -- likely we will target the last point release of 1.22 (which seems like it will be 1.22.3). Our "development" line will then take Deno 1.23 and we'll get these errors cleaned up (this will likely be in ~ 2 week time).

**Comment by cbrnr** [comment]
It looks like this can be closed because of #1518?

**Comment by trap000d** [comment]
> It looks like this can be closed because of #1518?

v1.2.157 is still "pre-release" 
"latest" v1.1.251 still can't be built against deno>1.22
so I'd like to keep it open for a while :)

**Comment by cbrnr** [comment]
Sure! So v1.2 will solve the issue?

**Comment by trap000d** [comment]
> Sure! So v1.2 will solve the issue?
Yes, 1.2 solves it. I've even created AUR package for tracking pre-release tags: https://aur.archlinux.org/packages/quarto-cli-pre-release

**Comment by trap000d** [comment]
Ooops, developers are late again. Deno 1.26 is just released and...

```
error: TS2446 [ERROR]: Property 'options' is protected and only accessible through an instance of class 'Row<T>'. This is an instance of class 'Row<any> | Row<T>'.
      row.options = { ...cells.options };
                               ~~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/table/row.ts:29:32

TS2446 [ERROR]: Property 'options' is protected and only accessible through an instance of class 'Table<T>'. This is an instance of class 'Table<any> | Table<T>'.
      table.options = { ...rows.options };
                                ~~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/table/table.ts:50:33

TS2344 [ERROR]: Type 'T' does not satisfy the constraint 'void | Record<string, any>'.
  ? TypedArguments<A, T>
                      ^
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2434:23

TS2208 [ERROR]:     This type parameter might need an `extends void | Record<string, any>` constraint.
    type ArgumentTypes<A extends string, T> = A extends `${string} ${string}`
                                         ^
        at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2433:38

TS2344 [ERROR]: Type 'T' does not satisfy the constraint 'void | Record<string, any>'.
  : N extends `${string} ${infer Args}` ? TypedArguments<Args, T>
                                                               ^
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2583:64

TS2208 [ERROR]:     This type parameter might need an `extends void | Record<string, any>` constraint.
    type TypedCommandArguments<N extends string, T> = number extends T ? any
                                                 ^
        at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2582:46

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'.
  Deno.setRaw(stdin.rid, true);
       ~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/ansi/cursor_position.ts:31:8

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'.
  Deno.setRaw(stdin.rid, false);
       ~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/ansi/cursor_position.ts:34:8

TS2322 [ERROR]: Type 'unknown' is not assignable to type '{}'.
          formats[format] = projectFormats[format];
          ~~~~~~~~~~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/project/project-context.ts:203:11

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'.
      (Deno.setRaw as setRaw)(
            ~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/prompt/_generic_prompt.ts:299:13

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'.
      Deno.setRaw(Deno.stdin.rid, false);
           ~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/prompt/_generic_prompt.ts:308:12

Found 9 errors.
ERROR: Failure to bundle /var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/quarto.ts

Error: Failure to bundle /var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/quarto.ts
    at bundle (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/util/deno.ts:40:11)
    at async prepareDist (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/common/prepare-dist.ts:39:3)
    at async Command.fn (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/cmd/pkg-cmd.ts:38:5)
    at async Command.execute (https://deno.land/x/cliffy@v0.24.2/command/command.ts:1275:7)
    at async quartoBld (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/bld.ts:48:3)
    at async mainRunner (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/core/main.ts:39:5)
    at async file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/bld.ts:52:3
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: quarto-cli-pre-release

```

**Comment by cbrnr** [comment]
Doesn't look too bad though. At least `Deno.setRaw` has always been unstable, but as of v1.26 this is now stable as `Deno.stdin.setRaw` (https://github.com/denoland/deno/pull/15797).

**Comment by trap000d** [comment]
> Doesn't look too bad though. At least `Deno.setRaw` has always been unstable, but as of v1.26 this is now stable as `Deno.stdin.setRaw` ([denoland/deno#15797](https://github.com/denoland/deno/pull/15797)).

Yep, patch should be trivial. The only issue is how to motivate Quarto developers to merge it :)

**Comment by cbrnr** [comment]
I'm sure they are more than happy to merge a PR with the fixes.

**Comment by trap000d** [comment]
Well... There are two errors where I have no idea what to do. That might be an issue in upstream (deno, or cliffy), though. Here I feel I'm not skilled enough for diving such deep into TS code.

```
Check file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/quarto.ts
error: TS2344 [ERROR]: Type 'T' does not satisfy the constraint 'void | Record<string, any>'.
  ? TypedArguments<A, T>
                      ^
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2434:23

TS2208 [ERROR]:     This type parameter might need an `extends void | Record<string, any>` constraint.
    type ArgumentTypes<A extends string, T> = A extends `${string} ${string}`
                                         ^
        at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2433:38

TS2344 [ERROR]: Type 'T' does not satisfy the constraint 'void | Record<string, any>'.
  : N extends `${string} ${infer Args}` ? TypedArguments<Args, T>
                                                               ^
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2583:64

TS2208 [ERROR]:     This type parameter might need an `extends void | Record<string, any>` constraint.
    type TypedCommandArguments<N extends string, T> = number extends T ? any
                                                 ^
        at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/vendor/deno.land/x/cliffy@v0.24.2/command/command.ts:2582:46

Found 2 errors.
ERROR: Failure to bundle /var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/quarto.ts

Error: Failure to bundle /var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/quarto.ts
    at bundle (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/util/deno.ts:40:11)
    at async prepareDist (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/common/prepare-dist.ts:39:3)
    at async Command.fn (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/cmd/pkg-cmd.ts:38:5)
    at async Command.execute (https://deno.land/x/cliffy@v0.24.2/command/command.ts:1275:7)
    at async quartoBld (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/bld.ts:48:3)
    at async mainRunner (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/src/core/main.ts:39:5)
    at async file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.2.167/package/src/bld.ts:52:3
==> ERROR: A failure occurred in build().
    Aborting...

```
P.S. Just in case, here I'm attaching patch (WIP)
[deno_set_raw.patch.gz](https://github.com/quarto-dev/quarto-cli/files/9679535/deno_set_raw.patch.gz)

**Comment by jjallaire** [comment]
Just to set expectations, we don't automatically move to the very latest Deno the day or week it comes out. Often times there are either bugs or compatibility issues that need to get worked through. Further, if we are in a release stabilization period (as we are now for v1.2) we don't want to bring in a new version of Deno underneath everything. We typically update Deno anywhere from 2-8 weeks after a given release. For this one I'd expect it will be ~ 6 weeks (after we ship v1.2).

**Comment by trap000d** [comment]
> Just to set expectations, we don't automatically move to the very latest Deno the day or week it comes out. Often times there are either bugs or compatibility issues that need to get worked through. Further, if we are in a release stabilization period (as we are now for v1.2) we don't want to bring in a new version of Deno underneath everything. We typically update Deno anywhere from 2-8 weeks after a given release. For this one I'd expect it will be ~ 6 weeks (after we ship v1.2).

Thanks for updates. No worries. Take your time.

P.S. You're loosing the momentum, though. In July it was more optimistic, some from "5-10 days" to "~2 weeks" :)

**Comment by jjallaire** [comment]
Yeah, during regular development we update pretty frequently but once we are winding down a release it gets slower.

**Comment by cscheid** [comment]
(We're on Deno 2.3.1)
