### ISSUE TITLE
Filter extensions can't be specified in combination with processing phases

### ISSUE THREAD

**Issue by multimeric** [quarto-dev/quarto-cli#11750]
### Bug description

[The AST processing phases feature](https://quarto.org/docs/prerelease/1.4/lua_changes.html#more-precise-targeting-of-ast-processing-phases) doesn't seem compatible with packaged extensions. 

This works:
```yaml
filters:
  - path: lifecycle.lua
    at: pre-ast
```

Whereas this fails:
```yaml
filters:
  - path: lifecycle
    at: pre-ast
```
With the error `ERROR (/opt/quarto/share/filters/main.lua:3832) cannot open lifecycle: No such file or directory`. I assume this is supposed to work, since otherwise extensions have no access to the lifecycle hooks.

### Steps to reproduce

I've made a super simple reprex of this here: https://github.com/multimeric/quarto-lifecycle:

1. `git clone https://github.com/multimeric/quarto-lifecycle`
2. `cd quarto-lifecycle`
3.  `quarto render example.qmd`.

### Expected behavior

The document to render without error.

### Actual behavior

`ERROR (/opt/quarto/share/filters/main.lua:3832) cannot open lifecycle: No such file or directory`

### Your environment

Ubuntu 22.04.

### Quarto check output

```bash
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /home/migwell/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/migwell/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.8 (Conda)
      Path: /home/migwell/micromamba/envs/bash-kernel/bin/python
      Jupyter: 5.7.2
      Kernels: python3, bash, rust

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK
```

**Comment by cderv** [comment]
I wanted to check an idea, and I believe this happens because we are not resolving filter looking in extension. 

Filters are resolved in 
https://github.com/nickvigilante/quarto-cli/blob/f7e913e5b71ccc59bb34151cbee918adefa72de3/src/command/render/defaults.ts#L46-L53
and resolved looking in extension
https://github.com/nickvigilante/quarto-cli/blob/f7e913e5b71ccc59bb34151cbee918adefa72de3/src/command/render/filters.ts#L733-L734
but we only resolve filter of type string (so not `{ path: 'lifecycle', at: 'pre-ast'}` at this part. 

So the full filter path is not resolved, and on Lua side the filter can be loaded. 

BTW @multimeric, with your example repo, this does not work for me either. 
> This works:
> ```
> filters:
>  - path: lifecycle.lua
>    at: pre-ast
> ```

Extension or not it fails 🤔  same cause to me: we don't resolve filter of the form `path / at` in extensions as you found. 

We should just tweak `resolveFilters()` to resolve filter path in extension also for entry point filter.

**Comment by mcanouil** [comment]
FYI, this is not the only problem with `path` for filters:

- #12408

**Comment by mcanouil** [comment]
Thanks @cderv based on your comment, I took a stab at this.

- https://github.com/quarto-dev/quarto-cli/pull/13067

It works and the new test also works locally.
Waiting for the complete test suite to complete with hopefully no breakage elsewhere.
