### ISSUE TITLE
Can't get js files in docs/presentations/index.qmd to work

### ISSUE THREAD

**Issue by burgerga** [quarto-dev/quarto-cli#1320]
Downloading the repo and rendering docs/presentations/index.qmd results in:
![image](https://user-images.githubusercontent.com/907362/168982692-36280f92-c3f0-4a20-bbb4-d1e4d5089fa7.png)
with in the console:
```js
quarto-ojs-runtime.js:18714 TypeError: Failed to resolve module specifier '....docspresentations
evealjsdemo/./actors.js'
    at Interpreter.resolveImportPath (quarto-ojs-runtime.js:18709:19)
    at Interpreter.cell (quarto-ojs-runtime.js:11864:38)
    at Interpreter.module (quarto-ojs-runtime.js:11838:31)
    at runCell (quarto-ojs-runtime.js:19428:40)
    at Array.map (<anonymous>)
    at QuartoOJSConnector.interpretWithRunner (quarto-ojs-runtime.js:18901:52)
    at QuartoOJSConnector.interpret (quarto-ojs-runtime.js:19435:17)
    at Object.interpret (quarto-ojs-runtime.js:19670:27)
    at Object.interpretFromScriptTags (quarto-ojs-runtime.js:19715:20)
    at VM52 title-slide:1705:25
(anonymous) @ quarto-ojs-runtime.js:18714
```
so somehow the importpath seems to get mangled?

**Comment by cscheid** [comment]
@burgerga Can you provide us with the information from our [github issue template](https://github.com/quarto-dev/quarto-cli/issues/new?assignees=&labels=bug&template=bug_report.yml) in order for us to track this down more specifically?

**Comment by burgerga** [comment]
Yes, of course!

Steps to reproduce:
* I pulled the last changes from Github (https://github.com/quarto-dev/quarto-web/commit/d172e572d369578c7a26d3113ace11893b62c1db) and update quarto-cli
* Did `renv::restore()`
* Open `docs/presentations/revealjs/demo/index.qmd`
* Click _Render_

## Output background job:
```
processing file: index.qmd
  |....                                                                  |   6%
  ordinary text without R code

  |........                                                              |  12%
label: unnamed-chunk-1 (with options) 
List of 3
 $ echo      : logi TRUE
 $ fig.width : int 10
 $ fig.height: num 4.5

  |............                                                          |  18%
  ordinary text without R code

  |................                                                      |  24%
label: unnamed-chunk-2
  |.....................                                                 |  29%
  ordinary text without R code

  |.........................                                             |  35%
label: unnamed-chunk-3
  |.............................                                         |  41%
  ordinary text without R code

  |.................................                                     |  47%
label: unnamed-chunk-4
  |.....................................                                 |  53%
  ordinary text without R code

  |.........................................                             |  59%
label: unnamed-chunk-5 (with options) 
List of 2
 $ echo      : logi FALSE
 $ fig.height: int 5

  |.............................................                         |  65%
  ordinary text without R code

  |.................................................                     |  71%
label: unnamed-chunk-6
  |......................................................                |  76%
  ordinary text without R code

  |..........................................................            |  82%
label: unnamed-chunk-7 (with options) 
List of 1
 $ engine: chr "ojs"

  |..............................................................        |  88%
  ordinary text without R code

  |..................................................................    |  94%
label: unnamed-chunk-8 (with options) 
List of 1
 $ engine: chr "ojs"

  |......................................................................| 100%
  ordinary text without R code


output file: index.knit.md

Warning message:
package 'ggplot2' was built under R version 4.2.1 
pandoc 
  to: revealjs
  output-file: index.html
  standalone: true
  title-prefix: Quarto
  wrap: none
  default-image-extension: png
  html-math-method:
    method: mathjax
    url: >-
      https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML-full
  slide-level: 2
  css:
    - styles.css
  
metadata
  link-citations: true
  width: 1050
  height: 700
  margin: 0.1
  center: false
  navigationMode: linear
  controlsLayout: edges
  controlsTutorial: false
  hash: true
  history: true
  hashOneBasedIndex: false
  fragmentInURL: false
  transition: none
  backgroundTransition: none
  pdfSeparateFragments: false
  lang: en
  auto-stretch: true
  bibliography:
    - ../../../../references.bib
  editor: visual
  title: Quarto Presentations
  subtitle: Create beautiful interactive slide decks with Reveal.js
  resources:
    - demo.pdf
  slideNumber: true
  chalkboard:
    buttons: false
  previewLinks: auto
  logo: images/quarto.png
  footer: '<https://quarto.org>'
  
Output created: ..\..\..\..\_site\docs\presentations\revealjs\demo\index.html

Watching files for changes
Browse at http://localhost:3654/docs/presentations/revealjs/demo/index.html
```

## `quarto check` Output:

```bash
[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\Users\burge\AppData\Local\Programs\Quarto\bin\
      CodePage: 65001

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.7
      Path: C:/Users/burge/GitHub/quarto-web/renv/python/virtualenvs/renv-python-3.9/Scripts/python.exe
      Jupyter: 4.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/burge/GitHub/quarto-web/renv/library/R-4.2/x86_64-w64-mingw32
        - C:/Users/burge/AppData/Local/Temp/RtmpKGYcw4/renv-system-library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

## `quarto tools check` Output:

```bash
[>] Inspecting tools

Tool         Status                    Installed     Latest
chromium     Not installed             ---           869685
tinytex      External Installation     ---           v2022.08
```

## Other stuff

* RStudio version: 2022.07.1 Build 554
* Running on Windows 11

**Comment by burgerga** [comment]
So it looks like the path is somehow parsed and /r is replaced with a carriage return? (see also the newline in the console output in my top post)

**Comment by cscheid** [comment]
I think we fixed this recently: #1605 Can you try the pre-release quarto 1.1 release? https://github.com/quarto-dev/quarto-cli/releases/tag/v1.1.48

**Comment by burgerga** [comment]
Do you know what the latest prerelease version is that does not have the mentioned issue?

**Comment by burgerga** [comment]
Yes, v1.1.49 works like a charm, thanks!
