### ISSUE TITLE
YAML error when using hrule markdown syntax ---

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#169]
Let's say I want to create this presentation 

````markdown
---
title: Speaker Note
format: revealjs
---

# Content

---

Slide without title

# Another

---

Slide without title
````

This should create a presentation with 1 title slide two section title slides which each section using one slide. 

However, there is an issue with YAML parsing by Quarto

````
ERROR: YAMLError: can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 1:
    # Another
    ^
    at generateError (https://deno.land/std@0.97.0/encoding/_yaml/loader/loader.ts:163:10)
    at throwError (https://deno.land/std@0.97.0/encoding/_yaml/loader/loader.ts:176:9)
    at readBlockMapping (https://deno.land/std@0.97.0/encoding/_yaml/loader/loader.ts:1187:16)
    at composeNode (https://deno.land/std@0.97.0/encoding/_yaml/loader/loader.ts:1509:13)
    at readDocument (https://deno.land/std@0.97.0/encoding/_yaml/loader/loader.ts:1695:3)
    at loadDocuments (https://deno.land/std@0.97.0/encoding/_yaml/loader/loader.ts:1757:5)
    at load (https://deno.land/std@0.97.0/encoding/_yaml/loader/loader.ts:1787:21)
    at parse (https://deno.land/std@0.97.0/encoding/_yaml/parse.ts:19:10)
    at readYamlFromMarkdown (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/core/yaml.ts:67:22)
    at readYamlFromMarkdownFile (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/core/yaml.ts:78:10)
````

The parser should take into account `---` as slide delimiter, right ?

**Comment by cderv** [comment]
But in fact it is not a presentation problem. It happens when using `---` as horizontal rule markdown syntax

````markdown
---
title: Speaker Note
format: html
---

# Content

---

Hrule above

# Another

---

Hrule above

````

**Comment by jjallaire** [comment]
I thought I fixed this a while back (https://github.com/quarto-dev/quarto-cli/commit/0f3385965e8e1750a3798aca0f185a3d798035a7#diff-1949f23f4fbea6089405ec444efec7316e9b0737beca7349589ad310857c1a37).

I don't get the error when I render on MacOS. I'll be the problem is \r on Windows. Will investigate further!

**Comment by cderv** [comment]
Following the hint, I made a PR with a fix.
