### ISSUE TITLE
open a quarto web project on internal network harddrive fails

### ISSUE THREAD

**Issue by eviatargu** [quarto-dev/quarto-cli#1774]
### Bug description

hello,
In office, I have an rdp windows server. 
when I open a quarto web project on the local server everything is fine but when I try to open a quarto web project
on another hard drive where data should be stored RStudio fails to create the .yml, .qmd and .css files. only the .Rproj file 
is created and there is an error that says the system can not find the file specified. 
so, for now we can't use the quarto projects outside the hosting server of the RStudio session. 
The server is new and I'm installing everything from scratch, so everything is updated.

### Checklist

- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by DMozzanica** [comment]
Hello,
i have the same issue.
The problem occurs when quarto on a Windows system try to create e project in a network shared folder.

To reproduce the problem:

1. Connect to a network shared folder

```
net use h: \\testremotepc\folder
```

2. Lauch the creation of the project

```
H:\R\test22>"C:\Program Files\RStudio\bin\quarto\bin\quarto.cmd" create-project prova
Creating project at UNC\testremotepc\folder\R\test22\prova:
ERROR: NotFound: Impossibile trovare il percorso specificato. (os error 3), open 'UNC\testremotepc\folder\R\test22\prova\_quarto.yml'
```

The directory of the project is empty:

```
H:\R\test22\prova>dir

Directory di H:\R\test22\prova

10/08/2022  14:33    <DIR>          .
10/08/2022  14:33    <DIR>          ..
               0 File              0 byte
               2 Directory  107.020.263.424 byte disponibili
```

The same issue occurs launching quarto directly from rstudio.


Creating the project on a local folder work fine:

```
C:\Users\xxxxxx\Documenti\prova>"C:\Program Files\RStudio\bin\quarto\bin\quarto.cmd" create-project prova
Creating project at C:\Users\xxxxxx\Documents\prova\prova:
  - Created _quarto.yml
  - Created prova.qmd


C:\Users\xxxxxx\Documenti\prova\prova>dir


 Directory di C:\Users\xxxxxx\Documenti\prova\prova

10/08/2022  14:34    <DIR>          .
10/08/2022  14:34    <DIR>          ..
10/08/2022  14:34               179 prova.qmd
10/08/2022  14:34                29 _quarto.yml
               2 File            208 byte
               2 Directory   9.343.623.168 byte disponibili
```


My installation is:
Windows 10 21H2 (build SO 19044.1826)
rstudio 2022.07.01 Build 554
Quarto is part of Rstudio distribution, i **haven't** installed a separate package.

The quarto check Output is:

```
C:\Users\xxxxx\Documenti\prova\prova>"C:\Program Files\RStudio\bin\quarto\bin\quarto.cmd" check

[>] Checking Quarto installation......OK
      Version: 1.0.36
      Path: C:\Program Files\RStudio\bin\quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/xxxxxx/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK

```


The quarto tools check Output is

```
C:\Users\xxxxxx\Documenti\prova\prova>"C:\Program Files\RStudio\bin\quarto\bin\quarto.cmd" tools check
[>] Inspecting tools

Tool         Status                    Installed     Latest
chromium     Not installed             ---           869685
tinytex      External Installation     ---           v2022.08
```

**Comment by jjallaire** [comment]
Perhaps something in Deno (our JS runtime) that has difficulty with UNC paths / mounted drives?

**Comment by daranzolin** [comment]
I think I'm having the same problem but getting a permissions error since upgrading to 1.6, even though I can freely create files and folders on this particular network drive. I have some older qmds on this drive that I'm almost positive used to render, so I don't know what's happening now.

```
<redacted>quarto create project quarto-reprex
? Type » default
? Directory » quarto-reprex
? Title (quarto-reprex) » reprex
Creating project at <redacted>\quarto-reprex:
ERROR: PermissionDenied: Requires all access to "<redacted>\\quarto-reprex\\_quarto.yml", run again with the --allow-all flag

Stack trace:
    at writeFileSync (ext:deno_fs/30_fs.js:899:3)
    at Object.writeTextFileSync (ext:deno_fs/30_fs.js:962:10)
    at projectCreate (file:///<redacted>/AppData/Local/Programs/Quarto/bin/quarto.js:91453:10)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Object.createArtifact1 [as createArtifact] (file:///<redacted>/AppData/Local/Programs/Quarto/bin/quarto.js:11837o.js:118376:5)
    at async Command.actionHandler (file:///<redacted>/AppData/Local/Programs/Quarto/bin/quarto.js:118707:34)
    at async Command.execute (file:///<redacted>/AppData/Local/Programs/Quarto/bin/quarto.js:8086:13)
    at async Command.parseCommand (file:///<redacted>/AppData/Local/Programs/Quarto/bin/quarto.js:7976:20)
    at async quarto (file:///<redacted>/AppData/Local/Programs/Quarto/bin/quarto.js:126366:9)
    at async file:///<redacted>/AppData/Local/Programs/Quarto/bin/quarto.js:126393:9
```

**Comment by cscheid** [comment]
No, that's something else strange happening; `deno` is refusing file access to those paths, but that shouldn't be happening because the launcher script for quarto should be setting the correct permissions. What version of Quarto are you running and how did you install it?

**Comment by daranzolin** [comment]
I just installed 1.6.32 by manually downloading the Windows installer from https://quarto.org/docs/download/. Then clicked through the setup wizard. `quarto check` output:

```
Quarto 1.6.32
[>] Checking environment information...
      Quarto cache location: C:\<>\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.32
      Path: C:\<>\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\<>\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/<>/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      knitr: 1.43
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
@cderv What could be going on here? Is there a chance our windows launcher is somehow not sending all the configuration options?

**Comment by cderv** [comment]
I believe this is was another occurrence of Deno bug with Windows and accessing some network drive problem with `--allow-read` and `--allow-write`
- https://github.com/quarto-dev/quarto-cli/issues/11332

and this is supposed to be fixed in 
- https://github.com/quarto-dev/quarto-cli/pull/11385

@daranzolin can you try latest pre-release 1.6 please ? 

Thanks !
