### ISSUE TITLE
VSCode Integrated Terminal: Render command running before `conda activate`

### ISSUE THREAD

**Issue by white-c** [quarto-dev/quarto-cli#1852]
I just install Quarto for VSCode. I was walking through the Get Started steps. After opening the folder where I want to run the demo, I select a specific Python interpreter environment, which is activated through `conda`. When I click Render in the Quarto walkthrough.qmd editor, an integrated terminal launches. However, the render command is executed before the `conda activate ...` command. Then the render errors because Jupyter isn't installed in my `base` environment.

How can I get the `conda activate ...` to run before the `quarto preview ...` in the integrated terminal?

**Comment by jjallaire** [comment]
Thanks for reporting this! I've just made a change to the VS Code extension to attempt to wait until the terminal activates the conda environment before running quarto preview. This is available in the v1.32.0 release. Give that a try and let me know if it resolves the problem.

**Comment by white-c** [comment]
That worked! Thank you. This is a great plugin and a great tool.

**Comment by jjallaire** [comment]
Great to hear!

**Comment by mnaR99** [comment]
I had the same issue on MacOs and now it is resolved, however I've also tried it on Windows but isn't working 

**Installed versions**

![image](https://user-images.githubusercontent.com/68126773/184988525-b6c38a22-33b3-4425-bc52-0da8b86b3603.png)

**Terminal output after clicking on render**
```
Microsoft Windows [Versión 10.0.22000.856]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\Users\Samantha\Documents\PythonTest>C:/ProgramData/Miniconda3/Scripts/activate

(base) C:\Users\Samantha\Documents\PythonTest>cmd /C"quarto preview test.qmd --no-browser --no-watch-inputs"

Starting python3 kernel...Traceback (most recent call last):
  File "C:\Program Files\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Program Files\Quarto\share\jupyter\notebook.py", line 16, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
There is an unactivated Python environment in env. Did you forget to activate it?


(base) C:\Users\Samantha\Documents\PythonTest>conda activate C:\Users\Samantha\Documents\PythonTest\env

(C:\Users\Samantha\Documents\PythonTest\env) C:\Users\Samantha\Documents\PythonTest>
```

**Comment by jjallaire** [comment]
It looks like VS Code is activating the `base` environment -- you may need to change your workspace configuration to ensure that it activates the other environment.

**Comment by NovaVolunteer** [comment]
Hi there I think I have something similar, I'm wanting to use my base environment but can't seem to get it pop up the preview, I get the ipython rendering just not the HTML preview. I installed the updated extension version. I'm likely not doing something right with the env. 

C:\Users\Brian Wright\Documents\R\jex_matching_algo>cmd /C"quarto preview quarto_demo.qmd --to html --no-browser --no-watch-inputs"
FINDSTR: Cannot open Wright

Starting python3 kernel...Traceback (most recent call last):
  File "C:\Users\Brian Wright\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module> 
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\Brian Wright\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 17, in <module>
    from nbclient import NotebookClient
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\nbclient\__init__.py", line 6, in <module>
    from .client import NotebookClient, execute  # noqa: F401
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\nbclient\client.py", line 14, in <module>
    from jupyter_client import KernelManager
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\Users\Brian Wright\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Brian Wright\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing _device: The specified module could not be found.

C:\Users\Brian Wright\Documents\R\jex_matching_algo>"C:/Users/Brian Wright/Anaconda3/Scripts/activate"

(base) C:\Users\Brian Wright\Documents\R\jex_matching_algo>conda activate base

(base) C:\Users\Brian Wright\Documents\R\jex_matching_algo>

**Comment by NovaVolunteer** [comment]
![quarto_issue](https://user-images.githubusercontent.com/19676476/185701405-cc5f0ffb-8840-41fa-9fb3-d57f94efbc4d.PNG)

**Comment by rkrug** [comment]
May I just revive this topic again:

rendering a quarto R document

- M1 MacBook Pro macOS Sonoma 14.4.1 (23E224)
- VSCode  1.88.1
- Quarto Extension v2.8.2

![Screenshot 2024-04-16 at 09 14 23](https://github.com/quarto-dev/quarto-cli/assets/487172/785b5d05-0613-4de1-8d8f-19fb1c35a07a)
