### ISSUE TITLE
v0.2.261 seems to have broken nested divs

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#193]
We are using nested divs, and v0.2.261 seems to have broken our build.

With the following page:

```
# A title

::: {.callout-note}

::: {.another-div}
Some text
:::

:::
```

https://github.com/matthew-brett/mysite

`quarto render` gives me:

```
Error running filter /Volumes/zorg/mb312/dev_trees/quarto-cli/src/resources/filters/quarto-pre/quarto-pre.lua:
...cli/src/resources/filters/quarto-pre/../common/table.lua:13: attempt to get length of a Block value (local 'values')
stack traceback:
	...cli/src/resources/filters/quarto-pre/../common/table.lua:13: in function 'tprepend'
	.../quarto-cli/src/resources/filters/quarto-pre/callout.lua:236: in function 'calloutLatex'
	(...tail calls...)
	...li/src/resources/filters/quarto-pre/../common/pandoc.lua:122: in function <...li/src/resources/filters/quarto-pre/../common/pandoc.lua:116>
ERROR: Error
    at Object.onComplete (file:///Volumes/zorg/mb312/dev_trees/quarto-cli/src/project/types/book/book-render.ts:245:15)
    at async renderFiles (file:///Volumes/zorg/mb312/dev_trees/quarto-cli/src/command/render/render.ts:222:12)
    at async renderProject (file:///Volumes/zorg/mb312/dev_trees/quarto-cli/src/command/render/project.ts:157:25)
    at async Command.fn (file:///Volumes/zorg/mb312/dev_trees/quarto-cli/src/command/render/cmd.ts:164:24)
    at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
    at async quarto (file:///Volumes/zorg/mb312/dev_trees/quarto-cli/src/quarto.ts:71:3)
    at async file:///Volumes/zorg/mb312/dev_trees/quarto-cli/src/quarto.ts:89:5
```

There is no error if I change the initial div to something generic like `{.some-div}`.

v0.2.260 gives no error.

**Comment by jjallaire** [comment]
Thanks! v0.2.293 has the fix: https://github.com/quarto-dev/quarto-cli/releases/tag/v0.2.293

The change in v0.2.261 is that in that release we started rendering all project formats by default (i.e. `quarto render` of your book is rendering HTML, PDF, etc.). This in turn tickled a LaTeX callout bug which has likely been there for a while (callouts w/ a nested div give this error).

Note that you can render still a single format or subset of formats with `--to` (e.g. `quarto render --to html` or `quarto render --to html,pdf`)

**Comment by matthew-brett** [comment]
Hmm - interesting - we did render our book (that has these divs) to PDF, most recently about [10 days ago](https://github.com/resampling-stats/resampling-with/runs/4156662466?check_suite_focus=true#step:12:57) - with no reported error.

**Comment by jjallaire** [comment]
That is interesting! There have been other changes related to divs in the
past couple of weeks. There was also a change in how we used the
pandoc.List class that was related to a regression in pandoc 2.16.1. So
perhaps one of those things?

**Comment by jjallaire** [comment]
@matthew-brett Since you are working on a multi-format book, some of the page layout stuff that we just added might be of interest: https://quarto.org/docs/authoring/page-layout.html

**Comment by matthew-brett** [comment]
Thanks - yes - those look useful.

**Comment by stefanv** [comment]
I see this issue was closed, but the regression (with pandoc 2.14.1, quarto 44d930e9e0bb36fe4a57819c49cbb18c02ee4d61) is still present.  I can confirm that the failure only happens on our PDF builds.

<details>

```
Error running filter /home/stefan/src/quarto-cli/src/resources/filters/quarto-pre/quarto-pre.lua:
...cli/src/resources/filters/quarto-pre/../common/table.lua:13: attempt to get length of a Block value (local 'values')
stack traceback:
	...cli/src/resources/filters/quarto-pre/../common/table.lua:13: in function 'tprepend'
	.../quarto-cli/src/resources/filters/quarto-pre/callout.lua:236: in function 'calloutLatex'
	(...tail calls...)
	...li/src/resources/filters/quarto-pre/../common/pandoc.lua:122: in function <...li/src/resources/filters/quarto-pre/../common/pandoc.lua:116>
ERROR: Error
    at Object.onComplete (file:///home/stefan/src/quarto-cli/src/project/types/book/book-render.ts:245:15)
    at async renderFiles (file:///home/stefan/src/quarto-cli/src/command/render/render.ts:222:12)
    at async renderProject (file:///home/stefan/src/quarto-cli/src/command/render/project.ts:157:25)
    at async Command.fn (file:///home/stefan/src/quarto-cli/src/command/render/cmd.ts:164:24)
    at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
    at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
    at async quarto (file:///home/stefan/src/quarto-cli/src/quarto.ts:72:3)
    at async file:///home/stefan/src/quarto-cli/src/quarto.ts:90:5
```

</details>

**Comment by stefanv** [comment]
I just did a bisect, and that points to the following commit:

```
commit 042764f836e629f7e710a4b46f54bc17d921c10a
Author: JJ Allaire <jj@rstudio.com>
Date:   Sun Nov 7 12:33:36 2021 -0500

    update to pandoc 2.16.1

 configuration | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by jjallaire** [comment]
Yes, the fix for this went it just a couple commits after the one you are running: https://github.com/quarto-dev/quarto-cli/commit/4157dce6954540ba12d937b823c938de8b38fd46

**Comment by stefanv** [comment]
OK, thanks!
