### ISSUE TITLE
error: TS2801 [ERROR]: This condition will always return true since this 'Promise<boolean>' is always defined.

### ISSUE THREAD

**Issue by yurivict** [quarto-dev/quarto-cli#201]
Build fails:

```
Check file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/quarto.ts
error: TS2801 [ERROR]: This condition will always return true since this 'Promise<boolean>' is always defined.
    if (exists(yamlFile)) {
        ~~~~~~~~~~~~~~~~
    at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/config/metadata.ts:54:9

TS2773 [ERROR]:     Did you forget to use 'await'?
        if (exists(yamlFile)) {
            ~~~~~~~~~~~~~~~~
        at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/config/metadata.ts:54:9

TS2345 [ERROR]: Argument of type '9' is not assignable to parameter of type 'Signal'.
      serverLogProcess.kill(9);
                            ^
    at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/execute/jupyter/jupyter-kernel.ts:143:29

TS2801 [ERROR]: This condition will always return true since this 'Promise<string | undefined>' is always defined.
  } else if (which("git")) {
             ~~~~~~~~~~~~
    at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/project/project-gitignore.ts:44:14

TS2773 [ERROR]:     Did you forget to use 'await'?
      } else if (which("git")) {
                 ~~~~~~~~~~~~
        at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/project/project-gitignore.ts:44:14

TS2801 [ERROR]: This condition will always return true since this 'Promise<boolean>' is always defined.
  if (installed()) {
      ~~~~~~~~~~~
    at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/command/tools/tools/tinytex.ts:98:7

TS2773 [ERROR]:     Did you forget to use 'await'?
      if (installed()) {
          ~~~~~~~~~~~
        at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/command/tools/tools/tinytex.ts:98:7

TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'.
  const streams = signos.map(Deno.signal);
                                  ~~~~~~
    at https://deno.land/std@0.97.0/signal/mod.ts:35:35

TS2345 [ERROR]: Argument of type 'unknown' is not assignable to parameter of type 'AsyncIterableIterator<void>'.
    mux.add(stream);
            ~~~~~~
    at https://deno.land/std@0.97.0/signal/mod.ts:38:13

TS2571 [ERROR]: Object is of type 'unknown'.
      stream.dispose();
      ~~~~~~
    at https://deno.land/std@0.97.0/signal/mod.ts:44:7

TS2801 [ERROR]: This condition will always return true since this 'Promise<boolean>' is always defined.
    isPortAvailable({
    ^
    at https://deno.land/x/port@1.0.0/mod.ts:182:5

TS2773 [ERROR]:     Did you forget to use 'await'?
        isPortAvailable({
        ^
        at https://deno.land/x/port@1.0.0/mod.ts:182:5

TS2801 [ERROR]: This condition will always return true since this 'Promise<boolean>' is always defined.
    isPortAvailable({
    ^
    at https://deno.land/x/port@1.0.0/mod.ts:201:5

TS2773 [ERROR]:     Did you forget to use 'await'?
        isPortAvailable({
        ^
        at https://deno.land/x/port@1.0.0/mod.ts:201:5

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
      onSignal(Deno.Signal.SIGINT, abend);
                    ~~~~~~
    at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/quarto.ts:83:21

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
      onSignal(Deno.Signal.SIGTERM, abend);
                    ~~~~~~
    at file:///disk-samsung/freebsd-ports/misc/quarto-cli/work/quarto-cli-0.2.312/src/quarto.ts:84:21

Found 11 errors.
*** Error code 1
```

Command:
> deno cache --reload ${WRKSRC}/src/quarto.ts --unstable --importmap=${WRKSRC}/src/import_map.json

Version: 0.2.312
deno-1.16.1
FreeBSD 13

**Comment by jjallaire** [comment]
We are currently on Deno 1.13.2 (see https://github.com/quarto-dev/quarto-cli/blob/main/configuration#L11) and it looks like you are compiling with 1.16.1. We'll soon be moving to the latest Deno and these build issues should go away at that point.

**Comment by jjallaire** [comment]
We are now on Deno 1.16.4
