### ISSUE TITLE
Property 'Signal' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by yihui** [quarto-dev/quarto-cli#225]
I think this error started to appear recently (in the past few days). I've been building quarto-latexmk in the tinytex repo and started to see this error:

```
Check file:///Users/appveyor/projects/tinytex/quarto-cli/src/command/render/latexmk/quarto-latexmk.ts
error: TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
      onSignal(Deno.Signal.SIGINT, cleanup);
                    ~~~~~~
    at file:///Users/appveyor/projects/tinytex/quarto-cli/src/command/render/latexmk/quarto-latexmk.ts:137:21
TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
      onSignal(Deno.Signal.SIGTERM, cleanup);
                    ~~~~~~
    at file:///Users/appveyor/projects/tinytex/quarto-cli/src/command/render/latexmk/quarto-latexmk.ts:138:21
Found 2 errors.
error: Uncaught (in promise) Error: Failure to compile /Users/appveyor/projects/tinytex/quarto-cli/src/command/render/latexmk/quarto-latexmk.ts
    throw Error(`Failure to compile ${input}`);
          ^
    at compile (file:///Users/appveyor/projects/tinytex/quarto-cli/package/src/util/deno.ts:65:11)
    at async compileQuartoLatexmk (file:///Users/appveyor/projects/tinytex/quarto-cli/package/src/common/compile-quarto-latexmk.ts:131:7)
```

It seems the problem came from https://github.com/quarto-dev/quarto-cli/blob/7c3c8467b17df45782d7eba741b3faf6165d8b54/src/command/render/latexmk/quarto-latexmk.ts#L137

@dragonstyle Any ideas?

**Comment by dragonstyle** [comment]
This is almost certainly related to the Deno version- we recently upgraded to Deno 1.16 and this changed the way Signal is used. We may have missed this usage- I’ll check it out first thing tomorrow (est). Sorry about that!

**Comment by jjallaire** [comment]
fixed here: https://github.com/quarto-dev/quarto-cli/commit/47b0648ea0d6de8da151cd6a32cc97217e112c9b

**Comment by dragonstyle** [comment]
Thanks @jjallaire!

**Comment by yihui** [comment]
Thanks! I can confirm that it was fixed.
