### ISSUE TITLE
More informative error when format-resources isn't found

### ISSUE THREAD

**Issue by Nenuial** [quarto-dev/quarto-cli#2291]
I was hunting an error in one of my extensions today and it took me a very long time to understand what was going wrong. The error message I was getting was `ERROR: Source and destination cannot be the same.`

This was caused by a missing format ressource I had listed under `format-resources`. Would it be possible to have a clearer error when this happens?

**Comment by jkylearmstrong** [comment]
I just got a similar message

**Comment by higgi13425** [comment]
Same message - ERROR: Source and destination cannot be the same.
I published interactively once. Now trying to set up auto-update with linux server and cron.
Everything renders to HTML, then I get this error in the log.

Full details from the log:

[1m[34mRendering for publish:
[39m[22m
[31m

processing file: sgm_data.qmd
[39m1/17                  
2/17 [setup]          
3/17                  
4/17 [unnamed-chunk-1]
5/17                  
6/17 [unnamed-chunk-2]
7/17                  
8/17 [unnamed-chunk-3]
9/17                  
10/17 [unnamed-chunk-4]
11/17                  
12/17 [unnamed-chunk-5]
13/17                  
14/17 [unnamed-chunk-6]
15/17                  
16/17 [unnamed-chunk-7]
17/17                  
[31moutput file: sgm_data.knit.md

[39m[1mpandoc [22m
  to: html
  output-file: sgm_data.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
[1mmetadata[22m
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: SGM Data for Pfizer Multicenter Project
  editor: visual
  
[91mERROR: Source and destination cannot be the same.

Stack trace:
    at copyTo (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:41328:15)
    at stageDocumentPublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:102128:9)
    at renderForPublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:102116:24)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async handlePublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:102015:26)
    at async publishDocument (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106587:38)
    at async publish6 (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106679:132)
    at async doPublish (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106639:13)
    at async publishAction (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106650:9)
    at async Command.fn (file:///app/apps/rhel8/quarto/1.4.549/bin/quarto.js:106627:9)[39m

**Comment by cderv** [comment]
> [91mERROR: Source and destination cannot be the same.

@higgi13425 thanks for your feedback. This error message is generic when quarto happens to be in a situation where files need to be copied, but another version of these files already exist at destination. 

Following your other issue, I don't think this is related to this old one. Let's note revive old thread - we prefer that new discussion happen in newer thread. Thank you

**Comment by higgi13425** [comment]
Done in #10276. Perhaps someday a cleaned up version of this can make it to quarto documentation.
