### ISSUE TITLE
Installing "python3 -m pip install jupyter matplotlib plotly_express" fails

### ISSUE THREAD

**Issue by mudgen** [quarto-dev/quarto-cli#2327]
### Bug description

I followed the instructions in the tutorial here: https://quarto.org/docs/get-started/hello/vscode.html
In said to execute this command:
```
python3 -m pip install jupyter matplotlib plotly_express
```
I executed it and I got the following error output:
```
 Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-nopuxoh1/scipy/setup.py", line 631, in <module>
          setup_package()
        File "/tmp/pip-install-nopuxoh1/scipy/setup.py", line 627, in setup_package
          setup(**metadata)
        File "/tmp/pip-build-env-osw6z1d6/lib/python3.7/site-packages/numpy/distutils/core.py", line 137, in setup
          config = configuration()
        File "/tmp/pip-install-nopuxoh1/scipy/setup.py", line 529, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
      See site.cfg.example in the Scipy source directory and
      https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
  
      ----------------------------------------
  Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-nopuxoh1/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mzmn3in7/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-0s4nd0vv --compile" failed with error code 1 in /tmp/pip-install-nopuxoh1/scipy/
  
  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-0s4nd0vv --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.29.22 oldest-supported-numpy scipy>=1.3" failed with error code 1 in None
```

I am using MX Linux 19.4.    What should I do to get this working so I can follow the rest of the tutorial?

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Unfortunately, this is an issue with your python/distribution setup, and not a quarto issue.

**Comment by mudgen** [comment]
Yes, but it is also an issue with the [Quarto instructions]( https://quarto.org/docs/get-started/hello/vscode.html) since they don't work.

**Comment by cscheid** [comment]
What you're seeing is that you need to install the appropriate dependencies for the libraries, and that will depend on your python and distribution. Unfortunately, that is a general issue with Python and OS support: you will need to know your way. This is sadly, truly not a bug on our end (we would love to be able to fix this, but that's not possible to do given the variety of OSs out there.) I would look for your error message on forums of your particular operating system.

**Comment by jspaezp** [comment]
I guess this could be moved as a request for improved documentation ... maybe a line mentioning that setting up python and installing packages is beyond the scope of that tutorial

fyi @mudgen  ... based on my experience in linux, you have to install `libopenblas-dev`,  which in debian would be something like `sudo apt install libopenblas-dev` but im not familiar with mx linux

**Comment by mudgen** [comment]
> What you're seeing is that you need to install the appropriate dependencies for the libraries, and that will depend on your python and distribution. Unfortunately, that is a general issue with Python and OS support: you will need to know your way. This is sadly, truly not a bug on our end (we would love to be able to fix this, but that's not possible to do given the variety of OSs out there.) I would look for your error message on forums of your particular operating system.

I understand, thanks.
