### ISSUE TITLE
Error: Checking Jupyter engine render

### ISSUE THREAD

**Issue by Dagwbl** [quarto-dev/quarto-cli#2510]
### Bug description

# Description
- Windows 11
- quarto-cli version 1.1.251

Anaconda I have installed it before, but I have uninstalled it and replaced it with miniconda. At the same time, I also set an environment variable for `Quarto_python`.But I still get a mistake in running Quarto Check. Output is as follows

```bash

❯ quarto check

[>] Checking Quarto installation......OK
      Version: 1.1.251
      Path: D:\Program Files\Quarto\bin
      CodePage: 936

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: D:/ProgramData/Miniconda3/Python.exe
      Jupyter: 4.10.0
      Kernels: base, micropython, python38364bitfc016c1517d34469ac97e72b9510044e, python3, d2l

(\) Checking Jupyter engine render....2022-09-20 13:14:09,015 - traitlets - ERROR - Failed to run command:
['D:\\ProgramData\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\Sky\\AppData\\Local\\Temp\\tmphxxkvr19.json']
    PATH='C:\\Users\\Sky\\.oh-my-posh;D:\\ProgramData\\Miniconda3;D:\\ProgramData\\Miniconda3\\Library\\mingw-w64\\bin;D:\\ProgramData\\Miniconda3\\Library\\usr\\bin;D:\\ProgramData\\Miniconda3\\Library\\bin;D:\\ProgramData\\Miniconda3\\Scripts;D:\\ProgramData\\Miniconda3\\bin;D:\\ProgramData\\Miniconda3\\condabin;D:\\Program Files\\Quarto\\bin;D:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin;D:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\libnvvp;C:\\Program Files\\Common Files\\Siemens\\Automation\\Simatic OAM\\bin;D:\\Program Files\\SMV6;D:\\Program Files\\Cfast;D:\\Program Files\\Python\\Python39\\Scripts;D:\\Program Files\\Python\\Python39;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;D:\\Program Files\\Microsoft VS Code\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;D:\\Program Files\\mingw64\\bin;C:\\Program Files\\dotnet;D:\\Program Files\\MATLAB\\R2016b\\runtime\\win64;D:\\Program Files\\MATLAB\\R2016b\\bin;D:\\Program Files\\MATLAB\\R2016b\\polyspace\\bin;D:\\Program Files\\MiKTeX\\miktex\\bin\\x64;D:\\Program Files\\Java\\jdk-15.0.2\\bin;E:\\AppData\\Android\\Sdk\\platform-tools;D:\\Program Files (x86)\\PDFtk Server\\bin;D:\\Applications\\firemodels\\FDS6\\bin;D:\\Program Files (x86)\\NIST\\CONTAM 3.4.0.2;D:\\Applications\\Scoop\\apps\\msys2-cn\\20210725\\usr\\bin;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn;C:\\Program Files\\PKWARE\\pkzipc;D:\\Program Files\\LINGO 12;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.1.0;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;D:\\Program Files (x86)\\WinSCP;C:\\amp\\Apache24\\bin;C:\\amp\\Apache24;C:\\amp\\php;C:\\amp\\MariaDB\\bin;C:\\ProgramData\\ComposerSetup\\bin;C:\\Users\\Sky\\scoop\\shims;D:\\Applications\\Scoop\\shims;D:\\Program Files\\Quarto\\bin;D:\\ProgramData\\Python\\Python310\\Scripts;D:\\ProgramData\\Python\\Python310;C:\\Users\\Sky\\AppData\\Local\\Programs\\Python\\Launcher;C:\\Users\\Sky\\AppData\\Roaming\\Aria2\\maria2c.exe;C:\\Users\\Sky\\.dotnet\\tools'
    with kwargs:
{'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': None, 'close_fds': False}

2022-09-20 13:14:09,015 - traitlets - ERROR - [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 389, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\utils.py", line 38, in ensure_async
    return await obj
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 307, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 204, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\launcher.py", line 158, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\Miniconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified


[WinError 2] The system cannot find the file specified
[>] Checking Jupyter engine render....OK
```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Thanks for the report

I see you are using quarto-cli version 1.1.251 - can you try the last pre-release please ? 
https://quarto.org/docs/download/

We could confirm this is still an issue. Thank you

**Comment by cderv** [comment]
Currently I can't reproduce with a clean install of Anaconda and using latest quarto pre-release
````
(base) PS C:\Users\WDAGUtilityAccount> quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.139
      Path: C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: C:/Users/WDAGUtilityAccount/anaconda3/python.exe
      Jupyter: 4.9.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

(base) PS C:\Users\WDAGUtilityAccount> quarto --version
1.2.139
````

I ran the above from anaconda powershell prompt 

Can you check your anaconda installation ? Maybe update it somehow ? 

Some hints from your shared information also, even if I don't know if related: 
* I see `Path: D:/ProgramData/Miniconda3/Python.exe` so miniconda right ? 
* I see also Anaconda run after that 
````
ERROR - Failed to run command:
['D:\\ProgramData\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher',
````

Can you check if you have both ? and see why one would call the other ? Can you check your PATH for both ?

**Comment by Dagwbl** [comment]
First of all, thank you for reply.

I'm sorry I didn't describe it clearly. As you pointed out, the path of Anaconda3 is weird, I have installed Anaconda before, but I have uninstalled it a long time ago.
Therefore, this `D:\\ProgramData\\Anaconda3\\python.exe` does not exist. This `D:/ProgramData/Miniconda3/Python.exe`  exists. 
However, I've checked all the environment variables about the Anaconda3 and didn't find any trace.

I don't know how quarto retrieves the path.

**Comment by Dagwbl** [comment]
I have installed the pre-release version, but the error is still continuous.

**Comment by Dagwbl** [comment]
I notice a suspicious point that about ipykernel in quarto-cli pre-release.
```bash
❯ quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.140
      Path: D:\Program Files\Quarto\bin
      CodePage: 936

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: D:/ProgramData/Miniconda3/Python.exe
      Jupyter: 4.10.0
      Kernels: base, micropython, python38364bitfc016c1517d34469ac97e72b9510044e, python3, d2l

(|) Checking Jupyter engine render....2022-09-21 21:02:05,532 - traitlets - ERROR - Failed to run command:
['D:\\ProgramData\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\Sky\\AppData\\Local\\Temp\\tmpltmfftui.json']
    PATH='C:\\Users\\Sky\\.oh-my-posh;D:\\ProgramData\\Miniconda3;D:\\ProgramData\\Miniconda3\\Library\\mingw-w64\\bin;D:\\ProgramData\\Miniconda3\\Library\\usr\\bin;D:\\ProgramData\\Miniconda3\\Library\\bin;D:\\ProgramData\\Miniconda3\\Scripts;D:\\ProgramData\\Miniconda3\\bin;D:\\ProgramData\\Miniconda3\\condabin;D:\\Program Files\\Quarto\\bin;D:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin;D:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\libnvvp;C:\\Program Files\\Common Files\\Siemens\\Automation\\Simatic OAM\\bin;D:\\Program Files\\SMV6;D:\\Program Files\\Cfast;D:\\Program Files\\Python\\Python39\\Scripts;D:\\Program Files\\Python\\Python39;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;D:\\Program Files\\Microsoft VS Code\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;D:\\Program Files\\mingw64\\bin;C:\\Program Files\\dotnet;D:\\Program Files\\MATLAB\\R2016b\\runtime\\win64;D:\\Program Files\\MATLAB\\R2016b\\bin;D:\\Program Files\\MATLAB\\R2016b\\polyspace\\bin;D:\\Program Files\\MiKTeX\\miktex\\bin\\x64;D:\\Program Files\\Java\\jdk-15.0.2\\bin;E:\\AppData\\Android\\Sdk\\platform-tools;D:\\Program Files (x86)\\PDFtk Server\\bin;D:\\Applications\\firemodels\\FDS6\\bin;D:\\Program Files (x86)\\NIST\\CONTAM 3.4.0.2;D:\\Applications\\Scoop\\apps\\msys2-cn\\20210725\\usr\\bin;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn;C:\\Program Files\\PKWARE\\pkzipc;D:\\Program Files\\LINGO 12;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.1.0;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;D:\\Program Files (x86)\\WinSCP;C:\\amp\\Apache24\\bin;C:\\amp\\Apache24;C:\\amp\\php;C:\\amp\\MariaDB\\bin;C:\\ProgramData\\ComposerSetup\\bin;C:\\Users\\Sky\\scoop\\shims;D:\\Applications\\Scoop\\shims;D:\\Program Files\\Quarto\\bin;D:\\Applications\\winget\\r\\bin;D:\\ProgramData\\Python\\Python310\\Scripts;D:\\ProgramData\\Python\\Python310;C:\\Users\\Sky\\AppData\\Local\\Programs\\Python\\Launcher;C:\\Users\\Sky\\AppData\\Roaming\\Aria2\\maria2c.exe;C:\\Users\\Sky\\.dotnet\\tools'
    with kwargs:
{'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\Sky\\AppData\\Local\\Temp\\quarto-session5f894f6a\\ad23f575', 'close_fds': False}

2022-09-21 21:02:05,532 - traitlets - ERROR - [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 389, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\utils.py", line 38, in ensure_async
    return await obj
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 307, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 204, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "D:\ProgramData\Miniconda3\lib\site-packages\jupyter_client\launcher.py", line 158, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "D:\ProgramData\Miniconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\Miniconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified


[WinError 2] The system cannot find the file specified
[>] Checking Jupyter engine render....OK
```
focus on this pattern
```bash
[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: D:/ProgramData/Miniconda3/Python.exe
      Jupyter: 4.10.0
      Kernels: base, micropython, python38364bitfc016c1517d34469ac97e72b9510044e, python3, d2l
```
These Kernel were created by Anaconda before, but now it is not available.

**Comment by Dagwbl** [comment]
Even if I reinstall it, the problem comes back。
I thick there must be other residual files about jupyter.

**Comment by Dagwbl** [comment]
Thank you very much for your help. I type `jupyter kernelspec list` to get the key.
```bash
❯ jupyter kernelspec list
Available kernels:
  base                                              C:\Users\Sky\AppData\Roaming\jupyter\kernels\base
  micropython                                       C:\Users\Sky\AppData\Roaming\jupyter\kernels\micropython
  python38364bitfc016c1517d34469ac97e72b9510044e    C:\Users\Sky\AppData\Roaming\jupyter\kernels\python38364bitfc016c1517d34469ac97e72b9510044e
  python3                                           D:\ProgramData\Miniconda3\share\jupyter\kernels\python3
```
And then I removed this folder `C:\Users\Sky\AppData\Roaming\jupyter\`.
Check again
```bash
❯ quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.140
      Path: D:\Program Files\Quarto\bin
      CodePage: 936

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: D:/ProgramData/Miniconda3/Python.exe
      Jupyter: 4.10.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: D:/Applications/winget/r
      LibPaths:
        - D:/Applications/winget/r/library
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK
```
This is not a bug, but it can be optimized I think.
I think this issue can be closed, thank you again for your patience and reproduction.

**Comment by cderv** [comment]
Glad it is working now! 

> And then I removed this folder C:\Users\Sky\AppData\Roaming\jupyter\.

Is this from a previous installation ? 

Your issue will be a good documentation for anyone else encountering the same problem.

**Comment by Dagwbl** [comment]
Uninstalling anaconda does not delete the configuration file of jupyter.
We can use this command to look up all path about jupyter kernels:
```bash
jupyter kernelspec list
```
In my case, the jupyter folder in `C:/ProgramData/` or `C:/xxxx/Roaming/` both need to be removed

**Comment by gianfa** [comment]
Hi, the same thing happened to me and this thread was helpful.
The point, as I understand it, is that Quarto requests the first available jupyter kernel, and if it is corrupted/reference-non-existent, it gives an error.

Let me summarize my steps in full for future usefulness.

OS: MacOs
Quarto: v1.4.466

### 1. Quarto check
First, type in `quarto check`.
This will do several checks to make sure you have everything in order for running quarto.
The check on the python installation will tell you "what kernels does quarto see" (*Kernels*) and "where does it see the available python interpreter" (*Path*).
<img width="701" alt="Screenshot 2023-10-31 alle 21 33 54" src="https://github.com/quarto-dev/quarto-cli/assets/25075574/d5d15055-3898-43b5-abaa-3cefe93907bd">

### 2. Find the corrupted kernel

You now have everything you need to fix this by acting via jupyter.

Type `jupyter kernelspec list` to get the list of available kernels from jupyter. This command also shows the paths where the configurations of each of the kernels are stored.
Remember that it does not depend on which virtual environment you type this command, they are visible from everywhere.  

<img width="583" alt="Screenshot 2023-10-31 alle 21 33 06" src="https://github.com/quarto-dev/quarto-cli/assets/25075574/33ecddf1-e15b-4a3e-8bc0-117498d7ebd3">  

We now visit what we believe to be the JSON of the offending kernel and verify that the path is its own.
<img width="702" alt="Screenshot 2023-10-31 alle 21 33 14" src="https://github.com/quarto-dev/quarto-cli/assets/25075574/32515b4f-e7ba-4609-a387-f0b58be27c66">

### 3. Remove the kernel

Once we ascertain that the path is that of this kernel, we can proceed to remove it
`jupyter kernelspec remove <bad_kernel_name>`

<img width="519" alt="Screenshot 2023-10-31 alle 21 34 41" src="https://github.com/quarto-dev/quarto-cli/assets/25075574/56bb4257-d309-4399-82ac-a069ece2527e">

Now we can execute `quarto check` and note that everything passes the check. 

<img width="644" alt="Screenshot 2023-10-31 alle 21 29 59" src="https://github.com/quarto-dev/quarto-cli/assets/25075574/38f1cdcc-8b4a-4dc9-b684-232ffd328fbb">

Hope it will be helpful

**Comment by quinfer** [comment]
@gianfa I found you documentation very useful.  But after following your steps I am step getting the following output (I had 2 bad kernels I needed to remove)

```
(cv) (base) quinference@Barrys-MBP computer_vision % quarto check                   
Quarto 1.5.16
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.16
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/quinference/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.0 (Conda)
      Path: /Users/quinference/miniforge3/envs/cv/bin/python
      Jupyter: 5.7.1
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK
```

I wonder is there any information I am missing in the above output that could help my issues?
