### ISSUE TITLE
quarto serve contains-no-r.qmd fails

### ISSUE THREAD

**Issue by thomasballinger** [quarto-dev/quarto-cli#264]
Running serve on a file with only obs and no R in it fails:

    $ cat tmp.qmd
    ---
    title: "weird"
    format: html
    editor: visual
    ---

    ## Running Code

    ```{ojs}
    123 + 123
    ```
    $ quarto serve tmp.qmd
    ERROR: Error: Unable to run computations for input file
	at serve (file:///Users/tomb/quarto-cli/src/command/serve/serve.ts:32:5)
	at async Command.fn (file:///Users/tomb/quarto-cli/src/command/serve/cmd.ts:41:20)
	at async Command.execute (https://deno.land/x/cliffy@v0.19.3/command/command.ts:997:7)
	at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:918:16)
	at async Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:16)
	at async quarto (file:///Users/tomb/quarto-cli/src/quarto.ts:95:3)
	at async file:///Users/tomb/quarto-cli/src/quarto.ts:115:5

If I add some R it works fine.

Is `quarto serve` intended only for serving things that need a kernel, not dumb webserving? It's still useful for an ojs-only document, to render then serve from filesystem I have to run a server somehow and enable CORS headers.

**Comment by jjallaire** [comment]
`quarto serve` is only for shiny interactive documents

For documents w/o Shiny, just use `quarto preview`
