### ISSUE TITLE
puppeteer bug: "No inspectable targets"

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#2733]
This happens inconsistently in renders that require puppeteer:

```
$ quarto render mermaid-clip.qmd
ERROR: No inspectable targets

Error: No inspectable targets
    at defaultTarget (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/cri/deno-cri/chrome.js:63:15)
    at Chrome._fetchDebuggerURL (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/cri/deno-cri/chrome.js:211:24)
    at async Chrome._start (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/cri/deno-cri/chrome.js:158:19)
```

**Comment by cscheid** [comment]
See https://github.com/GoogleChrome/chrome-launcher/issues/145
