### ISSUE TITLE
ERROR: Theme file complation failed

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#338]
After pulling the latest commits, I got the following errors when previewing/rendering a project:

```markdown
ERROR: Theme file compilation failed:

Error: Undefined variable.
    ╷
968 │ $card-cap-bg: $gray-500 !default;
    │               ^^^^^^^^^
    ╵

Error: Theme file compilation failed:

Error: Undefined variable.
    ╷
968 │ $card-cap-bg: $gray-500 !default;
    │               ^^^^^^^^^
    ╵
    at dartCommand (file:///home/julian/quarto-cli/src/core/dart-sass.ts:71:11)
    at async dartCompile (file:///home/julian/quarto-cli/src/core/dart-sass.ts:44:10)
    at async compileWithCache (file:///home/julian/quarto-cli/src/core/sass.ts:314:25)
    at async compileSass (file:///home/julian/quarto-cli/src/core/sass.ts:126:10)
    at async resolveSassBundles (file:///home/julian/quarto-cli/src/command/render/pan
doc-html.ts:122:21)
    at async resolveExtras (file:///home/julian/quarto-cli/src/command/render/pandoc.t
s:685:14)
    at async runPandoc (file:///home/julian/quarto-cli/src/command/render/pandoc.ts:25
4:20)
    at async renderPandoc (file:///home/julian/quarto-cli/src/command/render/render.ts
:582:24)
    at async Object.onRender (file:///home/julian/quarto-cli/src/command/render/render
.ts:819:26)
    at async renderFiles (file:///home/julian/quarto-cli/src/command/render/render.ts:
261:9)

```

**Comment by dragonstyle** [comment]
I just made a change that I believe fixes this issue. I'm-opening until you are able to confirm (if you wouldn't mind updating on whether this fixed the issue)...

**Comment by juliantao** [comment]
That was fast! Thank you, I confirm that the issue is fixed now!

**Comment by dragonstyle** [comment]
Great news, thanks for reporting and the quick confirmation!
