### ISSUE TITLE
Problem with GitHub actions complaining about lack of Julia kernel while computations should be done locally

### ISSUE THREAD

**Issue by prosoitos** [quarto-dev/quarto-cli#3628]
### Bug description

I set-up a new website following the approach described [here](https://quarto.org/docs/publishing/netlify.html#github-action):

- Repo hosted on GitHub
- Site built by GitHub actions
- Computation ran locally with creation of a `_freeze` directory put under version control
- Site hosted on Netlify

All worked great until I created a reveal.js presentation in that site with Julia code.

GitHub actions failed with the following error in "Render and Publish":

```
ERROR: Jupyter kernel 'julia-1.8' not found.
```

Since the computations are supposed to happen locally in this workflow, I don't understand what is happening.

My `.github/workflows/publish.yml` matches the one shown in the doc and I followed the set of instructions literally. My `_freeze` is under vc and all changes in it pushed.

Thanks for the help.

OS: Arch Linux (6.0.11-arch1-1)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by rgaiacs** [comment]
I believe that your presentation is not using all the

**Comment by prosoitos** [comment]
> Are you rendering your project as a website and a presentation? If this is the case, I believe that render the website is making quarto think that the presentation changed and it needs to evaluate the cells again.

Yes: I am rendering my Quarto project as a website. In that website, I will have quite a few reveal.js presentations (rendered by Quarto as part of the same project). This reveal.js presentation with Julia code was the first one I added to the site, so it seems likely that I would have had the same problem with R or Python code, although I have tested it.

All works well when I preview the site on the local quarto server and I know someone who is building a similar Quarto project website with reveal.js presentations rendered by Quarto in it and who is not having any build problem while using `quarto publish` to publish in GitHub Pages.

So it seems that something with GitHub actions is not working when reveal.js presentations are rendered by Quarto inside a Quarto website project and when the code is ran locally.

I tried to switch to `freeze: true` and the problem remains the same.

**Comment by prosoitos** [comment]
It seems that GitHub actions is ignoring the `_freeze` content for the reveal.js presentation. I don't know how to go around this (other than changing my entire publish workflow strategy: running the code by GitHub actions, or using `quarto publish`, etc.)

**Comment by prosoitos** [comment]
I imagine that the `execute` `freeze` settings only apply at the project level, right?

Is there any way to make this apply at a more granular level? (e.g. at the directory level or at the document level). This could add some flexibility for sites that have various parts and it might be a way to have a `_freeze` dir more directly associated with those reveal.js presentation and that GitHub actions would detect.

**Comment by prosoitos** [comment]
A note: I haven't put my cache under version control as it seemed to me that the `_freeze` dir is all that was needed to build.

I supposed that the `.jupyter_cache` is irrelevant to this issue and that putting it under version control wouldn't help. Right?

**Comment by prosoitos** [comment]
Actually, I realized that it is possible to have `execute` `freeze` options specified at the file level.

But setting freeze to `true` for my reveal.js file still does not solve the problem.

**Comment by prosoitos** [comment]
As I am totally stuck with this, I decided to go the hard route (at least temporarily) and have GitHub run my code.

Unfortunately, I do not find any information on how to do this for Julia.

venv is documented for Python, renv for R (and R + Python), but my site will have R, Python, and Julia and, while I know how to create Julia environments, I am unsure how to integrate all 3 languages in an environment.

While this is not what I planned on doing, this seems like a new issue. So I will open one on this particular topic.

**Comment by mcanouil** [comment]
We can't really help here.
You describe something as it only occurs to your repository but do not share it.
If you wish for an helpful answer, could you provide with the repository in which you are having issue or at least share a small reproducible example in order to check if the issue is your setup or if this is a bug (or missing feature eventually).

**Comment by prosoitos** [comment]
Sure!

Here is the repo: https://github.com/WestDRI/arc-training

**Comment by mcanouil** [comment]
@prosoitos Sorry for not getting back sooner on this.

Is your issue still there? It appears the repository is active, so I assume you figured out the issue.

**Comment by prosoitos** [comment]
No, I never figured it out and since I decided that I didn't want to have the computations run by GitHub actions, I went for the easy (but totally unsatisfactory) solution of building the site locally and putting the `_site` dir under version control.

**Comment by prosoitos** [comment]
I would be curious to know whether this is reproducible.

Has anybody tested this setup following the Quarto documentation using Julia?

**Comment by mcanouil** [comment]
Did you explicitly set the kernel to use on the document(s) using Julia?

Might be related to the fact that you rely on kernel auto-detection, see .

**Comment by prosoitos** [comment]
I just checked out my commits when I was trying to get this to work and the kernel was explicitly set in my only Julia file with code at that point. I removed it later on. So this doesn't seem to be the problem.

**Comment by cderv** [comment]
Related issue possibly duplicate https://github.com/quarto-dev/quarto-cli/issues/4252

**Comment by prosoitos** [comment]
It does seem to be the same problem indeed. Thank you Christophe for looking into it.

**Comment by cscheid** [comment]
Hi, I'm now having a hard time reproducing this issue.

Here's an example where I ran a simple Julia notebook locally, and then had GHA render and publish to gh-pages with freeze: https://github.com/cscheid/quarto-julia-freeze-test/actions/runs/4359573877/jobs/7621505929

**Comment by mcanouil** [comment]
Thank you for using Quarto and reporting an issue!

Unfortunately, this issue is now considered stale because it has been opened since 14 days without providing a "working" reproducible example to help us investigate.
If you are still facing the issue, please review the ["Bug Reports" guide](https://quarto.org/bug-reports.html) on how to provide a fully reproducible example as a self-contained Quarto document or a link to a Git repository.
Without a reproducible example, it is unlikely that the issue will be addressed and thus will be closed.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

_Remove `stale` / `needs-repro` labels or this will be closed in 14 days._

**Comment by prosoitos** [comment]
A reproducible example was provided (by another user) in a Discussion and explained in detail in #4252 which was closed because it is a duplicate of the issue here.

If the issue here is closed, I think that #4252 (which provide necessary information) should be re-opened.

**Comment by mcanouil** [comment]
Thanks for the information.

I put it back here then 😉

---

> Test I did based on discussion below: 
> 
> 
> 
> * Clone project https://github.com/dmbates/plotdemo which has a `_freeze` folder and use Julia. 
> 
> * Delete the `docs` folder which is the output to recreate and I don't have Julia setup on my environment. 
> 
> * Rendering locally with `quarto preview` -> Julia is not needed. The freezing works - HTML file is created and I can preview result
> 
> * Trying to publish using `quarto publish quarto-pub` => **Rendering using Julia is happening** - It errors on my side as not setup. 
> 
> 
> 
> So we have an issue here I believe in our publish workflow. 
> 
> 
> 
> Side note : Trying to publish with `--no-render` fails also 
> 
> ````
> 
> quarto publish quarto-pub --no-render
> 
> ? Publish with account christophe.dervieux@gmail.com (Y/n) » Yes
> 
> ? Publish with name 'plots-demo-5bc8'? (Y/n) » Yes
> 
> 
> 
> [>] Creating quarto-pub document
> 
> 
> 
> ERROR: Output file plotdemo.html does not exist.
> 
> 
> 
> Error: Output file plotdemo.html does not exist.
> 
>     at renderForPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:235:19)
> 
>     at renderForPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:248:28)
> 
>     at handlePublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:117:30)
> 
>     at async publishDocument (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:260:36)
> 
>     at async publish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:282:9)
> 
>     at async doPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:195:7)
> 
>     at async publishAction (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:258:7)
> 
>     at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:153:11)
> 
>     at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
> 
>     at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:111:3)
> 
> ````
> 
> 
> 
> Probably related to how the document are supposed to be rendered and why `freeze` does not work. Or another issue
> 
> 
> 
> cc @cscheid 
> 
> 
> 
> ### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4237
> 
> 
> 
> <div type='discussions-op-text'>
> 
> 
> 
> <sup>Originally posted by **dmbates** February  5, 2023</sup>
> 
> I have been looking at the way that I currently have a Quarto book with Julia code chunks being rendered to gh-pages.  (Book is at https://JuliaMixedModels.github.io/EmbraceUncertainty).
> 
> 
> 
> If I understand the documents at https://quarto.org/docs/publishing/github-pages.html#freezing-computations correctly then setting `freeze: auto` in `_quarto.yml` and rendering the book will save the output of the code chunks in the `_freeze` directory (which I do have committed in the repository).
> 
> 
> 
> I was hoping that I could then render the book in a github action without the need to configure Jupyter and a Julia kernel.    However, the render and publish step fails because it can't access the kernel. (I am actually experimenting on another, private repository but can pull back the curtains if my description is too vague.)
> 
> 
> 
> Should this be happening or have I misconfigured the github action?  In other words, is there a way I can configure the github action so that Quarto recognizes that it will use the results in the _freeze directory and can ignore the jupyter specification in the files?
> 
> 
> 
> An alternative approach, although perhaps less efficient, would be to get a recipe for configuring a Julia kernel in Jupyter for the github action.</div>

**Comment by wtbarnes** [comment]
I am having the same problem, but in executing Python code in a revealjs presentation. The repository can be found here: https://github.com/wtbarnes/sphere-workshop-2023-talk

I am checking in `_freeze` and setting 

```yaml
execute:
  freeze: auto
```

in `_quarto.yml`. However, quarto is still trying to execute all of the inline code when rendering the presentation on Actions and is failing because of that. An example of this failure can be found in this build: https://github.com/wtbarnes/sphere-workshop-2023-talk/actions/runs/5350531419/jobs/9703251314.

My only guess is that this may be due to my quarto files not being in the root of my repository. I set `path` appropriately in `publish.yml` but maybe this is not propagated through when checking for the `_freeze` directory? My temporary workaround has been to render this locally and manually push to GH Pages, but this is not very satisfactory.

**Comment by cscheid** [comment]
I'm missing a small reproducible example. The one on https://github.com/quarto-dev/quarto-cli/issues/4252 is no longer available since the repository has been deleted and my attempts to reproduce have failed.

I'm going to push this to `Future`, but we can't actually address it without a repro case.
