### ISSUE TITLE
After pulling recent changes, all `quarto` commands fail

### ISSUE THREAD

**Issue by postylem** [quarto-dev/quarto-cli#3695]
### Bug description

I just pulled the most recent version of `quarto-cli`, and now all `quarto` commands fail.

For instance, `quarto check` gives the following errors:

```
Check file:///Users/j/Documents/GitHub/quarto-cli/src/quarto.ts
error: TS2554 [ERROR]: Expected 1 arguments, but got 0.
          process.kill();
                  ~~~~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/core/process.ts:30:19

    An argument for 'signo' was not provided.
        kill(signo: Signal): void;
             ~~~~~~~~~~~~~
        at asset:///lib.deno.ns.d.ts:2693:10

TS2339 [ERROR]: Property 'gid' does not exist on type 'typeof Deno'.
    return Deno.gid()!;
                ~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/std@0.166.0/node/process.ts:637:17

TS2339 [ERROR]: Property 'uid' does not exist on type 'typeof Deno'.
    return Deno.uid()!;
                ~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/std@0.166.0/node/process.ts:642:17

TS2339 [ERROR]: Property 'uid' does not exist on type 'typeof Deno'.
    if (Deno.build.os !== "windows" && info.uid === Deno.uid()) {
                                                         ~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/std@0.166.0/node/_fs/_fs_access.ts:33:58

TS2339 [ERROR]: Property 'uid' does not exist on type 'typeof Deno'.
    if (Deno.build.os !== "windows" && info.uid === Deno.uid()) {
                                                         ~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/std@0.166.0/node/_fs/_fs_access.ts:87:58

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; readonly readable: ReadableStream<Uint8Array>; }'.
  Deno.stdin.setRaw(true);
             ~~~~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/ansi/cursor_position.ts:31:14

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; readonly readable: ReadableStream<Uint8Array>; }'.
  Deno.stdin.setRaw(false);
             ~~~~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/ansi/cursor_position.ts:34:14

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; readonly readable: ReadableStream<Uint8Array>; }'.
      (Deno.stdin.setRaw as setRaw)(
                  ~~~~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/prompt/_generic_prompt.ts:299:19

TS2339 [ERROR]: Property 'setRaw' does not exist on type 'Reader & ReaderSync & Closer & { readonly rid: number; readonly readable: ReadableStream<Uint8Array>; }'.
      Deno.stdin.setRaw(false);
                 ~~~~~~
    at file:///Users/j/Documents/GitHub/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/prompt/_generic_prompt.ts:307:18

Found 9 errors.

```

I’m running quarto-cli on macOS Ventura 13.1

**Comment by cscheid** [comment]
It seems that for some reason, your installation hasn't updated to the latest version of Deno. Are you running quarto with our scripts?

**Comment by postylem** [comment]
I originally installed quarto-cli (about a year ago) with

```bash
git clone https://github.com/quarto-dev/quarto-cli
cd quarto-cli
./configure.sh
```

Then I run quarto simply with the command `quarto` (which was installed in `/usr/local/bin/quarto`).

I've been updating periodically by running (within the `quarto-cli` dir)
```bash
git pull
quarto check
```

I've never had a problem before, but with the latest pull, I ran into the errors above (as you say, it seems to be related to Deno, which I do have installed locally [deno version 1.28.3 (apple silicon), v8 10.9.194.5], but quarto-cli doesn't use the local installation, right?).

__UPDATE: I solved the issue by re-running the configuration script (`./configure.sh`)__

^ Is this something that I should have known to try?  I guess what I'm saying is: is the safer/more correct workflow for updating to follow the `git pull` with a `./configure.sh`?

**Comment by cscheid** [comment]
> Is this something that I should have known to try?

No, that update should have happened automatically, and I don't understand how that could have happened. `./configure.sh` will definitely get you set up, but it shouldn't be necessary, given that we have checks in `quarto` for new version declarations that force the configuration script to run.
