### ISSUE TITLE
Error when I write to stdout: how to solve it?

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#4052]
(This seems like a bug.)

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4047

<div type='discussions-op-text'>

<sup>Originally posted by **aborruso** January 22, 2023</sup>
Hi,
if I run

```
quarto render ./report/4d9ceaa1-addd-43f0-a0a8-2623e818f348.qmd -o -
```

at the end I have, in the last line

```
</body></html>ERROR: NotFound: No such file or directory (os error 2)
```

If I add an output file, adding `>tmp.html` I have the file in the folder and `ERROR: NotFound: No such file or directory (os error 2)` message in the shell.

If I add `--metadata-file ../resources/only_content.yml` - it's a file to set `embed-resources: true` - the HTML output has no embedding.

How to solve it?

I'm using `1.3.115` in Debian 11.

Thank you</div>

**Comment by dragonstyle** [comment]
I bet somewhere we are assuming that a file is being written and trying to post process it somehow :(. There are definitely places I likely forgot that this was possible :(

**Comment by dragonstyle** [comment]
Side note - my analysis above appears wrong - at least for a simple individual document being rendered to HTML. It does appear to reproduce for a web project.

**Comment by cscheid** [comment]
Yeah, the stack trace is this:

```
ERROR: NotFound: No such file or directory (os error 2)

NotFound: No such file or directory (os error 2)
    at Object.realPathSync (deno:runtime/js/30_fs.js:146:16)
    at projectPath (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render.ts:307:20)
    at Object.complete (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render.ts:330:15)
    at async Object.onPostProcess (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render-files.ts:566:28)
    at async renderFiles (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render-files.ts:522:7)
    at async renderProject (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/project.ts:260:23)
    at async Command.fn (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/cmd.ts:193:26)
    at async Command.execute (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/quarto.ts:111:3)
    at async file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/quarto.ts:138:5
```

I'm on it.

**Comment by aborruso** [comment]
Thank you very much
