### ISSUE TITLE
Quarto publish fails when project ``output-dir`` is specified

### ISSUE THREAD

**Issue by dkubek** [quarto-dev/quarto-cli#4158]
### Bug description

# Bug description

Running ``quarto publish gh-pages`` when ``output-dir`` is specified in ``_quarto.yml`` fails with error:

```sh
ERROR: NotFound: No such file or directory (os error 2)
```

# Minimal working example

Create a new project with
```sh
quarto create-project foo
```
and initialize it with a git repository
```sh
cd foo/
git init
git add .
git commit -m "Initial commit"
```
and set a remote for the repository.

Create an orphan ``gh-pages`` branch
```sh
git checkout --orphan gh-pages
git reset --hard
git commit --allow-empty -m "Initialising gh-pages branch"
git push origin gh-pages
```

Edit the ``_quarto.yml`` file so that
```yaml
project:
  title: "foo"
  output-dir: "_output"
```

Running ``quarto publish`` yields:
```
$ quarto --version
1.2.313
$ quarto publish gh-pages --no-browser
From github.com:dkubek/test
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

pandoc
  to: html
  output-file: foo.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: foo

ERROR: NotFound: No such file or directory (os error 2)
```

Also tried running with the pre-release
```
$ quarto --version
1.3.142
$ quarto publish gh-pages --no-browser
From github.com:dkubek/test
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

pandoc
  to: html
  output-file: foo.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: foo

ERROR: NotFound: No such file or directory (os error 2), stat '/home/dkubek/devel/foo/foo.html'
```

# OS information

```sh
$ uname -a
Linux fedora 6.1.7-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 18 18:37:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Complete stack:

```
ERROR: NotFound: No such file or directory (os error 2), stat '/Users/ct/Desktop/daily-log/2023/02/27/foo/foo.html'

NotFound: No such file or directory (os error 2), stat '/Users/ct/Desktop/daily-log/2023/02/27/foo/foo.html'
    at Object.statSync (deno:runtime/js/30_fs.js:322:9)
    at file:///Users/ct/Development/quarto-dev/quarto-cli/src/publish/publish.ts:284:14
    at Array.reduce (<anonymous>)
    at normalizePublishFiles (file:///Users/ct/Development/quarto-dev/quarto-cli/src/publish/publish.ts:282:43)
    at renderForPublish (file:///Users/ct/Development/quarto-dev/quarto-cli/src/publish/publish.ts:212:16)
    at async renderForPublish (file:///Users/ct/Development/quarto-dev/quarto-cli/src/publish/common/publish.ts:248:22)
    at async Object.publish (file:///Users/ct/Development/quarto-dev/quarto-cli/src/publish/gh-pages/gh-pages.ts:152:24)
    at async publishDocument (file:///Users/ct/Development/quarto-dev/quarto-cli/src/publish/publish.ts:260:36)
    at async publish (file:///Users/ct/Development/quarto-dev/quarto-cli/src/command/publish/cmd.ts:282:9)
    at async doPublish (file:///Users/ct/Development/quarto-dev/quarto-cli/src/command/publish/cmd.ts:195:7)
```

files after render look like:

```
./_quarto.yml
./foo.qmd
./.gitignore
./_output
./_output/foo_files
./_output/foo_files/libs
./_output/foo_files/libs/bootstrap
./_output/foo_files/libs/bootstrap/bootstrap.min.css
./_output/foo_files/libs/bootstrap/bootstrap-icons.css
./_output/foo_files/libs/bootstrap/bootstrap.min.js
./_output/foo_files/libs/bootstrap/bootstrap-icons.woff
./_output/foo_files/libs/quarto-html
./_output/foo_files/libs/quarto-html/quarto.js
./_output/foo_files/libs/quarto-html/quarto-syntax-highlighting.css
./_output/foo_files/libs/quarto-html/tippy.css
./_output/foo_files/libs/quarto-html/tippy.umd.min.js
./_output/foo_files/libs/quarto-html/anchor.min.js
./_output/foo_files/libs/quarto-html/popper.min.js
./_output/foo_files/libs/clipboard
./_output/foo_files/libs/clipboard/clipboard.min.js
./_output/foo.html
```
