### ISSUE TITLE
number-offset does not accept a single number as doc says

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#416]
````markdown
---
titre : "Sans titre"
format:
  html:
    number-sections: true
    number-offset: 5
validate-yaml: false
---

# Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

````

This will throw an error 
````
ERROR: Invalid value for number-offset (should be an array of numbers)

Error: Invalid value for number-offset (should be an array of numbers)
    at file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/crossref.ts:50:17
    at Array.forEach (<anonymous>)
    at crossrefFilterParams (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/crossref.ts:42:25)
    at filterParamsJson (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/filters.ts:84:8)
    at runPandoc (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/pandoc.ts:453:22)
    at async renderPandoc (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render.ts:586:24)
    at async Object.onRender (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render.ts:824:26)
    at async renderFiles (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render.ts:265:9)
    at async render (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-shared.ts:87:18)
    at async renderForPreview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:196:24)
````

I would expect this to work as it is documented this way  (https://quarto.org/docs/reference/formats/html.html#numbering) 
> So, for example, if you want the first top-level heading in your document to be numbered “6”, specify `number-offset: 5` 

but by convenience (instead of array of single number), probably as habits from **rmarkdown**

It could be an array was enforced because Pandoc's default file expect an array or maybe because crossref expect it 
https://github.com/quarto-dev/quarto-cli/blob/f8ef2cfce97f516c66e7a2c513ba59335037d829/src/command/render/crossref.ts#L42-L54

Currently YAML autocompletion does not enforce array like 
```yaml
number-offset: 
  - 5
```
but probably because of my feedback to @cscheid and change in 5e7955e147cfab8b4e62f672cb25aad450299908. @cscheid you should consider revert this maybe, at least for now ? 

If we keep array-only, then we should probably adapt the documentation from the one we took on Pandoc CLI flag and not default file. I get `Error in $: parsing [] failed, expected Array, but encountered Number` if I set  `number-offset: 5` in pandoc's default file. 

Opening this issue for discussion on this instead of leaving it on slack. 

Initial feedback was about autocompletion showing `number-offset: -` with trailing dash and was not sure why.  
![image](https://user-images.githubusercontent.com/6791940/158136138-ca132dff-6310-4973-bd95-389efb6f128d.png)

**Comment by jjallaire** [comment]
Fixed here: https://github.com/quarto-dev/quarto-cli/commit/523ed3ddbdac27bae4352f1173653cdf79bcfcd4
