### ISSUE TITLE
Removing empty dir on windows seems to file for project 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4194]
Test error 

````
[smoke] > quarto render docs\project\site -o - => ./test.ts:121:72
error: AssertionError: Failed assertion:

--------------------------------------------------------------------------------
[smoke] > quarto render docs\project\site -o -
          run-tests.psl ..\..\..\..\..\..\C:\Users\chris\Documents\DEV_R\quarto-cli\tests\smoke\project\project-stdout.test.ts

[verify] > unknown

La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. (os error 123), stat 'C:\Users\chris\Documents\DEV_R\quarto-cli\tests\docs\project\site\C:\Users\chris\AppData\Local\Temp\quarto-session96c8468e\9b1cbc71\dc6b9af2_files'
Error: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. (os error 123), stat 'C:\Users\chris\Documents\DEV_R\quarto-cli\tests\docs\project\site\C:\Users\chris\AppData\Local\Temp\quarto-session96c8468e\9b1cbc71\dc6b9af2_files'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/std@0.166.0/fs/exists.ts:75:10)
    at removeIfEmptyDir (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/path.ts:47:7)
    at renderProject (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/project.ts:347:9)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:193:26)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:111:3)
    at async Object.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/tests/test.ts:68:5)
    at async fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/tests/test.ts:165:11)
    at async Object.testStepSanitizer [as fn] (deno:cli/js/40_testing.js:448:7)
````

That is definitely not correctly build 
````
C:\Users\chris\Documents\DEV_R\quarto-cli\tests\docs\project\site\C:\Users\chris\AppData\Local\Temp\quarto-session96c8468e\9b1cbc71\dc6b9af2_files
````

It comes from 
https://github.com/quarto-dev/quarto-cli/blob/9ce89221b1ac4f36a0826c8a9778b9e60b045f66/src/command/render/project.ts#L305-L312

If I had some log info 
````
      if (!keepFiles) {
        console.log(projDir);
        console.log(renderedFile.file);
        console.log(dirname(renderedFile.file));
        console.log(inputFilesDir(renderedFile.file));
````
this is the result
````
C:\Users\chris\Documents\DEV_R\quarto-cli\tests\docs\project\site
C:\Users\chris\AppData\Local\Temp\quarto-session96c8468e\9b1cbc71\dc6b9af2.html
C:\Users\chris\AppData\Local\Temp\quarto-session96c8468e\9b1cbc71
dc6b9af2_files
````

Definitely not right

**Comment by cderv** [comment]
It seems it is not only windows as I am also getting the weird paths creation on Linux 
````
/home/cderv/project/quarto-cli/tests/docs/project/site
/tmp/quarto-session1abdc710/278814a0/0bf4d961.html
/tmp/quarto-session1abdc710/278814a0
0bf4d961_files
/home/cderv/project/quarto-cli/tests/docs/project/site/tmp/quarto-session1abdc710/278814a0/0bf4d961_files
````

However, it does not error the tests on Linux

**Comment by cderv** [comment]
Just tested : Issue happens only with stdout rendering `quarto render docs/project/site -o -` as it seems some files are created in temp directory and not project directory

**Comment by cscheid** [comment]
@cderv take a look at https://github.com/quarto-dev/quarto-cli/pull/4102, I bet the fix I made there doesn't work on windows.

**Comment by cderv** [comment]
So I have looked at #4102 . I understand that with `stdout` output we write to a temp file that we do not move afterward. 

However, during rendering of the project, we are computing some path (e.g. for resources) based on the rendered file. 
https://github.com/quarto-dev/quarto-cli/blob/9517cc3c82764763760e97701dfc4ab4724f818d/src/command/render/project.ts#L375
which will call at some point `dirname(file)` (being a temp folder), and join with project dir 
https://github.com/quarto-dev/quarto-cli/blob/9517cc3c82764763760e97701dfc4ab4724f818d/src/command/render/resources.ts#L91

This is not right, and creates issue on Windows (due to wrong path resulting of joining two absolute paths). 

I tried a few things but I don't think I got the correct fix for this. 

Do we need those resource files when `isTransient` is TRUE ? Can we skip somehow all those path computation step ?

Hopefully everything in the project folder is cleaned correctly when output to stdout. I need to check that too.
