### ISSUE TITLE
Python figure cross-reference missing caption and creating subcaption

### ISSUE THREAD

**Issue by lgonzalezsa** [quarto-dev/quarto-cli#4374]
### Bug description

When using Python via `vscode` Jupyter Notebook, adding the `label` and `fig-cap` to respective code cell not rendering properly in website project.

Expected one caption per figure but website project renders like subcaption, see image below.

Reproducible notebook here: 
https://github.com/lgonzalezsa/hello_quarto/blob/test_website/test/website/testing.ipynb

![image](https://user-images.githubusercontent.com/704686/219266454-3baff7db-3b9b-43cd-bfec-7702914f65d3.png)

My environment is:
Linux: Pop_OS! 22.04 6.0.12-76060006-generic
vscode:
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.0.12-76060006-generic
Sandboxed: No

quarto v1.2.335
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Up to date        v2023.02      v2023.02

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
I see you are using `pd.plot()` and `holoviews()` and I think we have some issues with such python plot graphics.

Here is a smaller reprex of issues with `holoviews`

````markdown
---
title: "test"
format: html 
keep-md: true
---

```{python}
import numpy as np
import pandas as pd

pd.options.plotting.backend = 'holoviews'
```

```{python}
#| label: fig-series
#| fig-cap: Tests Series
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()
```
````

![image](https://user-images.githubusercontent.com/6791940/219354686-34cd1ffd-5c54-431c-aca1-56eae346bee2.png)

Removing `pd.options.plotting.backend = 'holoviews'` will help, but still some issues as no caption 

![image](https://user-images.githubusercontent.com/6791940/219355291-5992d372-76d0-4319-9482-b559f2955a36.png)

So we have 2 issues here: 

* holoviews support
* Correctly set captions for output plots using `pd.plot()`

**Comment by lgonzalezsa** [comment]
Thank you for confirming, was thinking was an issue from my environment because was able to make it work before (see https://github.com/quarto-dev/quarto-cli/issues/2033 ) but that could be very well I was using older holoviews and pandas library versions. The Holoviews visualization renders properly yes, but the issue is with the captions as you indicated.
Another issue relates to pdf creation but that is another issue when I run: `quarto preview testing.ipynb --to pdf`
```
compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.161 
```

**Comment by cderv** [comment]
> LaTeX Error: Not in outer par mode.

Same as this one : https://github.com/quarto-dev/quarto-cli/issues/4370

Maybe related and something new in our layout feature it seems

**Comment by cscheid** [comment]
I can't even get holoviews to load on a simple virtualenv, so that will be hard to debug:

```
>>> pd.__version__
'1.5.2'
>>> holoviews.__version__
'1.15.4'
>>> pd.options.plotting.backend = 'holoviews'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/_config/config.py", line 226, in __setattr__
    _set_option(prefix, val)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/_config/config.py", line 160, in _set_option
    o.validator(v)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/core/config_init.py", line 751, in register_plotting_backend_cb
    _get_plot_backend(key)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1898, in _get_plot_backend
    module = _load_backend(backend_str)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1867, in _load_backend
    raise ValueError(
ValueError: Could not find plotting backend 'holoviews'. Ensure that you've installed the package providing the 'holoviews' entrypoint, or that the package has a top-level `.plot` method.
```

**Comment by lgonzalezsa** [comment]
Did you try `pd.options.plotting.backend = "holoviews"` ?

**Comment by cscheid** [comment]
> Did you try `pd.options.plotting.backend = "holoviews"` ?

From my earlier code,

```
>>> pd.__version__
'1.5.2'
>>> holoviews.__version__
'1.15.4'
>>> pd.options.plotting.backend = 'holoviews'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/_config/config.py", line 226, in __setattr__
    _set_option(prefix, val)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/_config/config.py", line 160, in _set_option
    o.validator(v)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/core/config_init.py", line 751, in register_plotting_backend_cb
    _get_plot_backend(key)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1898, in _get_plot_backend
    module = _load_backend(backend_str)
  File "/Users/cscheid/virtualenvs/homebrew-python3/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1867, in _load_backend
    raise ValueError(
ValueError: Could not find plotting backend 'holoviews'. Ensure that you've installed the package providing the 'holoviews' entrypoint, or that the package has a top-level `.plot` method.
@[cscheid](https://github.com/cscheid) cscheid modified the milestones: [v1.3](https://github.com/quarto-dev/quarto-cli/milestone/8), [v1.4](https://github.com/quarto-dev/quarto-cli/milestone/9) [10 minutes ago](https://github.com/quarto-dev/quarto-cli/issues/4374#event-8631970768)
@lgonzalezsa
Author
[lgonzalezsa](https://github.com/lgonzalezsa) commented [8 minutes ago](https://github.com/quarto-dev/quarto-cli/issues/4374#issuecomment-1448998983) • 
Did you try pd.options.plotting.backend = "holoviews" ?

I think my example is reproducible, try to run the code in my notebook:
https://github.com/lgonzalezsa/hello_quarto/blob/test_website/test/website/testing.ipynb

@cscheid

 
Add heading textAdd bold text, <Cmd+b>Add italic text, <Cmd+i>
Add a quote, <Cmd+Shift+.>Add code, <Cmd+e>Add a link, <Cmd+k>
Add a bulleted list, <Cmd+Shift+8>Add a numbered list, <Cmd+Shift+7>Add a task list, <Cmd+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
> Did you try `pd.options.plotting.backend = "holoviews"` ?

From my earlier code,

```
>>> pd.__version__
'1.5.2'
>>> holoviews.__version__
'1.15.4'
>>> pd.options.plotting.backend = 'holoviews'

```
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/quarto-dev/quarto-cli/blob/47d7ba29ac8e47aad3d2e618fc2813b7a594cfcf/.github/CONTRIBUTING.md) and [code of conduct](https://github.com/quarto-dev/quarto-cli/blob/47d7ba29ac8e47aad3d2e618fc2813b7a594cfcf/.github/CODE_OF_CONDUCT.md).
Assignees
@[cscheid](https://github.com/cscheid)
cscheid
Labels
[bug](https://github.com/quarto-dev/quarto-cli/labels/bug)
Something isn't working
[third-party](https://github.com/quarto-dev/quarto-cli/labels/third-party)
Issues involving interaction with a third-party library
Projects
None yet
Milestone
[v1.4](https://github.com/quarto-dev/quarto-cli/milestone/9)
Development
 for this issue or link a pull request.
3 participants
@cscheid
@lgonzalezsa
@cderv
```

**Comment by lgonzalezsa** [comment]
Oh got it. Seems a dependency issue. When I create my virtual env I use conda as follows. Seems the hvplot might be the missing dependency.

```
conda create --name hello_quarto
conda activate hello_quarto
conda install hvplot holoviews -c conda-forge
```

**Comment by cscheid** [comment]
Thank you, that solved the installation issue! That error message isn't the best.

I can now repro this on my side. I'll report back when i know more.

**Comment by cscheid** [comment]
I think there's something more fundamentally wrong with the way the `holoviews` backend is interacting with jupyter. On first preview of this file:

````
---
title: "test"
format: html 
keep-md: true
---

```{python}
import numpy as np
import pandas as pd

pd.options.plotting.backend = 'holoviews'
```

```{python}
#| label: fig-series
#| fig-cap: Tests Series
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()
```

````

I get an intermediate markdown output that looks like this:


````
::: {#fig-series .cell execution_count=2}
``` {.python .cell-code}
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()
```

::: {#fig-series-1 .cell-output .cell-output-display}

````````````{=html}
<script type="application/javascript">
(function(root) {
  function now() {
    return new Date();
  }

  var force = true;

  if (typeof root._bokeh_onload_callbacks === "undefined" || force === true) {
    root._bokeh_onload_callbacks = [];
...
````

If I reload the preview, though, by hitting shift-command-k again on VS Code, then I get a completely different output:

````
---
title: "test"
format: html 
keep-md: true
---


::: {#1cf56b1d .cell execution_count=1}
``` {.python .cell-code}
import numpy as np
import pandas as pd

pd.options.plotting.backend = 'holoviews'
```
:::


::: {#fig-series .cell execution_count=2}
``` {.python .cell-code}
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()
```

::: {#fig-series-1 .cell-output .cell-output-display}
:::

::: {#fig-series-2 .cell-output .cell-output-display execution_count=4}

```{=html}
<div id='1188'>
  <div class="bk-root" id="f98d0cf6-20ea-4503-a1b9-fe292413dfcf" data-root-id="1188"></div>
</div>
<script type="application/javascript">(function(root) {
  function embed_document(root) {
    var docs_json = {"99683c10-39c5-421d-b7ff-e7e8c86001d9":{"defs":[{"extends":null,"module":null,"name":"Rea
...
````

I'm not sure how to proceed here.
