### ISSUE TITLE
ERROR: NotFound: No such file or directory (os error 2), rename

### ISSUE THREAD

**Issue by royfrancis** [quarto-dev/quarto-cli#4583]
### Bug description

When defining both html and revealjs formats in the config (**_quarto.yml**), if format is not defined in individual qmd files, it gives this error:

```
ERROR: NotFound: No such file or directory (os error 2), rename '/home/user/Desktop/test/report.html' -> '/home/user/Desktop/test/_site/report.html'
```

To reproduce, create three files:

**_quarto.yml**

```
project:
  type: website

website:
  title: "Test"

format:
  html:
    theme: "flatly"
  revealjs:
    theme: "beige"
```

**presentation.qmd**

```
---
title: "Presentation"
format: revealjs
---

## Slide 1

This is a presentation

## Slide 2

More contents here
```

**report.qmd**

```
---
title: "Report"
---

## Heading 1

This is a report
```

Then run `quarto render`. Adding `format: html` to **report.qmd** fixes this issue.

It took me a while to troubleshoot as the error message was not helpful.

```
🢒  quarto --version
1.2.1

🢒  lsb_release -a
No LSB modules are available.
Distributor ID:	Zorin
Description:	Zorin OS 16.2
Release:	16
Codename:	focal
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
It would be ideal for quarto to issue a warning in this sort of scenario. But what's happening here is that both of your `html` and `revealjs` formats are rendering to the same output file. When you write in your _quarto.yml

````
format:
  html:
    theme: "flatly"
  revealjs:
    theme: "beige"
````

you're effectively telling quarto: "render these two formats when I don't specify otherwise". So quarto will attempt to render a revealjs presentation _and_ a webpage for every .qmd file. This confuses quarto, because they both generate .html files.

Things work when you specify a single format (like `format: html` or `format: revealjs`) because we take those to mean "render only this specific format".

As a result, when you're using this particular style in `_quarto.yml`, you really do need to specify a particular format at every .qmd file. We'd like to do better here and warn that multiple outputs are being generated (and so quarto will step on its own toes along the way), but it's a generally hard problem because we don't control all possible filenames.

In the end, I agree this is a bug, but it'll be very hard for us to fix it in a short to medium timeframe.

**Comment by chaz-clark** [comment]
Preview service running (5981)
ERROR: NotFound: No such file or directory (os error 2)

Stack trace:
    at opRun (ext:runtime/40_process.js:46:14)
    at Object.run (ext:runtime/40_process.js:132:15)
    at externalPreviewServer (file:///Applications/quarto/bin/quarto.js:96055:26)
    at serveProject (file:///Applications/quarto/bin/quarto.js:95998:240)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:96565:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8111:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:111534:5)
    at async file:///Applications/quarto/bin/quarto.js:111552:9
    
---
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-copy: true
    code-fold: true
    code-line-numbers: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-tools:
        source: false
        toggle: true
        caption: See code
---

Note: HTML file still produces and seems accurate. I tested both the current and the pre-release quarto 1.4.3 and i get the issue in both

**Comment by mcanouil** [comment]
@chaz-clark please format your post properly for it to be legible, i.e., use code blocks for code and outputs and use more backticks to enclose a code with code blocks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by mcanouil** [comment]
`output-file` can be set per format to avoid the issue:

```yml
format:
  html: default
  revealjs:
    output-file: my-revealjs
```

**Comment by petrelharp** [comment]
The original issue here has two formats in `_quarto.yml`; I'd like to point out the same bug manifesting in a different use case. Here's a MWE that fails to render:
```
---
title: Sample Page
format: 
  html: default
  revealjs: default
---

# Hello world

hi there
```
and (as `test.qmd`) gives the very non-informative error
```
ERROR: NotFound: No such file or directory (os error 2): rename '/home/peter/teaching/ds435/test_website/test.html' -> '/home/peter/teaching/ds435/test_website/docs/test.html'
```

As other have said (and is indeed in [the documentation](https://quarto.org/docs/output-formats/html-multi-format.html#rendering-formats-with-the-same-extension), a workaround is to specify the output file, for instance:
```
  revealjs:
      output-file: test.slides.html
```

The fundamental problem is not using unique file extensions for each format; it might have been nice to follow jupyter's `nbconvert` in making revealjs output use `.slides.html`.

A possible solution that doesn't break backwards compatibility would be to have a top-level configuration option that lets you set the suffix so that they don't clobber each other; for instance in `_quarto.yml`
```
revealjs:
    extension: slides.html
```

**Comment by mcanouil** [comment]
@petrelharp You mean `output-ext`? https://quarto.org/docs/reference/formats/html.html#rendering

**Comment by petrelharp** [comment]
Why, yes, that is what I mean!

So, here's a solution: add
```
format:
  revealjs:
    output-ext: slides.html
```
to either the file itself or to `_quarto.yml` (but if the latter, note that all files without `format` explicitly specified will then be rendered to slides). This seems like better advice than specifying `output-file` because it's a line that can be copy-pasted between files, or specified globally, without requiring file-specific changes.

It seems to me that (a) a more informative error, and (b) providing the advice to change `output-ext` in [the documentation](https://quarto.org/docs/output-formats/html-multi-format.html#rendering-formats-with-the-same-extension) and maybe the error message itself would close this issue (and the many quasi-duplicates of it).

**Comment by mcanouil** [comment]
Unfortunately, in complex projects such as book/website, changing the extension tends to break links last time I checked (there is probably an issue about it).

Edit:

- https://github.com/quarto-dev/quarto-cli/issues/13111

**Comment by petrelharp** [comment]
Good to know, thanks. However, that's also a bug, so if that is fixed then this will work...
