### ISSUE TITLE
Can't publish to top level of space

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4605]
### Bug description

Here's the error I was seeing.

```
(base) minimal: quarto publish --log-level debug confluence
Quarto v99.9.9
? Publish update to: › Add a new destination...
? Publish with account: › cwickham@gmail.com (https://cwickham.atlassian.net/)

[Confluence] [General] publish {
  account: {
    type: 1,
    name: "cwickham@gmail.com",
    server: "https://cwickham.atlassian.net/",
    token: "ATATT3xFfGF0tSKFA9RvdTX2E36tkbKr0IQ7BBRQ5aC6Yi6rjvbAG-IAsk-vMV4PeL9fKEHkhyWFV8tL4YyvWmFXV8CXjojuKwcW..."
  },
  type: "site",
  _input: "/Users/wickhamc/Documents/posit/confluence/minimal",
  title: "Minimal Project",
  _slug: "minimal-project",
  _options: {
    input: {
      dir: "/Users/wickhamc/Documents/posit/confluence/minimal",
      engines: [ "markdown" ],
      files: { input: [Array], resources: [Array], config: [Array], configResources: [Array] },
      config: { project: [Object], website: [Object], format: [Object], language: [Object] },
      formatExtras: [AsyncFunction: formatExtras]
    },
    server: null,
    token: undefined,
    id: undefined,
    render: true,
    prompt: true,
    browser: true
  },
  publishRecord: undefined
}
? Space or Parent Page URL: › https://cwickham.atlassian.net/wiki/spaces/QTS
[✓] Verifying...

[Confluence] [General] publish {
  parent: { space: "QTS", parent: undefined },
  server: "https://cwickham.atlassian.net/",
  id: 950275,
  key: "QTS"
}
ERROR: TypeError: Cannot read properties of undefined (reading 'id')

TypeError: Cannot read properties of undefined (reading 'id')
    at publishSite (file:///Users/wickhamc/Documents/posit/quarto-cli/src/publish/confluence/confluence.ts:614:61)
    at Object.publish (file:///Users/wickhamc/Documents/posit/quarto-cli/src/publish/confluence/confluence.ts:831:18)
    at async publishSite (file:///Users/wickhamc/Documents/posit/quarto-cli/src/publish/publish.ts:114:36)
    at async publish (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/publish/cmd.ts:278:9)
    at async doPublish (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/publish/cmd.ts:198:7)
    at async publishAction (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/publish/cmd.ts:261:7)
    at async Command.fn (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/publish/cmd.ts:156:11)
    at async Command.execute (file:///Users/wickhamc/Documents/posit/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/wickhamc/Documents/posit/quarto-cli/src/quarto.ts:119:3)
    at async file:///Users/wickhamc/Documents/posit/quarto-cli/src/quarto.ts:151:5
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
@cwickham Thank you for filing this.  I will take a look.

**Comment by allenmanning** [comment]
I'm not able to reproduce.
