### ISSUE TITLE
Can't publish to Confluence `attempt to index a nil value (field '_quarto')`

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#4699]
### Bug description

STR

Description: 

Publish to Confluence is failing.

Steps to Reproduce:

-  Attempt to render to `confluence-publish` format

Expected Result:
- Render without a failure

Actual Result:

````
Error running Lua:
...i/src/resources/extensions/quarto/confluence/publish.lua:112: attempt to index a nil value (field '_quarto')
stack traceback:
ERROR: Error
    at renderFiles (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/render/render-files.ts:532:23)
    at async renderProject (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/render/project.ts:263:23)
    at async renderForPublish (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/publish.ts:69:24)
    at async renderSite (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/confluence/confluence.ts:222:38)
    at async publishSite (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/confluence/confluence.ts:627:40)
    at async Object.publish (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/confluence/confluence.ts:835:12)
    at async publishSite (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/publish.ts:114:36)
    at async publish (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/publish/cmd.ts:275:9)
    at async doPublish (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/publish/cmd.ts:195:7)
    at async publishAction (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/publish/cmd.ts:258:7)
````

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
As part of debugging this, we should research if this smoke test caught it and is actually running:

https://github.com/quarto-dev/quarto-cli/blob/main/tests/docs/confluence/confluence-hello-world.qmd

**Comment by allenmanning** [comment]
It seems to have failed here: https://github.com/quarto-dev/quarto-cli/commit/789162faedc2a98091ff5221e5ac834324d96427

**Comment by jjallaire** [comment]
I just reverted that commit so we can get confluence working again for testing/docs/dev etc.

**Comment by cscheid** [comment]
I had made a terrible commit there, and Al and I fixed it this AM. Sorry!
