### ISSUE TITLE
[Confluence] Error publishing to site URL with param

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#4723]
STR

Description: 

Error publishing to site URL with param

Steps to Reproduce:
- Publish a doc to the following personal site URL `https://allenmanning.atlassian.net/wiki/spaces/~557058634d59d0949841909bb13093ab41d0c5/overview?homepageId=65617`

Expected Result:
It should work.

Actual Result:
It fails with

````
ERROR: Invalid Confluence parent URL: https://allenmanning.atlassian.net/wiki/spaces/~557058634d59d0949841909bb13093ab41d0c5/overview?homepageId=65617

Error: Invalid Confluence parent URL: https://allenmanning.atlassian.net/wiki/spaces/~557058634d59d0949841909bb13093ab41d0c5/overview?homepageId=65617
    at verifyConfluenceParent (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/confluence/confluence-verify.ts:57:11)
    at Object.publish (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/confluence/confluence.ts:256:9)
    at async publishDocument (file:///Users/amanning/projects/github/quarto/quarto-cli/src/publish/publish.ts:293:36)
    at async publish (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/publish/cmd.ts:282:9)
    at async doPublish (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/publish/cmd.ts:195:7)
    at async publishAction (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/publish/cmd.ts:258:7)
    at async Command.fn (file:///Users/amanning/projects/github/quarto/quarto-cli/src/command/publish/cmd.ts:153:11)
    at async Command.execute (file:///Users/amanning/projects/github/quarto/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/amanning/projects/github/quarto/quarto-cli/src/quarto.ts:119:3)
    at async file:///Users/amanning/projects/github/quarto/quarto-cli/src/quarto.ts:151:5
````

**Comment by smithbn** [comment]
I am getting this same error. I'm trying to publish to my personal space in Confluence but I get:
ERROR: Invalid Confluence parent URL: https://basis.atlassian.net/wiki/spaces/~brian.smith/pages/125108290

Does this have something to do with the "~" that's in the space key? The command at least gets further for other spaces I have tried where the space key doesn't have the "~".

**Comment by allenmanning** [comment]
Thanks for logging this [issue here](https://github.com/quarto-dev/quarto-cli/issues/5405).  I will take a look and post information to that issue.
