### ISSUE TITLE
Font size changes after section break

### ISSUE THREAD

**Issue by jatalah** [quarto-dev/quarto-cli#4834]
### Bug description

Why does the font get smaller after a section is introduced with a title slide using a level 1 header (#) in a revealjs presentation with `{.smaller}` applied globally?

I am using RStudio 2022.07.1  and Quarto Version: 1.2.335

Thanks

````
---
title: "test"
format: 
  revealjs:
    smaller: true
---

## Slide 1

This text is normal 

# New section

## Slide 2

This text is smaller.

````

``` sessionInfo()```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.utf8  LC_CTYPE=English_New Zealand.utf8    LC_MONETARY=English_New Zealand.utf8
[4] LC_NUMERIC=C                         LC_TIME=English_New Zealand.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] fansi_1.0.3      utf8_1.2.2       dplyr_1.1.0      R6_2.5.1         lifecycle_1.0.3  magrittr_2.0.3   pillar_1.8.1    
 [8] rlang_1.0.6      cli_3.4.1        rstudioapi_0.14  vctrs_0.5.2      generics_0.1.3   ellipsis_0.3.2   tools_4.2.0     
[15] glue_1.6.2       rsconnect_0.8.29 compiler_4.2.0   pkgconfig_2.0.3  tidyselect_1.2.0 tibble_3.1.7   

C:\Users\javiera\OneDrive - Cawthron\UA\Stats course\Quarto>quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.335
      Path: C:\Users\javiera\AppData\Local\Apps\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: C:/Users/javiera/Miniconda3/python.exe
      Jupyter: 5.2.0
      Kernels: python3

(|) Checking Jupyter engine render....2023-03-15 18:39:23,598 - traitlets - ERROR - DLL load failed while importing _sqlite3: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Users\javiera\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 656, in get
    value = obj._trait_values[self.name]
KeyError: 'kernel_dirs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\javiera\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 85, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\javiera\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 397, in _async_start_kernel
    kernel_cmd, kw = await self._async_pre_start_kernel(**kw)
  File "C:\Users\javiera\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 359, in _async_pre_start_kernel
    self.kernel_spec,
  File "C:\Users\javiera\Miniconda3\lib\site-packages\jupyter_client\manager.py", line 182, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "C:\Users\javiera\Miniconda3\lib\site-packages\jupyter_client\kernelspec.py", line 284, in get_kernel_spec
    resource_dir = self._find_spec_directory(kernel_name.lower())
  File "C:\Users\javiera\Miniconda3\lib\site-packages\jupyter_client\kernelspec.py", line 259, in _find_spec_directory
    for kernel_dir in [kd for kd in self.kernel_dirs if os.path.isdir(kd)]:
  File "C:\Users\javiera\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 703, in __get__
    return self.get(obj, cls)
  File "C:\Users\javiera\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 659, in get
    default = obj.trait_defaults(self.name)
  File "C:\Users\javiera\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 1872, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "C:\Users\javiera\Miniconda3\lib\site-packages\jupyter_client\kernelspec.py", line 199, in _kernel_dirs_default
    from IPython.paths import get_ipython_dir
  File "C:\Users\javiera\Miniconda3\lib\site-packages\IPython\__init__.py", line 53, in <module>
    from .terminal.embed import embed
  File "C:\Users\javiera\Miniconda3\lib\site-packages\IPython\terminal\embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\Users\javiera\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 73, in <module>
    from IPython.core.history import HistoryManager
  File "C:\Users\javiera\Miniconda3\lib\site-packages\IPython\core\history.py", line 11, in <module>
    import sqlite3
  File "C:\Users\javiera\Miniconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\javiera\Miniconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.

DLL load failed while importing _sqlite3: The specified module could not be found.
[>] Checking Jupyter engine render....OK

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
I believe this was a duplicate by 
* https://github.com/quarto-dev/quarto-cli/issues/7366

which has been solved. This should now be ok in 1.4
