### ISSUE TITLE
Table with label in callout block

### ISSUE THREAD

**Issue by gdietl** [quarto-dev/quarto-cli#5191]
### Bug description

If  a table is inserted in a callout block, defining a label has no effect, i.e.,
````
:::{.callout-note}
## Table in Callout Block
@tbl-test is a table which has no reference.

| Col 1 | Col 2 |
| ----- | ----- |
| a     | b     |

: Caption {#tbl-test}
:::
````
produces the warning `WARNING: Unable to resolve crossref @tbl-test`. The same table works outside the callout block.

I'm using quarto version 1.3.283.

**Comment by rgaiacs** [comment]
This is fixed in version 1.3.324.

![Screenshot of call out with table and cross reference.](https://user-images.githubusercontent.com/1506457/232036355-19790f60-d821-4b64-aca2-27d9d911100a.png)

Output of `quarto check`

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.324
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```
