### ISSUE TITLE
notebook cell embedding not working in book project/pdf output 

### ISSUE THREAD

**Issue by MHellmund** [quarto-dev/quarto-cli#5239]
### Bug description

- quarto 1.3.330 on Debian Linux
- book project, HTML and pdf output, 
-  quarto preview in VS Code works perfect
- `quarto render --to html` works perfect
- `quarto render --to pdf`  fails

index.qmd:
```
# index
{{< embed notebooks/nb1.ipynb#cell1  >}}
```

`quarto render  --to pdf` fails:

```
ERROR: Internal Error: named lifetime render-file not found

Error: Internal Error: named lifetime render-file not found
    at getCachedNotebookInfo (file:///opt/quarto/bin/quarto.js:80750:15)
    at notebookMarkdown (file:///opt/quarto/bin/quarto.js:80700:32)
    at replaceNotebookPlaceholders (file:///opt/quarto/bin/quarto.js:80679:38)
    at renderPandoc (file:///opt/quarto/bin/quarto.js:80981:34)
    at renderSingleFileBook (file:///opt/quarto/bin/quarto.js:98912:36)
    at async Object.onComplete (file:///opt/quarto/bin/quarto.js:98890:48)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:86640:16)
    at async renderProject (file:///opt/quarto/bin/quarto.js:86785:25)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:90841:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8437:13)
```

all files attached in test.zip 
[test.zip](https://github.com/quarto-dev/quarto-cli/files/11273575/test.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
Thanks for reporting this - I can reproduce it. It appears to be related to being a in book project. We'll take a look ASAP.

**Comment by dragonstyle** [comment]
This should be fixed in the next pre-release build (should be available any time). The fix is here:

https://github.com/quarto-dev/quarto-cli/pull/5241

Thanks again from reporting this!
