### ISSUE TITLE
NotFound Error when connecting to Jupyter Kernel on Windows

### ISSUE THREAD

**Issue by c-my** [quarto-dev/quarto-cli#5395]
I pressed the "Render" button in VSCode and the following error appears:
```powershell
PS C:\Users\xxx\Code\demo> quarto preview c:/Users/xxx/Code/demo/quarto/walkthrough.qmd --no-browser --no-watch-inputs
ERROR: NotFound: 系统找不到指定的文件。 (os error 2), remove 'C:\Users\xxx\AppData\Local\quarto\jt\f55fba9f67420280e4ee'

NotFound: 系统找不到指定的文件。 (os error 2), remove 'C:\Users\xxx\AppData\Local\quarto\jt\f55fba9f67420280e4ee'
    at Object.removeSync (deno:runtime/js/30_fs.js:157:9)
    at connectToKernel (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:54706:18)
    at async executeKernelKeepalive (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:54500:31)
    at async Object.execute (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:55305:17)
    at async renderExecute (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:86465:27)
    at async renderFiles (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:86588:51)
    at async render (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:90675:21)
    at async renderForPreview (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:102408:26)
    at async render (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:102303:20)
    at async preview (file:///C:/Users/xxx/scoop/apps/quarto/current/bin/quarto.js:102309:21)
```

Note: It doesn't happen every time. If the error occurs in this run, the next time it will succeed, and the next time there will be an error again.

**Comment by cderv** [comment]
I don't think this is related only to VSCODE, as I sometime encounter this issue also on Windows in RStudio IDE. I moved it to main repo. 

It happens for me when using document with Jupyter kernel and it follows the same pattern
* It runs ok 
* Then I encounter this error 
* Then it works. 

I thought it could be linked to my setup on Windows with Python, but it seems I am not the only one. Good to know. 

Can you confirm this is with a document using jupyter kernel ?

**Comment by c-my** [comment]
> Can you confirm this is with a document using jupyter kernel ?

Yes, the document is with jupyter kernel.

**Comment by YuanchenZhu2020** [comment]
The same error occurred when I use RStudio:

```
NotFound: 系统找不到指定的文件。 (os error 2)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at ServeRenderManager.fileRenderHash (file:///D:/R/Quarto/bin/quarto.js:103114:33)
    at file:///D:/R/Quarto/bin/quarto.js:103092:46
    at Array.forEach (<anonymous>)
    at ServeRenderManager.onRenderResult (file:///D:/R/Quarto/bin/quarto.js:103089:23)
    at serveProject (file:///D:/R/Quarto/bin/quarto.js:103200:19)
    at async Command.fn (file:///D:/R/Quarto/bin/quarto.js:103742:13)
    at async Command.execute (file:///D:/R/Quarto/bin/quarto.js:8437:13)
    at async quarto (file:///D:/R/Quarto/bin/quarto.js:127535:5)
    at async file:///D:/R/Quarto/bin/quarto.js:127553:9
```
But the `quarto preview` and `quarto server` work well in command line.

**Comment by elgabbas** [comment]
I also have this issue when using either `embed-resources: true` or `self-contained: true`

**Comment by mcanouil** [comment]
Possibly, there are quite a number of GitHub Issues/Discussion already opened on the subject.
Right Quarto is not recommended to be used in network/cloud drive/volume.

**Comment by doctor-phil** [comment]
I get the same error when not in a cloud drive.

ERROR: NotFound: The system cannot find the file specified. (os error 2)

```
NotFound: The system cannot find the file specified. (os error 2)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at sassLayerFile (file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:59996:30)
    at themeLayer (file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:126721:12)
    at file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:126639:20
    at Array.map (<anonymous>)
    at revealTheme (file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:126627:8)
    at Object.formatExtras (file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:126772:33)
    at runPandoc (file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:79982:81)
    at async renderPandoc (file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:81044:26)
    at async Object.onRender (file:///C:/Users/Phil/AppData/Local/Programs/Quarto/bin/quarto.js:86673:36)
```

This happens both in VScode and in the cmd

**Comment by cderv** [comment]
@doctor-phil this is not the same error as the OP - the stack trace is different.  Your error is not related to Jupyter kernel but SASS theme file. 

Can you open a new issue about this please ? You then will be able to fill the issue template and provide us with more context information, and a reproducible document with the issue.

thank you.

**Comment by cderv** [comment]
I can't reproduce anymore, and it's been a long time it has not happen. 

@c-my are you using 1.4 Pre-release already ? Did you encounter this issue recently ? 

I'll mark as need-repro and we'll fix when we can reproduce easily.

**Comment by zachsiegel-capsida** [comment]
> Possibly, there are quite a number of GitHub Issues/Discussion already opened on the subject. Right Quarto is not recommended to be used in network/cloud drive/volume.

Hi @mcanouil can you please say more about this?

In my company we use Quarto on AWS network drives (EFS volumes). We experience occasional freezes with `render`
 and `preview`.
 
Can you comment on what kinds of drives would cause Quarto to fail, and why?

**Comment by cscheid** [comment]
> Can you comment on what kinds of drives would cause Quarto to fail

We mean user-space network drives such as Dropbox, OneDrive, and Google Drive. 

> and why?

Unfortunately, we are not precisely sure: it's quite hard to diagnose these issues when they happen sporadically on someone else's computer. We currently suspect an interaction between [Deno's](https://deno.land/) implementation of file system calls and these drives' implementation of file system primitives.

> In my company we use Quarto on AWS network drives (EFS volumes).

We haven't had a report of issues in EFS, but it would be consistent with the other problems we have witnessed.

**Comment by zachsiegel-capsida** [comment]
Hi @cscheid, thank you so much for this response! 🙏

If there's any diagnostic process you recommend, I'd be glad to share details about our experience and (redacted where appropriate) logs. Otherwise, we'll just do our best.

We're already using the  steps recommended in [the Quarto docs on troubleshooting](https://quarto.org/docs/troubleshooting/), and the extra debug-level logging isn't giving anything useful when the freezes occur. It seems to mostly freeze on "Connecting to kernel".

**Comment by cscheid** [comment]
We need an example that's as close to reproducible on our end as possible. That's of course the problem, because these issues tend to involve a specific setup (as I imagine is the case in your AWS deployment). But if you could isolate a case in a simple EC2 instance where you can somewhat consistently trigger the bug, we'd love to hear about it!
