### ISSUE TITLE
JSON input breaks Panflute filters

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#5443]
### Bug description

Commit c5b6176 seems to have broken our Panflute filters.

As of that commit, when we do `quarto render`, we get the following traceback:

```
Traceback (most recent call last):
  File "/Users/mb312/dev_trees/test-quarto/a_filter", line 19, in <module>
    main()
  File "/Users/mb312/dev_trees/test-quarto/a_filter", line 13, in main
    return run_filter(action,
  File "/Users/mb312/dev_trees/panflute/panflute/io.py", line 230, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/Users/mb312/dev_trees/panflute/panflute/io.py", line 203, in run_filters
    doc = load(input_stream=input_stream)
  File "/Users/mb312/dev_trees/panflute/panflute/io.py", line 61, in load
    doc = json.loads(in_text, object_hook=from_json)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/Users/mb312/dev_trees/panflute/panflute/elements.py", line 1424, in from_json
    assert (len(data) == 1) or (len(data) == 2 and 'c' in data)
AssertionError
Error running filter /Users/mb312/dev_trees/quarto-cli/src/resources/filters/main.lua:
Error running filter /Users/mb312/dev_trees/test-quarto/a_filter:
Filter returned error status 1

```

This turns out to be because the JSON passed down into Panflute breaks on a Panflute assumption.

Reproducer : clone <https://github.com/matthew-brett/test-quarto> and `quarto render`.

Investigation of JSON - to get JSON passed to filter, use development version of `panflute`.  Patch `panflute` with:

```diff
diff --git a/panflute/io.py b/panflute/io.py
index d95d81e..5160767 100644
--- a/panflute/io.py
+++ b/panflute/io.py
@@ -55,7 +55,10 @@ def load(input_stream=None):
         input_stream = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')
 
     # Load JSON and validate it
-    doc = json.load(input_stream, object_hook=from_json)
+    in_text = input_stream.read()
+    with open('here.json', 'wt') as fobj:
+        fobj.write(in_text)
+    doc = json.loads(in_text, object_hook=from_json)
 
     # Notes:
     # - The hook gets called for dicts (not lists), and the deepest dicts
```

Add any Panflute filter to list of filters in `_quarto.yml`.  The `test-quarto` project above has one such, called `a_filter`.

Run `quarto render` to get error (and write `here.json`, the input JSON to the filter).   Now run:

```python
import json

from panflute import elements

contents = open('source/here.json', 'rt').read()
json.loads(contents, elements.from_json)
```

reproduces the error.

Running on macOS 13.3.1.

```
$ quarto check
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.1: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/mb312/dev_trees/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.11
      Path: /Users/mb312/.virtualenvs/resampling-with/bin/python3
      Jupyter: 5.3.0
      Kernels: ir

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /opt/homebrew/Cellar/r/4.3.0_1/lib/R
      LibPaths:
        - /Users/mb312/Library/R/arm64/4.3/library
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.0_1/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by matthew-brett** [comment]
Sorry - I did not make this clear in the initial writeup (edited now) but the break occurs when there is a `{{< var ` block.

**Comment by matthew-brett** [comment]
Or a `{{< meta ` block.

**Comment by matthew-brett** [comment]
Just to add - the breakage is older than this for other markup.   A page with:

```
::: {.callout-note}

Some text

:::
```

will also generate the same error as above, at least for Quarto 1.4.37.   See the updated test repository linked above.

**Comment by matthew-brett** [comment]
I should be clear - I don't need to process the callouts in a JSON filter - but I do need to use Panflute - which breaks on reading this JSON ...   The same applies to the var and meta blocks - I don't need to process them - but I do need to get the JSON into my Panflute filter to process other stuff.

**Comment by cscheid** [comment]
> which breaks on reading this JSON

Panflute breaks on JSON because _panflute_ it doesn't yet support Pandoc 3. That's unfortunately a Panflute bug. Quarto still supports JSON filters, though. It's important to understand the distinction.

To summarize:

1. quarto 1.3 uses Pandoc 3. Panflute doesn't support Pandoc 3 (until it does, there's nothing we can do.)
2. quarto 1.3 changed the path resolution for JSON filters. I didn't expect this to be a feature people depended on, and so I didn't communicate this as well as I should have.
3. quarto 1.3 changes the way callout filters are represented internally, which makes JSON filters that process them more challenging.

In quarto 1.4 (in the next 2-3 weeks actually), we will improve the situation for 2 and 3, but we can't solve 1.

**Comment by matthew-brett** [comment]
https://github.com/sergiocorreia/panflute claims that Panflute supports up to Pandoc 3.0.x, and Pandoc API 1.23 . Isn't that the API version y'all are getting from current Pandoc (3.1.2)?

```
$ echo a | ./package/dist/bin/tools/pandoc --to=json

{"pandoc-api-version":[1,23],"meta":{},"blocks":[{"t":"Para","c":[{"t":"Str","c":"a"}]}]}
```

**Comment by cscheid** [comment]
@matthew-brett Oh, thank you for setting me straight, I was wrong. Panflute 2.3.0 now _does_ support Pandoc 3: https://github.com/sergiocorreia/panflute/releases/tag/2.3.0 (This used to be the blocker, and I'm now wrong.)

Unfortunately, that means I don't know what's causing your error. The JSON we send your filter is just the output of pandoc's json format...

**Comment by matthew-brett** [comment]
The instructions above will generate the JSON that arrives at the filter - is that what you mean (latest quarto, patch to Panflute, `quarto render` with repo linked above, etc).

**Comment by matthew-brett** [comment]
Sorry - just to clarify - the patch to Panflute just outputs the JSON that arrives at the filter - it doesn't affect the behavior of the filter.

**Comment by cscheid** [comment]
> The instructions above will generate the JSON that arrives at the filter - is that what you mean (latest quarto, patch to Panflute, `quarto render` with repo linked above, etc).

I mean a single .qmd file with an accompanying .py filter and the command that causes the problem, in a single message. I apologize that this feels like a lot, but we handle on the order of 20-30 of these a day and could use the help making it easy for us to get to the problem with minimal friction.

**Comment by matthew-brett** [comment]
Ouch - do you mean that you need something simpler than:

```
git clone https://github.com/matthew-brett/test-quarto
cd test-quarto
quarto render
```

?

That will reproduce the error.   I bet you've got a better idea for getting the JSON getting into the filter (you'll see that's the file `a_filter`) - than the patch to Panflute - but you don't need that patch to reproduce the error.

**Comment by cscheid** [comment]
That should be enough! I just hadn't seen the repo link. Sorry!

**Comment by cscheid** [comment]
With that said, I don't understand why our json breaks panflute 2.3.0. It's probably a bug on their parser related to how we serialize custom AST nodes. We're making that a lot simpler in this branch, so it might not be worth reporting the bug, but the output we're sending is simply the output from `pandoc.write()`.

**Comment by matthew-brett** [comment]
Thanks!   Would you mind letting me know when it is merged?  I guess it will fix both the `var` / `meta` block and the `{.callout-note}` Panflute breakage?

**Comment by cscheid** [comment]
It's [this PR](https://github.com/quarto-dev/quarto-cli/pull/5459). On this branch I could run your test repo successfully.

**Comment by cscheid** [comment]
I just merged that branch, and on my machine, your example renders without an error. Can you confirm on your side?
