### ISSUE TITLE
Should `"video"` be `video` in docs?

### ISSUE THREAD

**Issue by warrickball** [quarto-dev/quarto-cli#5518]
### Bug description

I just tried to embed my first video using a "shortcode" as described in [the docs](https://quarto.org/docs/authoring/videos.html) with something like this:
```
# Just a video

{{< "video" "https://nso1.b-cdn.net/wp-content/uploads/2016/04/DKIST-First-Light-MZ-fullFOV-loop_FHD-H264.mp4" >}}
```
When I try to render to HTML, I get:
```
ERROR: invalid shortcode: "video" "https://nso1.b-cdn.net/wp-content/uploads/2016/04/DKIST-First-Light-MZ-fullFOV-loop_FHD-H264.mp4"

Error: invalid shortcode: "video" "https://nso1.b-cdn.net/wp-content/uploads/2016/04/DKIST-First-Light-MZ-fullFOV-loop_FHD-H264.mp4"
    at parseShortcode (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:55007:15)
    at isBlockShortcode (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:54945:16)
    at breakQuartoMd (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:55108:32)
    at validateDocumentFromSource (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:84332:22)
    at renderFiles (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:86518:48)
    at async renderProject (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:86794:25)
    at async Command.fn (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:90850:32)
    at async Command.execute (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:8437:13)
    at async quarto (file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:127535:5)
    at async file:///home/wball/Downloads/quarto-1.3.340/bin/quarto.js:127553:9
```
but if I remove the quotation marks around `"video"`, i.e. have a document with
```
# Just a video

{{< video "https://nso1.b-cdn.net/wp-content/uploads/2016/04/DKIST-First-Light-MZ-fullFOV-loop_FHD-H264.mp4" >}}
```
the compilation works as expected.

So I suspect this is just a mistake in the document (or it's fallen out of sync with how the shortcode works) but I hesitate to open a PR because I'm surprised this hasn't been reported before...

This is Fedora 37 with the following `quarto check` output:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /home/wball/Downloads/quarto-1.3.340/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

(\) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/lib64/R
      LibPaths:
        - /home/wball/R/x86_64-redhat-linux-gnu-library/4.2
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Thanks.

This is a "duplicate" of #5507

**Comment by mcanouil** [comment]
Fixed!
