### ISSUE TITLE
Improve error message on malformed shortcodes in 1.4

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5535]
```qmd
---
title: "Quarto Playground"
format: html
---

This is a playground for Quarto.

{{< meta title>}}
```

In 1.3, the above code would compile without complaining about the malformed shortcode and does nothing.
In 1.4, it produces an error[^1] that is a bit mysterious and could be improved.

```txt
Error running Lua:
...arto-cli/src/resources//pandoc/datadir/lpegshortcode.lua:111: attempt to concatenate a nil value
stack traceback:
        [C]: in function 'lpeg.match'
        ...s/quarto/quarto-cli/src/resources/filters/qmd-reader.lua:116: in function 'parse_shortcodes'
        ...s/quarto/quarto-cli/src/resources/filters/qmd-reader.lua:133: in function 'Reader'
ERROR: Error
    at renderFiles (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render-files.ts:539:23)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async render (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render-shared.ts:97:18)
    at async renderForPreview (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/preview/preview.ts:430:24)
    at async render (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/preview/preview.ts:189:22)
    at async preview (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/preview/preview.ts:206:18)
    at async Command.fn (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/preview/cmd.ts:356:7)
    at async Command.execute (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/quarto.ts:122:3)
    at async file:///Users/mcanouil/Projects/quarto/quarto-cli/src/quarto.ts:154:5
```

[^1]: Better than previous behaviour in my opinion.

**Comment by cscheid** [comment]
It was easier to make the parsing slightly more robust so that this works than it was to make a good error message (given where this is being parsed now.)

So with the change in main, you now get this:

<img width="381" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/976fd65a-bda7-4de8-ba55-06162fd66a48">

**Comment by mcanouil** [comment]
So now we can have malformed shortcodes😅

**Comment by cscheid** [comment]
Yes. We're not going to advertise that, and providing a real syntax checker with proper error line attribution is _very hard_ in this particular case. So we just quietly do something slightly better instead :)
