### ISSUE TITLE
error with empty _metadata.yml file

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5600]
### Bug description

Using Quarto 1.3.340 on macOS

```bash
# Run in a brand new directory.
touch index.qmd
touch _quarto.yml
touch _metadata.yml
quarto render
#> ERROR: Internal Error: createSourceContext called with bad location.
#> 
#> Error: Internal Error: createSourceContext called with bad location.
#>     at createSourceContext (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:14790:15)
#>     at createLocalizedError (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:14864:28)
#>     at file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:15006:55
#>     at Array.map (<anonymous>)
#>     at ValidationContext.collectErrors (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:15006:32)
#>     at ValidationContext.validate (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:14929:21)
#>     at validate (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:15293:20)
#>     at YAMLSchema.validateParse (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:15318:34)
#>     at validate (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:18623:43)
#>     at withValidator (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:15381:25)
```

This can happen with an empty `_metadata.yml` at any position in a website hierarchy. I originally encountered this while preparing a directory structure to have sub-directory configuration overrides; I first created empty `_metadata.yml` files in each directory, but started experimenting with values in only one of the YAML files.

```

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
I can reproduce this one, but you're missing a `touch _quarto.yml`:

```
$ mkdir test
$ cd test
$ quarto --version
1.3.340
$ touch index.qmd
$ touch _metadata.yml
$ touch _quarto.yml
$ quarto render
ERROR: Internal Error: createSourceContext called with bad location.

Error: Internal Error: createSourceContext called with bad location.
    at createSourceContext (file:///Users/cscheid/repos/github/cscheid/quarto-regress/releases/v1.3.340/bin/quarto.js:14790:15)
```

I think you get the error on your machine because you have a lingering _quarto.yml somewhere upfolder.

**Comment by aronatkins** [comment]
Error also happens with 59219cf8dbc945a71a952794f1d63bf9d13b40da

**Comment by aronatkins** [comment]
Thanks, @cscheid - you're right; I did have an `_quarto.yml` in a parent folder. I've amended my instructions.

**Comment by mcanouil** [comment]
@aronatkins Thanks for reporting this and the steps to reproduces!

**Comment by gordonwoodhull** [comment]
We get a clear error on this now.

```
ERROR: Directory metadata validation failed for /Users/gordon/src/quarto-cli/tests/docs/smoke-all/2024/06/12/5600/_metadata.yml.

(line 1, column 1) YAML value is missing.
```

Perhaps there is nothing more to do?

**Comment by aronatkins** [comment]
@gordonwoodhull - the error is much better, yes. Does an empty file need to be treated as a problem? Empty `_quarto.yml` files are allowed (this wasn't always the case).

**Comment by gordonwoodhull** [comment]
IMO it would be nicer to treat it as "no metadata" and I'm willing to implement that. Let's see what others think.

**Comment by cscheid** [comment]
@gordonwoodhull I'd be happy to pair with you over this. Unfortunately I have a last-minute trip to take tomorrow and friday, but we can revisit on Monday if needed.

**Comment by gordonwoodhull** [comment]
Thanks @cscheid! I've been scanning old 1.5 issues that look like they are low risk and which I think I can handle with my limited domain knowledge. I will give this and #5601 a try.

**Comment by cscheid** [comment]
> IMO it would be nicer to treat it as "no metadata" and I'm willing to implement that. Let's see what others think.

I agreed with this at the time, but I now think this can only add to the confusion. We could make the error even better than "YAML value is missing", and add "(consider using `{}` instead)". But:

An empty file in YAML has a meaning: it is `null`. That's different from `{}` and `[]`. If we made this work, we'd be implying that Quarto interprets `null` to mean `{}`. I now think we shouldn't add to the confusion.

**Comment by aronatkins** [comment]
@cscheid - Will it confuse folks that an empty `_quarto.yml` is treated differently from other YAML files? I suppose that there are other implications of an empty `_quarto.yml` - one can `quarto render` without providing filenames.

**Comment by cscheid** [comment]
> Will it confuse folks that an empty _quarto.yml is treated differently from other YAML files?

It might, and ideally I would like to change that too. But that would be a big breaking change.
