### ISSUE TITLE
error with _metadata.yml containing only comments

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5601]
### Bug description

Using Quarto 1.3.340 on macOS

```bash
# Run in a brand new directory.
touch index.qmd
echo '# this is a comment' > _metadata.yml
quarto render
#> ERROR: Directory metadata validation failed.
#> 
#> (line 1, column 19) YAML value is missing.
#> 1: # this is a comment
#>                     ~
#> 
#> 
#> Error: Directory metadata validation failed.
#> 
#> (line 1, column 19) YAML value is missing.
#> 1: # this is a comment
#>                     ~
#> 
#>     at readAndValidateYamlFromFile (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:42120:15)
#>     at async directoryMetadataForInputFile (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:58421:26)
#>     at async resolveFormats (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:83119:46)
#>     at async renderContexts (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:82632:21)
#>     at async Object.renderFormats (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:82683:26)
#>     at async inputTargetIndex (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:83499:21)
#>     at async resolveInputTarget (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:83578:19)
#>     at async resolveItem (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:93620:26)
#>     at async navigationItem (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:93591:16)
#>     at async navbarEjsData (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:93510:28)
```

Related to https://github.com/quarto-dev/quarto-cli/issues/5600

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by aronatkins** [comment]
Error also happens with 59219cf8dbc945a71a952794f1d63bf9d13b40da

**Comment by cscheid** [comment]
yup. Probably goes all the way back to 1.0 :)

**Comment by mcanouil** [comment]
@aronatkins Thanks for reporting this and the steps to reproduces!

**Comment by cscheid** [comment]
I made a PR for #5600, and have a fix for this, but I'm no longer convinced this is a bug.

An empty file in YAML has a meaning: it is `null`. That's different from `{}` and `[]`. If we made this work, we'd be implying that Quarto interprets `null` to mean `{}`. I now think we shouldn't do it.
