### ISSUE TITLE
Run Time Issue: Number of Files

### ISSUE THREAD

**Issue by sophiestrazie** [quarto-dev/quarto-cli#5723]
### Bug description

I am publishing 77 html quarto files to Netlify with each page having at least one image in the `![]()` format. To get a sense of the amount of content and whether this is the problem, my website I was able to publish is [here](https://nd-upgrade.netlify.app). There does not seem to be a solution for non-code related run times. I cannot tell which file is in `bin/quarto.js:109513:17` to address it.

<img width="633" alt="Screenshot 2023-05-28 at 9 33 24 AM" src="https://github.com/quarto-dev/quarto-cli/assets/81820608/4f997347-86e6-4276-bf56-db0b8777c157">

### Steps to reproduce

In R terminal: `quarto publish netlify`

### Expected behavior

(base) mycomputer:Neurodivergent Upgrade myname $ quarto publish netlify
? Publish update to: › https://nd-upgrade.netlify.app (Netlify - my@email.com)
Rendering for publish:

[ 1/77] personal-ideals.qmd
[ 2/77] stats-ocd.qmd
[ 3/77] uni-professionalism.qmd
[ 4/77] university-respect.qmd
[ 5/77] explainer-cohesive-solidarity.qmd
[ 6/77] stats-happy.qmd
[ 7/77] explainer-neurodiversity.qmd
[ 8/77] explainer-ableism.qmd
[ 9/77] about-mission.qmd
[10/77] personal-friends.qmd
[11/77] personal-communication.qmd
[12/77] work-ideals.qmd
[13/77] personal-self-concept.qmd
[14/77] uni-study-strategies.qmd
[15/77] personal-parenthood.qmd
[16/77] stats-trigger.qmd
[17/77] personal-family.qmd
[18/77] stats-autism.qmd
[19/77] explainer-accessible-boundaries.qmd
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'quarto-input7c135172' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
[20/77] about-support-business.qmd
[21/77] personal-burnout.qmd
[22/77] uni-coding.qmd
[23/77] work.qmd
[24/77] work-advocate.qmd
[25/77] work-networking.qmd
[26/77] work-respect.qmd
[27/77] explainer-adhd.qmd
[28/77] stats-memory.qmd
[29/77] personal-sensory.qmd
[30/77] work-hiring-accommodations.qmd
[31/77] work-interviews.qmd
[32/77] uni-class-projects.qmd
[33/77] work-conflicts.qmd
[34/77] general-values.qmd
[35/77] explainer-sensory.qmd
[36/77] personal-safety.qmd
[37/77] index.qmd
[38/77] general-portfolio.qmd
[39/77] general.qmd
[40/77] explainer-autism.qmd
[41/77] about.qmd
[42/77] uni-testing.qmd
[43/77] domestic.qmd
[44/77] uni-essays.qmd
[45/77] uni-research.qmd
[46/77] personal-dopamine.qmd
[47/77] uni-grad-school.qmd
[48/77] personal-ef.qmd
[49/77] work-unemployment.qmd
[50/77] personal.qmd
[51/77] explainer-accommodation.qmd
[52/77] stats-sad.qmd
[53/77] uni-models.qmd
[54/77] uni-summer.qmd
[55/77] personal-overcome-trauma.qmd
[56/77] uni-self-advocating.qmd
[57/77] work-established-career.qmd
[58/77] explainer-strat-ig.qmd
[59/77] personal-emotions.qmd
[60/77] personal-introspection.qmd
[61/77] uni-accommodations.qmd
[62/77] explainer-meltdown.qmd
[63/77] stats.qmd
[64/77] uni-semester.qmd
[65/77] personal-meditate.qmd
[66/77] work-early-career-decisions.qmd
[67/77] uni-pick-class.qmd
[68/77] uni-labs.qmd
[69/77] explainer.qmd
[70/77] explainer-masking.qmd
[71/77] resources.qmd
[72/77] personal-sleep.qmd
[73/77] uni-roommates.qmd
[74/77] work-resume-tips.qmd
[75/77] personal-romantic.qmd
[76/77] university.qmd
[77/77] personal-severe-depression.qmd

**[✓] Preparing to publish site**
**[✓] Uploading files (complete)**
**[✓] Deploying published site**
**[✓] Published site: https://sophie-strassmann.netlify.app**

(base)mycomputer:Neurodivergent Upgrade myname$ 

### Actual behavior

(base) mycomputer:Neurodivergent Upgrade myname $ `quarto publish netlify`
? Publish update to: › https://nd-upgrade.netlify.app (Netlify - my@email.com)
Rendering for publish:

[ 1/77] personal-ideals.qmd
[ 2/77] stats-ocd.qmd
[ 3/77] uni-professionalism.qmd
[ 4/77] university-respect.qmd
[ 5/77] explainer-cohesive-solidarity.qmd
[ 6/77] stats-happy.qmd
[ 7/77] explainer-neurodiversity.qmd
[ 8/77] explainer-ableism.qmd
[ 9/77] about-mission.qmd
[10/77] personal-friends.qmd
[11/77] personal-communication.qmd
[12/77] work-ideals.qmd
[13/77] personal-self-concept.qmd
[14/77] uni-study-strategies.qmd
[15/77] personal-parenthood.qmd
[16/77] stats-trigger.qmd
[17/77] personal-family.qmd
[18/77] stats-autism.qmd
[19/77] explainer-accessible-boundaries.qmd
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'quarto-input7c135172' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
[20/77] about-support-business.qmd
[21/77] personal-burnout.qmd
[22/77] uni-coding.qmd
[23/77] work.qmd
[24/77] work-advocate.qmd
[25/77] work-networking.qmd
[26/77] work-respect.qmd
[27/77] explainer-adhd.qmd
[28/77] stats-memory.qmd
[29/77] personal-sensory.qmd
[30/77] work-hiring-accommodations.qmd
[31/77] work-interviews.qmd
[32/77] uni-class-projects.qmd
[33/77] work-conflicts.qmd
[34/77] general-values.qmd
[35/77] explainer-sensory.qmd
[36/77] personal-safety.qmd
[37/77] index.qmd
[38/77] general-portfolio.qmd
[39/77] general.qmd
[40/77] explainer-autism.qmd
[41/77] about.qmd
[42/77] uni-testing.qmd
[43/77] domestic.qmd
[44/77] uni-essays.qmd
[45/77] uni-research.qmd
[46/77] personal-dopamine.qmd
[47/77] uni-grad-school.qmd
[48/77] personal-ef.qmd
[49/77] work-unemployment.qmd
[50/77] personal.qmd
[51/77] explainer-accommodation.qmd
[52/77] stats-sad.qmd
[53/77] uni-models.qmd
[54/77] uni-summer.qmd
[55/77] personal-overcome-trauma.qmd
[56/77] uni-self-advocating.qmd
[57/77] work-established-career.qmd
[58/77] explainer-strat-ig.qmd
[59/77] personal-emotions.qmd
[60/77] personal-introspection.qmd
[61/77] uni-accommodations.qmd
[62/77] explainer-meltdown.qmd
[63/77] stats.qmd
[64/77] uni-semester.qmd
[65/77] personal-meditate.qmd
[66/77] work-early-career-decisions.qmd
[67/77] uni-pick-class.qmd
[68/77] uni-labs.qmd
[69/77] explainer.qmd
[70/77] explainer-masking.qmd
[71/77] resources.qmd
[72/77] personal-sleep.qmd
[73/77] uni-roommates.qmd
[74/77] work-resume-tips.qmd
[75/77] personal-romantic.qmd
[76/77] university.qmd
[77/77] personal-severe-depression.qmd

[✓] Preparing to publish site
**ERROR: ApiError: Generic Error**

**ApiError: Generic Error**
   ** at catchErrorCodes (file:///Applications/quarto/bin/quarto.js:109492:15)**
    **at file:///Applications/quarto/bin/quarto.js:109513:17***
(base)mycomputer:Neurodivergent Upgrade myname$ 

### Your environment

- IDE: 2023.03.1+446
- OS: MacOS Ventura 13.3
- R: 4.2.2

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.326
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /Applications/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3, ir

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

**Comment by dragonstyle** [comment]
Are you still seeing this error? It appears to be an error from Netlify or the publishing target rather than an error in Quarto itself (FWIW, the quarto.org website has several hundred documents with images, so we definitely expect that publishing sites of this scale should work).

**Comment by sophiestrazie** [comment]
Hi Charles,


How are you doing? Sorry for the late reply. I am really burned out and needed some time off.


I am still having the issue every time I render a file in Quarto for my project.I don't get the message when I knit a xaringan presentation in another project, nor do I get it when I knit R Markdown files.


Additionally, I wanted to know if you have any recommendations for publishing faster. It would be nice if I could update changes to certain pages when I made changes (I thought that's what the freeze: auto function was made to do.


I'm working on a GIS portion of my website and I'm worried that every time I render the website it downloads the large data set over and over again because it scrapes from an API. It would be nice to know the best practices for how to handle working on it or what to do when I'm done and want it to stay put.


Many Thanks,


Sophie Strassmann-Peña

(she/her)


--

Schedule a meeting here<https://calendly.com/sophie-strassmann/professional-sixty-minutes-mon-fri-9am-5pm> with Calendly

No confirmation needed!

--

________________________________

**Comment by dragonstyle** [comment]
No worries I hope you are feeling rested and energized after a break!

The best source on managing code execution in Quarto is here:

https://quarto.org/docs/projects/code-execution.html

We support freezing and caching, but you're best best to review that carefully and choose the configuration for what you need. It sounds like you're already experimenting with freeze, and that is designed to a deal with cases like this, but caching may be even more useful for you since that will cache the results of computations and use those even when the smile content on a page is changed.

**Comment by dragonstyle** [comment]
I'm going to close this issue as I don't think there is a change / fix required in Quarto, though I'm happy to keep helping out.
