### ISSUE TITLE
Error resolving header-includes- unable to open file includes.html

### ISSUE THREAD

**Issue by robcrystalornelas** [quarto-dev/quarto-cli#5724]
### Bug description

👋🏻 Hi, I was trying to publish my website via the GitHub actions process described [here](https://quarto.org/docs/publishing/github-pages.html)

### Steps to reproduce

Hopefully you are able to directly see the error from this [link](https://github.com/robcrystalornelas/robcrystalornelas.github.io/actions/runs/5106055750/jobs/9178022980).

The first time I saw the error was when uploading an image in this [commit](https://github.com/robcrystalornelas/robcrystalornelas.github.io/commit/4b0d52727c3fa3a98d9d84d0a10ff1b45871e89a).  Then the actions job automatically ran, and threw the error linked above.

The error message in the action is pasted below and is at the step `publish to github pages and render`
```python

Rendering for publish:


[1/6] portfolio.qmd
ERROR: Error resolving header-includes- unable to open file includes.html
ERROR: Error
    at renderFiles (file:///opt/quarto/bin/quarto.js:86657:30)
    at async renderProject (file:///opt/quarto/bin/quarto.js:86798:25)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:121188:33)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:109087:24)
    at async Object.publish4 [as publish] (file:///opt/quarto/bin/quarto.js:120457:26)
    at async publishSite (file:///opt/quarto/bin/quarto.js:121225:[38](https://github.com/robcrystalornelas/robcrystalornelas.github.io/actions/runs/5106055750/jobs/9178022980#step:5:40))
    at async publish5 (file:///opt/quarto/bin/quarto.js:121443:61)
    at async doPublish (file:///opt/quarto/bin/quarto.js:121[39](https://github.com/robcrystalornelas/robcrystalornelas.github.io/actions/runs/5106055750/jobs/9178022980#step:5:41)9:13)
    at async publishAction (file:///opt/quarto/bin/quarto.js:121[41](https://github.com/robcrystalornelas/robcrystalornelas.github.io/actions/runs/5106055750/jobs/9178022980#step:5:43)0:9)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:121387:9)

```

### Expected behavior

I was expecting the action to successfully run and then my webpage would be automatically updated.

### Actual behavior

The action step `publish to github pages and render` failed and threw the error mentioned above.

### Your environment

OS: ventura 13.3.1
Working just in the GitHub UI editing the qmd files directly

### Quarto check output

```bash
[✓] Checking Quarto installation......OK
      Version: 1.1.189
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 in
stallation....OK
      Version: 3.7.6 (Conda)
      Path: /Users/robcrystalornelas/opt/anaconda3/bin/python
      Jupyter: 4.6.1
      Kernels: python3, ir

[✓] Checking Jupyter engine render....OK

(\) Checking R installation...Unable to locate an installed version of R.
```

**Comment by mcanouil** [comment]
Your error is trying to include a file that does not exist.

https://github.com/robcrystalornelas/robcrystalornelas.github.io/blob/d7114868a470465fda1e4054bb8c4359022c68c3/_quarto.yml#L35-L36

**Comment by robcrystalornelas** [comment]
Thanks for the advice @mcanouil 👍🏻
