### ISSUE TITLE
Quarto Unable to locate an installed version of R.

### ISSUE THREAD

**Issue by BB1464** [quarto-dev/quarto-cli#5761]
### Bug description

Each time I run **quarto render** in RStudio, I always get this error that quarto is unable to find installed version of R. I have attached a screenshot below.

![2023-05-31](https://github.com/quarto-dev/quarto-cli/assets/76583394/3064d3ee-6ea2-41ec-b7ee-274ddaf38593)

**Here is my session info:**

````

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Africa/Lagos
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] quarto_1.2

loaded via a namespace (and not attached):
 [1] digest_0.6.31   later_1.3.1     fastmap_1.1.1  
 [4] xfun_0.39       knitr_1.43      htmltools_0.5.5
 [7] rmarkdown_2.21  ps_1.7.5        cli_3.6.1      
[10] processx_3.8.1  compiler_4.3.0  rstudioapi_0.14
[13] tools_4.3.0     evaluate_0.21   yaml_2.3.7     
[16] Rcpp_1.0.10     rlang_1.1.1     jsonlite_1.8.4 
````

**Here is the output from quarto check:**

````

$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
ERROR: Theme file compilation failed:



Stack trace:


    at dartCommand (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:38385:15)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async checkVersions (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:85221:26)
    at async check (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:85178:13)
    at async Command.fn (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:85406:5)
    at async Command.execute (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:8105:13)
    at async quarto (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:102325:5)
    at async file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:102343:9
````
**Please I will like to know how I can fix this?**, but I can see that quarto check shows a potential problem that theme file compilation failed but I have struggled for days now and I am unable to fix this. Thank you very much all.

### Steps to reproduce

````

---
title: "Debugging"
author: "Oluwafemi Oyedele"
format: html
editor: visual
---

# Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see https://quarto.org/.

# Running Code

When you click the Render button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The echo: false option disables the printing of code (only output is displayed).
````

### Expected behavior

I expect this document to give me an html output when I run Quato render in RStudio

### Actual behavior

When I render the document in RStudio it will give me an error that quarto is unable to find installed version of R

![2023-05-31](https://github.com/quarto-dev/quarto-cli/assets/76583394/b2a577ab-0a3a-47d4-91e1-c8fdd443359b)

### Your environment

````

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Africa/Lagos
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] quarto_1.2

loaded via a namespace (and not attached):
 [1] digest_0.6.31   later_1.3.1     fastmap_1.1.1  
 [4] xfun_0.39       knitr_1.43      htmltools_0.5.5
 [7] rmarkdown_2.21  ps_1.7.5        cli_3.6.1      
[10] processx_3.8.1  compiler_4.3.0  rstudioapi_0.14
[13] tools_4.3.0     evaluate_0.21   yaml_2.3.7     
[16] Rcpp_1.0.10     rlang_1.1.1     jsonlite_1.8.4 
````

### Quarto check output

````

$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
ERROR: Theme file compilation failed:



Stack trace:


    at dartCommand (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:38385:15)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async checkVersions (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:85221:26)
    at async check (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:85178:13)
    at async Command.fn (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:85406:5)
    at async Command.execute (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:8105:13)
    at async quarto (file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:102325:5)
    at async file:///C:/Users/USER/AppData/Local/Programs/Quarto/bin/quarto.js:102343:9

````

**But I dont know how to fix the theme file compilation failed**

**Comment by cderv** [comment]
There is an opened issue about this theme file error : https://github.com/quarto-dev/quarto-cli/issues/3883

Maybe this is related if RStudio IDE also see that error from `quarto check` and interpret this as missing R. 🤔

**Comment by BB1464** [comment]
Ok @cderv I will try to remove quarto and install it agian, I will report back here with a minimal setup on how to reproduce my issue!!!

**Comment by BB1464** [comment]
I have uninstall quarto and install it again and yet I am still having the same issue. Here is the link to my github repository with the example I was working on:

https://github.com/BB1464/Debugging-Quarto.git

**Comment by cderv** [comment]
Unfortunately, I can't reproduce this. It is probably something due to your environment. I think #3883 should be solved for your before trying to solve this one. This theme compilation failure is not expected for sure.

**Comment by BB1464** [comment]
Thank you very much @cderv, I will wait until when #3883 is fixed.

**Comment by mcanouil** [comment]
I wonder, did you explicitly tell RStudio where to find R?
How did you install R? Did you check the box to add the version to the registry?

Did you try to run R from PowerShell?

**Comment by cderv** [comment]
> I wonder, did you explicitly tell RStudio where to find R?

Usually RStudio IDE won't start without finding a R that works. So I assume that R itself is working inside RStudio IDE.

**Comment by BB1464** [comment]
thank you all, I see, my problem is related to RStudio not able to find R. When I try to run R in the terminal as suggested by @mcanouil, I discovered that I cannot run R there. So please how can I fix this please because this is the third time I am reinstalling R and RStudio ?

**Comment by BB1464** [comment]
@mcanouil yes I did  check the box to add the version to the registry

**Comment by mcanouil** [comment]
> > I wonder, did you explicitly tell RStudio where to find R?
> 
> 
> 
> Usually RStudio IDE won't start without finding a R that works. So I assume that R itself is working inside RStudio IDE. 
> 
> 

You can change the path using environment variables, change it in RStudio after it started properly.
Since this is stored as settings, you can forget you did that.

For example:
- R 4.2.0 is installed
- RStudio is installed and finds 4.2.0
- You install R 4.3.0
- You manually change the path for RStudio to work with 4.3.0 which is not in the PATH
- you uninstall R 4.2.0

RStudio will still works because it knows where R is, but everything else is totally unaware of where R is.

**Comment by mcanouil** [comment]
@BB1464  Where did you install R? I believe it's not a default install.

**Comment by mcanouil** [comment]
This is not where you installed it, but where you got the instructions to download it.

**Comment by BB1464** [comment]
Thank you very much @cderv @mcanouil, I have been able to fix this issue and now my quarto is rendering. I also figured out the my CMD Prompt was not opening but when I watch the first step on this youtube video I discovered that my CMD prompt was infected with virus. But I was able to fix it. Here is the link to the video:

https://www.youtube.com/watch?v=XKdHTjWDY9c&t=174s

**Comment by BB1464** [comment]
I shall mark this as closed. Thank you all!!!

**Comment by GitHunter0** [comment]
> But I was able to fix it. Here is the link to the video:
> 
> https://www.youtube.com/watch?v=XKdHTjWDY9c&t=174s

Thanks a lot, that solved my issue to.
