### ISSUE TITLE
Plotly not correctly rendering on confluence page

### ISSUE THREAD

**Issue by grepinsight** [quarto-dev/quarto-cli#5779]
### Bug description

Tried to see if plotly plots are correctly rendered on confluence using following snippets

### Steps to reproduce

1. Create a jupyter notebook
```python
import plotly.express as px
from sklearn import datasets
import pandas as pd

iris = datasets.load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
px.histogram(iris, x="sepal_width")
```

2. Push it to confluence

### Expected behavior

plotly plots are correctly created and rendered on cofluence like below:

<img width="745" alt="CleanShot 2023-06-01 at 22 15 12@2x" src="https://github.com/quarto-dev/quarto-cli/assets/3666080/554af776-631b-4ac7-a3b7-4b206ac0b3f8">

`quarto render <path to jupyter>` correctly creates a plot in html

<img width="536" alt="CleanShot 2023-06-01 at 22 18 05@2x" src="https://github.com/quarto-dev/quarto-cli/assets/3666080/8966e729-7092-40ee-87d8-222814c38f05">

### Actual behavior

<img width="725" alt="CleanShot 2023-06-01 at 22 19 05@2x" src="https://github.com/quarto-dev/quarto-cli/assets/3666080/e8f281cd-4ad4-4f23-a39c-6493ea5886e3">

### Your environment

- OS: MacOS 

### Quarto check output

```bash
└─> quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.353
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.12 (Conda)
      Path: /Users/allee/miniconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

**Comment by allenmanning** [comment]
Thanks for posting this @grepinsight and for the reply @cscheid.  We are limited by [CSF](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html) which, as Carlos said, basically makes [the entire Interactivity section](https://quarto.org/docs/interactive/) of Quarto "off limits".  

That being said, there may be ways to work-around this if there are Confluence plugins that we can create shortcode for.  There is a [ plotly plugin for confluence](https://marketplace.atlassian.com/apps/1226000/plotly-for-confluence?tab=overview&hosting=cloud).  You could install that plugin and use a Confluence Raw Block (and potentially wrap it as a shortcode) to integrate it.  You would need to view the source on the page to get the plugin CSF and try to use it that way.
