### ISSUE TITLE
Unexpected handling of symbolic link on Linux

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#5807]
### Bug description

I have a css file which I want to incorporate into every book project of mine to establish baseline styles.  I created a main copy of the file and created a symbolic link to the main copy in a project directory.  But when compiling, instead of copying the link target file into the _book directory, a copy of the symbolic link file is made instead.  Having a symbolic link file in the rendered static site directory is of no value.

When I use e.g. `cp` to copy a symbolic link file from the command line, a new copy of the link target file is created instead of a copy of the symbolic link file.  I expected the same behavior when rendering my project.

I don't know if this should be considered a bug report or an enhancement request.

**Comment by cscheid** [comment]
> I have a css file which I want to incorporate into every book project of mine to establish baseline styles.

In general, that's not how we hope people will organize their quarto projects. Specifically, it means that the behavior of the project is dependent on the ambient environment, and we consider that to be a sort of anti-pattern given our goals of replicability. Instead, we recommend using project templates for this: https://quarto.org/docs/extensions/starter-templates.html

The additional issue with following symbolic links is that their behavior is always much less intuitive than people expect it to be, and it's by necessity a Unix-only feature. I think we could change our behavior, but I'm reluctant to "just do it".

**Comment by chrstphmr** [comment]
Just wanted to weigh in on this topic. Symlinks may have their pitfalls, but quarto being able to de-reference symlinks when copying files to *output-dir* would be appreciated - at least as an option for binary files.

Specific use case are research data management solutions like git annex/datalad, which rely on symlinks for binary files. Currently, quarto cannot render files linking to images under version control with these tools:

```
$ quarto render .
pandoc 
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  
ERROR: AlreadyExists: File exists (os error 17): symlink '.git/annex/objects/m6/Jk/MD5E-s247953--527c2662b2b19a2951e7255fb2e9e3af.jpg/MD5E-s247953--527c2662b2b19a2951e7255fb2e9e3af.jpg' -> '/home/c/temp/quarto-symlink-issue/_site/test.jpg'

Stack trace:
    at Object.symlinkSync (ext:deno_fs/30_fs.js:548:3)
    at copySymlinkSync1 (file:///home/c/miniconda3/envs/test_quarto/bin/quarto.js:41735:14)
    at copyTo (file:///home/c/miniconda3/envs/test_quarto/bin/quarto.js:41630:9)
    at doCopy (file:///home/c/miniconda3/envs/test_quarto/bin/quarto.js:41664:9)
    at copyFileIfNewer (file:///home/c/miniconda3/envs/test_quarto/bin/quarto.js:41681:9)
    at copyResourceFile (file:///home/c/miniconda3/envs/test_quarto/bin/quarto.js:42424:5)
    at file:///home/c/miniconda3/envs/test_quarto/bin/quarto.js:86210:25
    at Set.forEach (<anonymous>)
    at file:///home/c/miniconda3/envs/test_quarto/bin/quarto.js:86207:30
    at Array.forEach (<anonymous>)


$ quarto --version
1.6.40

```
