### ISSUE TITLE
Installing extension from private Gitlab repository

### ISSUE THREAD

**Issue by kamapu** [quarto-dev/quarto-cli#5827]
### Bug description

I am having troubles by adding extensions from a GitLab repo, which I am developing. The extension seems to be downloaded but it fails when unzipping the zip-file.

### Steps to reproduce

```bash
quarto add https://gitlab.cc-asp.fraunhofer.de/quarto-extensions/mdz/-/archive/main/shorty-main.zip
```

### Expected behavior

The installed extension.

### Actual behavior

An error message is retrieved:

```
Quarto extensions may execute code when documents are rendered. If you do not 
trust the authors of the extension, we recommend that you do not install or 
use the extension.
 ? Do you trust the authors of this extension (Y/n) › Yes
[✓] Downloading
(|) Unzipping
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[✓] Unzipping
ERROR: Failed to unzip extension.

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

### Your environment

- IDE: VScode
- OS: Ubuntu

### Quarto check output

```
[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.1.5
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/miguel/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
It's supposed to work.

There is two things here:
- some inconsistencies in the documentation
- issues with handling zip file made by GitLab

**Comment by kamapu** [comment]
I installed the new version of quarto and I still get errors, this time a different message.

### Actual behavior

```
Quarto extensions may execute code when documents are rendered. If you do not 
trust the authors of the extension, we recommend that you do not install or 
use the extension.
 ? Do you trust the authors of this extension (Y/n) › Yes
[✓] Downloading
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip or
        /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.zip, and cannot find /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.ZIP, period.
[✓] Unzipping
ERROR: Failed to unzip extension.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip or
        /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.zip, and cannot find /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.ZIP, period.


Error: Failed to unzip extension.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip or
        /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.zip, and cannot find /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.ZIP, period.

    at file:///opt/quarto/bin/quarto.js:104965:19
    at async withSpinner (file:///opt/quarto/bin/quarto.js:56613:9)
    at async unzipAndStage (file:///opt/quarto/bin/quarto.js:104960:5)
    at async installExtension (file:///opt/quarto/bin/quarto.js:104872:30)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:121772:13)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:127540:5)
    at async file:///opt/quarto/bin/quarto.js:127558:9
```

### Quarto check output

```
Quarto extensions may execute code when documents are rendered. If you do not 
trust the authors of the extension, we recommend that you do not install or 
use the extension.
 ? Do you trust the authors of this extension (Y/n) › Yes
[✓] Downloading
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip or
        /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.zip, and cannot find /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.ZIP, period.
[✓] Unzipping
ERROR: Failed to unzip extension.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip or
        /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.zip, and cannot find /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.ZIP, period.


Error: Failed to unzip extension.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip or
        /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.zip, and cannot find /tmp/quarto-sessionb7f1cc2c/9fc8814d/876cb740/archive/extension.zip.ZIP, period.

    at file:///opt/quarto/bin/quarto.js:104965:19
    at async withSpinner (file:///opt/quarto/bin/quarto.js:56613:9)
    at async unzipAndStage (file:///opt/quarto/bin/quarto.js:104960:5)
    at async installExtension (file:///opt/quarto/bin/quarto.js:104872:30)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:121772:13)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:127540:5)
    at async file:///opt/quarto/bin/quarto.js:127558:9
```

**Comment by kamapu** [comment]
Sorry, @mcanouil. I just realized that the project was by mistake private, now I made it public and you could test:

```bash
quarto add https://gitlab.cc-asp.fraunhofer.de/quarto-extensions/mdz/-/archive/main/shorty-main.zip
```

**Comment by kamapu** [comment]
> Sorry, @mcanouil. I just realized that the project was by mistake private, now I made it public and you could test:
> 
> ```shell
> quarto add https://gitlab.cc-asp.fraunhofer.de/quarto-extensions/mdz/-/archive/main/shorty-main.zip
> ```

... and this was the solution. After making it public, I managed to install the extension :partying_face: .

**Comment by mcanouil** [comment]
Could you update the title to highlight the "private repo" aspect?

**Comment by mcanouil** [comment]
In the end it's related to the following feature request to handle private repositories, see #4444

**Comment by kamapu** [comment]
I think, this issue may be closed.

**Comment by mcanouil** [comment]
Reopening this as it's still not possible to install from private repository as far as I can tell.

**Comment by mcanouil** [comment]
I made a PR to clarify <https://github.com/quarto-dev/quarto-cli/issues/5827#issuecomment-1578271647>.

**Comment by mcanouil** [comment]
As suggested initially by @cderv (<https://github.com/quarto-dev/quarto-cli/discussions/4444#discussioncomment-5064368>) it would be great if Quarto was able to leverage usual credentials store.

For GitHub:
- `tar`: <https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-tar>
- `zip`: <https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-zip>

For GitLab:
- <https://docs.gitlab.com/ee/api/repositories.html#get-file-archive>

**Comment by aronatkins** [comment]
Another vote for extension installation from a private repository. If possible, use existing configuration (credentials, SSH keys, etc) to obtain the targeted extension from the Git repository.

If it helps, adding a private repository could require the full repository path, leaving the "username/repo" syntax for extensions in public repositories.

```
quarto add git@github.com:company/private-extension.git
```

**Comment by mcanouil** [comment]
As a workaround which can be applied to any setup/host:

- using Git (assuming you are not using credentials store or SSH key):

```sh
export GIT_USERNAME=...
export GIT_PAT=...
git clone --depth 1 "https://${GIT_USERNAME}:${GIT_PAT}@github.com/organisation/repository.git" /tmp/quarto-extension
quarto add /tmp/quarto-extension
rm -rf /tmp/quarto-extension
```

- using CURL

```sh
curl -L -H "Authorization: token ${GIT_PAT}" \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/organisation/repository/zipball/main \
  -o /tmp/quarto-extension.zip
quarto add /tmp/quarto-extension.zip
rm -rf /tmp/quarto-extension.zip
```

**Comment by mcanouil** [comment]
In some aspects related to:

- https://github.com/quarto-dev/quarto-cli/issues/5515

**Comment by mnlang** [comment]
Same issue here. Working on a private corporate GitLab instance with no public repo access allowed by system admins.

**Comment by mcanouil** [comment]
@mnlang please prefer a reaction on the original message such as a thumb up rather than a comment restating the original post.
A reaction helps maintainers see the interest while a comment only trigger notifications to all participants which generate noise and interrupt maintainers' flow.
Thank you for your interest and understanding.

Note also that solutions have been provided which you can already use/adapt.

**Comment by mcanouil** [comment]
Quarto Wizard (https://m.canouil.dev/quarto-wizard/) the VSCode/Positron extension now offers to install extension from private GitHub repositories. For GitLab and other hosts, it's a bit tricky because they do not pass on the token the same way or in a standard way.

> [!NOTE]
> This is a third party tool.
> It might be seen as a workaround rather than a fix.
