### ISSUE TITLE
md vs markdown output format

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#5830]
### Bug description

`quarto render index.qmd --to md` and `quarto render index.qmd --to markdown` produce different output.

### Steps to reproduce

Consider the minimal working example where `index.qmd` is

```
---
title: MWE
---

## Section
This is a simple placeholder for the manuscript's main document.
```

Run `quarto render index.qmd --to md --output md_output` and `quarto render index.qmd --to markdown --output markdown_output`.

Run `diff markdown_output md_output`.

### Expected behavior

`markdown_output` and `md_output` will be the same.

### Actual behavior

```
1,4c1
< ---
< title: MWE
< toc-title: Table of contents
< ---
---
> # MWE
8c5
< This is a simple placeholder for the manuscript's main document.
---
> This is a simple placeholder for the manuscript’s main document.
```

### Your environment

- Ubuntu

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.126
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

ERROR: YAMLError: unexpected end of the stream within a double quoted scalar at line 3, column 1:
    
    ^

Stack trace:
    
    ^
    at generateError (file:///opt/quarto/bin/quarto.js:10487:12)
    at throwError (file:///opt/quarto/bin/quarto.js:10490:11)
    at readDoubleQuotedScalar (file:///opt/quarto/bin/quarto.js:10836:12)
    at composeNode (file:///opt/quarto/bin/quarto.js:11309:125)
    at readBlockMapping (file:///opt/quarto/bin/quarto.js:11124:17)
    at composeNode (file:///opt/quarto/bin/quarto.js:11306:84)
    at readDocument (file:///opt/quarto/bin/quarto.js:11420:5)
    at loadDocuments (file:///opt/quarto/bin/quarto.js:11455:9)
    at load (file:///opt/quarto/bin/quarto.js:11460:23)
    at parse3 (file:///opt/quarto/bin/quarto.js:11470:12)
```

**Comment by mcanouil** [comment]
`md` is not a format, `markdown` is at least to Pandoc which Quarto relies on.

**Comment by mcanouil** [comment]
Note that as from #5828 you have an issue in your setup, since even `quarto check` fails to output properly.
I suggest your clean your environment.

**Comment by mcanouil** [comment]
I am closing this as there is nothing to be done here.

**Comment by cscheid** [comment]
Hm. I'm not sure about "nothing". This is pretty confusing.

Since we already do some "non-pandoc" format changes, maybe there's some clever thing to be done. It might not be feasible and it might not be simple, but I am also surprised by this.

**Comment by mcanouil** [comment]
To address the "issue" here, it would mean to make "md" an alias of "markdown".

I personally not sure that's a good idea.
I would recommend to use actual format name.

This being said, there is room for discussion.

**Comment by mcanouil** [comment]
Maybe the question is about why Quarto allows "md" as a format name while Pandoc does not.

**Comment by jjallaire** [comment]
The reason we use `md` as an alias for `commonmark` is that custom formats always have their base format as their suffix (e.g. `fancy-html` or `acm-pdf`). When defining derivative markdown formats e.g. Hugo or Docusaurus this implied that they would be named `hugo-commonmark` and `docusaurus-commonmark` which makes them overly verbose. As it stands they are named `hugo-md` and `docusaurus-md` which are much more compact, readable, and consistent with other shorter format names.

**Comment by mcanouil** [comment]
So in the end `md` is not and should not be considered as an alias to `markdown` which means there is nothing to be done here.

**Comment by jjallaire** [comment]
That's correct, it's not an alias to `markdown` it's an alias to `commonmark` as a convenience to custom markdown formats (i.e. used internally as you said)

**Comment by rgaiacs** [comment]
Because `md` should only be used internally, would be possible to provide an earlier error to the user? For example, `quarto render index.qmd --to md` raise an error saying that `md` is not a valid format and the user might want `markdown`.
