### ISSUE TITLE
Issue with automatic project root discovery

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-cli#5843]
I get a `Permission denied` error on my Linux machine when I work on one of my network shares. I believe that Quarto tries to access `_quarto.yml` outside of my share (actually, two folders up), which I don't have permission to read and/or write.

Specifically, my project is located in `/run/user/1000/gvfs/smb-share:server=pers.ad.uni-graz.at,share=fs/home/home_b/brunnerc/quarto-issue`. The Quarto source is in another subfolder, i.e. `test/test.qmd` (but that doesn't seem relevant).

From the folder I mentioned, I run

```
quarto preview test/test.qmd 
```

This results in the following error:

```
ERROR: PermissionDenied: Permission denied (os error 13), stat '/run/user/1000/gvfs/smb-share:server=pers.ad.uni-graz.at,share=fs/home/home_b/_quarto.yml'

PermissionDenied: Permission denied (os error 13), stat '/run/user/1000/gvfs/smb-share:server=pers.ad.uni-graz.at,share=fs/home/home_b/_quarto.yml'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///opt/quarto/bin/quarto.js:492:14)
    at Array.find (<anonymous>)
    at projectConfigFile (file:///opt/quarto/bin/quarto.js:58280:37)
    at file:///opt/quarto/bin/quarto.js:82866:28
    at projectContext (file:///opt/quarto/bin/quarto.js:82724:32)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:103696:25)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:127540:5)
    at async file:///opt/quarto/bin/quarto.js:127558:9
```

The contents of `test.qmd` does not seem to matter, since the error occurs before even reading it.

This is on Arch Linux.

_Originally posted by @cbrnr in https://github.com/quarto-dev/quarto-cli/issues/4594#issuecomment-1580591702_

**Comment by mxw010** [comment]
Same issue, trying to render a python file with jupyter on a cluster (where I don't have admin privilege). I was using the example with both `quarto render` and `quarto preview` and both failed. Rendering R succeeded with no such errors.

```

ERROR: PermissionDenied: Permission denied (os error 13): mkdir '/run/user/2094276432/jt'

Stack trace:
    at Object.mkdirSync (ext:deno_fs/30_fs.js:136:7)
    at ensureDirSync (file:file_path/quarto-cli/src/vendor/deno.land/std@0.185.0/fs/ensure_dir.ts:49:10)
    at quartoDir (file:file_path/quarto-cli/src/core/appdirs.ts:33:3)
    at quartoRuntimeDir (file:file_path/quarto-cli/src/core/appdirs.ts:23:10)
    at kernelTransportFile (file:file_path/quarto-cli/src/execute/jupyter/jupyter-kernel.ts:296:25)
    at connectToKernel (file:file_path/quarto-cli/src/execute/jupyter/jupyter-kernel.ts:355:25)
    at executeKernelKeepalive (file:file_path/quarto-cli/src/execute/jupyter/jupyter-kernel.ts:88:35)
    at Object.execute (file:file_path/quarto-cli/src/execute/jupyter/jupyter.ts:281:15)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderExecute (file:file_path/quarto-cli/src/command/render/render-files.ts:199:25)
```

**Comment by cscheid** [comment]
@mxw010 Sorry you're running into this. Your issue is not the same; your stack trace implies you're running into #4594 instead. Unfortunately, in this case we believe the issue is that your cluster is actually misconfigured (I know you might not have the ability to change that). The issue is that according to the unix standard, the temporary directory reported by your cluster should be writable (and it isn't). See that issue for a workaround.
