### ISSUE TITLE
Fail to render a pptx file that contains a mermaid graph in which an external image is embedded

### ISSUE THREAD

**Issue by CLRafaelR** [quarto-dev/quarto-cli#5913]
### Bug description

I made a mermaid graph where an external image (e.g. https://iconscout.com/ms-icon-310x310.png) is embedded and I am trying to use that entire resulting mermaid graph in a pptx file by processing a qmd file with the option `format: pptx`. However, I fail to render a pptx file that contains the mermaid graph, with an error `ERROR: Internal Error: couldn't determine svg dimensions`, although I successfully render an HTML out of the qmd file in question.

### Steps to reproduce

Please render 

````qmd
---
format:
  pptx: default
  html: default
---


<script src="https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js"></script>

## External image on the web

```{mermaid}
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[<img src='https://iconscout.com/ms-icon-310x310.png' width='40' height='40' />]
    C -->|Two| E[iPhone]
    C -->|Three| F[Car]
```

## External image on the local folder

```{mermaid}
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[<img src='./ms-icon-310x310.png' width='40' height='40' />]
    C -->|Two| E[iPhone]
    C -->|Three| F[Car]
```
````

### Expected behavior

The following image made using `mermaid` with an external image should be displayed in a pptx file that Quarto produces:

![image](https://github.com/quarto-dev/quarto-cli/assets/42314553/0cc9e226-c784-404c-aee9-ca8920057f05)

Actually, the 

### Actual behavior

On the command line, the following error and stack trace come up:

```bash
$ quarto preview c:/Users/.../test.qmd --no-browser --no-watch-inputs
ERROR: Internal Error: couldn't determine svg dimensions

This is a bug in quarto. We apologize for the inconvenience.
Please consider reporting it at https://github.com/quarto-dev/quarto-cli. Thank you!

Stack trace:
    at resolveSize (file:///C:/Program%20Files/Quarto/bin/quarto.js:59855:19)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async makePng (file:///C:/Program%20Files/Quarto/bin/quarto.js:60177:57)
    at async makeDefault (file:///C:/Program%20Files/Quarto/bin/quarto.js:60227:24)
    at async Object.cell (file:///C:/Program%20Files/Quarto/bin/quarto.js:60250:20)
    at async Promise.all (index 0)
    at async Object.document (file:///C:/Program%20Files/Quarto/bin/quarto.js:36179:25)
    at async handleLanguageCells (file:///C:/Program%20Files/Quarto/bin/quarto.js:36150:42)
    at async file:///C:/Program%20Files/Quarto/bin/quarto.js:64332:61
    at async withTimingAsync (file:///C:/Program%20Files/Quarto/bin/quarto.js:19439:25)
```

On the preview pane in VSCode, we can see an incomplete preview, which means that the external image is not shown in the resulting mermaid graph:

![image](https://github.com/quarto-dev/quarto-cli/assets/42314553/3594cc8c-4241-4e2b-871a-cf9e01d4ccd8)

### Your environment

- IDE: VSCode 1.79.0 (user setup)
- OS: Windows 11

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.117
      Path: C:\Program Files\Quarto\bin
      CodePage: 932

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.11
      Path: C:/Users/<my_username>/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: 5.3.0
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/PROGRA~1/R/R-43~1.0
      LibPaths:
        - C:/Program Files/R/R-4.3.0/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Let's get everything cleared up first. Why are you including this in your qmd?

```
<script src="https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js"></script>
```

**Comment by cscheid** [comment]
1. regarding the crash: we should fix this, I'll create a separate issue.

2. regarding the `img` tag resolution: we won't be able to solve this in general.

The problem is that in non-HTML formats, we create the diagram by first rendering an off-screen HTML page with the mermaid diagram, using puppeteer to get a PNG screenshot, and then embedding the result. When the dependencies are in an external webpage, the chromium instance in puppeteer finds the image successfully and loads it. But a local reference doesn't yet exist on the file system (since the page hasn't been rendered yet), and so the process that produces the screenshot fails.

The fundamental problem is that it's generally impossible for us to analyze a mermaid graph and determine the resources it needs to render correctly. This is, unfortunately, a limitation in the way that mermaid is designed and implemented; we can't do much about it.

**Comment by CLRafaelR** [comment]
Thank you for your efforts regarding this issue. And apologies for the delay in my response.

> Let's get everything cleared up first. Why are you including this in your qmd?
> 
> ```
> <script src="https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js"></script>
> ```

I incorporated the aforementioned script to enhance the visual depiction of the image. In the absence of the `<script src="https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js"></script>`, the edges and the textual content within the nodes was completely imperceptible.

![image](https://github.com/quarto-dev/quarto-cli/assets/42314553/04b83766-bb06-4f03-a7e8-a1c64fb7e52f)

> ### regarding the crash
> We should fix the error message, I'll create a separate issue.
> 
> ### Regarding the `img` tag resolution: we won't be able to solve this in general.
> The problem is that in non-HTML formats, we create the diagram by first rendering an off-screen HTML page with the mermaid diagram, using puppeteer to get a PNG screenshot, and then embedding the result. When the dependencies are in an external webpage, the chromium instance in puppeteer finds the image successfully and loads it. But a local reference doesn't yet exist on the file system (since the page hasn't been rendered yet), and so the process that produces the screenshot fails.
> 
> The fundamental problem is that it's generally impossible for us to analyze a mermaid graph and determine the resources it needs to render correctly. This is, unfortunately, a limitation in the way that mermaid is designed and implemented; we can't do much about it.
> 
> ## Ultimately, these problems are the same.
> Upon inspection of the rendered result, in the case of a local image reference `./ms-icon...`, it seems that mermaid is emitting an svg without a `viewbox` attribute describing its width and height. That makes it impossible for us to generate a screenshot of the right size. This is, I think, a mermaid bug; we can't do anything in this case.

I genuinely appreciate your comprehensive response. I have understood that the error does not originate from Quarto, but rather from Mermaid. I will endeavor to submit another issue on Mermaid's repository.

**Comment by mcanouil** [comment]
> I incorporated the aforementioned script to enhance the visual depiction of the image. In the absence of the `<script src="https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js"></script>`, the edges and the textual content within the nodes was completely imperceptible.

This is a side effect of embedding a different version of `Mermaid.js` which you should not do, especially because you are specifying an old version.
Quarto 1.3 embed Mermaid.js 9.2.2 and Quarto 1.4-pre embed 10.2.0-rc.2 (the latest is 10.2.3).

To tweak themes, see <https://quarto.org/docs/authoring/diagrams.html#mermaid-theming>.

**Comment by CLRafaelR** [comment]
> > I incorporated the aforementioned script to enhance the visual depiction of the image. In the absence of the `<script src="https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js"></script>`, the edges and the textual content within the nodes was completely imperceptible.
> 
> This is a side effect of embedding a different version of `Mermaid.js` which you should not do, especially because you are specifying an old version. Quarto 1.3 embed Mermaid.js 9.2.2 and Quarto 1.4-pre embed 10.2.0-rc.2 (the latest is 10.2.3).
> 
> To tweak themes, see https://quarto.org/docs/authoring/diagrams.html#mermaid-theming.

@mcanouil 

Thank you for your comment, I will configure the theme using the proper method you mentioned next time!
