### ISSUE TITLE
Beamer output adds a "32" to the References in TOC

### ISSUE THREAD

**Issue by pachadotdev** [quarto-dev/quarto-cli#5925]
### Bug description

If I render https://github.com/pachadotdev/varsityblues/blob/main/inst/extdata/presentation1/presentation1.qmd, then it's all cool but the TOC says "References32" instead of "References". See https://github.com/pachadotdev/varsityblues/blob/main/inst/extdata/presentation1/presentation1.pdf.

### Steps to reproduce

From RStudio:

Create a new project and then run

```r
remotes::install_github("pachadotdev/varsityblues")
varsityblues::start_project()
```

Then open `presentation1/presentation1.qmd` and render it.

### Expected behavior

No "32" added to TOC

### Actual behavior

It prints a "32" that is not in the qmd file

### Your environment

```r
> library(varsityblues)
> library(tinytex)

> tinytex::tlmgr_version()
tlmgr revision 66798 (2023-04-08 02:15:21 +0200)
tlmgr using installation: /home/pacha/.TinyTeX
TeX Live (https://tug.org/texlive) version 2023

> session_info()
─ Session info ─────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.0 (2023-04-21)
 os       Linux Mint 21.1
 system   x86_64, linux-gnu
 ui       RStudio
 language en_CA:en
 collate  en_CA.UTF-8
 ctype    en_CA.UTF-8
 tz       America/Toronto
 date     2023-06-14
 rstudio  2023.06.0-daily+411 Mountain Hydrangea (desktop)
 pandoc   2.9.2.1 @ /usr/bin/pandoc

─ Packages ─────────────────────────────────────────────────────────────────
 package      * version    date (UTC) lib source
 bspm           0.5.2      2023-05-20 [1] CRAN (R 4.3.0)
 cachem         1.0.8      2023-05-01 [3] CRAN (R 4.3.0)
 callr          3.7.3      2022-11-02 [3] CRAN (R 4.2.2)
 cli            3.6.1      2023-03-23 [3] CRAN (R 4.2.3)
 cpp11        * 0.4.3.9000 2023-05-31 [1] local
 crayon         1.5.2      2022-09-29 [3] CRAN (R 4.2.1)
 devtools     * 2.4.5      2022-10-11 [1] CRAN (R 4.3.0)
 digest         0.6.31     2022-12-11 [1] CRAN (R 4.3.0)
 ellipsis       0.3.2      2021-04-29 [3] CRAN (R 4.1.1)
 fastmap        1.1.1      2023-02-24 [3] CRAN (R 4.2.2)
 fs             1.6.2      2023-04-25 [3] CRAN (R 4.3.0)
 glue           1.6.2      2022-02-24 [3] CRAN (R 4.2.0)
 htmltools      0.5.5      2023-03-23 [3] CRAN (R 4.2.3)
 htmlwidgets    1.6.2      2023-03-17 [3] CRAN (R 4.2.3)
 httpuv         1.6.11     2023-05-11 [3] CRAN (R 4.3.0)
 later          1.3.1      2023-05-02 [3] CRAN (R 4.3.0)
 lifecycle      1.0.3      2022-10-07 [3] CRAN (R 4.2.1)
 magrittr       2.0.3      2022-03-30 [3] CRAN (R 4.2.0)
 memoise        2.0.1      2021-11-26 [3] CRAN (R 4.2.0)
 mime           0.12       2021-09-28 [3] CRAN (R 4.2.0)
 miniUI         0.1.1.1    2018-05-18 [3] CRAN (R 4.0.1)
 pkgbuild       1.4.0      2022-11-27 [3] CRAN (R 4.2.2)
 pkgload        1.3.2      2022-11-16 [1] CRAN (R 4.3.0)
 prettyunits    1.1.1      2020-01-24 [3] CRAN (R 4.0.1)
 processx       3.8.1      2023-04-18 [3] CRAN (R 4.3.0)
 profvis        0.3.8      2023-05-02 [3] CRAN (R 4.3.0)
 promises       1.2.0.1    2021-02-11 [3] CRAN (R 4.1.1)
 ps             1.7.5      2023-04-18 [3] CRAN (R 4.3.0)
 purrr          1.0.1      2023-01-10 [3] CRAN (R 4.2.2)
 R6             2.5.1      2021-08-19 [3] CRAN (R 4.2.0)
 Rcpp           1.0.10     2023-01-22 [3] CRAN (R 4.2.2)
 remotes        2.4.2      2021-11-30 [3] CRAN (R 4.2.0)
 rlang          1.1.1      2023-04-28 [3] CRAN (R 4.3.0)
 rstudioapi     0.14       2022-08-22 [3] CRAN (R 4.2.1)
 sessioninfo    1.2.2      2021-12-06 [3] CRAN (R 4.2.0)
 shiny          1.7.4      2022-12-15 [1] CRAN (R 4.3.0)
 stringi        1.7.12     2023-01-11 [3] CRAN (R 4.2.2)
 stringr        1.5.0      2022-12-02 [3] CRAN (R 4.3.0)
 tinytex      * 0.45       2023-04-18 [3] CRAN (R 4.3.0)
 urlchecker     1.0.1      2021-11-30 [1] CRAN (R 4.3.0)
 usethis      * 2.2.0.9001 2023-06-14 [1] local
 varsityblues * 0.5.0      2023-06-12 [1] local
 vctrs          0.6.2      2023-04-19 [3] CRAN (R 4.3.0)
 xfun           0.39       2023-04-20 [3] CRAN (R 4.3.0)
 xtable         1.8-4      2019-04-21 [3] CRAN (R 4.0.1)

 [1] /home/pacha/R/x86_64-pc-linux-gnu-library/4.3
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library

────────────────────────────────────────────────────────────────────────────
```

### Quarto check output

```bash
~ $ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
There is an unactivated Python environment in miniconda3. Did you forget to activate it?

[✓] Checking Jupyter engine render....OK
```

**Comment by pglpm** [comment]
In the [pdf you enclosed](https://github.com/pachadotdev/varsityblues/blob/main/inst/extdata/presentation1/presentation1.pdf) I don't see any "32" attached to "References", neither on the page nor in the bookmarks. Here's a screenshot:
![Screenshot_20230614_194721](https://github.com/quarto-dev/quarto-cli/assets/9976691/eb467743-f36a-40ff-92ec-94966ff5e37e)

Can it be a problem with the pdf viewer?

**Comment by pachadotdev** [comment]
It's in the table pof contents

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cscheid** [comment]
Thanks for the report. Can you please generate a minimal example? This uses your framework, a 32-page presentation and a number of custom features (like a custom template, etc). It's hard for us to track down what's happening.

**Comment by cscheid** [comment]
I suspect this isn't an issue with quarto. If you change `keep-tex: false` to `keep-tex: true`, you can inspect the resulting .tex file and verify that there's no `References32` text in the file that quarto generates. It looks like it's coming from the way your template generates the table of contents in the `templatebeamer.tex` file.

**Comment by pachadotdev** [comment]
some curious aspects so far:

1. It worked ok with R Markdown
2. If I write `# References {.unnumbered}` or `# References {-}` I have the problem
3. Otherwise, the problem dissapears

**Comment by pachadotdev** [comment]
also, great work with Quarto @cscheid , it really simplifies using LaTeX
