### ISSUE TITLE
Embed shortcode does not resolve `/` as root when using`_quarto.yml`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#6147]
### Bug description

AS of the latest development version `{{< embed >}}` shortcode does not resolve path as `{{< include >}}`, in particular when using leading `/` to use have resources relatives to the root of the project.

### Actual behavior

```
ERROR: Unable to embed content from notebook '/penguins.ipynb'
The file /penguins.ipynb doesn't exist or cannot be read.

Stack trace:
The file /penguins.ipynb doesn't exist or cannot be read.
    at notebookIncludes (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/core/jupyter/jupyter-embed.ts:308:17)
    at replaceNotebookPlaceholders (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/core/jupyter/jupyter-embed.ts:313:18)
    at renderPandoc (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render.ts:114:32)
    at Object.onRender (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render-files.ts:669:36)
    at renderFileInternal (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render-files.ts:631:30)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderFiles (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render-files.ts:310:9)
    at async renderProject (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/project.ts:266:23)
    at async renderForPreview (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/preview/preview.ts:417:24)
    at async render (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/preview/preview.ts:161:22)
```

### Quarto check output

```bash

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/mcanouil/Projects/quarto/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /Users/mcanouil/Projects/misc/quarto-playground/env/bin/python
      Jupyter: 5.3.1
      Kernels: julia-1.9, python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

(\) Checking R installation...........ℹ R version 4.3.1 (2023-06-16)
! Config '~/.Rprofile' was loaded!
[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mcanouil/Projects/misc/quarto-playground/renv/library/R-4.3/aarch64-apple-darwin20
        - /Users/mcanouil/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/84ba8b13
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK
```

**Comment by dragonstyle** [comment]
Fixed in 99f2a9689979af8bc25768c8aef4047c2c32bdd8
