### ISSUE TITLE
quarto looks for Mu Editor.app - fails because it is not there

### ISSUE THREAD

**Issue by flipphillips** [quarto-dev/quarto-cli#6537]
### Bug description

On macOS `quarto` seems obsessed with trying to use `Mu Editor.app`, which is not installed. 

### Steps to reproduce

1. Install quarto 
2. `quarto check`

### Expected behavior

should pass tests.

### Actual behavior

```
...
[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /Users/flip/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: mu_venv-38-20220913-145136, python3

(/) Checking Jupyter engine render....2023-08-15 17:31:32,876 - traitlets - ERROR - Failed to run command:
['/Applications/Mu Editor.app/Contents/MacOS/../Resources/Python/bin/Mu Editor', '-m', 'ipykernel_launcher', '-f', '/private/var/folders/7x/2mly31912gzf2qvbvjr75r6w0000gq/T/tmps8hy0r_r.json']
```

## foundation
- conda --version 23.7.2
- quarto --version 1.3.450
- code --version 1.81.1 6c3e3dba23e8fadc360aed75ce363ba185c49794 arm64
- pandoc --version 3.1.6.1
- macOS 13.5 (22G74)

## jupyter
jupyter --version
Selected Jupyter core packages...
IPython          : 8.12.2
ipykernel        : 6.25.0
ipywidgets       : 8.0.4
jupyter_client   : 7.4.9
jupyter_core     : 5.3.0
jupyter_server   : 1.23.4
jupyterlab       : 3.6.3
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.7.0
notebook         : 6.5.4
qtconsole        : 5.4.2
traitlets        : 5.7.1

## things not installed
- R - not installed
- Mu Editor - not installed

## environment that I can think might be relevant?
```bash
❯ echo $EDITOR
code
❯ echo $VISUAL
code
```

### Quarto check output

```bash
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /Users/flip/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: mu_venv-38-20220913-145136, python3

(/) Checking Jupyter engine render....2023-08-15 17:31:32,876 - traitlets - ERROR - Failed to run command:
['/Applications/Mu Editor.app/Contents/MacOS/../Resources/Python/bin/Mu Editor', '-m', 'ipykernel_launcher', '-f', '/private/var/folders/7x/2mly31912gzf2qvbvjr75r6w0000gq/T/tmps8hy0r_r.json']
    PATH='/Users/flip/anaconda3/bin:/Users/flip/anaconda3/condabin:/opt/homebrew/opt/curl/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities:/usr/local/sbin:/Users/flip/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/flip/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/Users/flip/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/Users/flip/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/Users/flip/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/flip/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/brew:/Users/flip/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/flip/.antigen/bundles/conda-incubator/conda-zsh-completion:/Users/flip/.antigen/bundles/micrenda/zsh-nohup:/Users/flip/.antigen/bundles/romkatv/powerlevel10k'
    with kwargs:
{'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/var/folders/7x/2mly31912gzf2qvbvjr75r6w0000gq/T/quarto-session382ac31a/35e224b1', 'start_new_session': True}

2023-08-15 17:31:32,876 - traitlets - ERROR - [Errno 2] No such file or directory: '/Applications/Mu Editor.app/Contents/MacOS/../Resources/Python/bin/Mu Editor'
Traceback (most recent call last):
  File "/Users/flip/anaconda3/lib/python3.11/site-packages/jupyter_client/manager.py", line 82, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/flip/anaconda3/lib/python3.11/site-packages/jupyter_client/manager.py", line 395, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "/Users/flip/anaconda3/lib/python3.11/site-packages/jupyter_client/utils.py", line 38, in ensure_async
    return await obj
           ^^^^^^^^^
  File "/Users/flip/anaconda3/lib/python3.11/site-packages/jupyter_client/manager.py", line 311, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/flip/anaconda3/lib/python3.11/site-packages/jupyter_client/provisioning/local_provisioner.py", line 204, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/flip/anaconda3/lib/python3.11/site-packages/jupyter_client/launcher.py", line 170, in launch_kernel
    raise ex
  File "/Users/flip/anaconda3/lib/python3.11/site-packages/jupyter_client/launcher.py", line 158, in launch_kernel
    proc = Popen(cmd, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/flip/anaconda3/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/flip/anaconda3/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Mu Editor.app/Contents/MacOS/../Resources/Python/bin/Mu Editor'


[Errno 2] No such file or directory: '/Applications/Mu Editor.app/Contents/MacOS/../Resources/Python/bin/Mu Editor'
[✓] Checking Jupyter engine render....OK
```

**Comment by flipphillips** [comment]
I'm gonna self-close this because it turns out, there was a crufty kernel spec in

`/Users/flip/Library/Jupyter/kernels/mu_venv-38-20220913-145136` 

Maybe some safety checking in `jupyter-shared.ts` would be useful. That must have been left over from some 'messing about' apparently in 2022 :)

**Comment by cscheid** [comment]
> Maybe some safety checking in `jupyter-shared.ts` would be useful.

That wouldn't work - we intentionally respect your `venv`, by design. I'm glad you figured it out, though! For future reference, this is the hint:

```
[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /Users/flip/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: mu_venv-38-20220913-145136, python3
```

Note the `Kernels:` line there...
