### ISSUE TITLE
Rendering fails after direct clone of VS Code template for Quarto Manuscript (file not found error)

### ISSUE THREAD

**Issue by jchiquet** [quarto-dev/quarto-cli#6578]
### Bug description

I wanted to test quarto's new Manuscript feature: looks very exiting! 

Unfortunately, while the cell compilation is working, when it comes to generating the HTML document, the ipynb file can't be found (wrong name, wrong location?).

### Steps to reproduce

I'm using the preview version 1.4.322 of quarto, the quarto extension for vs-code and the manuscript template for vs-code: https://github.com/cwickham/manuscript-template-vscode

I  launch the following command (Linux Ubuntu 22.04)

```
quarto preview /home/jchiquet/Repos/quarto-manuscript/index.qmd --no-browser --no-watch-input
```

### Expected behavior

Success of the compilation

### Actual behavior

```
ERROR: Rendering of output notebook produced an unexpected result
ERROR: NotFound: No such file or directory (os error 2): readfile '/home/jchiquet/Repos/quarto-manuscript/notebooks/data-screening.ipynb'
Path: /home/jchiquet/Repos/quarto-manuscript/notebooks/data-screening.ipynb

Stack trace:
Path: /home/jchiquet/Repos/quarto-manuscript/notebooks/data-screening.ipynb
    at readTextFileSync (ext:deno_fs/30_fs.js:723:14)
    at Object.Deno.readTextFileSync (file:///opt/quarto/bin/quarto.js:5626:25)
    at Object.target (file:///opt/quarto/bin/quarto.js:37406:37)
    at fileExecutionEngineAndTarget (file:///opt/quarto/bin/quarto.js:40258:33)
    at renderFileInternal (file:///opt/quarto/bin/quarto.js:75367:44)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async renderFile (file:///opt/quarto/bin/quarto.js:75303:13)
    at async Object.renderHtmlNotebook [as render] (file:///opt/quarto/bin/quarto.js:75571:22)
    at async Object.render (file:///opt/quarto/bin/quarto.js:74410:34)
    at async Object.renderPreviews (file:///opt/quarto/bin/quarto.js:107133:45)
```

### Your environment

- OS: Ubuntu 22.04
- Python 3.10
- VSCode 1.81.1

### Quarto check output

```
*
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.322
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.05
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/jchiquet/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3, julia-1.8

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/jchiquet/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by cwickham** [comment]
Thanks for the report @jchiquet 

I can't reproduce this error. I'm using the Quarto 1.4.351 and the latest copy of the VS Code template repo (there was a small change today to this repo, but I think it was unrelated). 

Could you confirm you still get this error with the latest pre-release version of Quarto, and the template repo?

**Comment by jchiquet** [comment]
Hi @cwickham ,

thank you for your feedback. Indeed, after updating quarto to version 1.4.352, everything works fine.

So I'am closing the Issue.
