### ISSUE TITLE
Rendering failed after cloning the Rstudio repo example

### ISSUE THREAD

**Issue by MarieEtienne** [quarto-dev/quarto-cli#6579]
### Bug description

I wanted to  give a try to manuscript, which sounds very exciting.

Thanks for your help and for the quarto manuscript proposition
Marie

### Steps to reproduce

I followed the [tutorial for Rstudio](https://quarto.org/docs/manuscripts/authoring/rstudio.html,) used the [correpondind repo](https://github.com/cwickham/manuscript-template-rstudio) as a template and then cloned my repo on my local computer. 
When I run quarto render, I get the error 
ERROR: The cell fig-spatial-plot does not exist in notebook

### Expected behavior

 During the rendering process, all formats are present in notebooks/explore-earthquakes_files, but the html formats are deleted and only the figure-ipynb directory. 

### Actual behavior

ERROR: The cell fig-spatial-plot does not exist in notebook

### Your environment

- IDE Rstudio  2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-06) for Ubuntu Focal
- OS  Ubuntu Focal

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.330
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2019

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.16 (Conda)
      Path: /home/metienne/miniconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/metienne/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK

**Comment by cwickham** [comment]
Thanks for the report @MarieEtienne ! This should be fixed now. Could you try again starting with getting a copy of the template repo.

**Comment by MarieEtienne** [comment]
Thanks for the answer and the tentative fix. It doesn"t seem to work for me but the error is not the same anymore.  It seems that part of the code is designed for Jupyter Notebook and not R.


processing file: index.qmd
1/7                  
2/7 [unnamed-chunk-1]
3/7                  
4/7 [fig-timeline]   
5/7                  
6/7 [unnamed-chunk-3]
7/7                  
output file: index.knit.md

ERROR: Unable to embed content from notebooks/explore-earthquakes.qmd. Embedding currently only supports content from Juptyer Notebooks.

Stack trace:
    at unsupportedEmbed (file:///home/metienne/quarto-cli/src/core/jupyter/jupyter-embed.ts:134:9)
    at parseNotebookAddress (file:///home/metienne/quarto-cli/src/core/jupyter/jupyter-embed.ts:105:7)
    at Object.handle (file:///home/metienne/quarto-cli/src/core/handlers/embed.ts:46:31)
    at Object.directive (file:///home/metienne/quarto-cli/src/core/handlers/embed.ts:101:36)
    at handleLanguageCells (file:///home/metienne/quarto-cli/src/core/handlers/base.ts:409:38)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///home/metienne/quarto-cli/src/command/render/render-files.ts:483:45
    at async withTimingAsync (file:///home/metienne/quarto-cli/src/core/timing.ts:50:20)
    at async renderFiles (file:///home/metienne/quarto-cli/src/command/render/render-files.ts:481:13)
    at async renderProject (file:///home/metienne/quarto-cli/src/command/render/project.ts:266:23)

**Comment by dragonstyle** [comment]
> ERROR: Unable to embed content from notebooks/explore-earthquakes.qmd. Embedding currently only supports content from Juptyer Notebooks.

This error is likely because you are using an older version of Quarto. This feature requires the latest pre-release (1.4.x) versions of Quarto. You can use the command `quarto check` to verify the version of Quarto that you are using. If you are seeing this error from Quarto 1.4, it is definitely a bug and I would love if you could let us know.

**Comment by dragonstyle** [comment]
I'm going to go ahead and close this issue out since it has been sitting for a while. If you continue to have issues, please re-open this and we can help you out.
