### ISSUE TITLE
ERROR: API ERROR: 429 - Too Many Requests

### ISSUE THREAD

**Issue by RadicalResearchLLC** [quarto-dev/quarto-cli#6624]
### Bug description

Basically, I am experience the same issue as the one reported in https://github.com/quarto-dev/quarto-cli/issues/1577 and https://github.com/quarto-dev/quarto-cli/issues/6014

The complete error message I had is shown below.

C:\Dev\testQuarto\testQuarto>quarto publish quarto-pub
? Publish with account <USERNAME> (Y/n) » No
? Authorize (Y/n) » Yes
? Publish with name 'testquarto'? (Y/n) » Yes

[>] Creating quarto-pub document
ERROR: API Error: 429 - Too Many Requests

Error: API Error: 429 - Too Many Requests
    at QuartoPubClient.createSite (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:111363:23)
    at async file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:108988:26
    at async withSpinner (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:56614:9)
    at async handlePublish (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:108985:9)
    at async publishDocument (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121352:38)
    at async publish5 (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121448:132)
    at async doPublish (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121404:13)
    at async publishAction (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121440:13)
    at async Command.fn (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121392:9)
    at async Command.execute (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:8437:13)

### Steps to reproduce

1.    I use quarto create-project testQuarto --type website to create a quarto website project.
2.    Then, I CD testQuarto, and run quarto publish quarto-pub.

### Expected behavior

I should get the example website published on quartopub.com, see oatsite example from previous error - the rendered files work locally.

### Actual behavior

I get the same error as has been seen in previous examples.

[>] Creating quarto-pub document
ERROR: API Error: 429 - Too Many Requests

Error: API Error: 429 - Too Many Requests
    at QuartoPubClient.createSite (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:111363:23)
    at async file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:108988:26
    at async withSpinner (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:56614:9)
    at async handlePublish (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:108985:9)
    at async publishDocument (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121352:38)
    at async publish5 (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121448:132)
    at async doPublish (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121404:13)
    at async publishAction (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121440:13)
    at async Command.fn (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:121392:9)
    at async Command.execute (file:///C:/Users/MichaelMcCarthy/AppData/Local/Programs/Quarto/bin/quarto.js:8437:13)

### Your environment

RStudio 2023.06.1+524 "Mountain Hydrangea" 
R 4.3.1 'Beagle Scouts'
Windows 11 - Version 10.0.22621 Build 22621

### Quarto check output

C:\Dev\testQuarto\testQuarto>quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\MichaelMcCarthy\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: C:/Users/MichaelMcCarthy/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/MichaelMcCarthy/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK

**Comment by racing-focus** [comment]
I tried this today for the first time and received the same error.

**Comment by mcanouil** [comment]
This is not an issue with Quarto CLI with Quarto Pub host.

**Comment by lervin1** [comment]
I got this same error, so how do we fix it?

**Comment by lervin1** [comment]
I did this, and now it says my site cannot be found. Does anyone know how to fix this?

**Comment by mcanouil** [comment]
There is nothing you can do beside waiting for this to be fixed on Quarto Pub side.

**Comment by softwarenerd** [comment]
Hi,

We are still investigating the issue. The problem is occurring in one of the services we use to host Quarto Pub, and we are working with the vendor on a resolution for the issue.

Best,

Brian

**Comment by softwarenerd** [comment]
Hello. The Quarto Pub service is available again. Please try again let us know if you are able to successfully publish.

**Comment by racing-focus** [comment]
I was able to publish, thank you.

**Comment by mcanouil** [comment]
Thanks for confirming!
Closing now.

**Comment by RadicalResearchLLC** [comment]
It also worked for me.  Thank you!

**Comment by ezraschwartzMD** [comment]
Opening this conversation again. Trying to publish a quarto book project under a different quarto pub account, receiving the "ERROR: API Error: 429 (Too Many Requests)" error. 

Any advice?

**Comment by mcanouil** [comment]
No need to post everywhere.

**Comment by ezraschwartzMD** [comment]
2 Chats. This one was closed, saw another was opened yesterday and posted there. Would appreciate your advice.
