### ISSUE TITLE
Show full path of `_quarto.yml` when error happens

### ISSUE THREAD

**Issue by arthur-shaw** [quarto-dev/quarto-cli#6625]
### Bug description

After receiving Windows 10 updates on a corporate device, Quarto stopped rendering documents. Hoping that this could be resolved by updating Quarto, IT installed the latest RStudio and Quarto.

When trying to render a simple HTML file, I get the following error message while Quarto continues to try to render (without success)

```
PS C:\Users\wb393438\Downloads> quarto preview c:/Users/wb393438/Downloads/quarto_issue/quarto_issue.qmd --no-browser --no-watch-inputs
ERROR: Project _quarto.yml validation failed.

(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 7, columns 13--16) Field "search" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:navbar:search.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 5, columns 20--23) Field "page-navigation" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:page-navigation.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


Error: Project _quarto.yml validation failed.

(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 7, columns 13--16) Field "search" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:navbar:search.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 5, columns 20--23) Field "page-navigation" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:page-navigation.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.

    at readAndValidateYamlFromFile (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:42120:15)
    at async file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:82871:26
    at async projectContext (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:82723:26)
    at async Command.fn (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:103695:25)
    at async Command.execute (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:127539:5)
    at async file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:127557:9
```

Since nothing changed on my system apart from the Windows 10 updates (and whatever else IT packaged with it), I suspect that there's been a change in policy that prevents Quarto from doing it's work. While I know that this is a broad question, what might prevent Quarto from working? Put another way, what system permissions are necessary on Windows for Quarto to run correctly?

### Steps to reproduce

````qmd
---
format: html
---

Hello, World

````

### Expected behavior

This should render an HTML file.

### Actual behavior

This error appears in the terminal:

```
PS C:\Users\wb393438\Downloads> quarto preview c:/Users/wb393438/Downloads/quarto_issue/quarto_issue.qmd --no-browser --no-watch-inputs
ERROR: Project _quarto.yml validation failed.

(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 7, columns 13--16) Field "search" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:navbar:search.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 5, columns 20--23) Field "page-navigation" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:page-navigation.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


Error: Project _quarto.yml validation failed.

(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 23, columns 10--12) Field "toc" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location format:html:toc.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 7, columns 13--16) Field "search" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:navbar:search.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.


(line 5, columns 20--23) Field "page-navigation" has value yes, which must instead be `true` or `false`

x The value yes is a string.
i The error happened in location website:page-navigation.
i Quarto uses YAML 1.2, which interprets booleans strictly.
i Try using true instead.

    at readAndValidateYamlFromFile (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:42120:15)
    at async file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:82871:26
    at async projectContext (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:82723:26)
    at async Command.fn (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:103695:25)
    at async Command.execute (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:127539:5)
    at async file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:127557:9
PS C:\Users\wb393438\Downloads> 
```

### Your environment

- IDE: VSCode
```
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
```
- Quarto
```
PS C:\Users\wb393438\Downloads> quarto --version
1.3.353
```
- OS:
```
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19044 Build 19044
```

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
Sending fatal alert BadCertificate
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.353
      Path: C:\Program Files\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: C:/Users/wb393438/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-42~1.2
      LibPaths:
        - C:/Program Files/R/R-4.2.2/library
      knitr: 1.43
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
```

**Comment by arthur-shaw** [comment]
As noted above, Quarto stopped rendering documents after Windows 10 updates were applied to my cmputer. In an effort to troubleshoot the issue, IT installed the latest version of Quarto. For the prior version of Quarto, different error messages appeared in the console.

```
PS C:\Users\wb393438\PICES\data_quality_support\data_quality_proposal> $ENV:QUARTO_PRINT_STACK="true"
PS C:\Users\wb393438\PICES\data_quality_support\data_quality_proposal> quarto preview c:/Users/wb393438/PICES/data_quality_support/data_quality_proposal/data_quality_proposal.qmd --no-browser --no-watch-inputs
ERROR: NotFound: The system cannot find the path specified. (os error 3)

NotFound: The system cannot find the path specified. (os error 3)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at sassLayerFile (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:62822:30)
    at themeLayer (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:73616:12)
    at file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:73529:20
    at Array.map (<anonymous>)
    at revealTheme (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:73518:8)
    at Object.formatExtras (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:73667:33)
    at runPandoc (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:69052:81)
    at async renderPandoc (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:69648:26)
    at async Object.onRender (file:///C:/Program%20Files/RStudio/resources/app/bin/quarto/bin/quarto.js:79331:32)
PS C:\Users\wb393438\PICES\data_quality_support\data_quality_proposal>
```

Note: unlike other issues that cite this error message (e.g., #2711 , #2380, #2316), the Quarto file is not on a remote/shared/synched drive. This is running on my C drive. Also, R, RStudio, and Quarto are all located on C.

Here are some details about that prior version of Quarto where different errors appeared.

````
PS C:\Users\wb393438\PICES\data_quality_support\data_quality_proposal> quarto --version
1.2.269
```

```
PS C:\Users\wb393438\PICES\data_quality_support\data_quality_proposal> quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.269
      Path: C:\Program Files\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: C:/wbg/Anaconda3/python.exe
      Jupyter: 4.8.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK    
      Version: 4.2.2
      Path: C:/PROGRA~1/R/R-42~1.2
      LibPaths:
        - C:/Program Files/R/R-4.2.2/library
      rmarkdown: 2.23

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Please do share the content of the repository and the Quarto document.
Also what version were you using before?

It seems you have issues in your document such as `toc: yes` instead of `toc: true` as stated in the messages.
Also ensure you don't have a `_quarto.yml` somewhere in the parent path of the document you are rendering.

**Comment by arthur-shaw** [comment]
>Please do share the content of the repository and the Quarto document.
> ...
>It seems you have issues in your document such as toc: yes instead of toc: true as stated in the messages.
Also ensure you don't have a _quarto.yml somewhere in the parent path of the document you are rendering.

The document producing the error on my system is the same as under `Steps to reproduce` heading of the initial message:

````quarto
---
format: html
---

Hello, World

````

This file is in a folder with no other files present.

The error messages, hence, do not seem to be related to content that's detected.

>Also what version were you using before?

The issue was first encountered on Quarto 1.2.269, albeit with same behavior (i.e., Quarto fails to render) but a different error message.

**Comment by cscheid** [comment]
> Project _quarto.yml validation failed

When this happens, quarto really should also write the full qualified path of `_quarto.yml`...

**Comment by cderv** [comment]
> After deleting that file (i.e., C:/Users/wb393438/Downloads/_quarto.yml) and following the steps you outlined, the project renders as expected.

Good to know ! Glad it is not something else. 

> For reference, here's the error message:

This seems related to SASS compilation. Document mentions `theme: [default, assets/core.scss, assets/data_quality_proposal.scss]` so be sure that those `scss` file exists. 

Again not a good error message IMO... 😞  sorry

> When this happens, quarto really should also write the full qualified path of _quarto.yml...

@cscheid for sure ! I agree with you. We should report absolute path.

**Comment by cderv** [comment]
> I didn't realize that Quarto searches parent folders for _quarto.yml. I'll try to be less messy in future.

Not sure it searches in parent folder, but your config file is in `C:/Users/wb393438/Downloads/_quarto.yml`  and you ran your command from this folder 
```
PS C:\Users\wb393438\Downloads> quarto preview c:/Users/wb393438/Downloads/quarto_issue/quarto_issue.qmd --no-browser --no-watch-inputs
```

So technically, you `C:/Users/wb393438/Downloads/` folder is a quarto project.

**Comment by cscheid** [comment]
Actually, I'm going to close this one and open a new issue just so that we have a cleaner comment thread.
