### ISSUE TITLE
Cannot output to stdout on Windows ("filename is incorrect")

### ISSUE THREAD

**Issue by rchaput** [quarto-dev/quarto-cli#6690]
### Bug description

Trying to render a file on Windows directly to the standard output (using `--output -`) does not work, and raises an error:

> ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'D:\a\acronyms\acronyms\tests\C:\Users\RUNNER~1\AppData\Local\Temp\quarto-session156a9866\e4edb8da\eb097f19.md'
>
> Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'D:\a\acronyms\acronyms\tests\C:\Users\RUNNER~1\AppData\Local\Temp\quarto-session156a9866\e4edb8da\eb097f19.md'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:492:14)
    at renderResultFinalOutput (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:81166:10)
    at Command.fn (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:90873:33)
    at async Command.execute (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:127545:5)
    at async file:///C:/Users/runneradmin/scoop/apps/quarto/current/bin/quarto.js:127563:9

(This specific error trace is taken from a GitHub Actions workflow to test my extension).

I assume that, at some point, Quarto tries to create a path to a temp file (`C:\Users\RUNNER~1\AppData\Local\Temp\quarto-session156a9866\e4edb8da\eb097f19.md`), but concatenates it with the path to the current working directory (`D:\a\acronyms\acronyms\tests\`).
Because both paths begin with a volume, Windows bugs.

### Steps to reproduce

Using any Quarto document, as simple as:

```qmd
---
title: "MVE"
---

This will not work when outputting to stdout
```

And render it using Powershell:

```powershell
quarto render document.qmd --output -
```

### Expected behavior

Quarto should render the document to a temporary file correctly, read it and print it to the stdout.

### Actual behavior

The `quarto` command invocation crashes, no file is produced, and error code `1` is returned.

### Your environment

OS: Windows (Windows 10 on my machine, Windows Server 2022 on GitHub Actions, both have the same bug)

### Quarto check output

```
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
      Version: 1.3.450
      Path: C:\Users\runneradmin\scoop\apps\quarto\current\bin
      CodePage: 1252

      Version: 3.11.4
      Path: C:/hostedtoolcache/windows/Python/3.11.4/x64/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Program Files/R/R-4.3.1/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by mcanouil** [comment]
As far as I know, this was never supported likely because only a few of the formats (and under specific option, such as `embed-resources: true`) could make this work.

Could you elaborate on your use case and the formats you are using?

**Comment by rchaput** [comment]
I'm using this in a TS script to automatically test my extension. Basically, I have a set of test folders, and I run `const command = new Deno.Command('quarto', { args: [ 'render', 'testFolder/input.qmd', '--output', '-' ] })` for each folder. I then compare the stdout (`const { code, stdout, stderr } = command.outputSync()`) to an expected result.

This code works perfectly well on Linux (Ubuntu) and macOS.

I understand that most formats do not need this option; I'm using `markdown` (with a few options, e.g., `markdown-headings`, `wrap` to make sure the output exactly corresponds to the expected result).

Alternatively, I would be fine with using a temporary file instead of stdout, especially since Quarto will write to a temporary file anyway, so there would be no performance difference, but I cannot specify a full path to `--output`.

(As for Pandoc, their doc mentions:
> Write output to FILE instead of stdout. If FILE is -, output will go to stdout, even if a non-textual format (docx, odt, epub2, epub3) is specified.

but I think that it's irrelevant to the problem; I believe I saw somewhere in Quarto's source code that a path was created when `output` is `-`, so `--output -` is never passed to Pandoc when using Quarto)

**Comment by mcanouil** [comment]
Output takes a file not a file path.
See <https://github.com/quarto-dev/quarto-cli/discussions/2171> for a complete overview of this.

**Comment by cderv** [comment]
This is definitely related to  (close to a duplicate)
* https://github.com/quarto-dev/quarto-cli/issues/4194

I think we have a simple fix now considering our internal logic. I'll make a PR for you to review @cscheid
