### ISSUE TITLE
Quarto front matter expects ending with --- while pandoc allows ...

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6698]
I'm asking if Quarto is supposed to allow ending the frontmatter with `...`.
(Because it makes it possible for me to modify the frontmatter with standard yaml libraries.)

Your answer above is "Yes", because Pandoc allows this. Great :-)

Unfortunately Quarto throws an error. Should I file a bug report?

```
Expected front matter to end with '---'

Error: Expected front matter to end with '---'
    at validateDocumentFromSource (file:///opt/quarto/bin/quarto.js:84346:19)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:86587:55)
    at async render (file:///opt/quarto/bin/quarto.js:90681:21)
    at async renderForPreview (file:///opt/quarto/bin/quarto.js:102415:26)
    at async render (file:///opt/quarto/bin/quarto.js:102310:20)
    at async Object.promise (file:///opt/quarto/bin/quarto.js:102466:33)
```

_Originally posted by @th0ger in https://github.com/quarto-dev/quarto-cli/discussions/6687#discussioncomment-6896517_

**Comment by cscheid** [comment]
This should be part of our "replace all syntax treatment with a single parser" future project...
