### ISSUE TITLE
Error when running quarto preview with --no-browser

### ISSUE THREAD

**Issue by kamransoomro84** [quarto-dev/quarto-cli#6776]
**EDIT:** I was editing this issue when it was transferred so my edits were lost. I have amended the problem description.

I just installed Quarto on Mac OS 13.5.1 with Homebrew. My python is installed inside a conda environment and I am using VS Code with the Quarto extension.

I have two separate problems.

# Running Quarto from iTerm2

When I run `quarto preview` from iTerm2 it works fine once, but running it again results in the following error:

```bash
ERROR: NotFound: No such file or directory (os error 2), remove '*/Library/Caches/quarto/jt/933e4fbbd2d6777b2ed0'

NotFound: No such file or directory (os error 2), remove '*/Library/Caches/quarto/jt/933e4fbbd2d6777b2ed0'
    at Object.removeSync (deno:runtime/js/30_fs.js:157:9)
    at connectToKernel (file:///Applications/quarto/bin/quarto.js:54708:18)
    at async executeKernelKeepalive (file:///Applications/quarto/bin/quarto.js:54502:31)
    at async Object.execute (file:///Applications/quarto/bin/quarto.js:55307:17)
    at async renderExecute (file:///Applications/quarto/bin/quarto.js:86470:27)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:86593:51)
    at async render (file:///Applications/quarto/bin/quarto.js:90681:21)
    at async renderForPreview (file:///Applications/quarto/bin/quarto.js:102415:26)
    at async render (file:///Applications/quarto/bin/quarto.js:102310:20)
    at async preview (file:///Applications/quarto/bin/quarto.js:102316:21)
```

I have replaced my homedir with '*'. Running it further times alternates between working fine and the above error.

# Running Quarto from within VS Code

When I click the "Render" button within VS Code, I get the following error:

```bash
Starting python271764bit0ff40240af7d417ead24c80fa14385f5 kernel...ERROR: 

[Errno 2] No such file or directory: '/usr/local/opt/python@2/bin/python2.7'
```

I can see the correct conda environment being activated so I don't understand why it tries to run Python 2. Running it further times alternates between the two errors above.

**Comment by kamransoomro84** [comment]
@cderv  please see the edited problem description above.

**Comment by mcanouil** [comment]
Could you provide the output of `quarto check`?

**Comment by kamransoomro84** [comment]
@mcanouil here is the output:

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /usr/local/Caskroom/mambaforge/base/envs/quarto/bin/python
      Jupyter: 5.3.1
      Kernels: python3, python271764bit0ff40240af7d417ead24c80fa14385f5, julia-1.1, jlab-desktop, python37764bitjupyterlabcondabe22684217bc402995f5d4518ed7f5fc, python2

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/local/Caskroom/mambaforge/base/envs/quarto/lib/R
      LibPaths:
        - /usr/local/Caskroom/mambaforge/base/envs/quarto/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

I've installed the `r-markdown` package in conda so not sure why it says the package is not installed.

**Comment by mcanouil** [comment]
Could you provide the Quarto document you tried to render? Did you properly specified the Jupyter kernel?

Thanks for the report!

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

The R library path detected by Quarto is `/usr/local/Caskroom/mambaforge/base/envs/quarto/lib/R/library`. I am pretty sure whatever the method "I've installed the r-markdown package in conda" is, it's not installed in that path.

**Comment by kamransoomro84** [comment]
That path is the conda environment. r itself was installed using conda.

Here is the document:

````qmd
---
title: "Hello, Quarto"
format: html
---

## Markdown

Markdown is an easy to read and write text format:

- It's _plain text_ so works well with version control
- It can be **rendered** into HTML, PDF, and more
- Learn more at: <https://quarto.org/docs/authoring/>

## Code Cell

Here is a Python code cell:

```{python}
import os
os.cpu_count()
```

## Equation

Use LaTeX to write equations:

$$
\chi' = \sum_{i=1}^n k_i s_i^2
$$
````

**Comment by kamransoomro84** [comment]
And yes. I set the interpreter to the virtual conda environment that contains r and jupyerlab.

**Comment by mcanouil** [comment]
But you did not tell Quarto which kernel to use as per the document you shared.

See <https://quarto.org/docs/computations/python.html#kernel-selection>.

**Comment by kamransoomro84** [comment]
@mcanouil I see. This document was auto-generated by the Quatro VS Code extension. Is this a bug then?

I'm not sure what the kernel should be. Also, do you have any idea about the first problem?

**Comment by mcanouil** [comment]
It's not a bug.
It's your environment that has multiple kernel and Python version, thus you need to choose/set one.
In a clean environment you don't have that many kernel listed in quarto check output.

The other error might be due to something missing in the Python/Jupyter environment you are using.
Unfortunately, since we don't have your setup and can't reproduce, we can only try to guess what's wrong in your setup.

Here, I would recommend to make a clean Conda environment.

**Comment by kamransoomro84** [comment]
> It's not a bug.
> It's your environment that has multiple kernel and Python version, thus you need to choose/set one.

I get that. But there was no obvious way for me to know where the error was coming from without reading through the documentation. Perhaps the auto generated document could at least point the user to the environment-specific options. 

Regarding the environment, this is a clean install specifically for quarto. It only has the packages quarto requires. If you want I can share the environment configuration with you.

**Comment by mcanouil** [comment]
See <https://quarto.org/docs/troubleshooting/index.html> which shows the `quarto check` command.

From your `quarto check` output there are multiple Python version and multiple kernel registered.
Maybe that's the "normal" Conda environment which in my opinion is really messy.

**Comment by kamransoomro84** [comment]
I'll send you the environment config tomorrow. Those other kernels you see are from other, now defunct environments. I'm not sure why they appear here as this is definitely a clean install. I'll investigate tomorrow.

**Comment by mcanouil** [comment]
You can remove obsolete registered kernel using `jupyter kernelspec uninstall NAME`.

**Comment by kamransoomro84** [comment]
@mcanouil ok I've removed all the extra kernels but I still get the same alternating error behaviour:

```bash

      Version: 3.11.5 (Conda)
      Path: /usr/local/Caskroom/mambaforge/base/envs/quarto/bin/python
      Jupyter: 5.3.1
      Kernels: python3, julia-1.1

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

`requirements.txt` file:

```bash
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1693488585952/work
appnope @ file:///home/conda/feedstock_root/build_artifacts/appnope_1649077682618/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1692818318753/work
argon2-cffi-bindings @ file:///Users/runner/miniforge3/conda-bld/argon2-cffi-bindings_1666850758378/work
arrow @ file:///home/conda/feedstock_root/build_artifacts/arrow_1662382474514/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1694046349000/work
async-lru @ file:///home/conda/feedstock_root/build_artifacts/async-lru_1690563019058/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1677767029043/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1687772187254/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1680888073205/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1674535352125/work
Brotli @ file:///Users/runner/miniforge3/conda-bld/brotli-split_1693583678882/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi==2023.7.22
cffi @ file:///Users/runner/miniforge3/conda-bld/cffi_1671179612308/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1688813409104/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1691044910542/work
debugpy @ file:///Users/runner/miniforge3/conda-bld/debugpy_1694118104592/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1692026125334/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1690055433477/work/dist
fqdn @ file:///home/conda/feedstock_root/build_artifacts/fqdn_1638810296540/work/dist
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1688754491823/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1691408075105/work
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1693880377119/work
ipython @ file:///Users/runner/miniforge3/conda-bld/ipython_1693580003080/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1690877070294/work
isoduration @ file:///home/conda/feedstock_root/build_artifacts/isoduration_1638811571363/work/dist
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1690896916983/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1688248289187/work
jsonpointer==2.0
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1691761378595/work
jsonschema-specifications @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-specifications_1689701150890/work
jupyter @ file:///Users/runner/miniforge3/conda-bld/jupyter_1670249893813/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1678118109161/work
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1691505939576/work
jupyter-lsp @ file:///home/conda/feedstock_root/build_artifacts/jupyter-lsp-meta_1685453365113/work/jupyter-lsp
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1673615989977/work
jupyter_core @ file:///Users/runner/miniforge3/conda-bld/jupyter_core_1686775757864/work
jupyter_server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1693487358826/work
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1673491454549/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1692015883666/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1688489450369/work
jupyterlab_server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1690205927615/work
MarkupSafe @ file:///Users/runner/miniforge3/conda-bld/markupsafe_1685769179270/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1692116650819/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1684790896106/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1693331710275/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1690814868471/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1693410793506/work
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1682360583588/work
overrides @ file:///home/conda/feedstock_root/build_artifacts/overrides_1691338815398/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1690813113769/work
ply==3.11
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1689032443210/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1688565951714/work
psutil @ file:///Users/runner/miniforge3/conda-bld/psutil_1681775196112/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1691408637400/work
pyobjc-core @ file:///Users/runner/miniforge3/conda-bld/pyobjc-core_1686129336286/work
pyobjc-framework-Cocoa @ file:///Users/runner/miniforge3/conda-bld/pyobjc-framework-cocoa_1686136009200/work
PyQt5-sip==12.11.0
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1693930252784/work
PyYAML @ file:///Users/runner/miniforge3/conda-bld/pyyaml_1692737410683/work
pyzmq @ file:///Users/runner/miniforge3/conda-bld/pyzmq_1666828680984/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole-base_1693604303222/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1693347765905/work
referencing @ file:///home/conda/feedstock_root/build_artifacts/referencing_1691337268233/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rpds-py @ file:///Users/runner/miniforge3/conda-bld/rpds-py_1693850362535/work
Send2Trash @ file:///Users/runner/miniforge3/conda-bld/send2trash_1682601407921/work
sip @ file:///Users/ec2-user/ci_py311/sip_1678318421743/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1693929250441/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
terminado @ file:///Users/runner/miniforge3/conda-bld/terminado_1670254106711/work
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
tornado @ file:///Users/runner/miniforge3/conda-bld/tornado_1692311824797/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
typing-utils @ file:///home/conda/feedstock_root/build_artifacts/typing_utils_1622899189314/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1688315532570/work
uri-template @ file:///home/conda/feedstock_root/build_artifacts/uri-template_1688655812972/work/dist
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1689789803562/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webcolors @ file:///home/conda/feedstock_root/build_artifacts/webcolors_1679900785843/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1692730992302/work
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1688504439014/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1689374466814/work
```

`conda export`:

```bash
name: quarto
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.0.0=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h5547dcb_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hdf8f085_0
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2023.7.22=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311ha86e640_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.7.0=py311hdf8f085_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hb7f2c08_3
  - glib=2.76.4=h7d26f99_0
  - glib-tools=2.76.4=h7d26f99_0
  - gst-plugins-base=1.22.5=hb5d3a86_1
  - gstreamer=1.22.5=h840fbdc_1
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - ipykernel=6.25.2=pyh1050b4e_0
  - ipython=8.15.0=pyh31c8845_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.1.0=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hb7f2c08_3
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.19.0=pyhd8ed1ab_1
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.0=pyhd8ed1ab_1
  - jupyter=1.0.0=py311h6eed73b_8
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h6eed73b_0
  - jupyter_events=0.7.0=pyhd8ed1ab_2
  - jupyter_server=2.7.3=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - krb5=1.20.1=h049b76e_0
  - lerc=4.0.0=hb486fe8_0
  - libclang=13.0.1=root_62804_h2961583_3
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.17=hb664fd8_0
  - libedit=3.1.20191231=h0678c8f_2
  - libexpat=2.5.0=hf0c8a7f_1
  - libffi=3.4.2=h0d85af4_5
  - libglib=2.76.4=hc62aa5d_0
  - libiconv=1.17=hac89ed1_0
  - libllvm12=12.0.1=hd011deb_2
  - libllvm13=13.0.1=h64f94b2_2
  - libogg=1.3.4=h35c211d_1
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.39=ha978bb4_0
  - libpq=15.3=h9dc22bb_1
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.43.0=h58db7d2_0
  - libtiff=4.5.0=hee9004a_2
  - libvorbis=1.3.7=h046ec9c_0
  - libwebp=1.2.4=h70a068d_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxml2=2.10.3=h201ad9d_4
  - libxslt=1.1.37=h5d22bc9_0
  - libzlib=1.2.13=h8a1eda9_5
  - markupsafe=2.1.3=py311h2725bcf_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.1=pyhd8ed1ab_0
  - mysql-common=8.0.33=hc6116ba_3
  - mysql-libs=8.0.33=haa61052_3
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.8.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.8.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=hf0c8a7f_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=7.0.3=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.92=hd6ac835_0
  - openssl=3.1.2=h8a1eda9_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandoc=3.1.3=h9d075a6_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311h5547dcb_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyobjc-core=9.2=py311hf110eff_0
  - pyobjc-framework-cocoa=9.2=py311hf110eff_0
  - pyqt=5.15.7=py311hcec6c5f_0
  - pyqt5-sip=12.11.0=py311hcec6c5f_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.5=h30d4d87_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h2725bcf_0
  - pyzmq=24.0.1=py311habfacb3_1
  - qt-main=5.15.8=h1d3b3f8_6
  - qt-webengine=5.15.9=h90a370e_7
  - qtconsole=5.4.4=pyhd8ed1ab_0
  - qtconsole-base=5.4.4=pyha770c72_0
  - qtpy=2.4.0=pyhd8ed1ab_0
  - qtwebkit=5.212=h11e631a_8
  - readline=8.2=h9e318b2_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.10.2=py311h299eb51_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=68.1.2=pyhd8ed1ab_0
  - sip=6.6.2=py311hcec6c5f_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.43.0=h2b0dec6_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.3=py311h2725bcf_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.2=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - widgetsnbextension=4.0.8=pyhd8ed1ab_0
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h8a1eda9_5
  - zstd=1.5.5=h829000d_0
prefix: /usr/local/Caskroom/mambaforge/base/envs/quarto
```

**Comment by mcanouil** [comment]
Please consider sharing a Git repository to reproduce your setup.

**Comment by kamransoomro84** [comment]
@mcanouil  what would you like to see in the repository? The environment lives inside a separate folder from the document.

**Comment by mcanouil** [comment]
The Python modules, etc. or the exact steps to try to reproduce your case, such as:

1. Execute this command
2. Then that command
3. etc.

**Comment by kamransoomro84** [comment]
Well as far as the environment is concerned the conda export and requirements files should give you all that you need to reconstruct it at your end, but happy to provide the environment. 

Regarding steps, take the document above, and click "Render". Shut down the server if successful and click "Render" again.

**Comment by cscheid** [comment]
> Well as far as the environment is concerned the conda export and requirements files should give you all that you need to reconstruct it at your end, but happy to provide the environment.

Please do. The issue is that we suspect it's something outside of the Quarto environment. So it's significantly easier for us to test it if you provide a single git repository where you experience the problem, so we can check whether _we_ experience the problem _in that exact same git repository_.

> Regarding steps, take the document above, and click "Render". Shut down the server if successful and click "Render" again.

I've done that, and I unfortunately can't reproduce your issue.

**Comment by kamransoomro84** [comment]
@cscheid @mcanouil ok I've created a git repo [here](https://github.com/kamransoomro84/quarto_test). I tried creating a virtual environment using `venv` from the `requirements.txt` file and I get the same behaviour.

**Comment by mcanouil** [comment]
I have no issue using either conda or virtualenv and restoring your `requirements.txt`.
I don't believe the issue is with Quarto, but really with your setup.
Could you uninstall and reinstall Quarto in case your install was corrupted somehow?

**Comment by kamransoomro84** [comment]
@mcanouil I just did a clean reinstall and get the same issue. Can you think of anything that might help me diagnose the problem?

**Comment by mcanouil** [comment]
Please stop tagging/pinging at every replies.

I am out of ideas about what's wrong in your setup.

**Comment by kamransoomro84** [comment]
Ok apologies. I wasn't sure whether I'm supposed to tag you or not when replying. 

I guess I can get by like this since I am able to get it to work for every alternate run. 

Thank you for your help.

**Comment by mcanouil** [comment]
> Ok apologies. I wasn't sure whether I'm supposed to tag you or not when replying.

We watch every new issues/discussions/comments. Tagging means an extra more prominent level of notification.
As a rule of thumb, usually in a conversation / thread, people don't repeat each other names at every sentence.

**Comment by kamransoomro84** [comment]
Just to clarify, I don't run the two separate instances at the same time, but in sequence.
