### ISSUE TITLE
`quarto run` with a TS script is no more working on windows

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6818]
````powershell 
> echo "console.log('hello')" > test.ts
> > quarto run .\test.ts
ERROR: Error executing 'C:\Users\chris\Documents\DEV_R\quarto-cli\package\dist\bin\tools\x86_64\deno': Le fichier spécifié est introuvable. (os error 2)

Stack trace:
    at execProcess (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/process.ts:170:11)
    at Object.run (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/run/deno.ts:42:18)
    at runScript (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/run/run.ts:29:24)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:90:20)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:167:5
> rm test.ts
````

This is because deno does not live in `C:\Users\chris\Documents\DEV_R\quarto-cli\package\dist\bin\tools\x86_64\deno` but in `tools` directly. 

This is after reming `dist` folder and re-running configure. 

````powershell
> tree .\package\dist\bin\tools\ /F
Structure du dossier pour le volume OS
Le numéro de série du volume est D412-A01A
C:\USERS\CHRIS\DOCUMENTS\DEV_R\QUARTO-CLI\PACKAGE\DIST\BIN\TOOLS
│   deno.exe
│   pandoc.exe
│
└───x86_64
    │   esbuild.exe
    │   typst.exe
    │
    ├───dart-sass
    │   │   sass.bat
    │   │
    │   └───src
    │           dart.exe
    │           LICENSE
    │           sass.snapshot
    │
    └───deno_dom
            plugin.dll
````

Posibbly related to change in 
* https://github.com/quarto-dev/quarto-cli/pull/6182

that introduced a architecture folder for tooling 
https://github.com/quarto-dev/quarto-cli/blob/ea8942094ad670ccbb9d6f8fcafc4bcf097aa7cc/src/core/run/deno.ts#L42-L45

But somehow it is not there on Windows. 

No issue on Linux as it is in the correct place after a configure
````
$ tree package/dist/bin/tools/
package/dist/bin/tools/
├── deno -> x86_64/deno
├── pandoc -> x86_64/pandoc
└── x86_64
    ├── dart-sass
    │   ├── sass
    │   └── src
    │       └── LICENSE
    ├── deno
    ├── deno_dom
    │   └── libplugin.so
    ├── esbuild
    ├── pandoc
    └── typst

4 directories, 9 files
````

<details>
<summary>EDIT: this is only Dev version as pre-release does seem to put everything in the right place</summary>

````
> tree "$(scoop prefix quarto-prerelease)/bin/tools/" /F
Structure du dossier pour le volume OS
Le numéro de série du volume est D412-A01A
C:\USERS\CHRIS\SCOOP\APPS\QUARTO-PRERELEASE\CURRENT\BIN\TOOLS
│   pandoc.exe
│
└───x86_64
    │   deno.exe
    │   esbuild.exe
    │   typst.exe
    │
    ├───dart-sass
    │   │   sass.bat
    │   │
    │   └───src
    │           dart.exe
    │           LICENSE
    │           sass.snapshot
    │
    └───deno_dom
            plugin.dll
````

</details>

**Comment by cderv** [comment]
We probably just need to update `configure.cmd` to download in the right place 
https://github.com/quarto-dev/quarto-cli/blob/ea8942094ad670ccbb9d6f8fcafc4bcf097aa7cc/configure.cmd#L22-L57

**Comment by cderv** [comment]
Nevermind the above regarding `code-workspace`. It is not working even if I add a symlink, because it is `deno.exe` on windows. Not just `deno`

I forgot I had my own custom setting for VSCODE dev work on windows for quarto
