### ISSUE TITLE
`quarto inspect` fails related to OJS in specific file

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#6984]
Randomly while testing something else I ran `quarto inspect` on the `trace-viewer.qmd` file in our tools directory. This resulted in the following exception:

```
$ quarto inspect trace-viewer.qmd
ERROR: TypeError: Cannot read properties of undefined (reading 'attach')

Stack trace:
    at extractResourceDescriptionsFromOJSChunk (file:///Users/ct/Development/quarto-dev/quarto-cli/src/execute/ojs/extract-resources.ts:561:24)
    at async extractResolvedResourceFilenamesFromQmd (file:///Users/ct/Development/quarto-dev/quarto-cli/src/execute/ojs/extract-resources.ts:224:13)
    at async resolveFileResources (file:///Users/ct/Development/quarto-dev/quarto-cli/src/command/render/resources.ts:59:11)
    at async resolveResources (file:///Users/ct/Development/quarto-dev/quarto-cli/src/quarto-core/inspect.ts:182:20)
    at async inspectConfig (file:///Users/ct/Development/quarto-dev/quarto-cli/src/quarto-core/inspect.ts:136:25)
    at async Command.fn (file:///Users/ct/Development/quarto-dev/quarto-cli/src/command/inspect/cmd.ts:47:20)
    at async Command.execute (file:///Users/ct/Development/quarto-dev/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///Users/ct/Development/quarto-dev/quarto-cli/src/quarto.ts:135:3)
    at async file:///Users/ct/Development/quarto-dev/quarto-cli/src/quarto.ts:167:5
```

It seems that this shouldn't throw in this case.

**Comment by cscheid** [comment]
Thanks for catching this!
