### ISSUE TITLE
'embed-resources: true' results in ermissionDenied: Permission denied (os error 13), open '/tmp/quarto-session.../.../template.patched'

### ISSUE THREAD

**Issue by HenrikBengtsson** [quarto-dev/quarto-cli#7024]
### Bug description

`quarto render <file>` gives `PermissionDenied: Permission denied (os error 13), open '/tmp/quarto-session.../.../template.patched'` when using `embed-resources: true`.  Setting `embed-resources: false` avoids the error.

### Steps to reproduce

Create file `selfcontained.qmd`:

```md
---
format:
  html:
    embed-resources: true
---

# Testing

Hello world.
```

Then call:

```sh
quarto render selfcontained.qmd
```

### Expected behavior

A self-contained HTML is produced.

### Actual behavior

```sh
$ quarto render selfcontained.qmd
ERROR: PermissionDenied: Permission denied (os error 13), open '/tmp/quarto-session843dfb33/44aa46d2/c59278b6/template.patched'

PermissionDenied: Permission denied (os error 13), open '/tmp/quarto-session843dfb33/44aa46d2/c59278b6/template.patched'
    at writeFileSync (deno:runtime/js/40_write_file.js:15:9)
    at Object.writeTextFileSync (deno:runtime/js/40_write_file.js:63:12)
    at applyTemplatePatches (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:58699:14)
    at stageTemplate (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:58661:9)
    at async runPandoc (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:80069:36)
    at async renderPandoc (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:81044:26)
    at async Object.onRender (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:86673:36)
    at async renderFiles (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:86636:25)
    at async render (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:90681:21)
    at async Command.fn (file:///home/henrik/shared/software/CBI/quarto-1.3.450/bin/quarto.js:90856:32)
```

Nothing is generated, but an empty folder:

```sh
$ tree selfcontained_files/
selfcontained_files/
└── mediabag

1 directory, 0 files
```

This is with:

```sh
$ quarto --version
1.3.450
```

### Your environment

# Command-line

* Command-line quarto on Linux
* quarto installed as a non-priviliged user, i.e. _not_ as admin/root
* Linux distributions tested: Ubuntu 22.04, CentOS 7.9, and Rocky 8
* Issue reproducible with quarto 1.3.450 as well as quarto 1.2.335
* Tested with and without `TMPDIR` set.  Also tested with `TMPDIR=$(mktemp -d)`

# RStudio Desktop

I've also tested:

* RStudio Desktop 2023.06.2 Build 561
* Linux distributions tested: Ubuntu 22.04
* Installed as a non-priviliged user, i.e. _not_ as admin/root

### Quarto check output

```bash
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /home/henrik/shared/software/CBI/quarto-1.3.450/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /home/henrik/shared/software/CBI/_ubuntu22_04/R-4.3.1-gcc11/lib/R
      LibPaths:
        - /home/henrik/R/ubuntu22_04-x86_64-pc-linux-gnu-library/4.3-CBI-gcc11
        - /home/henrik/shared/software/CBI/_ubuntu22_04/R-4.3.1-gcc11/lib/R/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by HenrikBengtsson** [comment]
FWIW, using `--debug` as in:

```sh
$ quarto render selfcontained.qmd --debug 
```

leaves file `selfcontained.md`;

```sh
$ at selfcontained.md
---
format:
  html:
    embed-resources: true
---



# Testing

Hello world.
```

The `--log ...` options does not reveal anything more.

**Comment by mcanouil** [comment]
Actually to get the stack trace and more logs, see <https://quarto.org/docs/troubleshooting/index.html>.

**Comment by HenrikBengtsson** [comment]
Maybe `strace` reveal some clues;

```sh
$ strace -f -s 200 -o quarto.strace quarto render selfcontained.qmd
```

gives:

```sh
$ tail -n 180 quarto.strace | head -n -60
883230 unlink("/tmp/quarto-sessioncbe66502/9c1a2aef/d05311a2/title-metadata.html") = 0
883230 statx(AT_FDCWD, "/home/henrik/shared/software/CBI/quarto-1.3.450/share/formats/html/templates/title-metadata.html", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5632, ...}) = 0
883230 openat(AT_FDCWD, "/home/henrik/shared/software/CBI/quarto-1.3.450/share/formats/html/templates/title-metadata.html", O_RDONLY|O_CLOEXEC) = 13
883230 statx(13, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=5632, ...}) = 0
883230 openat(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef/d05311a2/title-metadata.html", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0100444) = 14
883230 statx(14, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=0, ...}) = 0
883230 fchmod(14, 0100444)              = 0
883230 copy_file_range(13, NULL, 14, NULL, 1073741824, 0) = 5632
883230 copy_file_range(13, NULL, 14, NULL, 1073741824, 0) = 0
883230 close(14)                        = 0
883230 close(13)                        = 0
883230 openat(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef/d05311a2/template.patched", O_RDONLY|O_CLOEXEC) = 13
883230 statx(13, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=707, ...}) = 0
883230 lseek(13, 0, SEEK_CUR)           = 0
883230 read(13, "<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"$lang$\" xml:lang=\"$lang$\"$if(dir)$ dir=\"$dir$\"$endif$>\n\n<head>\n\n$metadata.html()$\n\n<style>\n$styles.html()$\n</style>\n\n<!-- htmldependenc"..., 707) = 707
883230 read(13, "", 32)                 = 0
883230 close(13)                        = 0
883230 openat(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef/d05311a2/template.patched", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = -1 EACCES (Permission denied)
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502/abba8631", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502/abba8631", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502/abba8631", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 openat(AT_FDCWD, "/tmp/quarto-sessioncbe66502/abba8631", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 13
883230 newfstatat(13, "", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_EMPTY_PATH) = 0
883230 fcntl(13, F_GETFL)               = 0x38000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
883230 fcntl(13, F_SETFD, FD_CLOEXEC)   = 0
883230 getdents64(13, 0x559d4f9bade0 /* 2 entries */, 32768) = 48
883230 getdents64(13, 0x559d4f9bade0 /* 0 entries */, 32768) = 0
883230 close(13)                        = 0
883230 unlinkat(AT_FDCWD, "/tmp/quarto-sessioncbe66502/abba8631", AT_REMOVEDIR) = 0
883230 openat(AT_FDCWD, "selfcontained.qmd", O_RDONLY|O_CLOEXEC) = 13
883230 statx(13, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=76, ...}) = 0
883230 lseek(13, 0, SEEK_CUR)           = 0
883230 read(13, "---\nformat:\n  html:\n    embed-resources: true\n---\n\n# Testing\n\nHello world.\n\n", 76) = 76
883230 read(13, "", 32)                 = 0
883230 close(13)                        = 0
883230 mprotect(0x559cc00c4000, 241664, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
883230 mprotect(0x559cc00c4000, 241664, PROT_READ|PROT_EXEC) = 0
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 openat(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 13
883230 newfstatat(13, "", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_EMPTY_PATH) = 0
883230 fcntl(13, F_GETFL)               = 0x38000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
883230 fcntl(13, F_SETFD, FD_CLOEXEC)   = 0
883230 getdents64(13, 0x559d4f9bade0 /* 7 entries */, 32768) = 208
883230 unlinkat(13, "e7bd11b3", 0)      = 0
883230 openat(13, "38378146", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 14
883230 newfstatat(14, "", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_EMPTY_PATH) = 0
883230 fcntl(14, F_GETFL)               = 0x38000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
883230 fcntl(14, F_SETFD, FD_CLOEXEC)   = 0
883230 getdents64(14, 0x559d4f9c2e20 /* 2 entries */, 32768) = 48
883230 getdents64(14, 0x559d4f9c2e20 /* 0 entries */, 32768) = 0
883230 close(14)                        = 0
883230 unlinkat(13, "38378146", AT_REMOVEDIR) = 0
883230 openat(13, "d05311a2", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 14
883230 newfstatat(14, "", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_EMPTY_PATH) = 0
883230 fcntl(14, F_GETFL)               = 0x38000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
883230 fcntl(14, F_SETFD, FD_CLOEXEC)   = 0
883230 getdents64(14, 0x559d4f9c2e20 /* 8 entries */, 32768) = 272
883230 unlinkat(14, "metadata.html", 0) = 0
883230 unlinkat(14, "styles.html", 0)   = 0
883230 unlinkat(14, "title-block.html", 0) = 0
883230 unlinkat(14, "toc.html", 0)      = 0
883230 unlinkat(14, "template.patched", 0) = 0
883230 unlinkat(14, "title-metadata.html", 0) = 0
883230 getdents64(14, 0x559d4f9c2e20 /* 0 entries */, 32768) = 0
883230 close(14)                        = 0
883230 unlinkat(13, "d05311a2", AT_REMOVEDIR) = 0
883230 unlinkat(13, "07453766", 0)      = 0
883230 unlinkat(13, "2bc140d1.css", 0)  = 0
883230 getdents64(13, 0x559d4f9bade0 /* 0 entries */, 32768) = 0
883230 close(13)                        = 0
883230 unlinkat(AT_FDCWD, "/tmp/quarto-sessioncbe66502/9c1a2aef", AT_REMOVEDIR) = 0
883235 mprotect(0x7fd2c021b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0223000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c022b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0233000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c023b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0243000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c024b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0253000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c025b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0263000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c026b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0273000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c027b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0283000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c028b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c0293000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c029b000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c02a3000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c02ab000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c02b3000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c02bb000, 4096, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c02bc000, 32768, PROT_READ|PROT_WRITE) = 0
883235 mprotect(0x7fd2c02c4000, 32768, PROT_READ|PROT_WRITE) = 0
883235 futex(0x559d4f34b320, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
883230 mprotect(0x38a7042c0000, 520192, PROT_READ|PROT_WRITE) = 0
883230 mprotect(0x559cc00c4000, 241664, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
883230 mprotect(0x559cc0084000, 241664, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
883230 mprotect(0x559cc0084000, 241664, PROT_READ|PROT_EXEC) = 0
883230 mprotect(0x559cc00c4000, 241664, PROT_READ|PROT_EXEC) = 0
883230 mprotect(0x559cc0084000, 241664, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
883230 mprotect(0x559cc0044000, 241664, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
883230 mprotect(0x559cc0044000, 241664, PROT_READ|PROT_EXEC) = 0
883230 mprotect(0x559cc0084000, 241664, PROT_READ|PROT_EXEC) = 0
883230 mprotect(0x559cc0044000, 241664, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
883230 mprotect(0x559cc0044000, 241664, PROT_READ|PROT_EXEC) = 0
883230 write(2, "\33[91mERROR: PermissionDenied: Permission denied (os error 13), open '/tmp/quarto-sessioncbe66502/9c1a2aef/d05311a2/template.patched'\n\nPermissionDenied: Permission denied (os error 13), open '/tmp/quar"..., 1229) = 1229
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 statx(AT_FDCWD, "/tmp/quarto-sessioncbe66502", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
883230 openat(AT_FDCWD, "/tmp/quarto-sessioncbe66502", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 13
883230 newfstatat(13, "", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_EMPTY_PATH) = 0
883230 fcntl(13, F_GETFL)               = 0x38000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
883230 fcntl(13, F_SETFD, FD_CLOEXEC)   = 0
883230 getdents64(13, 0x559d4f3e8a60 /* 2 entries */, 32768) = 48
883230 getdents64(13, 0x559d4f3e8a60 /* 0 entries */, 32768) = 0
883230 close(13)                        = 0
883230 unlinkat(AT_FDCWD, "/tmp/quarto-sessioncbe66502", AT_REMOVEDIR) = 0
```

**Comment by HenrikBengtsson** [comment]
> Actually to get the stack trace and more logs, see https://quarto.org/docs/troubleshooting/index.html.

Thank you.  So,

```sh
$ export QUARTO_PRINT_STACK=true
$ quarto render selfcontained.qmd
```

gives the same output as above, i.e. I seem to get a stacktrace by default even without that env var set.

Oddly enough, with:

```sh
$ export QUARTO_LOG_LEVEL=DEBUG
$ quarto render selfcontained.qmd
```

I do not get any log files generated, at least they're not in the documented output locations.  I don't have a `${HOME}/.local/share/quarto/` folder:

```sh
ls -la "${HOME}/.local/share/quarto/"
ls: cannot access '/home/henrik/.local/share/quarto/': No such file or directory
```

This is with:

```sh
$ echo "XDG_DATA_HOME=${XDG_DATA_HOME:-<not set>}"
XDG_DATA_HOME=<not set>
$ echo "QUARTO_LOG_LEVEL=${QUARTO_LOG_LEVEL:-<not set>}"
QUARTO_LOG_LEVEL=DEBUG
```

Even after `mkdir -p "${HOME}/.local/share/quarto/logs"`, there's nothing written to that folder.

**Comment by HenrikBengtsson** [comment]
# Bug identified

This happens if the files under `${QUARTO_HOME}/` are read-only.  By if one set write permissions on `${QUARTO_HOME}/share/formats/html/pandoc/template.html`, it works again.


Here's a minimal reproducible example.

```sh
td=$(mktemp -d)
cd "$td"
curl -L -O https://github.com/quarto-dev/quarto-cli/eleases/download/v1.3.450/quarto-1.3.450-linux-amd64.tar.gz
tar xf quarto-1.3.450-linux-amd64.tar.gz
printf -- "---\nformat:\n  html:\n    embed-resources: true\n---\n# Testing\n\nHello world.\n" > fail.qmd
```

The following works:

```sh
$ quarto-1.3.450/bin/quarto render fail.qmd
pandoc 
  to: html
  output-file: fail.html
  standalone: true
  embed-resources: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  
Output created: fail.html

$ ls -l fail.html 
-rw-rw-r-- 1 henrik henrik 870176 Sep 26 16:16 fail.html
```

However, if we make the installation path _read-only_;

```sh
$ chmod -R ugo-w quarto-1.3.450/
```

it fails

```sh
$ quarto-1.3.450/bin/quarto render fail.qmd
ERROR: PermissionDenied: Permission denied (os error 13), open '/tmp/henrik/quarto-sessionecde4e55/4de63422/6940efe7/template.patched'
...
```

However however, if we make `${QUARTO_HOME}/share/formats/html/pandoc/template.html` writable, it works again;

```sh
$ chmod u+w quarto-1.3.450/share/formats/html/pandoc/template.html
$ quarto-1.3.450/bin/quarto render fail.qmd
...
Output created: fail.html
```

What is really odd is that this makes it also work when running as another user, i.e. as long as it is writable for user `henrik` who installed quarto, it will also work for user `alice`.

# Conclusion

I think this is a bug, because it should be possible to install quarto to a folder `${QUARTO_HOME}/` for which no one has write-permissions, including the user who installs the software.
