### ISSUE TITLE
Quarto render error for pre-crafted template

### ISSUE THREAD

**Issue by Thanh-8213** [quarto-dev/quarto-cli#7030]
### Bug description

Quarto render error for one template on my machine (Other machines work)

### Steps to reproduce

The template came from: https://github.com/numbats/monash-quarto-thesis

I ran quarto render in the terminal. 

### Expected behavior

I expected to see the file in the pre-defined format.

### Actual behavior

Error returned: 
Error: Theme file compilation failed:

    at dartCommand (file:///C:/PROGRA~1/Quarto/bin/quarto.js:59894:15)
    at async dartCompile (file:///C:/PROGRA~1/Quarto/bin/quarto.js:59856:5)
    at async compileWithCache (file:///C:/PROGRA~1/Quarto/bin/quarto.js:60084:17)
    at async compileSass (file:///C:/PROGRA~1/Quarto/bin/quarto.js:59946:12)
    at async resolveSassBundles (file:///C:/PROGRA~1/Quarto/bin/quarto.js:76333:27)
    at async resolveExtras (file:///C:/PROGRA~1/Quarto/bin/quarto.js:80428:18)
    at async runPandoc (file:///C:/PROGRA~1/Quarto/bin/quarto.js:79983:24)
    at async renderPandoc (file:///C:/PROGRA~1/Quarto/bin/quarto.js:81044:26)
    at async Object.onRender (file:///C:/PROGRA~1/Quarto/bin/quarto.js:98878:42)
    at async renderFiles (file:///C:/PROGRA~1/Quarto/bin/quarto.js:86636:25)

### Your environment

─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16 ucrt)
 os       Windows 11 x64 (build 22621)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Australia.utf8
 ctype    English_Australia.utf8
 tz       Australia/Sydney
 date     2023-09-27
 rstudio  2023.06.2+561 Mountain Hydrangea (desktop)
 pandoc   NA

### Quarto check output

$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: C:/Users/thanh/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/thanh/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by dragonstyle** [comment]
I attempted to reproduce this locally and could not. It would be helpful if you could try to narrow the issue - since it works on many machines and fails on one, it is likely there is something about the configuration about that machine which is causing the failure. Given the error message, I wonder whether some policy regarding `.bat` files is related (the SASS compilation on windows is initiated by a `.bat` file).

**Comment by mcanouil** [comment]
I can't repro either on macOS using both stable or development version?

**Comment by cderv** [comment]
It seems exactly this issue. About the commands to run, more precisely you can follow the debug step I gave in this thread last time we encountered this issue: 
* https://github.com/quarto-dev/quarto-cli/discussions/6872#discussioncomment-7048221

Thanks!
