### ISSUE TITLE
Error: `Bad CPU type in executable` on MacOS with M2 CPU

### ISSUE THREAD

**Issue by RoyiAvital** [quarto-dev/quarto-cli#7099]
### Bug description

I am trying to compile a project on MacOS:
1. Installed `quarto` from ` quarto-1.3.450-macos.tar.gz` by extracting the files and adding the `bin` folder to path.
2. Made sure `quarto --version` works on terminal. 
3. Ran: `quarto preview /Users/royi/Courses/ImageProcessingPython/Lecture000.qmd --no-browser --no-watch-inputs`.
4. Got an error: `Bad CPU type in executable`.

The full error:

```zsh
ERROR: Theme file compilation failed:

/Users/royi/Applications/Quarto/bin/tools/dart-sass/sass: line 17: /Users/royi/Applications/Quarto/bin/tools/dart-sass/src/dart: Bad CPU type in executable

Error: Theme file compilation failed:

/Users/royi/Applications/Quarto/bin/tools/dart-sass/sass: line 17: /Users/royi/Applications/Quarto/bin/tools/dart-sass/src/dart: Bad CPU type in executable
    at dartCommand (file:///Users/royi/Applications/Quarto/bin/quarto.js:59894:15)
    at async dartCompile (file:///Users/royi/Applications/Quarto/bin/quarto.js:59856:5)
    at async compileWithCache (file:///Users/royi/Applications/Quarto/bin/quarto.js:60084:17)
    at async compileSass (file:///Users/royi/Applications/Quarto/bin/quarto.js:59946:12)
    at async revealTheme (file:///Users/royi/Applications/Quarto/bin/quarto.js:126672:17)
    at async Object.formatExtras (file:///Users/royi/Applications/Quarto/bin/quarto.js:126772:27)
    at async runPandoc (file:///Users/royi/Applications/Quarto/bin/quarto.js:79982:60)
    at async renderPandoc (file:///Users/royi/Applications/Quarto/bin/quarto.js:81044:26)
    at async Object.onRender (file:///Users/royi/Applications/Quarto/bin/quarto.js:86673:36)
    at async renderFiles (file:///Users/royi/Applications/Quarto/bin/quarto.js:86636:25)
```

The project works on Windows.

**Comment by mcanouil** [comment]
You downloaded the amd64 build while you need the arm64 build.
Currently, it's not part of the links provided as assets in each GitHub releases.

**Comment by RoyiAvital** [comment]
I see. So I need to wait for version `1.4` to be released.

Thanks!

**Comment by cscheid** [comment]
You need to download the 1.3 version with the correct architecture.

**Comment by mcanouil** [comment]
@cscheid The thing is it's not part of the assets for macOS.
Also, there is nothing stating that `quarto-1.3.450-macos.pkg` is amd64.
![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/d1c3eed4-2760-4cd3-9870-c35c36bc0f89)

**Comment by RoyiAvital** [comment]
@cscheid , There is only a single `tar.gz` for macOS on the current release (`1.3.450`).
Where can I find the one for ARM based M cpu's?

**Comment by cscheid** [comment]
Oof, I'm sorry. You're right. You'll need Rosetta instead.

**Comment by RoyiAvital** [comment]
OK.
I prefer waiting for version `1.4` which doesn't require Rosetta (At least according to the link by @mcanouil).

My main driver is Windows, so I will stick with it.
