### ISSUE TITLE
"quarto tools" docs/behaviour mismatch

### ISSUE THREAD

**Issue by barryrowlingson** [quarto-dev/quarto-cli#7286]
### Bug description

"quarto tools --help" says "Use 'quarto tools' with no arguments to show the status of all tools." but that doesn't work.

```
$ quarto tools --help

  Usage:   quarto tools <command> [tool]
  Version: 1.3.450                      

  Description:

    Installation and update of ancillary tools.                          
                                                                         
      tools:                                                             
        tinytex                                                          
        chromium                                                         
                                                                         
      commands:                                                          
        install                                                          
        uninstall                                                        
        update                                                           
                                                                         
    Use 'quarto tools' with no arguments to show the status of all tools.
```
but then:

```
$ quarto tools
ERROR: Missing argument(s): command

Error: Missing argument(s): command
    at Command.parseArguments (file:///opt/quarto-1.3.450/bin/quarto.js:8566:31)
    at Command.parseCommand (file:///opt/quarto-1.3.450/bin/quarto.js:8320:31)
    at async quarto (file:///opt/quarto-1.3.450/bin/quarto.js:127545:5)
    at async file:///opt/quarto-1.3.450/bin/quarto.js:127563:9
```

It looks like the tool status output can be returned by adding anything after the `quarto tools command

```
$ quarto tools buggy
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2023.10
```

### Steps to reproduce

Run "quarto tools --help" to show the text

Run "quarto tools" as suggested in the text to show the error.

### Expected behavior

It should do what it says in the help text, ie "Use 'quarto tools' with no arguments to show the status of all tools" so it should show the status of all tools.

### Actual behavior

Missing argument command and a JS error.
```
$ quarto tools
ERROR: Missing argument(s): command

Error: Missing argument(s): command
    at Command.parseArguments (file:///opt/quarto-1.3.450/bin/quarto.js:8566:31)
    at Command.parseCommand (file:///opt/quarto-1.3.450/bin/quarto.js:8320:31)
    at async quarto (file:///opt/quarto-1.3.450/bin/quarto.js:127545:5)
    at async file:///opt/quarto-1.3.450/bin/quarto.js:127563:9

```

### Your environment

Linux command line, 

Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

### Quarto check output

```
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto-1.3.450/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.1.0
      Kernels: ir, python3, python2

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.1
      Path: /opt/R-4.1.1/lib/R
      LibPaths:
        - /opt/R-4.1.1/lib/R/library
      knitr: 1.34
      rmarkdown: 2.11

[✓] Checking Knitr engine render......OK

```

**Comment by mcanouil** [comment]
Thanks for the report.
Unfortunately, Quarto CLI help pages are a bit outdated.
See also:
- #5421
