### ISSUE TITLE
Incorrect render to PDF using titlepage extension

### ISSUE THREAD

**Issue by dmkaplan2000** [quarto-dev/quarto-cli#7293]
### Bug description

When the document below is rendered, it fails because there is no line break between the header of the output LaTeX document and the content immediately after it, so `\begin{center}` gets placed on the last line of the header that contains LaTeX comments. I am not sure if this is a quarto bug or a `titlepage` extension bug.

If the initial content of the document is not a special environment, the document renders, but incorrectly, placing the first line of content on the same line as a LaTeX comment, essentially erasing the line

### Steps to reproduce

Try rendering this document:

````qmd
---
format: titlepage-pdf
---

::: {.center data-latex=""}
**ABSTRACT**
:::
````

### Expected behavior

Render should work

### Actual behavior

Render fails

### Your environment

- IDE: RStudio 2023.09.0 Build 463
- R: version 4.3.1 (2023-06-16)
- OS: Ubuntu 20.04.6 LTS

### Quarto check output

````bash
$ quarto check
Quarto 1.4.429
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.429
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2019

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: 4.6.3
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK

````

**Comment by cscheid** [comment]
If you can't reproduce this without titlepage, then I'd ask you to report it at the titlepage repo.

**Comment by cderv** [comment]
> I am not sure if this is a quarto bug or a titlepage extension bug.

I'll share with you below how I would look into such issue to know where it comes from and what should be done. Hopefully this will help you for next time you run into such an issue. 

First It would have been useful to post the error you get and provide a full reproducible example - **titlepage** extension is from community, and rendering your document requires to install it from somewhere... 

Anyhow this is what I get
````
ERROR: 
compilation failed- error
LaTeX Error: \begin{document} ended by \end{center}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.275 \end{center}
````

Which gives good clue on what happens. Especially, if you run `keep-tex: true` to look at the `.tex` - but when there is an error you don't need it because the `.tex` is not removed for you to look at the `.log` and other LaTeX renderering files. 

We can see this in the `.tex` file 
````latex
%%%%% end titlepage extension code\begin{center}
````

So this is clearly wrong as the `\begin{center}` is inside a comment. 

> If the initial content of the document is not a special environment, the document renders, but incorrectly, placing the first line of content on the same line as a LaTeX comment, essentially erasing the line

This is confirmed by your observation. 

So know you have found all this and no there is something with **titlepage** partials and how it is used inside Quarto and Pandoc. Partials syntax is a bit special and especially this (https://pandoc.org/MANUAL.html#partials) 

> Final newlines are omitted from included partials. 

Overall, this happens because the extention's partial is ending with a comment. 
https://github.com/nmfs-opensci/quarto_titlepages/blob/ad9c0b1c8f8a9053610a899b56bcc28983e70c3f/_extensions/titlepage/before-body.tex#L38
This would be easily fix in **titlepage** by adding another new line. 

You can try it yourself by modifying `_extensions/nmfs-opensci/titlepage/before-body.tex` 

Hope it helped understand the process you can apply to your own debugging. Sharing a deep debugging report is always welcome as developer only need to apply the fix. You should open an issue in **titlepage** package (or even a PR). 

I'll close this here.

**Comment by cderv** [comment]
For those interested, just sharing more technical explanation about this _strange_ behavior of partials and how it impacts the Pandoc's template system.  This will serve as note for later

Take this  template file called `test.txt`
````
$a$
$b$
````
and use it with variables to fill 
````
> quarto pandoc --template test.txt -V a:A -V b:B --metadata title="required"
not used
^Z
A
B
````
You'll get a new line. 

Now use a partials 
````
$partials.txt()$
$b$
````

and `partials.txt` being
````
$a$
````

Render this 
````
> quarto pandoc --template test.txt -V a:A -V b:B --metadata title="required"
not used
^Z
AB
````

No newline (🤯) - this prone to error when creating partials from a template file. 

Adding the newline in the partials solves it 
````
$a$

````
which gives now
````
> quarto pandoc --template test.txt -V a:A -V b:B --metadata title="required"
not used
^Z
A
B
````

**Comment by eeholmes-uw** [comment]
@cderv @cscheid I am pretty sure this is a Quarto 1.4 (pre-release) bug. All the partials in the titlepage-pdf extension have newlines at the end. I was able to reproduce the behavior by installing the Quarto pre-release 1.4.433. While the stable release works fine.

I will see if I can whip up a repro wo titlepage-pdf extension.

**Comment by cscheid** [comment]
@eeholmes-uw Thanks for the added context. It's totally possible that it's indeed a 1.4 bug! It's just hard for us to debug multiple moving parts!

I do have a sneaking suspicion about what might be going on. I have made some changes to LaTeX rendering to be more careful about not adding linebreaks where they don't belong, and it might be too aggressive.

I wonder what happens if you add a `%` to the last line by itself, simply to have some content after the newlines?

**Comment by eeholmes-uw** [comment]
@cscheid Here is a repro:

before-body.tex (notice newline AND %%% in the line before the end)
```
\begin{center}
Hello
\end{center}

%%%%%%%%% The end

```

Quarto file
```
---
format:
  pdf:
    template-partials:
      - "before-body.tex"
---

::: {.center data-latex=""}
**ABSTRACT**
:::
```

**Comment by eeholmes-uw** [comment]
However adding 2 newlines instead of one fixes the error. So the new Quarto is just stripping one newline from `before-body.tex` not all of the newlines.

This `before-body.tex` works.
```
\begin{center}
Hello
\end{center}

%%%%%%%%% The end


```

**Comment by dmkaplan2000** [comment]
> @cderv @cscheid I am pretty sure this is a Quarto 1.4 (pre-release) bug. All the partials in the titlepage-pdf extension have newlines at the end. I was able to reproduce the behavior by installing the Quarto pre-release 1.4.433. While the stable release works fine.
> 
> I will see if I can whip up a repro wo titlepage-pdf extension.
> 
> Note if you look at `before-body.tex` on GitHub, it appears that there is no newline, but there is in fact a blank newline. The GitHub UI "helpfully" doesn't show extra newlines at the bottom of files. Sigh. But they are in fact there which you can confirm by cloning and looking at the files locally.

I am glad someone with more expertise chimed in. I had started noticing this using 1.3 versions of quarto on some machines and 1.4 on others, but was hesitating whether to report it as I wasn't 100% sure where the error was coming from.

**Comment by cderv** [comment]
> However adding 2 newlines instead of one fixes the error.

Thanks for the additional information @eeholmes-uw. I was definitely not clear enough in my previous answer but that is what I meant by adding newlines in the template. It was one more newlines which pandoc expect... sorry for being unclear. 

> So the new Quarto is just stripping one newline from before-body.tex not all of the newlines.

Though I did not notice the Quarto 1.3 was modifying the pandoc behavior by keeping the newline. I don't think it is stripping but just no more adding newlines. As mentioned Pandoc is not considering newlines the same when used in main template or in partial template. And this has not changed between the two pandoc version including in Quarto 1.3 and 1.4.

@cscheid I'll let you handle it regarding the linebreak change you've made. 

I believe current 1.4 behavior is the same at what Pandoc is doing if you were to use the partial with it directly.

**Comment by cscheid** [comment]
> @cscheid I'll let you handle it regarding the linebreak change you've made.
> 
> I believe current 1.4 behavior is the same at what Pandoc is doing if you were to use the partial with it directly.

I don't really like the current behavior, even if it's more consistent with Pandoc. And, to our usual policy, "we don't regress on behavior". This feels to me more like a regression than a bugfix, even if the 1.4 behavior is closer to that of Pandoc.

**Comment by cscheid** [comment]
I don't think this is coming from my change, but some other pandoc change that has happened in the meantime. The change I was talking about was in the Lua filters, but this bug is coming entirely from Pandoc's template expansion, as best as I can tell.

I'm not entirely sure about the best way to do this, but a _simple_ workaround is to add a line break right after `$before-body.tex()$` in our [`template.tex`](https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/pdf/pandoc/template.tex).
