### ISSUE TITLE
Kepler.gl Jupyter widget does not render automatically

### ISSUE THREAD

**Issue by oneextrafact** [quarto-dev/quarto-cli#7469]
### Bug description

I have a Jupyter kepler.gl widget embedded in an .ipynb: 

```
import keplergl
the_map = keplergl.KeplerGl(height=800)
the_map.add_data(df[~pd.isnull(df["LATITUDE"])][["LONGITUDE", "LATITUDE"]])
the_map
```

when I render using Quarto, the map itself does not render. As a workaround, I can call the save_to_html method of the map

```
the_config = the_map.config
the_map.save_to_html(data=the_map.data, config=the_config)
```

and then use an iframe to hold the map, which does then render. It would be great if it just rendered without the workaround though. 

### Expected behavior

Kepler.gl widget should render without needing a workaround. 

### Actual behavior

Kepler.gl widget does not render. 

### Your environment

- IDE: VS Code

### Quarto check output

```bash
Quarto 1.4.468
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.468
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9
      Path: /Users/davidgallagher/.pyenv/versions/3.10.9/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
I think this is a keplergl bug. I'm not sure how keplergl works internally, but the issue appears to be that they don't record enough information in the .ipynb file for us to be able to do anything about it.

You can check this with `jupyter lab` itself by saving an ipynb and reopening it without re-executing the cell. You get this:

<img width="545" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/b71d5476-559f-46dd-8cb4-afb5d131220b">

In order for quarto to be able to do something useful, we need that information in the .ipynb, in the same way that jupyter lab needs that. 

Contrast this with, for example, plotly charts, which produce this output in the .ipynb:

````
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "12e4a522-7a95-419a-be82-114057052dcd",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "        <script type=\"text/javascript\">\n",
       "        window.PlotlyConfig = {MathJaxConfig: 'local'};\n",
       "        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n",
       "        if (typeof require !== 'undefined') {\n",
       "        require.undef(\"plotly\");\n",
       "        define('plotly', function(require, exports, module) {\n",
       "            /**\n",
       "* plotly.js v2.18.2\n",
       "* Copyright 2012-2023, Plotly, Inc.\n",
       "* All rights reserved.\n",
       "* Licensed under the MIT license\n",
       "*/\n",
       "/*! For license information please see plotly.min.js.LICENSE.txt */\n",
       "!function(t,e){\"object\"==typeof exports&&\"object\"==typeof module?module.exports=e():\"function\"==typeof define&&define.amd?define([],e):\"object\"==typeof exports?exports.Plotly=e():t.Plotly=e()}(self,(function(){return function(){var t={98847:function(t,e,r){\"use strict\";var n=r(71828),i={\"X,X div\":'direction:ltr;font-family:\"Open Sans\",verdana,arial,sans-serif;margin:0;padding:0;',\"X input,X button\":'font-family:\"Open Sans\",verdana,arial,sans-serif;',\"X input:focus,X button:focus\":\"outline:none;\",\"X a\":\"text-decoration:none;\",\"X a:hover\":\"text-decoration:none;\",\"X .crisp\":\"shape-rendering:crispEdges;\",\"X .user-select-none\":\"-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;\",\"X svg\":\"overflow:hidden;\",\"X svg a\":\"fill:#447adb;\",\"X svg a...
````

You'll need to file this with keplergl developers.
