### ISSUE TITLE
Blank lines in fenced code blocks within a list don't render

### ISSUE THREAD

**Issue by dijitali** [quarto-dev/quarto-cli#7498]
### Bug description

Using blank lines within a code block that's nested in a list prevents the code block being formatted:

![image](https://github.com/quarto-dev/quarto-cli/assets/4665045/5b14ecc2-a0bf-4527-aef7-fcb9c1ae8152)

Workarounds:

1. Use indented code blocks instead of fenced (without syntax highlighting)
2. Add an empty comment (e.g. `#` for shell scripts) instead of a blank line

### Steps to reproduce

```qmd
---
title: "Example Document"
---

1. Do this first
1. The second step:

    ```bash
sudo apt-get update
sudo apt-get install -y curl

echo 'foo'
    ```

1. Then this

```

### Expected behavior

Code block should render with a blank line:
![image](https://github.com/quarto-dev/quarto-cli/assets/4665045/bd44ac2e-5ccb-4b87-b1db-699bada4463b)


### Actual behavior

Code block is rendered as regular text:
![image](https://github.com/quarto-dev/quarto-cli/assets/4665045/5b14ecc2-a0bf-4527-aef7-fcb9c1ae8152)

### Your environment

- IDE: VSCode 1.84.1
- OS: macOS Sonoma 14.1

### Quarto check output

```text
Quarto 1.4.487
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.487
      Path: /Users/ieuan/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ieuan/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.1
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Users/ieuan/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Users/ieuan/Applications/quarto/share/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
You need to indent your code block correctly:

````
---
title: "Example Document"
---

1. Do this first
1. The second step:

   ```bash
   sudo apt-get update
   sudo apt-get install -y curl
   
   echo 'foo'
   ```

1. Then this
````

**Comment by dijitali** [comment]
🤦  thanks, not sure how I'd missed that
