### ISSUE TITLE
[Smoke Test] Lua `internal_error()` not defined when used in filter

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7571]
We have failure in CI (https://github.com/quarto-dev/quarto-cli/actions/runs/6846281517/job/18612687069#step:23:3533
) due to this test (https://github.com/quarto-dev/quarto-cli/blob/e99d2c0082ec96bc2c2949d8180a880adb9ad623/tests/docs/smoke-all/2023/10/30/7424.qmd) which run a Lua filter (https://github.com/quarto-dev/quarto-cli/blob/e99d2c0082ec96bc2c2949d8180a880adb9ad623/tests/docs/smoke-all/2023/10/30/7424.lua)

```
7424.lua:4: attempt to call a nil value (global 'internal_error')
```

@cscheid I am not sure how this is supposed to work, but it seems that `internal_error()` function is not available by default in filter 

Try 
````
---
filters:
  - error.lua
---
````

With `error.lua` being 

````lua
function Pandoc(doc)
        internal_error()
end
````

Trying to render will give 

`````
Error running filter C:/Users/chris/Documents/DEV_R/quarto-cli/src/resources/filters/main.lua:
error.lua:2: attempt to call a nil value (global 'internal_error')
stack traceback:
        [C]: in ?
        [C]: in method 'walk'
        ...R/quarto-cli/src/resources/filters/./ast/customnodes.lua:86: in local 'checked_walk'
        ...R/quarto-cli/src/resources/filters/./ast/customnodes.lua:138: in function 'run_emulated_filter'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:82: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:95: in upvalue 'run_emulated_filter_chain'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:133: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:130>
stack traceback:
        ...R/quarto-cli/src/resources/filters/./ast/customnodes.lua:86: in local 'checked_walk'
        ...R/quarto-cli/src/resources/filters/./ast/customnodes.lua:138: in function 'run_emulated_filter'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:82: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:95: in upvalue 'run_emulated_filter_chain'
        .../quarto-cli/src/resources/filters/./ast/runemulation.lua:133: in function <.../quarto-cli/src/resources/filters/./ast/runemulation.lua:130>
ERROR: Error
    at renderFiles (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-shared.ts:99:18)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:213:26)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:155:3)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:186:5
````

Is this a test to adapt following the new `at` config below `filters` or something else ?

**Comment by cderv** [comment]
Oh ok. It was not obvious - as `internal_error()` is indeed define in `error.lua`. I thought is was not loaded. 

So this means we have an issue in this 7424.qmd test... 🤔

**Comment by cscheid** [comment]
@cderv Did this issue get sorted out?

**Comment by cderv** [comment]
Yes it seems so. It was possibly transient somehow in our CI runs. 

Not reproducible locally either so let's close. I'll watch out it if happens again in CI in the future
