### ISSUE TITLE
two panel plot fails without subcaps with docx output

### ISSUE THREAD

**Issue by matthewfinkbeiner** [quarto-dev/quarto-cli#7617]
### Bug description

A two panel plot fails if there isn't a subcaption for each plot

### Steps to reproduce

This works:

````markdown
---
title: "test"
format: docx
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      dev = "png",
                      fig.width = 12,
                      fig.height = 10)

```
## Two Figures

```{r}
#| label: fig-twopanel
#| layout-ncol: 2
#| fig-cap: "Two figs side by side"
#| fig-subcap: 
#| - "plot 1"
#| - "plot 2"
library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)

```

````

This does not work:

````markdown
---
title: "test"
format: docx
editor: visual
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      dev = "png",
                      fig.width = 12,
                      fig.height = 10)

```


## Two Figures

```{r}
#| label: fig-twopanel
#| layout-ncol: 2
#| fig-cap: "Two figs side by side"

library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)

```
````

### Expected behavior

It would be nice to print a two-panel figure with a single fig-cap

### Actual behavior

````
FATAL (C:/Users/MFINKB~1/AppData/Local/Programs/Quarto/share/filters/main.lua:19555) An error occurred:
This is an internal error. Please file a bug report at https://github.com/quarto-dev/quarto-cli/
Error running filter C:/Users/MFINKB~1/AppData/Local/Programs/Quarto/share/filters/main.lua:
...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:2210: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:1798: in function 'fail'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:1803: in function 'internal_error'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:19555: in function 'decorate_caption_with_crossref'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:17071: in field 'render'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:816: in local 'filter_fn'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:283: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:273>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:205: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:195>
	(...tail calls...)
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:917: in local 'callback'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:932: in upvalue 'run_emulated_filter_chain'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:968: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:965>
stack traceback:
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:205: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:195>
	(...tail calls...)
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:917: in local 'callback'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:932: in upvalue 'run_emulated_filter_chain'
	...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:968: in function <...B~1/AppData/Local/Programs/Quarto/share/filters/main.lua:965>
````

### Your environment

````R
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8    LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                       LC_TIME=English_Australia.utf8    

time zone: Australia/Sydney
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] data.table_1.14.8      lubridate_1.9.3        forcats_1.0.0          stringr_1.5.0          dplyr_1.1.3            purrr_1.0.2            readr_2.1.4            tidyr_1.3.0           
 [9] tibble_3.2.1           tidyverse_2.0.0        haven_2.5.3            sjlabelled_1.2.0       MatchIt_4.5.5          ggnewscale_0.4.9       ggpattern_1.0.1        svglite_2.1.2         
[17] DBI_1.1.3              odbc_1.3.5             keyring_1.3.1          quarto_1.3             markdown_1.11          rmarkdown_2.25         officer_0.6.3          ggbump_0.1.0          
[25] patchwork_1.1.3        ggplot2_3.4.4          broom.mixed_0.2.9.4    flextable_0.9.4        rstudioapi_0.15.0      fortunes_1.5-4         showtext_0.9-6         showtextdb_3.0        
[33] sysfonts_0.8.8         marginaleffects_0.16.0 cobalt_4.5.1           pander_0.6.5           performance_0.10.8     pacman_0.5.1      
````
### Quarto check output
````
C:\Users\mfinkbeiner\Documents\PSDES\2022>quarto check
Quarto 1.4.504
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.504
      Path: C:\Users\mfinkbeiner\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

[>] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\mfinkbeiner\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

(/) Checking R installation...........Loading required package: pacman
[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/mfinkbeiner/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK


C:\Users\mfinkbeiner\Documents\PSDES\2022>
````

**Comment by mcanouil** [comment]
Thanks for the report!

Please format your post to be legible, use code blocks, "/details" commands, etc.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by cderv** [comment]
I think we have several topics / issues here based on what I see in the intermediate markdown. 

<details>
<summary>Intermediate .md</summary>

````markdown

::: {.cell layout-ncol="2"}

```{.r .cell-code}
library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)
```

::: {.cell-output-display}
![Two figs side by side](index_files/figure-html/fig-twopanel-1.png){#fig-twopanel-1 width=672}
:::

::: {.cell-output-display}
![Two figs side by side](index_files/figure-html/fig-twopanel-2.png){#fig-twopanel-2 width=672}
:::
:::

````

</details>



## The main issue: Layout Figures fails in Docx

This simple example will create the issue see above 

````markdown
---
title: "Test"
format: docx
keep-md: true
---


::: {layout-ncol="2"}

![placehold](https://placehold.co/400){#fig-place-2}

![placehold](https://placehold.co/400){#fig-place-1}

:::

````

<details>
<summary>Lua Error</summary>

```lua
Error running filter C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/resources/filters/main.lua:
...~1/DEV_R/QUARTO~2/src/resources/filters/./common/log.lua:30: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
	.../DEV_R/QUARTO~2/src/resources/filters/./common/error.lua:14: in function 'fail'
	.../DEV_R/QUARTO~2/src/resources/filters/./common/error.lua:19: in function 'internal_error'
	...2/src/resources/filters/./customnodes/floatreftarget.lua:117: in function 'decorate_caption_with_crossref'
	...1/DEV_R/QUARTO~2/src/resources/filters/./layout/docx.lua:36: in field 'render'
	...~1/DEV_R/QUARTO~2/src/resources/filters/./ast/render.lua:45: in local 'filter_fn'
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:164: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:154>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:86: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:76>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:82: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:97: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:133: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:130>
stack traceback:
	...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:86: in function <...V_R/QUARTO~2/src/resources/filters/./ast/customnodes.lua:76>
	(...tail calls...)
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:82: in local 'callback'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:97: in upvalue 'run_emulated_filter_chain'
	..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:133: in function <..._R/QUARTO~2/src/resources/filters/./ast/runemulation.lua:130>
ERROR: Error
    at renderFiles (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderProject (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/project.ts:268:23)
    at async renderForPreview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:436:24)
    at async render (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:167:22)
    at async preview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:184:18)
    at async Command.fn (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/cmd.ts:415:7)
    at async Command.execute (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:155:3)
    at async file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/quarto.ts:186:5
```


</details>

## Second one : **knitr** output for multiple figures

Here is the behavior for figures creation with cell options: 

* `fig-cap` does not create subfigures.
	* If one fig cap only but multiple figure in cell, then it is recycled and applied on each one
* Subfigures are triggered when `fig-subcap` is passed, even if empty, which can be done by `fig.subcap: true`. 
	* If not `fig-subcap`, then no subfigures

Examples: 

Setting `fig-cap` only does not create subfigures. 

<table>
<tr>
 <td> knitr
 <td> md result 
<tr>
 <td>

````
```{r}
#| label: fig-twopanel
#| echo: false
#| layout-ncol: 2
#| fig-cap: "Two figs side by side"

library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)

```
````

 <td>

````markdown
::: {.cell layout-ncol="2"}
::: {.cell-output-display}
![Two figs side by side](index_files/figure-html/fig-twopanel-1.png){#fig-twopanel-1 width=672}
:::

::: {.cell-output-display}
![Two figs side by side](index_files/figure-html/fig-twopanel-2.png){#fig-twopanel-2 width=672}
:::
:::

````
</table>

You need to add fig-subcap to have a main caption for the whole block

<table>
<tr>
 <td> knitr
 <td> md result 

<tr>
 <td>

````
```{r}
#| label: fig-twopanel
#| echo: false
#| layout-ncol: 2
#| fig-cap: "Two figs side by side"
#| fig-subcap: true

library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)

```


````

 <td>

````markdown
::: {#fig-twopanel .cell layout-ncol="2"}
::: {.cell-output-display}
![](index_files/figure-html/fig-twopanel-1.png){#fig-twopanel-1 width=672}
:::

::: {.cell-output-display}
![](index_files/figure-html/fig-twopanel-2.png){#fig-twopanel-2 width=672}
:::

Two figs side by side
:::

````
</table>

Note that the latter does work in Docx:

````markdown
---
title: "test"
format: docx
keep-md: true
editor: visual
---


## Two Figures

```{r}
#| label: fig-twopanel
#| echo: false
#| layout-ncol: 2
#| fig-cap: "Two figs side by side"
#| fig-subcap: true

library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)

```
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/2c946daa-b6a0-41eb-a1fe-4f60c407dd5c)


Hope it helps understand

**Comment by cscheid** [comment]
```
---
title: "Test"
format: docx
keep-md: true
---


::: {layout-ncol="2"}

![placehold](https://placehold.co/400){#fig-place-2}

![placehold](https://placehold.co/400){#fig-place-1}

:::
```

I think we fixed this - I can no longer reproduce the crash here.

**Comment by matthewfinkbeiner** [comment]
It no longer throws an error, but it is not behaving as expected.  Now the fig caption, which should be a single caption, appears twice as two sub-captions.

````
---
title: "test"
format: docx
editor: visual
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      dev = "png",
                      fig.width = 12,
                      fig.height = 10)

```


## Two Figures

This works as expected, and as documented here: https://quarto.org/docs/authoring/figures.html#subcaptions

```{r}
#| label: fig-twopanel_1
#| layout-ncol: 2
#| fig-cap: "This should only appear once"
#| fig-subcap: 
#|   - "first subcap"
#|   - "second subcap"

library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)

```

This no longer throws an error, but it is not as expected.  The figure caption, which is meant to appear as a single caption for both figures, appears twice as two sub-captions.

```{r}
#| label: fig-twopanel_2
#| layout-ncol: 2
#| fig-cap: "This should only appear once"

library(ggplot2)
p<- ggplot(mpg, aes(displ, cty, color = manufacturer)) +
  geom_point()

pp<- ggplot(mpg, aes(displ, hwy, color = manufacturer)) +
  geom_point()

plot(p)
plot(pp)

```

````

**Comment by cscheid** [comment]
I'm going to go ahead and close this one, but please reopen if you think @cderv's comment doesn't fix the bug.
