### ISSUE TITLE
Formatting backticks as code does not work in Typst format

### ISSUE THREAD

**Issue by stephan-koenig** [quarto-dev/quarto-cli#7688]
### Bug description

Formatting backticks as code does not work in Typst format

### Steps to reproduce

Reprex Quarto `test.qmd` document:

``````qmd
---
title: "Test"
format: typst
---

`````{=typst}
This works ``` ` ```.
`````

But this does not work ``` ` ```.

``````

Render command (here in bash):

````bash
quarto render test.qmd
````

### Expected behavior

Format backticks as code.

### Actual behavior

`quarto render` generates error message (same results in RStudio):

```
pandoc 
  to: typst
  output-file: test.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Test
  
[typst]: Compiling test.typ to test.pdf...error: content does not contain field "block"
   ┌─ test.typ:27:8
   │
27 │   if it.block {
   │         ^^^^^

help: error occurred while applying show rule to this raw
    ┌─ test.typ:237:24
    │
237 │ But this does not work #raw("`").
    │                         ^^^^^^^^
```

### Your environment

- IDE: RStudio 2023.09.1+494
- OS: macOS Sonoma 14.1.1 (23B81)

### Quarto check output

```
Quarto 1.4.510
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.510
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.01
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/stephan/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13 (Conda)
      Path: /Users/stephan/Library/r-miniconda/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
````
[typst]: Compiling test.typ to test.pdf...error: content does not contain field "block"
   ┌─ test.typ:27:8
   │
27 │   if it.block {
   │         ^^^^^
````

I believe this comes from our own addition 

https://github.com/quarto-dev/quarto-cli/blob/7fe97bed52d78f0d2e6ac143bc630c3d2408f055/src/resources/formats/typst/pandoc/quarto/definitions.typ#L24-L32

We need to check for existence maybe - not sure what this typst syntax is doing, so I'll look it up

**Comment by cderv** [comment]
Ok I believe this comes from the fact that the markdown syntax differs when using `` ` `` 
````
> pandoc --from markdown --to typst
`` a ``
^Z
`a`
> pandoc --from markdown --to typst
`` ` ``
^Z
#raw("`")
````

In the later case, `#raw` is used directly, while usually Pandoc will use backtick notation in typst too (https://typst.app/docs/reference/text/raw/#syntax). In the case where backticks is used, `block` argument of `#raw` is set, but otherwise it is not. 

Pandoc could have written this 
````
``` ` ```
````
and it would work, but `#raw` is used in this case specifically 
https://github.com/jgm/pandoc/blob/a2a0f73eb816917839eeffad9e487394ebd88443/src/Text/Pandoc/Writers/Typst.hs#L246 (from https://github.com/jgm/pandoc/commit/cd6b3bde622c93eea763e981692b4bc53dd5e5df) 

Any usage of `#raw()` that do no set `block` field will be create a Quarto error. 

Pandoc will also use `#raw` for when a  language is set on inline for Highlighting 

````markdown
---
title: "Test"
format: 
  typst: default
  html: default
keep-md: true
keep-typ: true
---

This should be highlighted ``` <div> ```{.html}.

````

See results in HTML - it highlights. When rendering to typst, 
````  
[typst]: Compiling index.typ to index.pdf...error: content does not contain field "block"
   ┌─ \\?\C:\Users\chris\Documents\DEV_OTHER\DEMOS\test-quarto\index.typ:27:8
   │
27 │   if it.block {
   │         ^^^^^

help: error occurred while applying show rule to this raw
    ┌─ \\?\C:\Users\chris\Documents\DEV_OTHER\DEMOS\test-quarto\index.typ:236:28
    │
236 │ This should be highlighted #raw(lang:"html", "<div>").
    │                             ^^^^^^^^^^^^^^^^^^^^^^^^^

ERROR: Error
    at Object.complete (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/output-typst.ts:70:13)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render.ts:281:23
    at async withTimingAsync (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/core/timing.ts:50:20)
    at async Object.complete (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render.ts:276:7)
    at async Object.onPostProcess (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-files.ts:711:28)
    at async renderFileInternal (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-files.ts:680:3)
    at async renderFiles (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/render-files.ts:321:9)
    at async renderProject (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/render/project.ts:268:23)
    at async renderForPreview (file:///C:/Users/chris/DOCUME~1/DEV_R/QUARTO~2/src/command/preview/preview.ts:436:24)
````

Same error ! 

This is because the typ produced is 
````typst
#raw(lang:"html", "<div>")
````

So we need to fix our code.
