### ISSUE TITLE
Typst example wont render

### ISSUE THREAD

**Issue by a0th** [quarto-dev/quarto-cli#7708]
### Bug description

Render or preview of typst document doesnt work.

### Steps to reproduce

Trying to render this document:

```
---
title: "My document"
format: typst
---

Hello, typst!
```
with both `quarto render example.qmd` and `quarto preview example.sql` yield same outputs

### Expected behavior

Quarto should generate a new pdf

### Actual behavior

This error happens:

```
ERROR: Unable to render example.qdm

Stack trace:
    at fileExecutionEngineAndTarget (file:///opt/quarto/bin/quarto.js:40957:15)
    at renderContexts (file:///opt/quarto/bin/quarto.js:71584:38)
    at renderFormats (file:///opt/quarto/bin/quarto.js:71635:28)
    at file:///opt/quarto/bin/quarto.js:97274:30
    at Command.fn (file:///opt/quarto/bin/quarto.js:97278:11)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8095:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:113774:5)
    at async file:///opt/quarto/bin/quarto.js:113792:9
```

### Your environment

Ubuntu WLS, running commands on CLI.

### Quarto check output

```
Quarto 1.4.510
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.510
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.05
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/nilo/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0 (Conda)
      Path: /home/nilo/miniconda3/envs/plotly/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
```

**Comment by mcanouil** [comment]
The error messages shows a typo in the extension for the file.
Why are run running Quarto on an SQL file?

**Comment by a0th** [comment]
Sorry, dont know where that .sql came from. But its a typing error when I was creating the ticket. The file is indeed called example.qmd, and the error message is from it.

```
$ quarto render example.qdm 
ERROR: Unable to render example.qdm

Stack trace:
    at fileExecutionEngineAndTarget (file:///opt/quarto/bin/quarto.js:40957:15)
    at renderFileInternal (file:///opt/quarto/bin/quarto.js:76545:42)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:76492:17)
    at async render (file:///opt/quarto/bin/quarto.js:81237:21)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:81357:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8095:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:113774:5)
    at async file:///opt/quarto/bin/quarto.js:113792:9
 ```

**Comment by mcanouil** [comment]
Still the error message shows
example.dqm

**Comment by a0th** [comment]
Omg, sorry =|
