### ISSUE TITLE
Div with layout-ncol and captioned images results in malformed .typ

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7808]
### Bug description

Using captions on images inside a div with a `layout-ncol` attribute results in an error on render to typst.

### Steps to reproduce

````qmd
---
title: figures
format: typst
keep-typ: true
---

::: {layout-ncol=2}

![Caption](elephant.png)

![Caption](elephant.png)

::: 
````

### Expected behavior

Something like this:
<img width="525" alt="Screenshot 2023-12-06 at 12 55 43 PM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/b69198d9-6069-4059-a0fd-6552dae10410">

### Actual behavior

I get an error:
```
2023-12-04/typst $ quarto render figures.qmd 
pandoc 
  to: typst
  output-file: figures.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: figures
  
[typst]: Compiling figures.typ to figures.pdf...error: unclosed delimiter
    ┌─ figures.typ:246:5
    │
246 │ #grid(
    │      ^

error: unclosed delimiter
    ┌─ figures.typ:249:26
    │
249 │ ], caption: figure.caption(
    │                           ^

error: unclosed delimiter
    ┌─ figures.typ:307:5
    │
307 │ #grid(
    │      ^

error: unclosed delimiter
    ┌─ figures.typ:310:26
    │
310 │ ], caption: figure.caption(
    │                           ^

ERROR: Error
    at Object.complete (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/output-typst.ts:79:13)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render.ts:281:23
    at async withTimingAsync (file:///Users/wickhamc/Documents/posit/quarto-cli/src/core/timing.ts:50:20)
    at async Object.complete (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render.ts:276:7)
    at async Object.onPostProcess (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render-files.ts:711:28)
    at async renderFileInternal (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render-files.ts:680:3)
    at async renderFiles (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render-files.ts:321:9)
    at async render (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render-shared.ts:99:18)
    at async Command.fn (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/cmd.ts:213:26)
```

### Your environment

- OS: Mac Sonoma 14.0

### Quarto check output

Currently, ends in an error, no idea if it is related:
```bash
$ quarto check
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/wickhamc/Documents/posit/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/wickhamc/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
      Jupyter: 5.5.0
      Kernels: ir, julia-1.9, python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Users/wickhamc/Documents/posit/quarto-cli/src/resources/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Users/wickhamc/Documents/posit/quarto-cli/src/resources/jupyter/notebook.py", line 17, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK

ERROR: Error
    at renderFiles (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/render/render-shared.ts:99:18)
    at async checkJupyterRender (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/check/check.ts:279:18)
    at async file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/check/check.ts:239:11
    at async withSpinner (file:///Users/wickhamc/Documents/posit/quarto-cli/src/core/console.ts:81:12)
    at async checkJupyterInstallation (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/check/check.ts:235:9)
    at async check (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/check/check.ts:59:7)
    at async Command.fn (file:///Users/wickhamc/Documents/posit/quarto-cli/src/command/check/cmd.ts:34:5)
    at async Command.execute (file:///Users/wickhamc/Documents/posit/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
```

**Comment by cscheid** [comment]
Thanks. PR incoming.
