### ISSUE TITLE
shortcode error provides no context

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#7881]
### Bug description

Either of these options (missing quote) anywhere in a project produces an error without any context.

```markdown
{{< include "something.qmd >}}
{{< include something.qmd" >}}
```

```
ERROR: invalid shortcode: include "something.qmd
ERROR: invalid shortcode: include something.qmd"
```

The error is accompanied with a stack trace:

```
Stack trace:
    at parseShortcodeCapture (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:37452:15)
    at parseShortcode (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:37462:21)
    at isBlockShortcode (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:37402:16)
    at breakQuartoMd (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:37565:32)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async handleLanguageCells (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:40262:22)
    at async renderContexts (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:71819:43)
    at async Object.renderFormats (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:71837:22)
    at async readBaseInputIndex (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:72974:21)
    at async inputTargetIndex (file:///Users/aron/Downloads/quarto-1.4.518/bin/quarto.js:72962:19)
```

This happens during a `quarto render` operation before it has emitted any of the filenames.

### Steps to reproduce

Toss the include shortcode with a missing quote somewhere in a Quarto project (website) then render that project.

### Expected behavior

The error includes information about which file contains the problem.

### Quarto check output

```
Quarto 1.4.518
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.518
      Path: /Users/aron/Downloads/quarto-1.4.518/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This is the error message now. It's a little overeager but at least it's informative:

ERROR: Invalid Shortcode: In file 7881.qmd (5:1):
invalid shortcode: include "something.qmd
