### ISSUE TITLE
Deno options not passed under windows

### ISSUE THREAD

**Issue by regob** [quarto-dev/quarto-cli#7969]
### Bug description

I would like to pass arguments to the deno engine, because I recieve a js error when rendering a document:
```
ERROR: RangeError: Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at countTicks (file:///C:/Program%20Files/Quarto/bin/quarto.js:53014:17)
    at ticksForCode (file:///C:/Program%20Files/Quarto/bin/quarto.js:53017:27)
    at mdFormatOutput (file:///C:/Program%20Files/Quarto/bin/quarto.js:54017:19)
    at mdHtmlOutput (file:///C:/Program%20Files/Quarto/bin/quarto.js:54024:12)
    at mdOutputDisplayData (file:///C:/Program%20Files/Quarto/bin/quarto.js:53916:20)
    at mdFromCodeCell (file:///C:/Program%20Files/Quarto/bin/quarto.js:53822:35)
    at jupyterToMarkdown (file:///C:/Program%20Files/Quarto/bin/quarto.js:53308:34)
    at async Object.execute (file:///C:/Program%20Files/Quarto/bin/quarto.js:55313:25)
    at async renderExecute (file:///C:/Program%20Files/Quarto/bin/quarto.js:86470:27)
    at async renderFiles (file:///C:/Program%20Files/Quarto/bin/quarto.js:86593:51)
```

This error can be resolved by increasing v8 engine's stack size: [see SO](https://stackoverflow.com/questions/76497555/quarto-julia-stack-size-exceeded-error-on-macos).
On a **Linux** system I am able to pass arguments by setting the following environment variable:
```bash
export QUARTO_DENO_EXTRA_OPTIONS=--v8-flags=--stack-size=10000
```

On a **Windows** system, however, the options defined in this variable do not get passed to deno (see below).

### Steps to reproduce

Try to render any document to html with setting the `QUARTO_DENO_EXTRA_OPTIONS` environment variable:

```powershell
PS> $Env:QUARTO_DENO_EXTRA_OPTIONS = "--v8-flags=--invalid-argument"
PS> quarto render .\quarto_bug.qmd
```
Example `quarto_bug.qmd` file:

````
---
format: html
---

```{python}
print('Hello world')
```
````

### Expected behavior

The `deno` engine should raise an error if it sees the argument:
```powershell 
PS> ./deno run --v8-flags="--invalid-argument" -
error: V8 did not recognize flag '--invalid-argument'

For a list of V8 flags, use '--v8-flags=--help'
```

Under a Linux system (WSL) this is exactly what happens:
```bash
$ export $QUARTO_DENO_EXTRA_OPTIONS="--v8-flags=--invalid-argument"
$ quarto render quarto_bug.qmd --to html
error: V8 did not recognize flag '--invalid-argument'

For a list of V8 flags, use '--v8-flags=--help'
```

### Actual behavior

On Windows the document is rendered without deno crashing (which means the options were not passed).  Probably the content of the environment variable is overwritten inside Quarto.

### Your environment

- OS: Windows 10

### Quarto check output

```bash
> quarto check
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: C:/Users/ebogrer/AppData/Local/miniforge3/python.exe
      Jupyter: 5.3.1
      Kernels: exp, python3, ir

(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/Users/ebogrer/AppData/Local/Programs/R/R-4.3.0
      LibPaths:
        - C:/Users/ebogrer/AppData/Local/Programs/R/R-4.3.0/library
      knitr: 1.43
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
```

**Comment by dragonstyle** [comment]
Can you give this a try using Quarto 1.4 pre-release? Support on windows for these extra options was added post Quarto 1.3...

**Comment by regob** [comment]
Thank you @dragonstyle, it works with Quarto 1.4.529 on Windows too!

**Comment by MisterBiggs** [comment]
Seeing what appears to be the same error when plotting a large (20,000 points) amount of data using Plotly from Julia. This command `export QUARTO_DENO_EXTRA_OPTIONS=--v8-flags=--stack-size=10000` from the original post fixed the issue. I was able to reproduce on `arm64` and `amd64` machines. 

```
ERROR: RangeError: Maximum call stack size exceeded

Stack trace:
    at countTicks (file:///opt/quarto/bin/quarto.js:31828:17)
    at ticksForCode (file:///opt/quarto/bin/quarto.js:31831:27)
    at mdFormatOutput (file:///opt/quarto/bin/quarto.js:32280:19)
    at mdHtmlOutput (file:///opt/quarto/bin/quarto.js:32928:12)
    at mdOutputDisplayData (file:///opt/quarto/bin/quarto.js:32824:20)
    at mdFromCodeCell (file:///opt/quarto/bin/quarto.js:32714:35)
    at jupyterToMarkdown (file:///opt/quarto/bin/quarto.js:32135:34)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Object.execute (file:///opt/quarto/bin/quarto.js:38387:25)
    at async renderExecute (file:///opt/quarto/bin/quarto.js:77012:27)
```


```
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.7.1
      Kernels: julia-1.10, python3

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```

**Comment by regob** [comment]
For me the issue was also caused by plotting, but using Folium in Python, plotting 10 000s of nodes on a map. Maybe the huge number of embedded elements could cause the issue.

**Comment by cscheid** [comment]
@MisterBiggs can you give us a repro document?

**Comment by MisterBiggs** [comment]
Did a few tests and it seems to just come down to the amount of plotly in the file. One large plot or multiple smaller ones causes the issue reliably.

Using Julia 1.10 with Plots, PlotlyJS, and IJulia installed, and Quarto 1.4.550.

---
title: "crashing example"
format: html
jupyter: julia-1.10
---

```{julia}
using Plots
plotlyjs()

x = 1:60000
y = sin.(x)

plot(x, y)
```
