### ISSUE TITLE
Not Found error with .qmd on Google Drive when using embed-resources

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7993]
This is a follow up of #4614

I have tested v1.4.31 and my .qmd scripts on Google Drive now render perfectly to html. They throw no errors and the html shows up in the viewer as expected.  Thank you so much!

Unfortunately, pdfs and docx still throw errors.  They do render, but the errors are still showing. I have pasted the error messages below.  Do you need more information about my setup or does this give you what you need?

````
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

ERROR: NotFound: The system cannot find the file specified. (os error 2): remove 'X:/My Drive/1_1_2023_R-Class/Course.Project.2023/code/Unit.10.B.practice.makes.purrr.fect_files'

Stack trace:
    at Object.removeSync (ext:deno_fs/30_fs.js:189:7)
    at file:///C:/PROGRA~1/Quarto/bin/quarto.js:69298:22
    at Array.forEach (<anonymous>)
    at renderCleanup (file:///C:/PROGRA~1/Quarto/bin/quarto.js:69296:39)
    at file:///C:/PROGRA~1/Quarto/bin/quarto.js:70062:50
    at withTiming (file:///C:/PROGRA~1/Quarto/bin/quarto.js:19429:25)
    at Object.complete (file:///C:/PROGRA~1/Quarto/bin/quarto.js:70062:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Object.onPostProcess (file:///C:/PROGRA~1/Quarto/bin/quarto.js:77146:36)
    at async renderFileInternal (file:///C:/PROGRA~1/Quarto/bin/quarto.js:77130:5)
```` 

_Originally posted by @neellab-umd in https://github.com/quarto-dev/quarto-cli/issues/4614#issuecomment-1864404082_

**Comment by cderv** [comment]
Minimal reprex 

````markdown
---
title: "test"
format: 
  html :
    embed-resources: true
---

Test

````

Same stacktrace

````
ERROR: NotFound: Le fichier spécifié est introuvable. (os error 2): remove 'test_files\libs'

Stack trace:
    at Object.removeSync (ext:deno_fs/30_fs.js:189:7)
    at safeRemoveSync (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/path.ts:53:10)
    at file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cleanup.ts:93:9
    at Array.forEach (<anonymous>)
    at renderCleanup (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cleanup.ts:91:25)
    at file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render.ts:363:11
    at withTiming (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/timing.ts:37:20)
    at Object.complete (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render.ts:362:9)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Object.onPostProcess (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:715:28)
````

But the folder exists 
````typescript
> import { existsSync } from "https://deno.land/std@0.209.0/fs/exists.ts";
undefined
> existsSync("test_files")
true
> existsSync("test_files/libs")
true
````

**Comment by pieterjanvc** [comment]
Hello,

I just wanted to chime in and confirm that this issue is still present. When I render my qmd file, it does generate the html file and when I open it in the browser rendered correctly, however, it will not show up in the viewer pane and throws the following error:
```
==> quarto preview analysis.qmd --to html --no-watch-inputs --no-browse



processing file: analysis.qmd
                                                                                                            
output file: analysis.knit.md

pandoc 
  to: html
  output-file: analysis.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: analysis
  editor: visual
  
ERROR: NotFound: The system cannot find the file specified. (os error 2), remove 'analysis_files\mediabag'

NotFound: The system cannot find the file specified. (os error 2), remove 'analysis_files\mediabag'
    at Object.removeSync (deno:runtime/js/30_fs.js:157:9)
    at removeIfEmptyDir (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:5701:18)
    at renderCleanup (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:80577:5)
    at file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:81111:46
    at withTiming (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:19624:25)
    at Object.complete (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:81111:13)
    at async Object.onPostProcess (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:86678:36)
    at async renderFiles (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:86649:13)
    at async render (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:90681:21)
    at async renderForPreview (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:102415:26)
```

My quarto file
````
---
title: "analysis"
format: html
editor: visual
---
# Test
```{r}
1+1
```
````
