### ISSUE TITLE
Error rendering GFM

### ISSUE THREAD

**Issue by matthew-brett** [quarto-dev/quarto-cli#81]
Please do tell me to stop if you've had enough of these, but, on current `main` branch  ...

```
quarto create-project quarto-project
cd quarto-project
quarto render . --to gfm
```

gives:

```
ERROR: NotFound: No such file or directory (os error 2)
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.realPathSync (deno:runtime/js/30_fs.js:137:17)
    at projectPath (file:///Volumes/zorg/mb312/dev_trees/quarto-cli/src/command/render/render.ts:569:16)
...
```

**Comment by jjallaire** [comment]
Please continue, we love it! :-)

Fix for this problem is here: https://github.com/quarto-dev/quarto-cli/commit/c808c463bf3ef50f2488a0053d847e826e33f41a

**Comment by matthew-brett** [comment]
Wilco - thanks.
