### ISSUE TITLE
Embedded notebook cells do not show source references in book format

### ISSUE THREAD

**Issue by kamicollo** [quarto-dev/quarto-cli#8151]
### Bug description

The embedded notebook cell feature does not produce source links to the notebook when used in book format. I would have expected this feature to work in book format, too - at a minimum, when the book output format is HTML (though it may apply to other formats, too, as long as the notebook is included in the book somewhere). 

I can see situations where the book includes code snippets along the way with the entire notebook available in the appendix, and having the ability to click through to the entire notebook would be awesome.

This does not seem to be controlled by `notebook-links` or `notebook-view` settings - changing them has no impact.

### Steps to reproduce

Embed a cell from a notebook `foo.ipynb` into a document using shortcode:

```{{< embed foo.ipynb#foo >}}```

### Expected behavior

The rendered page should include both the content of the notebook cell as well as a source reference to it.

### Actual behavior

The rendered page only includes the content of the notebook cell.

### Your environment

- IDE: VSCode
- Quarto version: 1.4.537
- WSL 2 with Ubuntu

### Quarto check output

Quarto 1.4.537
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.537
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/aurimas/.TinyTeX/bin/x86_64-linux
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /home/aurimas/micromamba/envs/confluence/bin/python
      Jupyter: 5.3.2
      Kernels: bsfinal, gp-processes, idendro, pymc3, bayes, python3, ncr, homecourt, pymc4, julia-1.9, cse6242hw4, ir, css, julia-1.6, bayesian, anaconda-real, strongarm, cse6242project, pdfparser

Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK

**Comment by dragonstyle** [comment]
This is currently a limitation of the use of embeds within books which we agree we should fix. We'll address in a coming release!

**Comment by kamicollo** [comment]
Thanks, that's great to hear!

**Comment by DOH-FAA3303** [comment]
The same occurs with manuscript project types. There is a global link to the notebooks but no link under the embeded code chunk like in the tutorials. the `notebook-links:` parameter does not do anything. However I do see the notebook link in the pdf output. I've tried with quarto 1.4+ and the current pre-release 1.5.22. 

for example here's my `index.qmd`

````
---
title: Test
authors:
  - name: Norah Jones
    affiliation: The University
    roles: writing
    corresponding: true
---

## Section

hello


embed ggplot

{{< embed notebooks/plot.qmd#fig-plot >}}
````

and my notebook - `notebooks/plot.qmd`

````
---
title: "Notebook"
---


```{r}
#| label: fig-plot

library(ggplot2)
ggplot(diamonds, aes(x=carat, y=price, color=cut)) +
  geom_point()

```

````

gives this output with no source link under the plot:

![image](https://github.com/quarto-dev/quarto-cli/assets/92396451/dcb1aaa4-329f-4dfc-b91e-247159b088ba)



Expected output:
![image](https://github.com/quarto-dev/quarto-cli/assets/92396451/a16bf1be-9856-435f-b560-02ca8219c040)

**Comment by mine-cetinkaya-rundel** [comment]
I'm seeing the same issue as in @DOH-FAA3303's comment above. 

@cderv I believe this is a regression for `manuscript`s and I would suggest breaking this issue off to a new one and addressing it earlier even if exposing them in `book` format might come later.

**Comment by GeorgRamer** [comment]
This would be a very important feature when using Quarto books as teaching material! What are the chances that it will make it into the next version?

**Comment by mcanouil** [comment]
@GeorgRamer We appreciate your interest in the project, but I'd like to share some guidance on how we can make discussions more productive.

Posts asking "Any news?" or "When will this be ready?" without specific questions or constructive feedback don't help move development forward.
They create notification noise for maintainers without providing actionable input that could influence development priorities.

Rather than asking for general updates, consider asking specific technical questions about implementation, contributing implementation suggestions, or submitting pull requests for features you need.
Consider upvoting and/or adding a "thumb up" on the original message.

The most valuable contributions focus on "here's how I can help solve this" rather than "here's what I want you to do for me."

For the latest information about progress and planned features, check the project's changelog, release notes, or issues.

Thanks for understanding and for your continued interest in the project.
