### ISSUE TITLE
Error executing 'reg': Access is denied. (os error 5)

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8245]
here is my output when i ran the quarto check, the errors in the quarto.js files displayed below are also what appears when i try to render a sample quarto document. 

Test.User@PHX-111 MINGW64 ~/Desktop/Brain2/R/quatro1/test2
$ quarto check
Quarto 1.4.539
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.539
      Path: C:\Users\Test.User\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

error: Uncaught (in promise) Error: Error executing 'reg': Access is denied. (os error 5)
        throw new Error(`Error executing '${options.cmd[0]}': ${e.message}`);
              ^
    at execProcess (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:5295:15)
    at registryReadString (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:26513:27)
    at registryReadString (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:26498:31)
    at cacheCodePage (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:39487:29)
    at readCodePage (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:39520:13)
    at checkInstall (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:98441:30)
    at check (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:98384:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Command.fn (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:98667:5)
    at async Command.execute (file:///C:/Users/Test.User/AppData/Local/Programs/Quarto/bin/quarto.js:8102:13)

_Originally posted by @serrulate in https://github.com/quarto-dev/quarto-cli/issues/5104#issuecomment-1889502630_

**Comment by cderv** [comment]
@serrulate I opened a new issue because it was different than #5104 

From the trace, this error is thrown from 
https://github.com/quarto-dev/quarto-cli/blob/27983066d0bfb5e5057c1deed6808f20c23c42a1/src/core/process.ts#L169-L171

This is an error while trying to read from the registry at 
https://github.com/quarto-dev/quarto-cli/blob/27983066d0bfb5e5057c1deed6808f20c23c42a1/src/core/windows.ts#L68-L72

We are supposed to call `reg`
https://github.com/quarto-dev/quarto-cli/blob/27983066d0bfb5e5057c1deed6808f20c23c42a1/src/core/registry.ts#L31-L37

Can you open a CMD window and try the following 

````
reg query HKLM\SYSTEM\CurrentControlSet\Control\Nls\CodePage /v ACP

reg query HKCU\SYSTEM\CurrentControlSet\Control\Nls\CodePage /v ACP
````

thank you

**Comment by serrulate** [comment]
Thank you for working with me on this, i will need to get help  from an Admin locally to run the command, i get an access denied message when i try to run the command. 

U:\>reg query HKLM\SYSTEM\CurrentControlSet\Control\Nls\CodePage /v ACP
Access is denied.

**Comment by dragonstyle** [comment]
I would be in favor of adding a try/catch in `registryReadString` so access denied to HKLM won't prevent us from trying to read HKCU.

**Comment by serrulate** [comment]
is there a way i could try these modifications, or is something  that i would need to wait for the next release?

**Comment by mcanouil** [comment]
It should be part of 1.4.453

**Comment by cderv** [comment]
And you can download current Release Candidate at: https://quarto.org/docs/get-started/

**Comment by serrulate** [comment]
Thank you for all of your work on this and all of the responses, one last
question, do you have a guess as to expected release of
1.4.453 ?

N

**Comment by mcanouil** [comment]
It's already available, but it's a release candidate which means soonish there will be a 1.4 stable release.

**Comment by cderv** [comment]
@serrulate we show the version number in the page I linked
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/d79947b6-37b3-4dcb-b0c0-fd345b18b685)

It happens that we are in release candidate phase, so this is the main download option

Latest pre-release of quarto is also always available at: https://quarto.org/docs/download/prerelease.html

**Comment by serrulate** [comment]
I wanted to confirm that after downloading the 1.4.543 candidate and installing a machine that i do now have admin rights on  i i was able to successfully render a quarto document.   Thank you!!!!

**Comment by mcanouil** [comment]
Thanks for letting us know.
