### ISSUE TITLE
QUARTO_PROFILER_OUTPUT fails

### ISSUE THREAD

**Issue by vangberg** [quarto-dev/quarto-cli#8296]
### Bug description

I realize this may not be intended for the public, but I am trying to see if I can make Quarto render faster for projects with 1000+ files. The Chrome profiler gave me something, but mostly showed me that `runPandoc`/`execProcess` is where the time is being spent. I hoped `QUARTO_PROFILER_OUTPUT` could tell me something about what happened in pandoc, but unfortunately it fails:

```bash
$ quarto --version
1.4.543
$ QUARTO_PROFILER_OUTPUT=profile.json quarto render docs/1.qmd
pandoc 
  to: html
  output-file: 1.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  editor: visual
  title: '1'
  
ERROR: TypeError: Cannot read properties of null (reading 'length')

Stack trace:
    at insertExplicitTimingEntries (file:///Applications/quarto/bin/quarto.js:19504:17)
    at runPandoc (file:///Applications/quarto/bin/quarto.js:69190:13)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:70039:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:77256:36)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77233:17)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77057:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:77384:25)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:81949:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8102:13)
```

### Your environment

- OS: macOS Ventura 13.2.1

### Quarto check output

```
$ quarto check
Quarto 1.4.543
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.543
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/harryvangberg/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

(|) Checking R installation...........During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /opt/homebrew/Cellar/r/4.3.2/lib/R
      LibPaths:
        - /opt/homebrew/Cellar/r/4.3.2/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

**Comment by cscheid** [comment]
Ideally it would work, but we haven't used that code in a while, because the resolution was simply too coarse to be usable.

Unfortunately, what we _do_ use for Lua profiling involves running a custom fork of both Pandoc and the Lua interpreter. It's a pretty involved process to get running that I have not documented yet.
