### ISSUE TITLE
pdf rendering works only if docx format is not specified

### ISSUE THREAD

**Issue by Sciemon** [quarto-dev/quarto-cli#8373]
### Bug description

An mwe can be found in the github repo 
https://github.com/Sciemon/issue_figures_folder

Somehow latex assumes the figures are in a 'mediabag' folder that does not exist.

### Steps to reproduce

It is only possible to render (with quarto render ...) the file 'model_requirements.qmd' if 'docx: default' is deleted from the yaml. 

### Expected behavior

 if 'docx: default' is deleted, the pdf is rendered

### Actual behavior

Otherwise latex throws the following error:

ERROR: 
compilation failed- error
Unable to load picture or PDF file 'model_requirements_files/mediabag/figs/SVS_droop.pdf'.
<to be read again>
                   }
l.373 ...ements_files/mediabag/figs/SVS_droop.pdf}### 

### Your environment

- IDE: VSCode 1.85.2
- OS: Windows 10

### Quarto check output

Quarto 1.4.545
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.545
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\seberlein\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: C:/Users/seberlein/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.7.1
      Kernels: python3

(-) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Program Files\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Program Files\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK

**Comment by cderv** [comment]
Some context about the issue.

This is similar to this one 
* https://github.com/quarto-dev/quarto-cli/issues/6705

but happens with mediabag supporting files and with output file name conflict. 

Overall issue is order of cleanup for supporting files 

I am putting back what I shared there at https://github.com/quarto-dev/quarto-cli/issues/6705#issuecomment-1706569288 by adapting to this use case. 

* Cleanup code is in `renderCleanup()`
	https://github.com/quarto-dev/quarto-cli/blob/248a3a4b1cd8985eb062cd53e53b23326c13eb2d/src/command/render/cleanup.ts#L48-L55
	we are cleanup supporting file in some situations and this happens with docx format. 

* When rendering to `--to all` we pass through this 3 times, and not in the order I though. 
   * Last format is called first.  So `docx` cleanup will happen before PDF rendering. 
   * Meaning that when PDF rendering happens, the shared resources is already deleted. 

	https://github.com/quarto-dev/quarto-cli/blob/e83119062f21a6ea8b98199ce21b041b6659d291/src/command/render/render-files.ts#L717-L724

* If `docx` is called first, the cleaning step happens last. So PDF rendering can work ok. 

Try just putting `docx` first as a workaround 

````diff
diff --git a/model_requirements.qmd b/model_requirements.qmd
index 522edb4..3f12bf1 100644
--- a/model_requirements.qmd
+++ b/model_requirements.qmd
@@ -8,6 +8,7 @@ toc: true
 number-sections: true
 highlight-style: pygments
 format:
+  docx: default^M
   pdf:
     geometry:
       - top=30mm
@@ -17,7 +18,6 @@ format:
     html-math-method: katex
     default-image-extension: svg
     css: style.css
-  docx: default
 ---
````

This is a topic we can deal with
* #6518 

This would probably be the better options. @cscheid do you agree ?

**Comment by cderv** [comment]
New use case I found: 

````markdown
---
title: About 
format: 
  typst: default
  typst+toc:
    toc: true
---

# Header

Content


````

````
❯ quarto render index.qmd
pandoc
  to: typst
  output-file: index.typ
  standalone: true
  default-image-extension: svg
  wrap: none
  citeproc: false

metadata
  title: About

pandoc
  to: typst
  output-file: index.typ
  standalone: true
  default-image-extension: svg
  wrap: none
  citeproc: false
  toc: true

metadata
  title: About

[typst]: Compiling index.typ to index.pdf...DONE

[typst]: Compiling index.typ to index.pdf...error: input file not found (searched at C:\Users\chris\Documents\DEV_OTHER\00-TESTS\test-quarto\index.typ)
ERROR: Error
    at Object.complete (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/output-typst.ts:80:13)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render.ts:282:23
    at async withTimingAsync (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/core/timing.ts:50:20)
    at async Object.complete (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render.ts:277:7)
    at async Object.onPostProcess (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:720:28)
    at async renderFileInternal (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:689:3)
    at async renderFiles (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:325:9)
    at async renderProject (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/project.ts:441:23)
    at async Command.actionHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:248:26)
````

Adding `keep-typ` solves it

````yaml
format: 
  typst: default
  typst+toc:
    toc: true
    keep-typ: true
````


So it is not possibly to use the variant format with Typst right now because of our rendering and cleaning process.

**Comment by cderv** [comment]
https://github.com/quarto-dev/quarto-cli/issues/10883 is another report

````
---
title: "Quazz"
format:
  pdf: default
  docx: default
---

# Quazz

This is a sumbol of a pie chart in SVG:

![Symbolic pie chart](./piechart.svg)

That is it.
````
With this svg to reproduce: [piechart.svg](https://github.com/user-attachments/assets/bd6cd9ba-6fb6-4829-9e23-172413cbac33)

**Comment by andrewheiss** [comment]
Hi! Running into this again. I normally address this with the +variant trick and keeping the intermediate markdown file (following this https://github.com/quarto-dev/quarto-cli/issues/8373#issuecomment-1979245883), and it works:

```qmd
---
title: About 

# This is necessary to keep intermediate files/folders hanging around when
# rendering to the same output format (like two different PDFs)
# https://github.com/quarto-dev/quarto-cli/issues/8373#issuecomment-1979245883
keep-md: true

format: 
  pdf: default
  pdf+toc:
    output-file: "testing-toc.pdf"
    toc: true
---

# Header

Content
```

↑ this creates two different PDFs with different names, one with a TOC and one without, as expected

But with typst, it doesn't work (as noted here https://github.com/quarto-dev/quarto-cli/issues/8373#issuecomment-2343189615)

This with `keep-md`…

```qmd
---
title: About 
keep-md: true
format: 
  typst: default
  typst+toc:
    output-file: "testing-toc.pdf"
    toc: true
---

# Header

Content
```

… causes this error:

```
ERROR: NotFound: No such file or directory (os error 2): readfile 'testing.typ'
Path: testing.typ
```

Using `keep-typ` instead *does* allow both formats to render, but they're identical—in this case both PDFs have a TOC:

```qmd
---
title: About 
keep-typ: true
format: 
  typst: default
  typst+toc:
    output-file: "testing-toc.pdf"
    toc: true
---

# Header

Content
```

Is there a different way to render two different typst formats like this?

**Comment by mcanouil** [comment]
The [error moved to the new Skylighting post-processor](https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/format/typst/format-typst.ts#L190-L225) but the underlying ordering is the same as described before.

Trace on `issue.qmd` with `format: { typst: default, typst+toc: { toc: true } }`:

1. Both pandoc passes write to the same `issue.typ` (shared intermediate, no modifier-aware suffix).
2. Completions drain "Last In, First Out", so `typst+toc` completes first: compiles `issue.pdf`, then `safeRemoveSync(issue.typ)`.
3. `typst` completion then runs its generic post-processors, which now try to read the already-removed `issue.typ`.

Disambiguating `output-file` per format key when modifiers are present would also be needed to make the variant useful, in addition to the broader cleanup-ordering fix tracked in #6518.

Relevant codes:

- https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/command/render/render-files.ts#L725-L738
- https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/command/render/render.ts#L260-L302
- https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/command/render/output-typst.ts#L218-L220
- https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/command/render/output-typst.ts#L286-L289
- https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/format/typst/format-typst.ts#L190-L225
- https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/command/render/render-contexts.ts#L331-L334
- https://github.com/quarto-dev/quarto-cli/blob/57705c3c7cce4b5921832aea007d6a1663309aad/src/core/pandoc/pandoc-formats.ts#L204-L249
