### ISSUE TITLE
quarto inspect with incorrect arguments gives a stack trace

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#8448]
### Bug description

When run with too many arguments, `quarto inspect` gives and error and an accompanying stack trace. The trace makes it appear like there is a Quarto problem rather than just a usage problem.

```bash
quarto inspect one two
```

```
ERROR: Too many arguments: two

Stack trace:
    at Command.parseArguments (file:///Applications/quarto/bin/quarto.js:8268:27)
    at Command.parseCommand (file:///Applications/quarto/bin/quarto.js:7987:31)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async quarto (file:///Applications/quarto/bin/quarto.js:114968:5)
    at async file:///Applications/quarto/bin/quarto.js:114986:9
```

### Steps to reproduce

```bash
quarto inspect one two
```

### Expected behavior

An error indicating the usage mistake.

### Actual behavior

An error indicating the usage mistake with a stack.

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This is fixed on `v1.5.45`.
