### ISSUE TITLE
Lightbox images descriptions don't work anymore with v1.4

### ISSUE THREAD

**Issue by ycrouin** [quarto-dev/quarto-cli#8607]
### Bug description

Hi team :wave: 

With the lightbox extension, we used to be able to add descriptions to images

### Steps to reproduce

See [example](https://github.com/quarto-ext/lightbox/blob/a738ff253fd46dd0cdd6aa992178cb7561b70251/example.qmd#L27)

### Expected behavior

![expected](https://github.com/quarto-dev/quarto-cli/assets/79843522/12577f6e-675d-44c9-b249-df9fbc9285bf)

### Actual behavior

![actual](https://github.com/quarto-dev/quarto-cli/assets/79843522/74bbfb31-622e-4b30-ba9f-71e36ee0404a)

### Your environment

- Quarto version: 1.4.549
- OS: Ubuntu 20.04.6 LTS

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2019

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /home/ycrouin/miniconda3/bin/python
      Jupyter: 5.7.1
      Kernels: [omitted for brevity ...]

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
There is an unactivated Python environment in venv. Did you forget to activate it?

[✓] Checking Jupyter engine render....OK
```

**Comment by dragonstyle** [comment]
This is correct (and accidental). We changed the way descriptions are read to better support descriptions that contain formatted. I'll fix- ty for catching this!
