### ISSUE TITLE
Inline code chunks don't evaluate unless a non-inline chunk is present.

### ISSUE THREAD

**Issue by kendonB** [quarto-dev/quarto-cli#8642]
### Bug description

quarto will not evaluate inline code chunks unless a non-inline chunk is present in the document. 

### Steps to reproduce

Create a qmd with no non-inline chunk and add `{r} nrow(mtcars)` inline. The text should be echoed through and not evaluated. 

### Expected behavior

The code should be evaluated.

### Actual behavior

The code is echoed through.

### Your environment

 - IDE RStudio 2023.12.1 Build 402
 - Windows 11

### Quarto check output

```bash
quarto check
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\KennyBell\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\KennyBell\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: C:/Users/KennyBell/anaconda3/python.exe
      Jupyter: 5.2.0
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\KennyBell\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\KennyBell\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[>] Checking Jupyter engine render....OK
```

**Comment by bhattmaulik** [comment]
In the yaml head, add the line - 
engine: knitr

It will work.

**Comment by mcanouil** [comment]
Indeed, engine auto-detection only happens based on code cells.
There are no bugs.

**Comment by kendonB** [comment]
thanks!
