### ISSUE TITLE
Quarto can't locate R installation with path containing special characters

### ISSUE THREAD

**Issue by rroelz** [quarto-dev/quarto-cli#8688]
### Bug description

When trying to use quarto on my windows pc from RStudio or powershell it can't locate my R installation, breaking with the message.
```
ERROR: Error executing 'C:\Users\RobinR�lz\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe': Das System kann den angegebenen Pfad nicht finden. (os error 3)

Unable to locate an installed version of R.
Install R from https://cloud.r-project.org/
```

R has been added to the path at :`C:\Users\RobinRölz\AppData\Local\Programs\R\R-4.3.2\bin\x64\R.exe`

### Steps to reproduce

Have R installed in a location with a special character (I wasn't able to try as this is only a work pc and I can't install anything outside my user account) 
```powershell
quarto.cmd render test.qmd
```

### Expected behavior

Quarto renders the document. 

### Actual behavior

Quarto can't locate R and doesn't render the document. 

### Your environment

- Windows 11 Enterprise: 22H2
- Powershell: 1.0
- RStudio: Ocean Storm" Release (4da58325, 2024-01-28) for windows
- R: version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes"

### Quarto check output

```
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\RobinRölz\AppData\Local\Programs\Quarto\bin\
      CodePage: unknown

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

(\) Checking basic markdown render....pandoc: Cannot decode byte '\xf6': Data.Text.Encoding: Invalid UTF-8 stream
[>] Checking basic markdown render....OK
```

**Comment by cderv** [comment]
Thanks for the report. 

This could be related to other codepage-related issues 
* https://github.com/quarto-dev/quarto-cli/issues/4103
* https://github.com/quarto-dev/quarto-cli/issues/8530

The other error shown seems related too 
````
pandoc: Cannot decode byte '\xf6': Data.Text.Encoding: Invalid UTF-8 stream
````

Can you run the command at https://github.com/quarto-dev/quarto-cli/issues/4103#issuecomment-1405226207 to check which codepage you have ?

`quarto check` report `unknown` which is unexpected by could be related to what happens in #8530 

Knowing the codepage will help us reproduce. 

thank you.

**Comment by cderv** [comment]
Can you also run the command for quarto check with verbose mode activitated ? 

https://quarto.org/docs/troubleshooting/#verbose-mode

This will show debug log about R detection. 

Thank you.

**Comment by rroelz** [comment]
I also talked with a friend later and he mentioned codepages. I've been mostly on Linux the last while so I need to get more into Windows again. I haven't tried running through Rstudio yet. 

```powershell
Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage" -Name ACP
```
1252
```powershell
Get-ItemPropertyValue -Path "HKCU:\SYSTEM\CurrentControlSet\Control\Nls\CodePage" -Name ACP
```
Error Message: 
```
Get-ItemPropertyValue : Der Pfad
"HKCU:\SYSTEM\CurrentControlSet\Control\Nls\CodePage" kann
nicht gefunden werden, da er nicht vorhanden ist.
In Zeile:1 Zeichen:1
+ Get-ItemPropertyValue -Path
"HKCU:\SYSTEM\CurrentControlSet\Control\N ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKCU:\SYSTEM
   \Cu...ol\Nls\CodePage:String) [Get-ItemPropertyValue],
  ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerS
   hell.Commands.GetItemPropertyValueCommand
```

```powershell
# The key we need 
Get-ChildItem -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"
```
```
    Hive: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Contro
    l\Nls\CodePage


Name                           Property
----                           --------
EUDCCodeRange                  932 : F040-F9FC
                               936 :
                               AAA1-AFFE,F8A1-FEFE,A140-A7A0
                               949 : C9A1-C9FE,FEA1-FEFE
                               950 : FA40-FEFE,8E40-A0FE,814
                               0-8DFE,C6A1-C8FE
```
```powershell
Get-ChildItem -Path "HKCU:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"
```
also erroring not found

```powershell
# All properties available 
Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"
```
```
10000             : c_10000.nls
10001             : c_10001.nls
10002             : c_10002.nls
10003             : c_10003.nls
10004             : c_10004.nls
10005             : c_10005.nls
10006             : c_10006.nls
10007             : c_10007.nls
10008             : c_10008.nls
10010             : c_10010.nls
10017             : c_10017.nls
10021             : c_10021.nls
10029             : c_10029.nls
10079             : c_10079.nls
10081             : c_10081.nls
10082             : c_10082.nls
1026              : c_1026.nls
1047              : c_1047.nls
1140              : c_1140.nls
1141              : c_1141.nls
1142              : c_1142.nls
1143              : c_1143.nls
1144              : c_1144.nls
1145              : c_1145.nls
1146              : c_1146.nls
1147              : c_1147.nls
1148              : c_1148.nls
1149              : c_1149.nls
1250              : c_1250.nls
1251              : c_1251.nls
1252              : c_1252.nls
1253              : c_1253.nls
1254              : c_1254.nls
1255              : c_1255.nls
1256              : c_1256.nls
1257              : c_1257.nls
1258              : c_1258.nls
1361              : c_1361.nls
20000             : c_20000.nls
20001             : c_20001.nls
20002             : c_20002.nls
20003             : c_20003.nls
20004             : c_20004.nls
20005             : c_20005.nls
20105             : c_20105.nls
20106             : c_20106.nls
20107             : c_20107.nls
20108             : c_20108.nls
20127             : c_20127.nls
20261             : c_20261.nls
20269             : c_20269.nls
20273             : c_20273.nls
20277             : c_20277.nls
20278             : c_20278.nls
20280             : c_20280.nls
20284             : c_20284.nls
20285             : c_20285.nls
20290             : c_20290.nls
20297             : c_20297.nls
20420             : c_20420.nls
20423             : c_20423.nls
20424             : c_20424.nls
20833             : c_20833.nls
20838             : c_20838.nls
20866             : c_20866.nls
20871             : c_20871.nls
20880             : c_20880.nls
20905             : c_20905.nls
20924             : c_20924.nls
20932             : c_20932.nls
20936             : c_20936.nls
20949             : c_20949.nls
21025             : c_21025.nls
21027             : c_21027.nls
21866             : c_21866.nls
28591             : C_28591.NLS
28592             : C_28592.NLS
28593             : c_28593.nls
28594             : C_28594.NLS
28595             : C_28595.NLS
28596             : C_28596.NLS
28597             : C_28597.NLS
28598             : c_28598.nls
28599             : c_28599.nls
28603             : c_28603.nls
28605             : c_28605.nls
37                : c_037.nls
38598             : c_28598.nls
437               : c_437.nls
500               : c_500.nls
50220             : c_is2022.dll
50221             : c_is2022.dll
50222             : c_is2022.dll
50225             : c_is2022.dll
50227             : c_is2022.dll
50229             : c_is2022.dll
51949             : c_20949.nls
52936             : c_is2022.dll
54936             : c_g18030.dll
55000             : c_gsm7.dll
55001             : c_gsm7.dll
55002             : c_gsm7.dll
55003             : c_gsm7.dll
55004             : c_gsm7.dll
57002             : c_iscii.dll
57003             : c_iscii.dll
57004             : c_iscii.dll
57005             : c_iscii.dll
57006             : c_iscii.dll
57007             : c_iscii.dll
57008             : c_iscii.dll
57009             : c_iscii.dll
57010             : c_iscii.dll
57011             : c_iscii.dll
708               : c_708.nls
720               : c_720.nls
737               : c_737.nls
775               : c_775.nls
850               : c_850.nls
852               : c_852.nls
855               : c_855.nls
857               : c_857.nls
858               : c_858.nls
860               : c_860.nls
861               : c_861.nls
862               : c_862.nls
863               : c_863.nls
864               : c_864.nls
865               : c_865.nls
866               : c_866.nls
869               : c_869.nls
870               : c_870.nls
874               : c_874.nls
875               : c_875.nls
932               : c_932.nls
936               : c_936.nls
949               : c_949.nls
950               : c_950.nls
AllowDeprecatedCP : 1111573537
OEMHAL            : vgaoem.fon
ACP               : 1252
OEMCP             : 850
MACCP             : 10000
PSPath            : Microsoft.PowerShell.Core\Registry::HKEY
                    _LOCAL_MACHINE\SYSTEM\CurrentControlSet\
                    Control\Nls\CodePage
PSParentPath      : Microsoft.PowerShell.Core\Registry::HKEY
                    _LOCAL_MACHINE\SYSTEM\CurrentControlSet\
                    Control\Nls
PSChildName       : CodePage
PSDrive           : HKLM
PSProvider        : Microsoft.PowerShell.Core\Registry
```
```
Get-ItemProperty -Path "HKCU:\SYSTEM\CurrentControlSet\Control\Nls\CodePage"
```
error, not found

Lastly the output of quarto check with the debug mode on is: 
```
Quarto version: 1.4.549
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
[execProcess] C:\Users\RobinRölz\AppData\Local\Programs\Quarto\bin\tools\pandoc --version
[execProcess] Success: true, code: 0
      Pandoc version 3.1.11: OK
[execProcess] C:\Users\RobinRölz\AppData\Local\Programs\Quarto\bin\tools\x86_64\dart-sass\sass.bat --version
[execProcess] Success: true, code: 0
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\Users\RobinRölz\AppData\Local\Programs\Quarto\bin\
[execProcess] reg query HKLM\SYSTEM\CurrentControlSet\Control\Nls\CodePage /v ACP
      CodePage: unknown

[execProcess] cmd /c C:\Users\ROBINR~1\AppData\Local\Temp\quarto-safe-execfc6763d3.bat
[execProcess] Success: true, code: 0
[execProcess] Success: false, code: 1
[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[execProcess] cmd /c C:\Users\ROBINR~1\AppData\Local\Temp\quarto-safe-exec26e8a8f9.bat
[execProcess] Success: false, code: 1
[execProcess] cmd /c C:\Users\ROBINR~1\AppData\Local\Temp\quarto-safe-execfa89ae47.bat
[execProcess] Success: false, code: 1
[>] Checking LaTeX....................OK
      Tex:  (not detected)

Error loading deno-dom-native: Could not open library: Das angegebene Modul wurde nicht gefunden.

[execProcess] C:\Users\RobinRölz\AppData\Local\Programs\Quarto\bin\tools\x86_64\dart-sass\sass.bat C:\Users\ROBINR~1\AppData\Local\Temp\quarto-sessionc20b11b8\e71706c2\b593b6c8.scss C:\Users\ROBINR~1\AppData\Local\Temp\quarto-sessionc20b11b8\e71706c2\sass\397ef2e52d54cf686e4908b90039e9db.css --style compressed --quiet --load-path=C:\Users\RobinRölz\AppData\Local\Programs\Quarto\share\formats\html\bootstrap\dist\scss --load-path=C:\Users\RobinRölz\AppData\Local\Programs\Quarto\share\formats\html\bslib\bslib-scss
(|) Checking basic markdown render....[execProcess] Success: true, code: 0
(/) Checking basic markdown render....Windows: Using code page 1252
[execProcess] C:\Users\RobinRölz\AppData\Local\Programs\Quarto\bin\tools\pandoc +RTS -K512m -RTS --defaults C:\Users\ROBINR~1\AppData\Local\Temp\quarto-sessionc20b11b8\e71706c2\quarto-defaults4dfaa2e0.yml C:\Users\ROBINR~1\AppData\Local\Temp\quarto-sessionc20b11b8\e71706c2\quarto-input7772819d.md --metadata-file C:\Users\ROBINR~1\AppData\Local\Temp\quarto-sessionc20b11b8\e71706c2\quarto-metadatad5cf1eb8.yml --verbose --trace --quiet --data-dir C:\Users\RobinRölz\AppData\Local\Programs\Quarto\share\pandoc\datadir
(-) Checking basic markdown render....[trace] Parsed [Plain [Str "long"]] at line 1
[trace] Parsed [Plain [Str "en"]] at line 1
[trace] Parsed [Plain [Str "true"]] at line 1
[trace] Parsed [Plain [Str "1.4.549"]] at line 1
[trace] Parsed [Plain [Str "Title"]] at line 1
[trace] Parsed [Plain [Str "Table",Space,Str "of",Space,Str "contents"]] at line 1
(\) Checking basic markdown render....[trace] Parsed [] at line 5
[trace] Parsed [Header 2 ("header",[],[]) [Str "Header"]] at line 8
(|) Checking basic markdown render....pandoc: Cannot decode byte '\xf6': Data.Text.Encoding: Invalid UTF-8 stream
[execProcess] Success: false, code: 1
[>] Checking basic markdown render....OK
```

**Comment by cderv** [comment]
@rroelz is the `quarto check` log complete ? 

I am interesting in the log for R (`quarto check knitr`) which should be part of a global `quarto check`. It should be after `Checking basic markdown render` in the log.

Thanks

**Comment by rroelz** [comment]
The checking knitr doesn't execute when calling `quarto.exe check`. Running it seperately setting
```powershell
$env:QUARTO_LOG_LEVEL="DEBUG"
```
gives the following response output: 
```
> quarto.exe check knitr
Quarto version: 1.4.549
Quarto 1.4.549
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: undefined
Looking for 'Rscript' in R_HOME: undefined
Looking for 'Rscript' in PATH.
[execProcess] CMD /C where Rscript
(|) Checking R installation...........[execProcess] Success: true, code: 0
Found in PATH at C:\Users\RobinR�lz\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe
[execProcess] C:\Users\RobinR�lz\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe --version

++ Error while checking R binary found at C:\Users\RobinR�lz\AppData\Local\Programs\R\R-4.3.2\bin\x64\Rscript.exe
[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

[NotebookContext]: Starting Cleanup
```
So it seems to find R in the path but then can't locate it because of the codepage I imagine

Just to be sure I reran `quarto.exe check` on debug and normal mode and it indeed does stop after `[>] Checking basic markdown render....OK`

**Comment by PicardQc** [comment]
Hi! I had the same problem with the character "ë" in a user folder in Windows. If you use RStudio, adding a Windows user variable called "Quarto_R" with the R "bin" folder path as a value worked for me (ex. "C:/Users/XXXXëXXX/R-4_5_0/bin". 

This solution, however, does not work in PowerShell.

This is my first github post by the way. Feel free to delete the comment if it does not belong here.

**Comment by cderv** [comment]
Thanks @PicardQc for your feedback. Any help appreciated

> If you use RStudio, adding a Windows user variable called "Quarto_R" with the R "bin" folder path as a value worked for me (ex. "C:/Users/XXXXëXXX/R-4_5_0/bin"

Do I understand correctly that setting `QUARTO_R` works, but automatic detection does not, however they are same path ? 🤔 

> This solution, however, does not work in PowerShell.

Do you mean setting `$env:QUARTO_R="C:/Users/XXXXëXXX/R-4_5_0/bin"` ?

**Comment by PicardQc** [comment]
In the Windows 11 gui, in "System properties" -> "Environment Variables", I added a variable called "Quarto_R" with "C:/Users/XXXXëXXX/R-4_5_0/bin" as value. Now, rendering documents works when using Quarto in RStudio. 

The other option that worked for me before that is calling "Sys.setenv(`Quarto_R` = "C:/Users/XXXXëXXX/R-4_5_0/bin")" in the R session. This second solution however does not seem to be permanent (you had to set the variable every time the R session restarted to be able to render the documents).

With my comment about PowerShell, I meant that trying to call Quarto directly in PowerShell with "Quarto render xxxxx.qmd" still doesn't work. The error message I get is however is different. Instead of an error about not being able to find the path of the R installation, it's an error that begins with 

"Error running filter C:/Users/XXXXëXXX/Quarto_1_7_31/share/filters/main.lua: 
[string "..."]:295: module 'modules/astshortcode' not found:
"

For a little context (in the case that could have change anything), the installation of R on the computer was done for one user (without administrator privileges). If I remember correctly, the installation was also done without saving the version number in registry, RStudio desktop was not installed, but rather extracted from the zip file and then executed (i.e. used like a portable version).

Hope this will help solve the problem. Thanks to everybody working or contributing on Quarto by the way. It's really a great app.

**Comment by cderv** [comment]
> In the Windows 11 gui, in "System properties" -> "Environment Variables", I added a variable called "Quarto_R" with "C:/Users/XXXXëXXX/R-4_5_0/bin" as value. Now, rendering documents works when using Quarto in RStudio.
>The other option that worked for me before that is calling "Sys.setenv(Quarto_R = "C:/Users/XXXXëXXX/R-4_5_0/bin")" in the R session.

That is really interesting - it means this is the automatic detection that fails. Would you be able to help me? 
- Can you run a recent version of Quarto this : `quarto check knitr --log-level debug` ? 
- You can then share the console output that will be long. Adding `--log check.log` as argument also will write into a file if you find it easier. 

Thank you 

> This second solution however does not seem to be permanent (you had to set the variable every time the R session restarted to be able to render the documents).

To make it permanent that way, you would need to add this in your global users `.Renviron` or project's one `.Renviron` (see `usethis::edit_r_environ()` https://usethis.r-lib.org/reference/edit.html). If you want to know more about R Startup see https://rstats.wtf/r-startup.html


> With my comment about PowerShell, I meant that trying to call Quarto directly in PowerShell with "Quarto render xxxxx.qmd" still doesn't work.

If your R autodetection by Quarto does not work, it won't in Powershell. You would need to set the env var the same using `$env:QUARTO_R`

> For a little context (in the case that could have change anything), the installation of R on the computer was done for one user (without administrator privileges). If I remember correctly, the installation was also done without saving the version number in registry, RStudio desktop was not installed, but rather extracted from the zip file and then executed (i.e. used like a portable version).

This is interesting details. By default, Quarto will try to find R in different places - this includes known locations like Program Files, Registry and Path. If you installed R manually in a way that makes it non foundable by Quarto then setting `QUARTO_R` is the only solution to make it work. And this is not a special character issue. 
Running `quarto check knitr --log-level debug` in powershell will tell us more. 

> [!NOTE]
> Latest Quarto 1.8 has a fix that may solve Quarto detection in RStudio IDE and other contexts when `R_HOME` is set.
> So you could try that out too


Thanks a lot for you help with this. This really help us !

**Comment by PicardQc** [comment]
Calling Quarto check knitr --log-level debug in Quarto 1.7.31 results in 

```
Quarto version: 1.7.31
Quarto 1.7.31
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin
Found in C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin
[execProcess] C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin\Rscript --version
[execProcess] Success: true, code: 0

++R found at C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin\Rscript is working.
-- Checking knitr engine capabilities --
[execProcess] C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin\Rscript C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\Quarto_1_7_31\share\capabilities\knitr.R
(-) Checking R installation...........[execProcess] Success: true, code: 0

++ Parsing results to get informations about knitr capabilities
[>] Checking R installation...........OK
      Version: 4.5.0
      Path: C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/R-4_5_0
      LibPaths:
        - C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/R-4_5_0/library
      knitr: 1.50
      rmarkdown: 2.29

(|) Checking Knitr engine render......Loaded deno-dom-native
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin
Found in C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin
[execProcess] C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin\Rscript C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\Quarto_1_7_31\share\rmd\rmd.R
(\) Checking Knitr engine render......[execProcess] Success: false, code: 1
ERROR: Erreur dans dir.exists(x) :
  problème de conversion de nom de fichier -- nom trop long ?
Appels : <Anonymous> ... lapply -> FUN -> dir_exists -> <Anonymous> -> dir.exists
Exécution arrêtée

-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin
Found in C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin
[execProcess] C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin\Rscript --version
[execProcess] Success: true, code: 0

++R found at C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin\Rscript is working.
-- Checking knitr engine capabilities --
[execProcess] C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin\Rscript C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\Quarto_1_7_31\share\capabilities\knitr.R
(-) Checking Knitr engine render......[execProcess] Success: true, code: 0

++ Parsing results to get informations about knitr capabilities
[>] Checking Knitr engine render......OK

[NotebookContext]: Starting Cleanup
```

I get the same error message at "Checking Knitr engine render...." if I use Quarto1.8.14. 

I also get the same error if I set a Quarto_R, QUARTO_R or R_HOME variable in PowerShell prior to rendering the document by calling "Quarto_R=C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin".

With Quarto 1.8.14 however I also get the following lines at the end of the log after adding the variable :

```
Stack trace:
    at _Command.handleError (file:///C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_8_14/bin/quarto.js:10025:117)
    at _Command.parseCommand (file:///C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_8_14/bin/quarto.js:9712:12)
    at eventLoopTick (ext:core/01_core.js:178:7)
    at async quarto (file:///C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_8_14/bin/quarto.js:170932:5)
    at async file:///C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_8_14/bin/quarto.js:170960:5
    at async file:///C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_8_14/bin/quarto.js:170815:14
    at async mainRunner (file:///C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_8_14/bin/quarto.js:170817:5)
    at async file:///C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_8_14/bin/quarto.js:170953:3
```

By the way I made a mistake in my preceding post. I get the error concerning lua while using the terminal via Rstudio (not PowerShell). Here is the full error message using the terminal (not R console) via RStudio :

```
Error running filter C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_7_31/share/filters/main.lua:
[string "..."]:295: module 'modules/astshortcode' not found:
        no field package.preload['modules/astshortcode']
        no file 'C:\Users\XXXXXXXXXX�XXXXXXXXXX\Applications\Quarto_1_7_31\bin\tools\lua\modules/astshortcode.lua'
        no file 'C:\Users\XXXXXXXXXX�XXXXXXXXXX\Applications\Quarto_1_7_31\bin\tools\lua\modules/astshortcode\init.lua'
        no file 'C:\Users\XXXXXXXXXX�XXXXXXXXXX\Applications\Quarto_1_7_31\bin\tools\modules/astshortcode.lua'
        no file 'C:\Users\XXXXXXXXXX�XXXXXXXXXX\Applications\Quarto_1_7_31\bin\tools\modules/astshortcode\init.lua'
        no file 'C:\Users\XXXXXXXXXX�XXXXXXXXXX\Applications\Quarto_1_7_31\bin\tools\..\share\lua\5.4\modules/astshortcode.lua'
        no file 'C:\Users\XXXXXXXXXX�XXXXXXXXXX\Applications\Quarto_1_7_31\bin\tools\..\share\lua\5.4\modules/astshortcode\init.lua'
        no file '.\modules/astshortcode.lua'
        no file '.\modules/astshortcode\init.lua'
        no file 'C:\Users\XXXXXXXXXX�XXXXXXXXXX\Applications\Quarto_1_7_31\share\pandoc\datadir\modules/astshortcode.lua'
        no file 'C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\Quarto_1_7_31\share\pandoc\datadir\..\..\filters\modules/astshortcode.lua'
        no file 'C:/Users/XXXXXXXXXXëXXXXXXXXXX/Applications/Quarto_1_7_31/share/filters\modules/astshortcode.lua'
        no file ''
stack traceback:
        [string "..."]:295: in upvalue 'orig_require'
        [string "..."]:1442: in function 'require'
        ...XXXXXX/Applications/Quarto_1_7_31/share/filters/main.lua:143: in main chunk
```

Finally I am not so sure about the hypothesis that this is not a special character issue. In RStudio, before using Sys.setenv() or adding the Quarto_R variable in the user environment in Windows, I could clearly see, after clicking on "Render", the error message saying that the R installation have not been found while printing at the same time the full path of the R installation with the "ë" character replaced by "�".

**Comment by cderv** [comment]
Thanks a lot

In the first log share, I see this 
````
Looking for 'Rscript' in QUARTO_R: C:\Users\XXXXXXXXXXëXXXXXXXXXX\Applications\R-4_5_0\bin
````

So this means `QUARTO_R` was set even in this first test. And R is found correctly. 
However, it still fails with this error 
````
(\) Checking Knitr engine render......[execProcess] Success: false, code: 1
ERROR: Erreur dans dir.exists(x) :
  problème de conversion de nom de fichier -- nom trop long ?
Appels : <Anonymous> ... lapply -> FUN -> dir_exists -> <Anonymous> -> dir.exists
Exécution arrêtée
````

This is a R error. It is not quarto specific but related to R as it has happen before in R Markdown (with **reticulate** for example: https://github.com/rstudio/reticulate/issues/486; or **renv** https://forum.posit.co/t/file-name-conversion-problem-name-too-long/67889, or even outside of rmarkdown with reticulate: https://stackoverflow.com/questions/74742617/error-in-dir-existsx-file-name-conversion-problem-name-too-long) 

So something about special characters in PATH and R ? 

> [string "..."]:295: module 'modules/astshortcode' not found:

Regarding this other problem, this is unrelated, and it looks like a bad installation. 

The file should be part of the 1.7.31 installation. Here is mine for example
````
❯ ls "C:\Users\chris\scoop\apps\quarto\1.7.31\share\filters\modules\astshortcode.lua"

    Directory: C:\Users\chris\scoop\apps\quarto\1.7.31\share\filters\modules

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-----          12/05/2025    20:25           8185 astshortcode.lua
````

So I think your errors are different from this one. I'll try to investigate the R issues but I think this is R Markdown problem if not R directly.

**Comment by PicardQc** [comment]
One last thing if that can be useful. Concerning the '[string "..."]:295: module 'modules/astshortcode' not found:` error, I verified and the file is there in every Quarto installation on the computer.

**Comment by cderv** [comment]
Ok then it must be the problem of special character in the path as I see `C:\Users\XXXXXXXXXX�XXXXXXXXXX`

This is preventing lua to find the correct module. 

For this you are having the same as 
- https://github.com/quarto-dev/quarto-cli/issues/9760
- https://github.com/quarto-dev/quarto-cli/issues/8530
