### ISSUE TITLE
Quarto fails to detect knitr capabilities on Aarch64 Windows

### ISSUE THREAD

**Issue by kevinushey** [quarto-dev/quarto-cli#8730]
### Bug description

I am fairly certain that this issue is specific to Aarch64 builds of Windows. To wit, I'm experiencing this with:

```
Device name	KEVINUSHEY8387
Processor	Apple Silicon   3.20 GHz  (8 processors)
Installed RAM	8.00 GB
Device ID	22727451-E184-4C09-B32B-D2BF5E2E7365
Product ID	00330-80835-98449-AA654
System type	64-bit operating system, ARM-based processor
Pen and touch	Pen support
```

and

```
Edition	Windows 11 Pro
Version	24H2
Installed on	‎2/‎10/‎2024
OS build	26052.1000
Experience	Windows Feature Experience Pack 1000.26052.1000.0
```

Here's the log I see:

```
==> quarto preview qqqq.qmd --to pdf --no-watch-inputs --no-browse

Quarto version: 1.4.549
[NotebookContext]: Starting Cleanup
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: undefined
Looking for 'Rscript' in R_HOME: C:/R/R-4.3.2
Looking for 'Rscript' in PATH.
[execProcess] CMD /C where Rscript
[execProcess] Success: true, code: 0
Found in PATH at C:\R\R-4.3.2\bin\x64\Rscript.exe
[execProcess] C:\R\R-4.3.2\bin\x64\Rscript.exe C:\PROGRA~1\RStudio\RESOUR~1\app\bin\quarto\share\rmd\rmd.R


processing file: qqqq.qmd
1/5                  
2/5 [unnamed-chunk-1]
3/5                  
4/5 [unnamed-chunk-2]
5/5                  
output file: qqqq.knit.md

[execProcess] Success: false, code: -1073741819
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: undefined
Looking for 'Rscript' in R_HOME: C:/R/R-4.3.2
Looking for 'Rscript' in PATH.
[execProcess] CMD /C where Rscript
[execProcess] Success: true, code: 0
Found in PATH at C:\R\R-4.3.2\bin\x64\Rscript.exe
[execProcess] C:\R\R-4.3.2\bin\x64\Rscript.exe --version
[execProcess] Success: true, code: 0

++R found at C:\R\R-4.3.2\bin\x64\Rscript.exe is working.
-- Checking knitr engine capabilities --
[execProcess] C:\R\R-4.3.2\bin\x64\Rscript.exe C:\PROGRA~1\RStudio\RESOUR~1\app\bin\quarto\share\capabilities\knitr.R
[execProcess] Success: false, code: -1073741819

++ Problem with results of knitr capabilities check.
    Return Code: -1073741819 (success is false)
    with stdout from R:
--- YAML_START ---
versionMajor: 4 
versionMinor: 3 
versionPatch: 2 
home: C:/R/R-4.3.2 
libPaths:
  - "C:/Users/kevin/AppData/Local/R/win-library/4.3" 
  - "C:/R/R-4.3.2/library" 
packages:
  knitr: "1.43"
  rmarkdown: "2.22"
--- YAML_END ---

Problem with running R found at C:\R\R-4.3.2\bin\x64\Rscript.exe to check environment configurations.
Please check your installation of R.

[NotebookContext]: Starting Cleanup
```

In other words, even though Quarto seemingly successfully interrogates R, because R doesn't shut down cleanly, it's inferred to be a non-functional build of R.

This is almost surely a Windows bug, but as far as I can tell there's no way for me to get out of this hole. 😞 

### Your environment

```
RStudio 2024.04.0-daily+440 "Chocolate Cosmos" Daily (017994e650caa386966773e1208a338354b62074, 2024-02-12) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+440 Chrome/120.0.6099.276 Electron/28.2.2 Safari/537.36
```

### Quarto check output

```
> system("quarto check")
Quarto version: 1.4.549
Quarto 1.4.549
[>] Checking versions of quarto binary dependencies...
[execProcess] C:\PROGRA~1\RStudio\RESOUR~1\app\bin\quarto\bin\tools\pandoc --version
[execProcess] Success: true, code: 0
      Pandoc version 3.1.11: OK
[execProcess] C:\PROGRA~1\RStudio\RESOUR~1\app\bin\quarto\bin\tools\x86_64\dart-sass\sass.bat --version
[execProcess] Success: true, code: 0
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.549
      Path: C:\PROGRA~1\RStudio\RESOUR~1\app\bin\quarto\bin
      CodePage: 1252
```

**Comment by cscheid** [comment]
That wouldn't surprise me. Can you try to run the latest from our git repo?

**Comment by kevinushey** [comment]
Seems the same:

```
==> quarto preview qqqq.qmd --to pdf --no-watch-inputs --no-browse

Quarto version: 99.9.9
[NotebookContext]: Starting Cleanup
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: undefined
Looking for 'Rscript' in R_HOME: C:/R/R-4.3.2
Looking for 'Rscript' in PATH.
[execProcess] CMD /C where Rscript
[execProcess] Success: true, code: 0
Found in PATH at C:\R\R-4.3.2\bin\x64\Rscript.exe
[execProcess] C:\R\R-4.3.2\bin\x64\Rscript.exe C:\Users\kevin\projects\QUARTO~1\src\resources\rmd\rmd.R


processing file: qqqq.qmd
1/5                  
2/5 [unnamed-chunk-1]
3/5                  
4/5 [unnamed-chunk-2]
5/5                  
output file: qqqq.knit.md

[execProcess] Success: false, code: -1073741819
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: undefined
Looking for 'Rscript' in R_HOME: C:/R/R-4.3.2
Looking for 'Rscript' in PATH.
[execProcess] CMD /C where Rscript
[execProcess] Success: true, code: 0
Found in PATH at C:\R\R-4.3.2\bin\x64\Rscript.exe
[execProcess] C:\R\R-4.3.2\bin\x64\Rscript.exe --version
[execProcess] Success: true, code: 0

++R found at C:\R\R-4.3.2\bin\x64\Rscript.exe is working.
-- Checking knitr engine capabilities --
[execProcess] C:\R\R-4.3.2\bin\x64\Rscript.exe C:\Users\kevin\projects\QUARTO~1\src\resources\capabilities\knitr.R
[execProcess] Success: false, code: -1073741819

++ Problem with results of knitr capabilities check.
    Return Code: -1073741819 (success is false)
    with stdout from R:
--- YAML_START ---
versionMajor: 4 
versionMinor: 3 
versionPatch: 2 
home: C:/R/R-4.3.2 
libPaths:
  - "C:/Users/kevin/AppData/Local/R/win-library/4.3" 
  - "C:/R/R-4.3.2/library" 
packages:
  knitr: "1.43"
  rmarkdown: "2.22"
--- YAML_END ---

Problem with running R found at C:\R\R-4.3.2\bin\x64\Rscript.exe to check environment configurations.
Please check your installation of R.

[NotebookContext]: Starting Cleanup
ERROR: Error
    at renderFiles (file:///C:/Users/kevin/projects/QUARTO~1/src/command/render/render-files.ts:354:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///C:/Users/kevin/projects/QUARTO~1/src/command/render/render-shared.ts:99:18)
    at async renderForPreview (file:///C:/Users/kevin/projects/QUARTO~1/src/command/preview/preview.ts:419:24)
    at async render (file:///C:/Users/kevin/projects/QUARTO~1/src/command/preview/preview.ts:165:22)
    at async preview (file:///C:/Users/kevin/projects/QUARTO~1/src/command/preview/preview.ts:182:18)
    at async Command.fn (file:///C:/Users/kevin/projects/QUARTO~1/src/command/preview/cmd.ts:415:7)
    at async Command.execute (file:///C:/Users/kevin/projects/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/kevin/projects/QUARTO~1/src/quarto.ts:155:3)
    at async file:///C:/Users/kevin/projects/QUARTO~1/src/quarto.ts:186:5
```

**Comment by cscheid** [comment]
Thanks - I wanted to check the stack trace to see if that could help.

If you want to try to brute force your way through this to see if that's the only problem, you could change line 277 of `src/execute/rmd.ts` to check for `(result.success || result.status === -1073741819)` (or something like that)

**Comment by cderv** [comment]
I do not have `Aarch64 builds of Windows` to test, but one question based on some other report we had: 

Did you use R binary for ARM? https://blog.r-project.org/2024/04/23/r-on-64-bit-arm-windows/ 

**rig** prerelease allows to install it also now: https://github.com/r-lib/rig/releases

Some of the previous report we had were about some R Packages used in x64 R not working on aarch64 windows for some reason. 

I wonder if the issue you noticed was with aarch64 version of R or not ? 

Thank you !

**Comment by remlapmot** [comment]
I'd say this is a problem of using the x86_64 R under emulation on AARCH64 Windows (you can see it's x86 R from the filepaths above). I found a very very similar error code using the Windows 11 on ARM GitHub Actions runner (running x86 R) - so you can recreate this yourself.

https://github.com/rstudio/rstudio/issues/15277#issuecomment-3324415176

It's so weird because the packages seem to work but for some mysterious reason they make R issue a non-zero exit code at the end of the R session (so maybe a problem with the x86_64 emulation) - in my testing R's exit code of 127 was converted to -1073741569 by Quarto.

I found I didn't get this problem if I used AARCH64 R on AARCH64 Windows.

Also it looks like Parallels VM and Apple Silicon Macs have improved/have some magic trick - because here @kevinushey reports a very similar error code as I found on the GHA runner - but a few months later he didn't seem to receive the error code anymore https://github.com/rstudio/rstudio/issues/15277#issuecomment-3324933274

**Comment by cderv** [comment]
> I'd say this is a problem of using the x86_64 R under emulation on AARCH64 Windows

Thanks, this confirms my understanding. 

> I found a very very similar error code using the Windows 11 on ARM GitHub Actions runner (running x86 R) - so you can recreate this yourself.

I'll try that thank you.

**Comment by remlapmot** [comment]
In case it's any help my demo repo (which is a mess) is at <https://github.com/remlapmot/windows-11-arm-quarto-example>

Here's a run which shows the error codes 
<https://github.com/remlapmot/windows-11-arm-quarto-example/actions/runs/20168464313/job/57897633626>
(the runs shows as passing because I ran it with `set +e` - i.e., don't stop on errors)
from <https://github.com/remlapmot/windows-11-arm-quarto-example/blob/main/.github/workflows/example-r-x86-exitcode-5.yml>

**Comment by cderv** [comment]
I also did one at https://github.com/cderv/quarto-windows-arm and I am currently in process on trying detect x64 R used on ARM windows to explain the problem we know about. (in `quarto check`)

**Comment by cderv** [comment]
@kevinushey, after investigating this in cderv/quarto-windows-arm, it seems to be related to some R functions not working well with certain R packages used by Quarto when running R x64 on Windows ARM. I plan to look at this deeper to understand this R failure on WOW64 emulation on Windows ARM. 

PR [#13822](https://github.com/quarto-dev/quarto-cli/pull/13822) tries to help detect that by looking at the error code and throwing a message to explain how to install R ARM on Windows ARM. It can be tested using the artifact build at https://github.com/quarto-dev/quarto-cli/actions/runs/20438280055 from the PR. 

The other option was #13790, but this involved trying to detect Windows ARM from a x64 Deno emulation. So for now, we prefer #13822 

I'll watch out how this evolve with future R versions though, but this is what we can currently do on Quarto side I guess.

**Comment by cderv** [comment]
For reference, Deno seems to build on ARM windows now:
- https://github.com/denoland/deno/pull/31917

So one more step to have a quarto ARM build probably.
