### ISSUE TITLE
Can't render PDF with fig-align="right"

### ISSUE THREAD

**Issue by m-fehr** [quarto-dev/quarto-cli#8733]
### Bug description

Getting started with Quarto, I wanted to test image alignment. While I can use "left," "center," and "right" when rendering to HTML, I get an error message when rendering to PDF.

### Steps to reproduce

https://github.com/m-fehr/Quarto_Alignment_Test

````quarto
---
title: "Quarto Testfile"
format: pdf
---

# Test alignment to the right

![dummy image](test_image.jpg){fig-align="left" #fig-logol  width=4in}

![dummy image](test_image.jpg){fig-align="center" #fig-logoc  width=4in}

![dummy image](test_image.jpg){fig-align="right" #fig-logor  width=4in}
````

### Expected behavior

I expect one image aligned to the left, another in the center, and a third one on the right, both in HTML and PDF.

### Actual behavior

I receive the following error message:
```bash
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:20464: wrong number of arguments to 'insert'
stack traceback:
        /Applications/quarto/share/filters/main.lua:20464: in field 'render'
        /Applications/quarto/share/filters/main.lua:835: in local 'filter_fn'
        /Applications/quarto/share/filters/main.lua:302: in function </Applications/quarto/share/filters/main.lua:292>
        (...tail calls...)
        [C]: in ?
        [C]: in method 'walk'
        /Applications/quarto/share/filters/main.lua:224: in function </Applications/quarto/share/filters/main.lua:214>
        (...tail calls...)
        /Applications/quarto/share/filters/main.lua:936: in local 'callback'
        /Applications/quarto/share/filters/main.lua:954: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:990: in function </Applications/quarto/share/filters/main.lua:987>
stack traceback:
        /Applications/quarto/share/filters/main.lua:224: in function </Applications/quarto/share/filters/main.lua:214>
        (...tail calls...)
        /Applications/quarto/share/filters/main.lua:936: in local 'callback'
        /Applications/quarto/share/filters/main.lua:954: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:990: in function </Applications/quarto/share/filters/main.lua:987>
ERROR: Error
    at renderFiles (file:///Applications/quarto/bin/quarto.js:77074:29)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///Applications/quarto/bin/quarto.js:81807:21)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:81954:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:114968:5)
    at async file:///Applications/quarto/bin/quarto.js:114986:9
```

### Your environment

- IDE VSCode Version: 1.86.0
- MacOS Sonoma 14.3

### Quarto check output

```bash
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.02
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mfehr/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
Thanks! That is a pretty bad bug. It's an easy fix and we'll have it out shortly.
