### ISSUE TITLE
listing glob without matches is error with stack

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9030]
### Bug description

When a listing glob has no matches, rendering fails with an error and a stack trace

### Steps to reproduce

````yaml
project:
  type: website
````

````markdown
---
title: listing
listing:
  contents: "sub/*.qmd"
---
````

### Expected behavior

Some listings may be created ahead of the files that match the glob. For example, an project could start with a listing `index.qmd` file and then later fill in the matching entries. The `index.qmd` would present no listing data until there are matching entries.

An empty listing glob should probably be a warning rather than an error. If it is required to be an error, that error should not present a stack trace.

### Actual behavior

```
ERROR: The listing in 'index.qmd' using the following contents:
- sub/*.qmd
doesn't match any files or folders.

Stack trace:
- sub/*.qmd
doesn't match any files or folders.
    at readContents (file:///Applications/quarto/bin/quarto.js:88746:19)
    at readListings (file:///Applications/quarto/bin/quarto.js:88416:42)
    at listingHtmlDependencies (file:///Applications/quarto/bin/quarto.js:90080:51)
    at Object.formatExtras (file:///Applications/quarto/bin/quarto.js:90400:51)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async runPandoc (file:///Applications/quarto/bin/quarto.js:68741:63)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:70041:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:77261:36)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77238:17)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77062:17)
```

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by aronatkins** [comment]
In the original example, the `sub` directory exists, but it contains no files.

The same type of error happens if you are globbing local files:

````markdown
---
title: listing
listing:
  contents: "thing-*.qmd"
---
````

```
ERROR: The listing in 'index.qmd' using the following contents:
- thing-*.qmd
doesn't match any files or folders.

Stack trace:
- thing-*.qmd
doesn't match any files or folders.
    at readContents (file:///Applications/quarto/bin/quarto.js:88746:19)
    at readListings (file:///Applications/quarto/bin/quarto.js:88416:42)
    at listingHtmlDependencies (file:///Applications/quarto/bin/quarto.js:90080:51)
    at Object.formatExtras (file:///Applications/quarto/bin/quarto.js:90400:51)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async runPandoc (file:///Applications/quarto/bin/quarto.js:68741:63)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:70041:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:77261:36)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77238:17)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77062:17)
```

**Comment by mcanouil** [comment]
I believe this is solved in 1.5 as the pre-render script is ran before file discovery now.

**Comment by cderv** [comment]
Stack trace thing is followed at 
* https://github.com/quarto-dev/quarto-cli/issues/9032

**Comment by aronatkins** [comment]
There is no pre-render script. The same error happens with quarto-1.5.24.

**Comment by dragonstyle** [comment]
This was purposely introduced here:

https://github.com/quarto-dev/quarto-cli/issues/5463

But I agree a warning is probably more sensible.

As for the stack trace, typically error stacks are controlled by whether stacks are enabled in the environment (or they are enabled by default in the debug version of the product). I'm not sure how this specific error could be enabling a stack trace (it is just a simple throw).

**Comment by aronatkins** [comment]
Thanks for the background, @dragonstyle. In my situation, I was trying to prepare a new directory within a Quarto project. Over time, that directory receives `ticket-NNNN.qmd` files, but it starts empty (other than having an `index.qmd` file configuring the listing).

We are creating a new, empty directory once a week; it would be useful to be able to add the skeleton directory structure and `index.qmd` without any of the target files.

This approach isn't required; now that we've realized this Quarto limitation, we're delaying directory creation until we have the first `ticket-NNN.qmd` file.

**Comment by dragonstyle** [comment]
I think a warning is about right (as you note) - it is helpful to users to highlight the lack of matching in the event that it is an error in the glob, but it seems to too strong to literally prevent it, since as you note, listings can be empty!
