### ISSUE TITLE
Rendering pdf  for book generates file not found error

### ISSUE THREAD

**Issue by dkapitan** [quarto-dev/quarto-cli#912]
## Environment
- clean quarto install on Ubuntu Linux (Windows Subsystem, Windows 11)
- clean install `quarto tools install tinytex`
- VS Code with quarto extension

## Reproduce error
- `quarto create-project test-pdf --type book`
- add example code below in `intro.qmd`
- render pdf with VS code extension
- `ERROR: NotFound: No such file or directory (os error 2)`

```
```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

**Comment by jjallaire** [comment]
I believe that we fixed this issue w/ this commit yesterday: https://github.com/quarto-dev/quarto-cli/commit/d24248605fe5d96b17c3f5f75379bc8a126a3264

Are you running on >= 0.9.415 ?

**Comment by cderv** [comment]
@jjallaire I can reproduce in using current dev version of quarto and outside of VS CODE also

Traceback of the issue 
```
ERROR: NotFound: No such file or directory (os error 2)

NotFound: No such file or directory (os error 2)
    at Object.opSync (deno:core/01_core.js:172:12)
    at Object.realPathSync (deno:runtime/js/30_fs.js:139:17)
    at renderCleanup (file:///home/cderv/project/quarto-cli/src/command/render/cleanup.ts:61:22)
    at cleanupExecutedFile (file:///home/cderv/project/quarto-cli/src/project/types/book/book-render.ts:513:3)
    at file:///home/cderv/project/quarto-cli/src/project/types/book/book-render.ts:106:9
    at Array.forEach (<anonymous>)
    at cleanupExecutedFiles (file:///home/cderv/project/quarto-cli/src/project/types/book/book-render.ts:105:29)
    at Object.onComplete (file:///home/cderv/project/quarto-cli/src/project/types/book/book-render.ts:214:9)
    at renderFiles (file:///home/cderv/project/quarto-cli/src/command/render/render-files.ts:437:36)
    at async renderProject (file:///home/cderv/project/quarto-cli/src/command/render/project.ts:247:23)
````

**Comment by jjallaire** [comment]
Okay, thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/cd0d8dcecffffea87154722c9ea25739229625ef (new build w/ this fix available shortly)

**Comment by vochicong** [comment]
I've tried the main branch (d7ad4d7) and still got the error.

### Environment

Arch Linux / WSL2 / Windows 11

### Error

```
$ quarto render --to pdf
Check file:///home/kon/tmp/quarto-cli/src/quarto.ts
[1/5] index.qmd
Check file:///home/kon/tmp/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
ERROR: NotFound: No such file or directory (os error 2)

NotFound: No such file or directory (os error 2)
    at opRun (deno:runtime/js/40_process.js:29:16)
    at Object.run (deno:runtime/js/40_process.js:112:17)
    at criClient (file:///home/kon/tmp/quarto-cli/src/core/cri/cri.ts:88:24)
    at async file:///home/kon/tmp/quarto-cli/src/core/cri/cri.ts:55:16
    at async Semaphore.runExclusive (file:///home/kon/tmp/quarto-cli/src/core/lib/semaphore.ts:42:22)
    at async Object.createPngsFromHtml (file:///home/kon/tmp/quarto-cli/src/core/handlers/base.ts:170:36)
    at async makePng (file:///home/kon/tmp/quarto-cli/src/core/handlers/mermaid.ts:279:11)
    at async makeDefault (file:///home/kon/tmp/quarto-cli/src/core/handlers/mermaid.ts:360:16)
    at async Object.cell (file:///home/kon/tmp/quarto-cli/src/core/handlers/mermaid.ts:400:14)
    at async Promise.all (index 0)
```

**Comment by vochicong** [comment]
@cderv Thank you for your response.

I've stopped using Arch Linux in WSL2 for now.
Quarto works perfectly in Ubuntu/WSL2 for me.
FYI, Quarto works well for natively running Arch Linux too.

I may come back and try Arch Linux in WSL2 later and will give update then.
