### ISSUE TITLE
Docusaurus `style` prop expects a mapping from style properties to values, not a string

### ISSUE THREAD

**Issue by krishaamer** [quarto-dev/quarto-cli#9179]
### Bug description

Docusaurus server-side rendering could not render static page with path ... because of error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.

**Comment by cscheid** [comment]
Can you give us a full .qmd that gives you the error?

**Comment by mcanouil** [comment]
You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by cscheid** [comment]
@krishaamer Sorry to ping you, but would it be possible for you to send us a repro case?

**Comment by krishaamer** [comment]
Thanks for trying to help @cscheid ! It happens on deploying to Vercel (which until 22 days ago was deploying fine).. Here's another log from my production app.. let me see I can get a minimal repro.

`[00:05:43.257] Running build in Washington, D.C., USA (East) – iad1
[00:05:43.364] Cloning github.com/krishaamer/green-filter-research (Branch: main, Commit: ed9aaee)
[00:05:43.661] Previous build cache not available
[00:05:45.713] Cloning completed: 2.349s
[00:05:45.969] Running "vercel build"
[00:05:46.413] Vercel CLI 33.7.0
[00:05:47.020] Installing dependencies...
[00:05:47.362] yarn install v1.22.22
[00:05:47.444] [1/4] Resolving packages...
[00:05:47.839] [2/4] Fetching packages...
[00:06:01.107] [3/4] Linking dependencies...
[00:06:01.111] warning "@docusaurus/core > react-loadable-ssr-addon-v5-slorber@1.0.1" has unmet peer dependency "react-loadable@*".
[00:06:01.114] warning "@docusaurus/core > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.3" has unmet peer dependency "typescript@>= 2.7".
[00:06:01.117] warning "@docusaurus/plugin-ideal-image > @slorber/react-ideal-image@0.0.12" has unmet peer dependency "prop-types@>=15".
[00:06:01.119] warning " > @mdx-js/react@3.0.1" has unmet peer dependency "@types/react@>=16".
[00:06:01.119] warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia@1.9.3" has unmet peer dependency "@algolia/client-search@>= 4.9.1 < 6".
[00:06:01.120] warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-core > @algolia/autocomplete-plugin-algolia-insights@1.9.3" has unmet peer dependency "search-insights@>= 1 < 3".
[00:06:01.120] warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-core > @algolia/autocomplete-shared@1.9.3" has unmet peer dependency "@algolia/client-search@>= 4.9.1 < 6".
[00:06:07.369] [4/4] Building fresh packages...
[00:06:08.796] Done in 21.44s.
[00:06:08.833] Running "yarn run build"
[00:06:09.027] yarn run v1.22.22
[00:06:09.058] $ docusaurus build
[00:06:10.332] [INFO] [en] Creating an optimized production build...
[00:06:11.377] [info] [webpackbar] Compiling Client
[00:06:11.399] [info] [webpackbar] Compiling Server
[00:06:34.797] [success] [webpackbar] Server: Compiled successfully in 23.40s
[00:06:44.670] [success] [webpackbar] Client: Compiled successfully in 33.29s
[00:06:48.348] 
[00:06:48.351] [ERROR] Error: Unable to build website for locale en.
[00:06:48.351]     at tryToBuildLocale (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:53:19)
[00:06:48.351]     at async /vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:64:9
[00:06:48.351]     at async mapAsyncSequential (/vercel/path0/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
[00:06:48.351]     at async Command.build (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
[00:06:48.351]   [cause]: Error: Docusaurus static site generation failed for 3 paths:
[00:06:48.351]   - "/research/discussion"
[00:06:48.351]   - "/research/literature/ai"
[00:06:48.352]   - "/research/literature/sustainability"
[00:06:48.352]       at generateStaticFiles (/vercel/path0/node_modules/@docusaurus/core/lib/ssg.js:85:15)
[00:06:48.352]       at async executeSSG (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:146:23)
[00:06:48.352]       ... 4 lines matching cause stack trace ...
[00:06:48.352]       at async Command.build (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
[00:06:48.352]     [cause]: AggregateError
[00:06:48.352]         at generateStaticFiles (/vercel/path0/node_modules/@docusaurus/core/lib/ssg.js:86:20)
[00:06:48.352]         at async executeSSG (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:146:23)
[00:06:48.352]         at async buildLocale (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:126:31)
[00:06:48.352]         at async tryToBuildLocale (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:46:13)
[00:06:48.352]         at async /vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:64:9
[00:06:48.352]         at async mapAsyncSequential (/vercel/path0/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
[00:06:48.352]         at async Command.build (/vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
[00:06:48.352]       [errors]: [
[00:06:48.352]         Error: Can't render static file for pathname "/research/discussion"
[00:06:48.352]             at generateStaticFile (/vercel/path0/node_modules/@docusaurus/core/lib/ssg.js:119:15)
[00:06:48.352]             at runNextTicks (node:internal/process/task_queues:60:5)
[00:06:48.352]             at process.processImmediate (node:internal/timers:449:9)
[00:06:48.352]             at async /vercel/path0/node_modules/p-map/index.js:57:22 {
[00:06:48.352]           [cause]: Error: Expected component `Figure` to be defined: you likely forgot to import, pass, or provide it.
[00:06:48.352]               at _missingMdxReference (server.bundle.js:1041:9)
[00:06:48.352]               at _createMdxContent (server.bundle.js:575:16)
[00:06:48.352]               at MDXContent (server.bundle.js:1038:8)
[00:06:48.352]               at Uc (server.bundle.js:46586:44)
[00:06:48.352]               at Xc (server.bundle.js:46588:253)
[00:06:48.352]               at Z (server.bundle.js:46594:89)
[00:06:48.352]               at Xc (server.bundle.js:46592:231)
[00:06:48.352]               at Z (server.bundle.js:46594:89)
[00:06:48.352]               at Xc (server.bundle.js:46588:481)
[00:06:48.352]               at Z (server.bundle.js:46594:89)
[00:06:48.353]         },
[00:06:48.353]         Error: Can't render static file for pathname "/research/literature/ai"
[00:06:48.353]             at generateStaticFile (/vercel/path0/node_modules/@docusaurus/core/lib/ssg.js:119:15)
[00:06:48.353]             at runNextTicks (node:internal/process/task_queues:60:5)
[00:06:48.353]             at process.processImmediate (node:internal/timers:449:9)
[00:06:48.353]             at async /vercel/path0/node_modules/p-map/index.js:57:22 {
[00:06:48.353]           [cause]: Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
[00:06:48.353]               at Fa (server.bundle.js:46543:49)
[00:06:48.353]               at K (server.bundle.js:46545:44)
[00:06:48.353]               at Pa (server.bundle.js:46555:222)
[00:06:48.353]               at Xc (server.bundle.js:46589:32)
[00:06:48.353]               at Z (server.bundle.js:46594:89)
[00:06:48.353]               at Yc (server.bundle.js:46597:98)
[00:06:48.353]               at $c (server.bundle.js:46596:140)
[00:06:48.353]               at Z (server.bundle.js:46594:345)
[00:06:48.353]               at Yc (server.bundle.js:46597:98)
[00:06:48.353]               at Xc (server.bundle.js:46589:145)
[00:06:48.353]         },
[00:06:48.353]         Error: Can't render static file for pathname "/research/literature/sustainability"
[00:06:48.354]             at generateStaticFile (/vercel/path0/node_modules/@docusaurus/core/lib/ssg.js:119:15)
[00:06:48.354]             at runNextTicks (node:internal/process/task_queues:60:5)
[00:06:48.354]             at process.processImmediate (node:internal/timers:449:9)
[00:06:48.354]             at async /vercel/path0/node_modules/p-map/index.js:57:22 {
[00:06:48.354]           [cause]: Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
[00:06:48.354]               at Fa (server.bundle.js:46543:49)
[00:06:48.354]               at K (server.bundle.js:46545:44)
[00:06:48.354]               at Ka (server.bundle.js:46548:184)
[00:06:48.354]               at Pa (server.bundle.js:46556:68)
[00:06:48.354]               at Xc (server.bundle.js:46589:32)
[00:06:48.354]               at Z (server.bundle.js:46594:89)
[00:06:48.354]               at Yc (server.bundle.js:46597:98)
[00:06:48.354]               at $c (server.bundle.js:46596:140)
[00:06:48.354]               at Z (server.bundle.js:46594:345)
[00:06:48.354]               at Xc (server.bundle.js:46589:476)
[00:06:48.354]         }
[00:06:48.354]       ]
[00:06:48.354]     }
[00:06:48.354]   }
[00:06:48.354] }
[00:06:48.355] [INFO] Docusaurus version: 3.2.1
[00:06:48.355] Node version: v20.12.1
[00:06:48.421] error Command failed with exit code 1.
[00:06:48.422] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[00:06:48.436] Error: Command "yarn run build" exited with 1
[00:06:48.919] `

**Comment by cscheid** [comment]
> Warning: Invalid DOM property `rowspan`. Did you mean `rowSpan`?

This is pretty sus.

> and also on localhost only on pages that have markdown tables (however some tables work)

Can you share those tables? I've tried a few things and still can't repro.

**Comment by cscheid** [comment]
Expanding more, I don't know how you're getting `rowspan` into markdown tables; Our docusaurus writer is relatively limited when it comes to markdown tables. Given a grid table, for example, we emit back a plain markdown table with no rowspans or colspans:

````markdown
---
title: table test
---

+---------------------+----------+
| Property            | Earth    |
+=============+=======+==========+
|             | min   | -89.2 °C |
| Temperature +-------+----------+
| 1961-1990   | mean  | 14 °C    |
|             +-------+----------+
|             | min   | 56.7 °C  |
+-------------+-------+----------+
````

```
$ quarto render tables.qmd --to docusaurus
$ cat tables.mdx
---
title: table test
---




| Property              |      | Earth    |
|-----------------------|------|----------|
| Temperature 1961-1990 | min  | -89.2 °C |
|                       | mean | 14 °C    |
|                       | min  | 56.7 °C  |
```

**Comment by krishaamer** [comment]
Hi @cscheid I managed to get a broken minimal repro, posted here: https://github.com/krishaamer/quarto-broken-citations-reproducible/tree/broken-markdown-tables

When I remove the MD title markers # from the table it starts to work.

<img width="592" alt="Screenshot 2024-04-10 at 17 34 49" src="https://github.com/quarto-dev/quarto-cli/assets/54409/ce9fccdb-1beb-4410-98de-e5eba3b77e6a">

**Comment by mcanouil** [comment]
Maybe a naive question, but why is there markdown headers in the table?

Also could you not share code as screenshot? It makes the code shared unusable. Thank you.

**Comment by krishaamer** [comment]
> Maybe a naive question, but why is there markdown headers in the table?
I was using the the VSCode "Edit in Visual Mode" to create the MD tabless. I got one file working by removing the # titles however another one is still broken without any titles inside the tables so probably some other markers are also problematic.

> Also could you not share code as screenshot? It makes the code shared unusable. Thank you.

Sure, here's the screenshotted code from the repro: https://github.com/krishaamer/quarto-broken-citations-reproducible/blob/broken-markdown-tables/research/broken.qmd

**Comment by cscheid** [comment]
Thank you, I can repro locally now. 

This is a bit of a wild one - the presence of the headings inside cells causes _Pandoc_ to emit HTML tables in the commonmark writer.

```
$ cat 9179.md
+-------+-------+---------------------------------------------+-------+
| # ad  | # ad  | # asd                                       |       |
+-------+-------+---------------------------------------------+-------+
|       |       |                                             |       |
+-------+-------+---------------------------------------------+-------+
| ad    | 2015  |                                             |       |
+-------+-------+---------------------------------------------+-------+
| aad   | 2021  | ad                                          |       |
+-------+-------+---------------------------------------------+-------+
| asd   | ad    | asd                                         |       |
+-------+-------+---------------------------------------------+-------+
| ad    | ad    | asd                                         |       |
+-------+-------+---------------------------------------------+-------+
| add   | ad    |                                             |       |
+-------+-------+---------------------------------------------+-------+
$ cat 9179.md | pandoc -f markdown -t commonmark
<table style="width:97%;">
<colgroup>
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 63%" />
<col style="width: 11%" />
</colgroup>
<tbody>
<tr class="odd">
<td><h1 id="ad">ad</h1></td>
<td><h1 id="ad-1">ad</h1></td>
<td><h1 id="asd">asd</h1></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>ad</td>
<td>2015</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>aad</td>
<td>2021</td>
<td>ad</td>
<td></td>
</tr>
<tr class="odd">
<td>asd</td>
<td>ad</td>
<td>asd</td>
<td></td>
</tr>
<tr class="even">
<td>ad</td>
<td>ad</td>
<td>asd</td>
<td></td>
</tr>
<tr class="odd">
<td>add</td>
<td>ad</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
```

Quarto is simply emitting this as an .mdx output, and MDX appears to be interpreting this as a react component (or something?), and so wants the structured form of the `style` property. What we need to do is wrap this HTML in an unsafe block.

The problem, however, is that I don't know how to detect when Pandoc will choose to emit HTML rather than Markdown as its output.

**Comment by mcanouil** [comment]
Isn't it something that Pandoc's developers could help with?

**Comment by cscheid** [comment]
Furthermore:

```hs
...
  let hasSimpleCells = onlySimpleTableCells $ headers : rows
  let isSimple = hasSimpleCells && all (==0) widths
...
  let isPlainBlock (Plain _) = True
      isPlainBlock _         = False
  let hasBlocks = not (all isPlainBlock $ concat . concat $ headers:rows)
...
```

`onlySimpleTableCells` comes from 

https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Shared.hs#L628-L637

```hs
onlySimpleTableCells :: [[[Block]]] -> Bool
onlySimpleTableCells = all isSimpleCell . concat
  where
    isSimpleCell [Plain ils] = not (hasLineBreak ils)
    isSimpleCell [Para ils ] = not (hasLineBreak ils)
    isSimpleCell []          = True
    isSimpleCell _           = False
    hasLineBreak = getAny . query isLineBreak
    isLineBreak LineBreak = Any True
    isLineBreak _         = Any False
```

None of this is exposed to Lua, sadly. There's at least two ways we could solve this:

1. Reimplement this logic in Lua
2. Perform a test write of the table output to commonmark, and if it comes back looking like HTML, then we add a wrapper block

I actually like option 2 better, because it's more robust against future changes in Pandoc (both in requiring changes to the required Lua reimplementation, and more likely to require such changes to begin with)
