### ISSUE TITLE
quarto publish quarto-pub does not seem to be able to update a deployed document 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9228]
Related to #9204 , updating a single file within a project seems not possible as it will round-trip to document creation 

````
❯ quarto publish quarto-pub index.qmd
? Publish update to: » https://examples.quarto.pub/collapsed-callout (Quarto Pub - quarto-examples@posit.co)
? Publish with account: » quarto-examples@posit.co
? Document name: » Use another name...
? Publish with name: » collapsed-callout
  The specified name is already in use within your account.
? Publish with name: »
ERROR: Error
    at promptForSlug (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:394:13)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async handlePublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:94:14)
    at async publishDocument (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:310:36)
    at async publish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:276:9)
    at async doPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:199:7)
    at async publishAction (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:252:7)
    at async Command.actionHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:157:11)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
````

- Example is already published
- `quarto publish` finds the existing url
- `quarto publish` wants to change name, and does not allow to reusing the same name. 

Not ideal behavior possibly linked... 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/8623908d-370d-4b78-99d6-f7d4803a1a10)

Document Name prompted will be used for the URL, but the title is not modified, and the one from the document name is used. 
It would have been better to have maybe a way to configure Title. 

Note that even using another name as `index.qmd` makes this problem happen.

**Comment by jthomasmock** [comment]
Ran into this one as well today 😢
