### ISSUE TITLE
"ERROR: TypeError: cell.source.join is not a function" thrown when running `quarto preview` with a notebook

### ISSUE THREAD

**Issue by nickvigilante** [quarto-dev/quarto-cli#9255]
### Bug description

We're in the process of migrating over notebooks from one repo to another. These notebooks run fine with the `jupyter execute` command, and they open with no issues in VS Code. However, if I copy them directly into my Quarto project and try to run any of the `quarto` commands, I get the error seen in **Actual behavior**.

However, if I open the notebook in VS Code, change anything about the notebook, and then save the notebook, Quarto runs fine.

### Steps to reproduce

```bash
git clone https://github.com/nickvigilante/cell-source-join-not-a-function-bug
cd cell-source-join-not-a-function-bug
quarto preview
```

### Expected behavior

If the notebook is properly formed, then Quarto should build without issues. If the notebook is not properly formed, there should be an error message with the path of the notebook from the repo root indicating a more detailed explanation of the problem.

### Actual behavior

```
(miniconda3)➜  cell-source-join-not-a-function-bug git:(main) quarto preview
Preparing to preview
ERROR: TypeError: cell.source.join is not a function

Stack trace:
    at file:///Applications/quarto/bin/quarto.js:31657:64
    at Array.findIndex (<anonymous>)
    at fixupFrontMatter (file:///Applications/quarto/bin/quarto.js:31655:43)
    at markdownFromNotebookJSON (file:///Applications/quarto/bin/quarto.js:37472:10)
    at Object.target (file:///Applications/quarto/bin/quarto.js:38270:43)
    at fileExecutionEngineAndTarget (file:///Applications/quarto/bin/quarto.js:41263:33)
    at renderContexts (file:///Applications/quarto/bin/quarto.js:72188:38)
    at Object.renderFormats (file:///Applications/quarto/bin/quarto.js:72239:28)
    at file:///Applications/quarto/bin/quarto.js:73385:91
    at withRenderServices (file:///Applications/quarto/bin/quarto.js:72594:12)
(miniconda3)➜  cell-source-join-not-a-function-bug git:(main) 
```

No filename is printed indicating where the problem is, which makes it difficult to troubleshoot.

### Your environment

- OS: macOS Sonoma 14.4.1

### Quarto check output

```
(miniconda3)➜  cell-source-join-not-a-function-bug git:(main) quarto check
Quarto 1.4.552
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.552
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /Users/nickv/miniconda3/bin/python
      Jupyter: 5.5.0
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

(miniconda3)➜  cell-source-join-not-a-function-bug git:(main) 
```

**Comment by cscheid** [comment]
Thanks for the report. Quarto is failing to consider the case where `cell.source` is a single string, which is allowed according to the [jupyter docs](https://ipython.org/ipython-doc/3/notebook/nbformat.html)

**Comment by nickvigilante** [comment]
Thank you for the expedient fix!
