### ISSUE TITLE
Stack trace for include shortcode in addition to error message

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9353]
### Bug description

When the file for a include shortcode is not found, a stack trace is also displayed in addition to the error message.

### Steps to reproduce

````qmd
---
title: "Quarto Playground"
format: html
---

{{< include _does-not-exist.qmd >}}
````

### Expected behavior

Only the error message.

```sh
ERROR: Include directive failed.
  in file /Users/mcanouil/Projects/quarto/quarto-playground/index.qmd, 
  could not find file /Users/mcanouil/Projects/quarto/quarto-playground/_does-not-exist.qmd.
```

### Actual behavior

```sh
ERROR: Include directive failed.
  in file /Users/mcanouil/Projects/quarto/quarto-playground/index.qmd, 
  could not find file /Users/mcanouil/Projects/quarto/quarto-playground/_does-not-exist.qmd.

Stack trace:
  in file /Users/mcanouil/Projects/quarto/quarto-playground/index.qmd, 
  could not find file /Users/mcanouil/Projects/quarto/quarto-playground/_does-not-exist.qmd.
    at retrieveInclude (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/core/handlers/include-standalone.ts:61:13)
    at standaloneInclude (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/core/handlers/include-standalone.ts:99:9)
    at processMarkdownIncludes (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/core/handlers/base.ts:369:28)
    at expandIncludes (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/core/handlers/base.ts:408:9)
    at async projectResolveFullMarkdownForFile (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/project/project-shared.ts:460:20)
    at async fileExecutionEngine (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/execute/engine.ts:170:22)
    at async fileExecutionEngineAndTarget (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/execute/engine.ts:201:18)
    at async renderContexts (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render-contexts.ts:222:30)
    at async renderFormats (file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/render/render-contexts.ts:313:20)
    at async file:///Users/mcanouil/Projects/quarto/quarto-cli/src/command/preview/cmd.ts:284:18
```

**Comment by mcanouil** [comment]
On a related note, the document below renders without any errors or warnings and the "bad" shortcode is completely removed from the AST.

````qmd
---
title: "Quarto Playground"
format: html
---

{{< include _does-not-exist.qmd >>>>>>>>>}}
````

(I put a lot of `>` simply to make it obvious there is a syntax issue)

**Comment by cderv** [comment]
Note that we currently have a bad behavior (IMO) where we show stack trace for all error now 
* https://github.com/quarto-dev/quarto-cli/issues/9032
Unless it has been fixed since I observed this.

**Comment by cscheid** [comment]
> On a related note, the document below renders without any errors or warnings and the "bad" shortcode is completely removed from the AST.
> 
> ```
> ---
> title: "Quarto Playground"
> format: html
> ---
> 
> {{< include _does-not-exist.qmd >>>>>>>>>}}
> ```
> 
> (I put a lot of `>` simply to make it obvious there is a syntax issue)

It's unfortunate and surprising, but it will be _very_ hard to give a good error message here, because we're doing shortcode parsing in Lua. This will have to wait for our linting epic.

**Comment by cscheid** [comment]
Yeah I'm pretty sure this is a dupliacte of #9032.
