### ISSUE TITLE
site without site block errs

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#94]
Using Quarto v0.2.94

Given a `_quarto.yml` file that declares a site but without a `site` block:

```yaml
project:
  type: site
```

Quarto will err when `quarto render`:

```
ERROR: TypeError: Cannot read property 'title' of undefined
    at title (file:///Users/aron/dev/rstudio/quarto-cli/src/project/types/website/website-navigation-md.ts:113:9)
    at Object.getUnrendered (file:///Users/aron/dev/rstudio/quarto-cli/src/project/types/website/website-navigation-md.ts:132:25)
    at file:///Users/aron/dev/rstudio/quarto-cli/src/project/types/website/website-navigation-md.ts:38:8
    at Array.forEach (<anonymous>)
    at createMarkdownEnvelope (file:///Users/aron/dev/rstudio/quarto-cli/src/project/types/website/website-navigation-md.ts:36:12)
    at websiteNavigationExtras (file:///Users/aron/dev/rstudio/quarto-cli/src/project/types/website/website-navigation.ts:237:9)
    at async Object.formatExtras (file:///Users/aron/dev/rstudio/quarto-cli/src/project/types/website/website.ts:114:11)
    at async runPandoc (file:///Users/aron/dev/rstudio/quarto-cli/src/command/render/pandoc.ts:165:10)
    at async renderPandoc (file:///Users/aron/dev/rstudio/quarto-cli/src/command/render/render.ts:498:24)
    at async Object.onRender (file:///Users/aron/dev/rstudio/quarto-cli/src/command/render/render.ts:678:26)
```

Running `quarto serve`, the command displays the same error and loops until killed.

The error goes away with an empty `site` block; the `title` is unnecessary:

```yaml
project:
  type: site

site: {}
```

**Comment by jjallaire** [comment]
Thx, seems like we should definitely tolerate the empty site. Will fix this after the current code freeze.

**Comment by dragonstyle** [comment]
@aronatkins Thank you for reporting this, it should be resolved now!
