### ISSUE TITLE
Sanitize CSS and HTML resources for URL modifiers, such as `...?#iefix`

### ISSUE THREAD

**Issue by andrie** [quarto-dev/quarto-cli#9547]
### Bug description

I get this error on rendering an HTML document:

```
Watching files for changes
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123): stat 'C:\Users\apdev\Documents\github\experiments\modal\font\weathericons-regular-webfont.eot?#iefix'
```

It seems that Quarto is  looking at the HTML/CSS to find resources that we need to monitor for changes, and we're not sanitizing them for URL appendages like ?#iefix

This is my yaml header:

```` md
---
title: "Thames River Conditions"
format: 
  html:
    css: 
    - custom.css
    - css/weather-icons.min.css
    - css/weather-icons-wind.css
    include-in-header: 
        - text: <script type="text/javascript" src="js/modal.js"></script>
    resource-path: 
      - js/modal.js
      - css/*
      - font/*
      - font/weathericons-regular-webfont.ttf
      - font/weathericons-regular-webfont.eot
---

```{=html}
<link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
<script src="https://unpkg.com/suncalc"></script>
```
````

### Stack trace

```
Watching files for changes
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123): stat 'C:\Users\apdev\Documents\github\paddling\modal\font\weathericons-regular-webfont.eot?#iefix'

Stack trace:
    at Object.statSync (ext:deno_fs/30_fs.js:363:7)
    at existsSync (file:///C:/Users/apdev/scoop/apps/quarto/current/bin/quarto.js:495:27)
    at file:///C:/Users/apdev/scoop/apps/quarto/current/bin/quarto.js:82933:44
    at Array.filter (<anonymous>)
    at file:///C:/Users/apdev/scoop/apps/quarto/current/bin/quarto.js:82933:32
    at Array.map (<anonymous>)
    at previewWatcher (file:///C:/Users/apdev/scoop/apps/quarto/current/bin/quarto.js:82930:23)
    at sync (file:///C:/Users/apdev/scoop/apps/quarto/current/bin/quarto.js:82919:23)
    at createChangeHandler (file:///C:/Users/apdev/scoop/apps/quarto/current/bin/quarto.js:82923:5)
    at preview (file:///C:/Users/apdev/scoop/apps/quarto/current/bin/quarto.js:82726:27)
```

### Repo with reprex

The following file contains the reprex

https://github.com/andrie/modal/blob/main/streaming-conditions.qmd

I can spend some more time to attempt to make it more minimal.

**Comment by cscheid** [comment]
@andrie Can you give me a full repository or a full stacktrace?

**Comment by andrie** [comment]
I have updated the original report with a stacktrace and repo.

**Comment by cscheid** [comment]
@cderv I've assigned this to you because I can't repro the problem on macOS. I think I fixed this in the branch `bugfix/9547`, but I can't really test it locally. Would it be possible for you to check my fix? Thanks!
