### ISSUE TITLE
Shortcode escaping no longer works with `include`

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#9635]
### Bug description

[The docs for the `var` shortcode](https://quarto.org/docs/authoring/variables.html#escaping) say it can be escaped using:
````
```{shortcodes=false}
{{< var version >}}
```
````

This also used to work for the `include` shortcode, but now results in an error.

Either this is a regression that needs fixing, or possibly (since it was documented only under the `var` shortcode), a feature request for similar escaping for `include`. 

### Steps to reproduce

````
---
title: "Untitled"
format: html
---

```{shortcodes=false}
{{< include file.qmd >}}
```
````

### Expected behavior

Intermediate markdown that looks like:
````
# Untitled

```
{{< include file.qmd >}}
```
````

### Actual behavior

An error:
```
ERROR: Include directive failed.
  in file /Users/charlottewickham/Documents/posit/weekly-log/2024-05-06/shortcode-escape.qmd, 
  could not find file /Users/charlottewickham/Documents/posit/weekly-log/2024-05-06/file.qmd.

Stack trace:
  in file /Users/charlottewickham/Documents/posit/weekly-log/2024-05-06/shortcode-escape.qmd, 
  could not find file /Users/charlottewickham/Documents/posit/weekly-log/2024-05-06/file.qmd.
    at retrieveInclude (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/core/handlers/include-standalone.ts:61:13)
    at standaloneInclude (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/core/handlers/include-standalone.ts:99:9)
    at processMarkdownIncludes (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/core/handlers/base.ts:369:28)
    at expandIncludes (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/core/handlers/base.ts:408:9)
    at async projectResolveFullMarkdownForFile (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/project/project-shared.ts:460:20)
    at async fileExecutionEngine (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/execute/engine.ts:170:22)
    at async fileExecutionEngineAndTarget (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/execute/engine.ts:201:18)
    at async renderContexts (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/command/render/render-contexts.ts:222:30)
    at async renderFormats (file:///Users/charlottewickham/Documents/posit/quarto-cli/src/command/render/render-contexts.ts:313:20)
    at async file:///Users/charlottewickham/Documents/posit/quarto-cli/src/command/preview/cmd.ts:284:18
```

### Your environment

- OS: Mac OS Sonoma 14.4.1

### Quarto check output

```bash
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.13: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
fatal: not a git repository (or any of the parent directories): .git
      Path: /Users/charlottewickham/Documents/posit/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/charlottewickham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /Users/charlottewickham/Documents/posit/quarto-web/.venv/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.10, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/charlottewickham/Library/R/arm64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

```

**Comment by cscheid** [comment]
I agree that we should offer support for that. In the meantime, though, the "standard" way to avoiding shortcode expansion in code blocks works:

````
---
title: "Untitled"
format: html
---

```
{{{< include file.qmd >}}}
```
````

Note the extra `{` and `}`, in analogy to how code cells can avoid execution. But if we have `{shortcodes=false}` support in one place, we should have it everywhere.
