### ISSUE TITLE
PDF Export Mode does not work

### ISSUE THREAD

**Issue by WolfgangSpahn** [quarto-dev/quarto-cli#9704]
### Bug description

When trying to use the "Pdf Export Mode" from the Menu in quarto reveal.js I get this error, visible in console

~~~
Uncaught TypeError: PdfExport.togglePdfExport is not a function
    at quarto-menu.js:41:15
    at Object.togglePdfExport (quarto-menu.js:4:5)
    at HTMLAnchorElement.onclick ((index):1930:37)
~~~~

I use Chrome Version 124.0.6367.208 (Official Build) (64-bit)

### Steps to reproduce

The problem appears to me at every presentation even with your demo

### Expected behavior

Should open PdfExport Window

### Actual behavior

Throws an error instead

### Your environment

- Windows: Chrome Version 124.0.6367.208 (Official Build) (64-bit)

### Quarto check output

~~~~
Quarto 1.4.553
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.553
      Path: C:\Users\Wolfgang Spahn\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
      ~~~~

**Comment by cderv** [comment]
Thanks a lot for the report. I'll fix this for next patch release. We missed this regression. sorry.

**Comment by cderv** [comment]
This has been backported to 1.4 for next patch release. 

Thanks again !
