### ISSUE TITLE
Wrong chromium installed on linux arm64

### ISSUE THREAD

**Issue by hwine** [quarto-dev/quarto-cli#9710]
### Bug description

Using Ubuntu 22-04 LTS on arm64, `quarto install` to install chromium succeeds, and `quarto check` reports no issues, however execution fails with an error indicating an `x86_64` binary was installed. 

I note that refused to install TinyTeX:
```bash
$ quarto install TinyTeX
Installing TinyTeX
This platform doesn't support installation at this time. Please install manually instead. See https://yihui.org/tinytex/#installation.
```
But the default install from there worked fine (`wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh`).

### Steps to reproduce

`````bash
$ quarto install chromium
$ quarto check
$ cat test.qmd
---
title: "test page"
---

Use Mermaid to force PDF rendering to try to use chromium installed by quarto

```{mermaid}
graph TD
    A <--> B
```
$ quarto render test.qmd --to pdf
`````

### Expected behavior

Obtain `test.pdf` with a simple mermaid diagram.

### Actual behavior

```bash
$ quarto render test.qmd --to pdf
ERROR: Couldn't find open server.
Chrome process error: x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory


Stack trace:
Chrome process error: x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

    at criClient (file:///opt/quarto/bin/quarto.js:40053:15)
    at eventLoopTick (ext:core/01_core.js:197:13)
    at async file:///opt/quarto/bin/quarto.js:40015:22
    at async Semaphore.runExclusive (file:///opt/quarto/bin/quarto.js:39692:29)
    at async Object.createPngsFromHtml (file:///opt/quarto/bin/quarto.js:40267:42)
    at async makePng (file:///opt/quarto/bin/quarto.js:73955:70)
    at async makeDefault (file:///opt/quarto/bin/quarto.js:74015:24)
    at async Object.cell (file:///opt/quarto/bin/quarto.js:74038:20)
    at async Promise.all (index 0)
    at async Object.document (file:///opt/quarto/bin/quarto.js:40528:25)
$ 
```

### Your environment

IDE: cli
OS:
```bash
$ uname -a
Linux ubuntu-arm64 5.15.0-107-generic #117-Ubuntu SMP Mon Apr 29 14:37:09 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

### Quarto check output

```bash
$ quarto check
Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/hwine/.TinyTeX/bin/aarch64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /home/hwine/.pyenv/versions/3.12.3/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Are you running in a qemu setting or even in a Docker container?

**Comment by hwine** [comment]
No qemu, no docker -- native arm64.

**Comment by cderv** [comment]
Regarding comment on TinyTeX 

> But the default install from there worked fine (wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh).

What does `uname` and `uname -m` returns in your terminal ? The script is checking this to know what to download

And also is `$OSTYPE` set ? or `bash -c 'echo $OSTYPE'` ? 

In Quarto we only consider that binary are available for `x86_64` architecture, because in TinyTeX project the bundle that quarto wants is not available for other arch. 

However, TinyTeX is released also as a special `installer-unix` bundle but it is not the same as other - lightweigth and less tested. 
So if you are a special architecture, installing install TinyTeX using the script is ok. 

Regarding Chromium issue, I believe this is related to Puppeteer no having ARM64 binary dowload from chromium. 
* https://github.com/puppeteer/puppeteer/issues/7740

We may want to detect arch and act accordingly.

**Comment by hwine** [comment]
> Regarding comment on TinyTeX
> 
> > But the default install from there worked fine (wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh).
> 
> What does `uname` and `uname -m` returns in your terminal ? The script is checking this to know what to download

```bash
❯ uname
Linux
❯ uname -m
aarch64
```

> And also is `$OSTYPE` set ? or `bash -c 'echo $OSTYPE'` ?

```bash
❯ echo $OSTYPE
linux-gnu
```

> However, TinyTeX is released also as a special `installer-unix` bundle but it is not the same as other - lightweigth and less tested. So if you are a special architecture, installing install TinyTeX using the script is ok.

This would be great to document.

> Regarding Chromium issue, I believe this is related to Puppeteer no having ARM64 binary dowload from chromium.

Well, not for Linux, but they do have one for Darwin ;)

> We may want to detect arch and act accordingly.

That, with a note to a wiki page or FAQ would be a much nicer n00b experience!

**Comment by jtkiley** [comment]
I get the same error when running bookworm arm64 in a docker dev container (on a Mac).

I was able to work around it with:

```
sudo apt-get install -y chromium
ln -s `which chromium` $HOME/.local/bin/chromium-browser
```

Mermaid output isn't great (e.g., overflowing page edges, cut off parts of the flowchart with `fig-width` and `fig-height` set, and so on), but I'm not sure how much of that is true outside of this issue and how much (if any) is attributable to the workaround.

**Comment by cderv** [comment]
This is addressed in #14334 (targeting main/v1.10) and backported in #14335 (targeting v1.9).

`quarto install chromium` used Puppeteer 9.0.2 which only had x86_64 Linux builds — it silently installed the wrong architecture on arm64. The fix adds arm64 Linux support to `quarto install chrome-headless-shell` via Microsoft's Playwright CDN, which provides arm64 builds. `quarto install chromium` now shows a deprecation warning directing users to `chrome-headless-shell` instead.

For arm64 users on current Quarto releases, the workaround is installing a system Chromium (`apt install chromium`) — Quarto detects it automatically.
