### ISSUE TITLE
Cannot read properties of undefined (reading 'name') when specifying Jupyter kernel specification 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9896]
When I create a notebook:
```python
import nbformat

# create notebook
nb = nbformat.v4.new_notebook()
raw_cell_content = """---
title: "Preprocessing of data"
format:
  html: default
execute: 
  enabled: true
jupyter:
  kernel: conda-paths-3.12
---"""

nb["cells"] += [nbformat.v4.new_raw_cell(raw_cell_content)]
test_cell = """x = 1
print(x)"""
nb["cells"] += [nbformat.v4.new_code_cell(test_cell)]
with open("test-notebook.ipynb", "w", encoding="utf-8") as f:
    nbformat.write(nb, f)
```
Running it with vscode

`quarto preview test-notebook.ipynb --to html --no-browser --no-watch-inputs`
gives me error
```
ERROR: TypeError: Cannot read properties of undefined (reading 'name')

Stack trace:
    at ensureYamlKernelspec (file:///Applications/quarto/bin/quarto.js:38580:48)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Object.execute (file:///Applications/quarto/bin/quarto.js:38358:30)
    at async renderExecute (file:///Applications/quarto/bin/quarto.js:77017:27)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77199:43)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77067:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:77394:25)
    at async renderForPreview (file:///Applications/quarto/bin/quarto.js:82818:26)
    at async render (file:///Applications/quarto/bin/quarto.js:82703:29)
    at async preview (file:///Applications/quarto/bin/quarto.js:82714:21)
 ```

_Originally posted by @danieltomasz in https://github.com/quarto-dev/quarto-cli/issues/5376#issuecomment-2151233644_

**Comment by cderv** [comment]
If the enabled is removed, then no issue 
````
execute: 
  enabled: true

**Comment by danieltomasz** [comment]
@cderv thanks for moving my comment to this issue!
I can avoid  this error when I create a notebook by setting metadata (but I see that fix is coming)
```python3
# Add kernel metadata
nb["metadata"]["kernelspec"] = {
    "display_name": "Python 3",
    "language": "python",
    "name": "python3",
}
```
