### ISSUE TITLE
unreadable docx output with flextable in labeled chunk

### ISSUE THREAD

**Issue by FlukeAndFeather** [quarto-dev/quarto-cli#9922]
### Bug description

If I create a flextable in a chunk with a label and render to docx then I get an "unreadable content" error in Word. This might be a duplicate of #7151, I'm not sure.

### Steps to reproduce

I created a repo with the minimal steps to produce the error: https://github.com/FlukeAndFeather/unreadabledocx. It has two Quarto documents. The one called "unreadabledocx.qmd" produces the error and the one called "readabledocx.qmd" does not. The only difference between the two is the R chunk in "unreadabledocx.qmd" has `label` and `tbl-cap` options set, and "readabledocx.qmd" does not.

### Expected behavior

The docx output of unreadabledocx.qmd should open in Word without warnings or errors.

### Actual behavior

When trying to open unreadabledocx.docx in Word I get an error saying "Word found unreadable content in unreadabledocx.docx."

### Your environment

```
─ Session info ──────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31)
 os       macOS Sonoma 14.4.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Los_Angeles
 date     2024-06-07
 rstudio  2024.04.0+735 Chocolate Cosmos (desktop)
 pandoc   3.1.11 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)
```

### Quarto check output

```bash
Quarto 1.5.43
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.43
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/frank/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2 (Conda)
      Path: /opt/miniconda3/bin/python
      Jupyter: 5.7.2
      Kernels: stickleback, python3

(\) Checking Jupyter engine render....2024-06-07 10:15:54,895 - traitlets - ERROR - Failed to run command:
['/Users/frank/opt/anaconda3/envs/stickleback/bin/python', '-m', 'ipykernel_launcher', '-f', '/private/var/folders/x2/pd2b41ls033f6_p4h4h37k880000gn/T/tmp3djqqofr.json']
    PATH='/opt/miniconda3/bin:/opt/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/TeX/texbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/quarto/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/bin/postback:/opt/homebrew/Cellar/git/2.45.1/bin'
    with kwargs:
{'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/var/folders/x2/pd2b41ls033f6_p4h4h37k880000gn/T/quarto-session694ea50de5a5c1d2/bbf7c1ab7719a007', 'start_new_session': True}

2024-06-07 10:15:54,896 - traitlets - ERROR - [Errno 2] No such file or directory: '/Users/frank/opt/anaconda3/envs/stickleback/bin/python'
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_client/manager.py", line 439, in _async_start_kernel
    await self._async_launch_kernel(kernel_cmd, **kw)
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_client/manager.py", line 354, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_client/provisioning/local_provisioner.py", line 210, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_client/launcher.py", line 170, in launch_kernel
    raise ex
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_client/launcher.py", line 155, in launch_kernel
    proc = Popen(cmd, **kwargs)  # noqa
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/miniconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/frank/opt/anaconda3/envs/stickleback/bin/python'


[Errno 2] No such file or directory: '/Users/frank/opt/anaconda3/envs/stickleback/bin/python'
[✓] Checking Jupyter engine render....OK
```

**Comment by mcanouil** [comment]
Duplicate of #7321
