### ISSUE TITLE
GitHub worktree issue

### ISSUE THREAD

**Issue by mroberts1** [quarto-dev/quarto-cli#9929]
I am getting a strange error when I try to publish a site with quarto publish gh-pages:

```
fatal: 'gh-pages' is already used by worktree at '/Users/dokoissho/GitHub/fsu-smt-su24/e3e869dfb3792a32'
ERROR: Error executing 'git': No such file or directory (os error 2)

Stack trace:
    at execProcess (file:///Applications/quarto/bin/quarto.js:4717:15)
    at withWorktree (file:///Applications/quarto/bin/quarto.js:105338:11)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Object.publish1 [as publish] (file:///Applications/quarto/bin/quarto.js:105177:5)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:109174:38)
    at async publish7 (file:///Applications/quarto/bin/quarto.js:109393:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:109353:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:109364:9)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:109341:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8015:13)

```
The error repeats when I try 'git checkout gh-pages' and I can't switch to the branch:

`fatal: 'gh-pages' is already used by worktree at '/Users/dokoissho/GitHub/fsu-smt-su24/e3e869dfb3792a32'`

I am still quite unclear on the workflow for using 'quarto publish' - I use RStudio for authoring and rendering, then switch to the terminal to publish to the GitHub repo with 'quarto publish gh-pages'.

**Comment by mroberts1** [comment]
> ```
> $ git worktree rm e3e869dfb3792a32
> ```

That fixed it, many thanks! The command should read 'remove' not 'rm' though:

```
$ git worktree remove e3e869dfb3792a32
```

**Comment by cscheid** [comment]
Great, and thanks for correcting the command.

**Comment by cderv** [comment]
@cscheid thanks for the debugging help. 

What do you suggest here ? I think we are supposed remove the worktree we created in the finally close. 

So not sure why there is a leftover. 

Idea of improvement: 
- Use a prefix we know  for the worktree dir so that we can easily identify it is quarto, if we encounter this in another run, we can know that it is a leftover from bad previous run, and we can remove before continuing.

**Comment by cscheid** [comment]
Your idea is exactly what I had in mind.

**Comment by jcolomb** [comment]
I had to use -f as in `git worktree remove -f e3e869dfb3792a32`.

It happens quite often and the solution is always difficult to find (as it is only here)...
Would be nice to have a better error message if it is easier than fixing the bug.

**Comment by sgolde13** [comment]
I also get like errors when I use `quarto publish gh-pages` from the main branch. Everything else appears to run right, but doing the force remove from the worktree helps.

Is there a sustainable solution that will prevent this error that is currently available?

**Comment by cderv** [comment]
> Is there a sustainable solution that will prevent this error that is currently available?

Not yet. The worktree created by Quattro is supposed to be removed after a `Quattro publish`, so I don't know what triggers this error. 

We'll try something by identifying and cleaning up previous worktree first. Though, it for some reason something prevent quarto CLI to clean worktree, then it won't help much. 

We'll see. If you are more insight about thow this happens, you can share. Otherwise, it is just a matter of time to come to this issue. Thanks for your patience. 

Thanks.

**Comment by mcanouil** [comment]
One thing that could block cleaning and basically a lot of Git actions is having concurrent commands that uses the `.git/index.lock`. If one command is unable to cleanly finish, the file will be left.
This being said, usually the error (at least on Git > 2.40, that's the oldest version I'm working with) mentions this file.

I wonder what is/was the Git version being used.

**Comment by mcanouil** [comment]
Is the error occurring only in RStudio?

**Comment by mcanouil** [comment]
Another idea, are you using a `.gitconfig` file with particular settings related to how syncing happen with the remote?

**Comment by cderv** [comment]
> So not sure why there is a leftover.

So in fact, there is a left over for same reason as discussed in #7757 

When program is interrupted from some reason (CTRL + C or similar), the `finally` close won't be run and the worktree is not cleaned. 

I can reproduce by `quarto publish gh-pages` and calling `CTRL + C` in the middle of the publishing. I'll add a cleanup step for leftover

**Comment by alexandre-bry** [comment]
I don't know if I should rather open a new issue, but I just had this same bug recently, and the solution mentioned here fixed it. I'm using quarto v1.8.27 on Linux (Ubuntu). Please tell me if you would prefer a new issue.

To give more context about the way it happened, I am using `quarto publish gh-pages --no-prompt`. The first time, I had an error related to setting user.name and user.email for git, and also this error from quarto (which I did not see) (sorry my git is in French):

```raw
Depuis github.com:alexandre-bry/MSc_Thesis-Report
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

[ 1/17] weekly_notes/2026_02_02.qmd
...
[17/17] reports/index.qmd

Préparation de l'arbre de travail (nouvelle branche 'gh-pages')
la branche 'gh-pages' est paramétrée pour suivre 'origin/gh-pages'.
HEAD est maintenant à 54a3240 Built site for gh-pages
Identité d'auteur inconnue

*** Veuillez me dire qui vous êtes.

Lancez

  git config --global user.email "Vous@exemple.com"
  git config --global user.name "Votre Nom"

pour régler l'identité par défaut de votre compte.
Éliminez --global pour ne faire les réglages que dans ce dépôt.

fatal: impossible de détecter automatiquement l'adresse ('ABry@DEL2202P108.(none)' trouvé)
fatal: '.quarto/quarto-publish-worktree-cfda07ef88e58d75' contient des fichiers modifiés ou non-suivis, utilisez --force pour le supprimer
```

There the command failed by itself (because I didn't set up git properly beforehand), and I didn't CTRL + C the program.
So I set the user.name and user.email, and then I ran the same command again, and got this:

```raw
Depuis github.com:alexandre-bry/MSc_Thesis-Report
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

[ 1/17] weekly_notes/2026_02_02.qmd
...
[17/17] reports/index.qmd

fatal: '/home/ABry/Documents/MSc_Thesis/MSc_Thesis-Report/.quarto/quarto-publish-worktree-cfda07ef88e58d75' contient des fichiers modifiés ou non-suivis, utilisez --force pour le supprimer
fatal: 'gh-pages' is already used by worktree at '/home/ABry/Documents/MSc_Thesis/MSc_Thesis-Report/.quarto/quarto-publish-worktree-cfda07ef88e58d75'
ERROR: Error executing 'git': Failed to spawn '/usr/bin/git': No such cwd '/home/ABry/Documents/MSc_Thesis/MSc_Thesis-Report/.quarto/quarto-publish-worktree-888a6321579d83c2'

Stack trace:
    at execProcess (file:///opt/quarto/bin/quarto.js:7098:11)
    at withWorktree (file:///opt/quarto/bin/quarto.js:155991:9)
    at eventLoopTick (ext:core/01_core.js:178:7)
    at async Object.publish2 [as publish] (file:///opt/quarto/bin/quarto.js:155836:3)
    at async publishSite (file:///opt/quarto/bin/quarto.js:159757:38)
    at async publish7 (file:///opt/quarto/bin/quarto.js:160093:58)
    at async doPublish (file:///opt/quarto/bin/quarto.js:160040:7)
    at async publishAction (file:///opt/quarto/bin/quarto.js:160059:5)
    at async _Command.actionHandler (file:///opt/quarto/bin/quarto.js:160018:9)
    at async _Command.execute (file:///opt/quarto/bin/quarto.js:10978:7)
```

There I was a bit confused so I just deleted the whole `.quarto` folder, hoping that it would fix it. But this only made the message disappear:

```raw
Depuis github.com:alexandre-bry/MSc_Thesis-Report
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

[ 1/17] weekly_notes/2026_02_02.qmd
...
[17/17] reports/index.qmd

fatal: 'gh-pages' is already used by worktree at '/home/ABry/Documents/MSc_Thesis/MSc_Thesis-Report/.quarto/quarto-publish-worktree-cfda07ef88e58d75'
ERROR: Error executing 'git': Failed to spawn '/usr/bin/git': No such cwd '/home/ABry/Documents/MSc_Thesis/MSc_Thesis-Report/.quarto/quarto-publish-worktree-18fe017e98427796'

Stack trace:
    at execProcess (file:///opt/quarto/bin/quarto.js:7098:11)
    at withWorktree (file:///opt/quarto/bin/quarto.js:155991:9)
    at eventLoopTick (ext:core/01_core.js:178:7)
    at async Object.publish2 [as publish] (file:///opt/quarto/bin/quarto.js:155836:3)
    at async publishSite (file:///opt/quarto/bin/quarto.js:159757:38)
    at async publish7 (file:///opt/quarto/bin/quarto.js:160093:58)
    at async doPublish (file:///opt/quarto/bin/quarto.js:160040:7)
    at async publishAction (file:///opt/quarto/bin/quarto.js:160059:5)
    at async _Command.actionHandler (file:///opt/quarto/bin/quarto.js:160018:9)
    at async _Command.execute (file:///opt/quarto/bin/quarto.js:10978:7)
```

Using the tips from this issue I managed to fix it with `git worktree remove quarto-publish-worktree-cfda07ef88e58d75`.

**Comment by cderv** [comment]
This is related edge case but new issue, I'll open one thank you
